### ISSUE TITLE
Flycheck not enabled on tramp buffers when using `(global-flycheck-mode)`

### ISSUE THREAD

**Issue by juergenhoetzel** [flycheck/flycheck#1000]
This is well documented [here](http://www.flycheck.org/en/latest/user/syntax-checks.html):

> Checking remote files may be very slow depending on the network connections,

IMO this is not valid, when using *Generic syntax checkers*. like I do in [flycheck-fsharp](https://github.com/fsharp/emacs-fsharp-mode/pull/88), which uses a persistent backend process.

Is it possible to relax this restrictions for generic checkers?

**Comment by lunaryorn** [comment]
@juergenhoetzel This restriction only applies to Global Flycheck Mode.  It's not possible to relax this restriction at this point—Flycheck doesn't even know about any syntax checkers yet.

In any case I'm not sure in how far a persistent background process changes anything.  You'd still end up sending buffer contents over the line at some point, in either direction, wouldn't you? 

Can you explain why you think that a persistent background process would not be affected by network latency and flakiness—particularly when considering slow 10kbit mobile edge connections or satellite lines with huge latencies?

**Comment by juergenhoetzel** [comment]
> @juergenhoetzel This restriction only applies to Global Flycheck Mode. It's not possible to relax this restriction at this point—Flycheck doesn't even know about any syntax checkers yet.
> 

I see. 

> In any case I'm not sure in how far a persistent background process changes anything. You'd still end up sending buffer contents over the line at some point, in either direction, wouldn't you?
> 
> Can you explain why you think that a persistent background process would not be affected by network latency and flakiness—particularly when considering slow 10kbit mobile edge connections or satellite lines with huge latencies?

On 10kbit mobile this could really be an issue. I have a DSL connection. IMO/experience the bottleneck ist always the *elisp* parsing code (JSON in case of `flycheck-fsharp`). 

Things look different when using external checkers. In this case Tramp have to spawn an extra SSH connection for each command. Flycheck like many other useful packages (Projectile, Magit) isn't useful in this case.

**Comment by juergenhoetzel** [comment]
Using mode-hooks is an easy workaround to enable `flycheck-mode` with suitable generic checkers. So I will close this issue. Thanks for your feedback!

**Comment by lunaryorn** [comment]
@juergenhoetzel You're welcome, keine Ursache 😊
