### ISSUE TITLE
Update doc string for flycheck-emacs-lisp-load-path variable

### ISSUE THREAD

**Issue by kevinj2016** [flycheck/flycheck#1008]
On another thread of mine, Sebastian asked me to open a separate issue for improving the doc string for flycheck-emacs-lisp-load-path. Here's the suggested improved doc string.

    Load path list to use in the Emacs Lisp syntax checker.

    Can be set to nil, `'inherit`, or to a list of load paths. Must NOT
    be set to a single string directory load path. If you have a single
    directory path to add, make it into a list first.

    When set to nil, do not explicitly set the ‘load-path’ during syntax
    checking.  The syntax check only uses the built-in ‘load-path’ of
    Emacs in this case.

    When set to ‘'inherit’ (note the leading apostrophe), use the 
    ‘load-path’ of the current Emacs session during syntax checking.

    When set to a list of strings, add each directory in this list to
    the ‘load-path’ before invoking the byte compiler.  Relative
    paths in this list are expanded against the ‘default-directory’
    of the buffer to check.

    Note that changing this variable can lead to wrong results of the
    syntax check, e.g. if an unexpected version of a required library
    is used.

**Comment by lunaryorn** [comment]
Thank you for reporting this issue.  I'm all for stating the required types more clearly, but I don't think that we should document what you must not use.   What about:

> Must be either nil, `inherit' or a list of strings where each item is a directory to be added to the `load-path` of the syntax check.

**Comment by kevinj2016** [comment]
Hi Sebastian, please, do what you like. I know from your other writings that you have pretty strong views on various coding projects and things, and that you like to allocate your time accordingly. And it is of course your Flycheck program (that we all use and are grateful for). 

I will not be offended (not that it matters!) whatever you do. It reminds me of when I was writing my first book for OReilly, and started working with editors and reviewers, and their comments and suggestions. My philosophy was that if I didn't feel really strongly about my view, and even if couldn't see how their suggestions would make a giant improvement, I would just implement their suggested changes on the theory that they saw something I didn't, and they were trying to make the project better too.

In this case, we have different views. I claim with evidence (in the other thread) that the variable doc is not quite clear, that you already do type checking on the variable (so checking for another type would not break any precedent), that a small coding fix would cure this (real, not theoretical) problem forever. 

I heard back that the maintainers (without evidence) do not want to add another type check, do not want to change the semantics of the variable, but were partially open to changes in the doc, and invited my suggestions there. I dutifully took the time to make my doc suggestions (based a lifetime of writing multiple books, dozens of technical patents, thousands of pages of technical docs, etc), but even my doc isn't quite what you like. (I wrote the doc to clearly nail down the only three values that were allowed, and then described each one, warning people away from the problem that sucked up so much of my time, and that triggered the crash in your code). 

We've all spent way more time on this problem than it is worth. So please let me be the reviewer with suggestions, and you be the author who decides what to do. I won't be offended. (But I will think that the project is a tiny bit worse for not picking up my suggestions. :-)  Best regards

**Comment by kevinj2016** [comment]
PS. Not that it will help any, but I quoted my first symbol in Multics MacLisp Emacs back in 1980 or so.. When I searched the net for flycheck-emacs-lisp-load-path info, I found several articles and examples. Some of them set the variable to 'inherit in their code examples, which was clear and precise, no ambiguity at all. Some of them said (not in code, but in doc) "set it to inherit and ..." which was not clear, not precise, and ambiguous enough to make a reader wonder if inherit was a quoted symbol, a variable, or a concept.  Again, we differ in our views. :-) The simple fact that a guy like me can trip over this problem should be a big sign that some change would be useful (or at least that's how I would think.)  Best regards.

**Comment by lunaryorn** [comment]
@kevinj2016 I'm not sure whether "evidence" is the proper word to use.  I don't think that this particular case constitutes evidence for anything other than that you misunderstood the documentation, for whatever reason.   It's probably an *indication* that the current documentation is unclear, but nothing more.  

In my opinion your case is just a single point of data, and there's other data about our documentation as well, such as that you're the first to report this issue although the variable's been there for probably two years and is [used by many people](https://github.com/search?q=+flycheck-emacs-lisp-load-path+&type=Code&utf8=✓).

I'm all for improving our documentation, but we need to write documentation that's accessible to more than just a one person.  This goal implies other things to care for, such as consistency with Emacs' built-in variables and Emacs' own documentation style—Emacs' doesn't permit a single string in `load-path` either, and Emacs' own docstrings never put a quote in front of plain symbols as well.

I appreciate your suggestions but I've a different point of view for a reason.

Besides, I'd like to talk to you privately.  I'd be happy to receive a mail from you at me@lunaryorn.com.

**Comment by kevinj2016** [comment]
Sebastian, I'm really ok with you having a different point of view. My life experience has been that lots of times people have real reasons (that I can't see) for having different opinions than me. I don't have to be "right." Let the 10,000 flowers bloom, and all that. You know far more about being consistent with Emacs, your user population, etc than I could possibly know. Go ahead and do what you think is right. As you point out, I'm just another single data point with yet another point of view on the Internet. :-) This is a tiny, tiny issue on the scale of things, and it's getting way more time and effort than it should. Cheers
