### ISSUE TITLE
Shellscript add option for shellcheck args

### ISSUE THREAD

**Issue by Thaodan** [flycheck/flycheck#1011]
It would be nice if there would be an option to set args for shellcheck (like x to allow external sources),
just like _flycheck-hlint-args_ for _haskell-hlind_

**Comment by lunaryorn** [comment]
@Thaodan Please feel free to add this option and open a pull request.  If it's about a specific flag, though, we should probably add a proper option so that it can be changed through Emacs' customise interface.

**Comment by Thaodan** [comment]
It's about the -x option to allow external sources via the definition # 
shellcheck source=example.sh


I'll try to add a proper option for this as they're maybe more options that 
are useful to add if desired.

**Comment by PrgrmAtCeleritas** [comment]
I came here to suggest this same thing. Hope this gets added soon. I will look into it

**Comment by seriousben** [comment]
I went the non generic way here: https://github.com/flycheck/flycheck/pull/1251

**Comment by fmdkdd** [comment]
Closing since #1256 was merged.
