### ISSUE TITLE
Flycheck's ESLint checker should support multiple custom rules directories

### ISSUE THREAD

**Issue by NateEag** [flycheck/flycheck#1016]
Flycheck currently offers `flycheck-eslint-rulesdir` to specify a directory containing custom rules.

However, ESLint supports multiple rules directories, [by passing the `--rulesdir` option multiple times](http://eslint.org/docs/user-guide/command-line-interface#specifying-rules-and-plugins).

To support this in the Flycheck checker, I would suggest creating an alias called `flycheck-eslint-rulesdirs` that is a customizable list, deprecating `flycheck-eslint-rulesdir`, and handling the case where `flycheck-eslint-rulesdirs` contains a string when using it to construct the ESLint command.

That should provide the desired semantics, be backwards-compatible, and encourage users to update their configurations appropriately.

Does this sound reasonable?

**Comment by cpitclaudel** [comment]
Sounds good to me. Not sure whether we need the deprecation and alias, as opposed to just supporting a string or a list of string in that variable.

Do you want to take a shot at implementing this?

**Comment by lunaryorn** [comment]
I wouldn't mind a breaking change.  It's easier to just move from an option with a single string to an option with a list of string.  Flycheck's always been moving fast in this aspect, I don't particularly care about backwards compatibility.

It'd be great if you could open a pull request :)

**Comment by NateEag** [comment]
Sure, I'll take a shot at it.

@lunaryorn - it sounds like you might prefer a breaking change to keep the code simple. Is that accurate?

I'm a backwards-compat guy myself, but if flycheck puts higher priority on simplicity, I can do that.

**Comment by lunaryorn** [comment]
@NateEag Yep that's correct.  It's just easier to maintain for us that way 😊

**Comment by NateEag** [comment]
Okay, sounds good. I'll check back in when I have something working.

It may be a little while - pretty busy these days.
