### ISSUE TITLE
Debian release tags pulled into upstream repository

### ISSUE THREAD

**Issue by spwhitton** [flycheck/flycheck#1017]
Someone has pushed the Debian release tags `debian/27-1`, `debian/28-1` and `debian/28-2` to the upstream flycheck repository . . . they are now appearing on the GitHub's "Releases" page.  Should probably be removed!

**Comment by lunaryorn** [comment]
Thanks for making me aware.  Note though that you can remove these tags yourself, you've got push access to the repo 😊

**Comment by lunaryorn** [comment]
@spwhitton Actually, it was you yourself who pushed these tags:

![bildschirmfoto 2016-07-21 um 11 12 36](https://cloud.githubusercontent.com/assets/224922/17017557/15e1a28c-4f34-11e6-809f-3d4c7b2cb640.png)

No blame, no harm done, but please check your Git setup for your Flycheck clones to make sure that it doesn't happen again.  Thanks.

**Comment by lunaryorn** [comment]
I've removed all these tags.

**Comment by spwhitton** [comment]
Sorry about that -- I didn't know that I could push tags.  Thanks for fixing it.

By the way, your screenshot is not evidence that I pushed the tags.  Because I didn't realise I had push access for tags, I assumed that someone had pulled them from my packaging repo and then pushed to GitHub.

**Comment by lunaryorn** [comment]
Ah so the user name in the screenshot is the user who tagged? I didn't know that tags had user names attached so I presumed it was the user who pushed the tag.  I'm sorry for the misunderstanding.

Never mind, no harm done.  It's easy enough to remove tags again.

**Comment by spwhitton** [comment]
Yeah.  Annotated tags are just like commits in that they have full authorship (and can be PGP-signed).  "Lightweight" tags are anonymous, and cannot be signed (they're generally less useful).

**Comment by lunaryorn** [comment]
@spwhitton Thanks for the explanation 😊
