### ISSUE TITLE
 flycheck show  a error in a file generated by protoc

### ISSUE THREAD

**Issue by Hardy5012** [flycheck/flycheck#1018]
![image](https://cloud.githubusercontent.com/assets/9472792/17023135/5bf7619e-4f84-11e6-8890-c097437ed3cd.png)
The base.pb.h is generated by protoc from base.proto, and check C-c ! C-c c/c++-clang output the follow message.

> clang -fsyntax-only -fno-color-diagnostics -fno-caret-diagnostics -fno-diagnostics-show-option -iquote  src/proto/ -std\=c++11 -Wall -Wextra -I /usr/local/protobuf/include/ -x c++ - <  src/proto/ base.pb.h 
> In file included from <stdin>:23:
> In file included from /usr/local/protobuf/include/google/protobuf/message.h:120:
> /usr/local/protobuf/include/google/protobuf/descriptor.h:1283:21: warning: unused parameter
>       'filename'
> /usr/local/protobuf/include/google/protobuf/descriptor.h:1284:21: warning: unused parameter
>       'element_name'
> /usr/local/protobuf/include/google/protobuf/descriptor.h:1285:22: warning: unused parameter
>       'descriptor'
> /usr/local/protobuf/include/google/protobuf/descriptor.h:1286:21: warning: unused parameter
>       'location'
> /usr/local/protobuf/include/google/protobuf/descriptor.h:1287:21: warning: unused parameter
>       'message'
> In file included from <stdin>:23:
> /usr/local/protobuf/include/google/protobuf/message.h:392:40: warning: unused parameter 'message'
> /usr/local/protobuf/include/google/protobuf/message.h:393:48: warning: unused parameter
>       'oneof_descriptor'
> /usr/local/protobuf/include/google/protobuf/message.h:397:36: warning: unused parameter 'message'
> /usr/local/protobuf/include/google/protobuf/message.h:398:50: warning: unused parameter
>       'oneof_descriptor'
> /usr/local/protobuf/include/google/protobuf/message.h:403:22: warning: unused parameter 'message'
> /usr/local/protobuf/include/google/protobuf/message.h:404:30: warning: unused parameter
>       'oneof_descriptor'
> In file included from <stdin>:24:
> /usr/local/protobuf/include/google/protobuf/repeated_field.h:86:34: warning: unused parameter
>       'begin'
> /usr/local/protobuf/include/google/protobuf/repeated_field.h:86:46: warning: unused parameter
>       'end'
> 
> Compilation finished at Thu Jul 21 17:36:20`

**Comment by lunaryorn** [comment]
@Hardy5012 Please correct the syntax of your comment.  Please use code blocks for the output of clang.

**Comment by Hardy5012** [comment]
google protobuf version is 2.6.1

**Comment by Hardy5012** [comment]
>clang version 3.4.2 (tags/RELEASE_34/dot2-final)
Target: x86_64-redhat-linux-gnu
Thread model: posix
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.2
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.5
Found candidate GCC installation: /usr/lib/gcc/x86_64-redhat-linux/4.8.2
Found candidate GCC installation: /usr/lib/gcc/x86_64-redhat-linux/4.8.5
>Selected GCC installation: /usr/bin/../lib/gcc/x86_64-redhat-linux/4.8.5

**Comment by lunaryorn** [comment]
I'm closing this issue—it's probably a flaw in our C++ error parsing, but I have no time to fix it.

Pull requests welcome.

**Comment by lunaryorn** [comment]
I'm sorry that I can't provide a better solution/
