### ISSUE TITLE
Remove JSCS

### ISSUE THREAD

**Issue by lunaryorn** [flycheck/flycheck#1024]
JSCS has reached [end of life](http://eslint.org/blog/2016/07/jscs-end-of-life), we should stop supporting it as well.

/cc @flycheck/javascript 

Edit: For reference, the [compatibility milestone](https://github.com/eslint/eslint/milestone/15)

**Comment by Simplify** [comment]
On the same page:

> We have setup a milestone for tracking all of our JSCS compatibility issues. At the time of this post, we are at 20% complete and are continuing to make progress.

And:

> We recommend holding off on switching from JSCS to ESLint until most of the compatibility work has been completed (we will make an announcement when that happens).

I'll wait until that announcement. JSCS still have [27000+ downloads every day](https://www.npmjs.com/package/jscs), around same number as in April when they announced joining ESLint.

**Comment by lunaryorn** [comment]
@Simplify We can wait, but I'd not like to prolong cleanup work beyond what's absolutely necessary.  Users who still need JSCS can either restore the definition, or stick to an older Flycheck release.

**Comment by Simplify** [comment]
Ok, give me few days to check few things that JSCS did better than ESLint, for example checking JSDoc comments in the code.

**Comment by Simplify** [comment]
We can also extract JSCS in gist.

**Comment by lunaryorn** [comment]
@Simplify As I said, we can wait until eslint provides full compatibility, but as soon as that's the case, we'll remove JSCS.

**Comment by Simplify** [comment]
@lunaryorn  Just a quick update: Compatibility is now at 38% and there is a draft of [JSCS migration guide](https://github.com/eslint/eslint/commit/1153955). However, there are still around 30K downloads of JSCS every day.

I'm busy next 2 weeks, but after that we can check status again. Maybe we can wait until compatibility hits 60-80% or that migration guide is done. Doe to high number of downloads, the best solution IMHO is to extract JSCS checker into GH gist, then people can load that file into Emacs if they still need JSCS support. Maybe provide link to that gist in ChangeLog.

**Comment by Simplify** [comment]
JSCS is [unmaintained](https://github.com/jscs-dev/node-jscs), [merged with ESLint](https://eslint.org/blog/2016/04/welcoming-jscs-to-eslint) and [compatibility with ESLint](https://github.com/eslint/eslint/milestone/15) is 84%.
