### ISSUE TITLE
Option to byte-compile without Cask

### ISSUE THREAD

**Issue by dunn** [flycheck/flycheck#1032]
Follow-up to https://github.com/flycheck/flycheck/pull/1029#issuecomment-238276670; it'd be nice to have a Make target that doesn't require Cask.  My usecase is Homebrew, where dependencies are already taken care of.

The path to each dependency might have to be specified in the Makefile with some sort of sensible default; this is how I did it in one case: https://github.com/dunn/homebrew-mode/blob/master/Makefile#L7-L16

**Comment by lunaryorn** [comment]
@dunn Thanks for opening this issue, I'll add an option soon.  Sorry for the delay, I've been on vacation the last days.

**Comment by dunn** [comment]
No worries!

**Comment by lunaryorn** [comment]
@dunn See #1043.  You've got to pass `EMACSFLAGS` to setup load path explicitly via `-L`.  The makefile doesn't try and guess where dependencies might be located, as I don't think that there's a sensible default in the absence of Cask.

**Comment by dunn** [comment]
Fixed by #1043, thanks again!

**Comment by lunaryorn** [comment]
@dunn You're welcome.
