### ISSUE TITLE
Different pylintrc file for each project.

### ISSUE THREAD

**Issue by nayefc** [flycheck/flycheck#1033]
Hello,

I use flycheck, specifically for pylint to check my python code. I decided to download a pylint plugin called `pylint_django`. I'd like to load it only for one project (in a virtualenv). I created a pylintrc file that loads that plugin. Is there a way to have emacs load that pylintrc, instead of the default `~/.pylintrc`? My `flycheck-pylintrc` variable is set to `.pylintrc`.

I am using pyenv to manage my virtualenvs.

I am using Emacs 24.5.1 with Flycheck 20160808.131.

Thanks!

**Comment by lunaryorn** [comment]
`~/.pylintrc` isn't the default.  Flycheck tries to find `.pylintrc` in a number of places, see `flycheck-locate-config-file-functions`.  In any case you can use Emacs' Directory Variables to set `flycheck-pylintrc` to the absolute path of the pylint configuration file you'd like to use for files in that directory.

Note, though, that if you install a pylint plugin into a virtualenv you've got to install pylint into the virtualenv as well, or pylint won't find the plugin.  In that case you've got to set `flycheck-python-pylint-executable` to the absolute path of the pylint executable of the corresponding virtualenv.

**Comment by nayefc** [comment]
@lunaryorn Ideally I'd like it such that once I activate that virtualenv, it will work automatically without having to set the variable manually each time I go int o that virtualenv.

I have pylint and the plugin installed into that virtualenv. Seems like setting the executable might do that. Will I still need to add the `load-plugin` line pylintrc? Because if I do, then that's back to square one and I'll just need to figure out how to set the pylintrc file for that virtualenv, and unset it once I exit that virtualenv.

What's the best way to do that? It seems like Emac's default directory is `~`, which is why it ends up always finding `~/.pylintrc`. Is it possible to have that change to the virtualenv that I'm in somehow?

**Comment by lunaryorn** [comment]
I'm not sure what activating a virtualenv in the context of Emacs means.  I've never used any of the virtualenv packages for Emacs. Back when I still did a lot of Python I just change the executable path.  But as long as the virtualenv ends up in exec-path Flycheck should pick up pylibt from the virtualenv.

As for the pylint configuration I don't know either.  I've never used Pylint plugins and I don't know where pylint loads these from.

I'm sorry but I'll not be able to help you with so specific questions about pylint.  It's long since I used Python.

**Comment by nayefc** [comment]
I see, it just really means activating it using Pyenv. Pyenv emulates what it does to shell to Emacs so that the linter will see that virtualenv's packages and figure out your imports. It also allows you to jump between files and projects using `projectile-helm` etc...

I guess I'll have to hardcode something. Thanks for your help anyway, Python packaging and tooling really sucks :(

**Comment by noobymcnoob** [comment]
I had to do this to get it to locate the file, for some reason the default didn't work:

`((nil . ((eval setf flycheck-pylintrc (flycheck-locate-config-file-ancestor-directories ".pylintrc" 'python-pylint)))))`
