### ISSUE TITLE
no delay for echo area message when explicitly jumping to errors

### ISSUE THREAD

**Issue by wbolster** [flycheck/flycheck#1034]
whenever i jump to an error, the echo area shows the error only after a delay. this is fine during normal editing, but when i _explicitly_ tell emacs to jump to an error, it would be useful to see the error message immediately, since the main reason to jump to an error is to investigate it. :-)

it would be great if flycheck ignored `flycheck-display-errors-delay` whenever triggered by an explicit jump to an error location using one of the flycheck "go to error" functions.

a condition like this in `(flycheck-display-error-at-point-soon)` would perhaps be a start:

```elisp
(memq this-command '(flycheck-first-error flycheck-next-error flycheck-previous-error))
```

**Comment by wbolster** [comment]
this seems to do the trick:

```diff
modified   Emacs/elpa/flycheck-20160731.17/flycheck.el
@@ -4167,8 +4167,12 @@ non-nil."
   "Display the first error message at point in minibuffer delayed."
   (flycheck-cancel-error-display-error-at-point-timer)
   (when (flycheck-overlays-at (point))
-    (setq flycheck-display-error-at-point-timer
-          (run-at-time flycheck-display-errors-delay nil 'flycheck-display-error-at-point))))
+    (if (memq this-command '(flycheck-first-error
+                             flycheck-next-error
+                             flycheck-previous-error))
+        (flycheck-display-error-at-point)
+      (setq flycheck-display-error-at-point-timer
+            (run-at-time flycheck-display-errors-delay nil 'flycheck-display-error-at-point)))))
```

let me know if you agree this is useful behaviour. then i'll open a proper pr. :)

**Comment by lunaryorn** [comment]
@wbolster Oh, thank you for reporting this issue.

Flycheck actually tries to display the error immediately, but only when `flycheck-standard-error-navigation` is enabled and when you're using the built-in `next-error` and friends.

For our own navigation commands I apparently forgot to implement that. Sorry :blush:

----

As to the suggested change, though, I think there's a better way.  Did you try to simply add a call to `flycheck-display-error-at-point` to the end of `flycheck-next-error`?

**Comment by wbolster** [comment]
thanks. that also works fine indeed. i'll come up with a proper pr soonish.

**Comment by lunaryorn** [comment]
That'd be awesome 👍
