### ISSUE TITLE
Add auto-formatter to Flycheck

### ISSUE THREAD

**Issue by lunaryorn** [flycheck/flycheck#1041]
Add `maint/format.el` and a corresponding `make format` which formats all sources according to our style guide as far as possible.  It should 

- [ ] reindent the buffer (requires loading unfortunately)
- [ ] cleanup whitespace to remove tabs, trailing spaces, etc.
- [ ] further ideas?

We should also replace the test that checks for proper indentation with a test that checks for proper formatting by applying the formatter to a file and checking for modifications.

**Comment by manuel-uberti** [comment]
Very nice idea.

Could there be naming conventions (i.e.: a checker's name) to check?

**Comment by lunaryorn** [comment]
@manuel-uberti Maybe, but not within the scope of this ticket.

**Comment by manuel-uberti** [comment]
@lunaryorn ok. Then reidenting the buffer and cleaning up whitespaces/tabs should be enough.
