### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by mambolevis** [flycheck/flycheck#1048]
Hi, 

In my **init** file I am defining a global constant:
`(defconst lisp-dir (expand-file-name "user/lisp" user-emacs-directory))`

I use that constant in other files `( e.g crossword.el)`, and everything works properly. Nonetheless,
flycheck shows the following message when `(require 'crossword)`
`symbol's value as variable is void: lisp-dir`

I verify the constant's value using C-h v , and it is not void!

Why this message appears and how can I silent it?

Thanks,

Levis

**Comment by lunaryorn** [comment]
Flycheck does not load your init file when checking files.  You need to move the definition into a common file which you can `require` whenever you use the variable, or you can declare it with `(defvar lisp-dir)` in every file you're using it.

Please note that it's generally not recommended to use variable names without prefix.

**Comment by mambolevis** [comment]
`You need to move the definition into a common file which you can require whenever you use the variable`

I chose this option because it keeps the definitions in one place. So, I made the following:
```
(use-package frey-directories
  :load-path "~/.emacs.d/user/lisp/")
```
In `frey-directories.el`  I put all my directories:
```
(defvar frey-user-dir (expand-file-name "user" user-emacs-directory))
(defvar frey-lisp-dir (expand-file-name "user/lisp" user-emacs-directory))
(defvar frey-site-lisp-dir (expand-file-name "user/site-lisp" user-emacs-directory))
(defvar frey-collection-dir (expand-file-name "user/collection" user-emacs-directory))
```
After that I `(require 'frey-directories)`and flycheck see the definitions. 

If you have any comment please let me know,
Thanks

**Comment by cpitclaudel** [comment]
This looks good :) Use-package might be superfluous, but it doesn't hurt.
