### ISSUE TITLE
Flycheck crashing on simple checker

### ISSUE THREAD

**Issue by aemoncannon** [flycheck/flycheck#1049]
Flycheck version: 29snapshot (package: 20160817.321)
GNU Emacs 24.4.50.1

Trying to setup a simple checker here:
(flycheck-define-checker tsc
  "A TypeScript syntax checker using tsc command."
  :command ("tsc" "--noEmit" source)
  :error-patterns ((error line-start (file-name)
			  "(" line "," column "): error "
			  (message) line-end))
  :modes typescript-mode)

(add-to-list 'flycheck-checkers 'tsc)
(flycheck-mode t)

But it every time I enter typescript-mode, I get the following error. It looks like it's trying to access a 'start property on the 'default checker, which doesn't exist.
Thanks!

Debugger entered--Lisp error: (void-function nil)
  nil(default #[128 "\301\302\300#\207" [[cl-struct-flycheck-syntax-check #<buffer animation.ts> default nil "/Users/foo/typescripts/"] apply flycheck-report-buffer-checker-status] 5 "\n\n(fn &rest ARGS)"])
  flycheck-syntax-check-start([cl-struct-flycheck-syntax-check #<buffer animation.ts> default nil "/Users/foo/typescripts/"] #[128 "\301\302\300#\207" [[cl-struct-flycheck-syntax-check #<buffer animation.ts> default nil "/Users/foo/typescripts/"] apply flycheck-report-buffer-checker-status] 5 "\n\n(fn &rest ARGS)"])
  flycheck-start-current-syntax-check(default)
  flycheck-finish-current-syntax-check(nil "/Users/foo/typescripts/")
  flycheck-report-buffer-checker-status([cl-struct-flycheck-syntax-check #<buffer animation.ts> tsc #<process flycheck-tsc> "/Users/foo/typescripts/"] finished nil)
  apply(flycheck-report-buffer-checker-status [cl-struct-flycheck-syntax-check #<buffer animation.ts> tsc #<process flycheck-tsc> "/Users/foo/typescripts/"] (finished nil))
  #[128 "\301\302\300#\207" [[cl-struct-flycheck-syntax-check #<buffer animation.ts> tsc #<process flycheck-tsc> "/Users/foo/typescripts/"] apply flycheck-report-buffer-checker-status] 5 "\n\n(fn &rest ARGS)"](finished nil)
  flycheck-finish-checker-process(tsc 0 nil "" #[128 "\301\302\300#\207" [[cl-struct-flycheck-syntax-check #<buffer animation.ts> tsc #<process flycheck-tsc> "/Users/foo/typescripts/"] apply flycheck-report-buffer-checker-status] 5 "\n\n(fn &rest ARGS)"] "/Users/foo/typescripts/")
  #[0 "\304\300!\211\305=\203\302\306!\202)\211\307=\203(\310\311\300\312\"\313\300!\301\314\300!\302\303&\202)\315\207" [#<process flycheck-tsc> nil #[128 "\301\302\300#\207" [[cl-struct-flycheck-syntax-check #<buffer animation.ts> tsc #<process flycheck-tsc> "/Users/foo/typescripts/"] apply flycheck-report-buffer-checker-status] 5 "\n\n(fn &rest ARGS)"] "/Users/foo/typescripts/" process-status signal interrupted exit flycheck-finish-checker-process process-get flycheck-checker process-exit-status flycheck-get-output nil] 8 "\n\n(fn)"]()
  funcall(#[0 "\304\300!\211\305=\203\302\306!\202)\211\307=\203(\310\311\300\312\"\313\300!\301\314\300!\302\303&\202)\315\207" [#<process flycheck-tsc> nil #[128 "\301\302\300#\207" [[cl-struct-flycheck-syntax-check #<buffer animation.ts> tsc #<process flycheck-tsc> "/Users/foo/typescripts/"] apply flycheck-report-buffer-checker-status] 5 "\n\n(fn &rest ARGS)"] "/Users/foo/typescripts/" process-status signal interrupted exit flycheck-finish-checker-process process-get flycheck-checker process-exit-status flycheck-get-output nil] 8 "\n\n(fn)"])
  flycheck-handle-signal(#<process flycheck-tsc> "finished\n")

**Comment by aemoncannon** [comment]
fwiw adding a null implementation of this function fixes it for me
(defun flycheck-get-next-checker-for-buffer (checker)
  nil)

**Comment by syohex** [comment]
I cannot reproduce and it looks working well on Emacs 25.1-RC2. It looks you use very old development version Emacs. Please upgrade Emacs and retry.

**Comment by lunaryorn** [comment]
Please edit your original post and add proper formatting.  The stack traces are hardly readable currently.

**Comment by lunaryorn** [comment]
And please update Emacs, yours is very old.  It's a development snapshot from some years ago?

**Comment by aemoncannon** [comment]
That did the trick. Thanks!
