### ISSUE TITLE
Puppet-lint has deprecated formatting with `linenumber`

### ISSUE THREAD

**Issue by rski** [flycheck/flycheck#1050]
Since [release 1.0.0](https://github.com/rodjek/puppet-lint/releases/tag/1.0.0) in 2014, puppet-lint has deprecated formatting messages with `linenumber` in favour of just `line`. 
Since flycheck calls it with `linenumber`, warnings are thrown. 
The last release that didn't have `line` was in 2013, so I think we can just make this change rather painlessly.

**Comment by cpitclaudel** [comment]
This sounds good. Can you prepare a pull request?

**Comment by rski** [comment]
Sure. I'm self assigning it for now, but I'll be rather busy this week so if anyone else wants to squash this that'll be good too.
