### ISSUE TITLE
Support older phpcs

### ISSUE THREAD

**Issue by yskkin** [flycheck/flycheck#1054]
Few coding standard requires phpcs < 2.6.
For example, [the standard for CakePHP 2.x](https://github.com/cakephp/cakephp-codesniffer/tree/1.x) requires [phpcs ^1.4.0](https://github.com/cakephp/cakephp-codesniffer/blob/1.x/composer.json#L21).

Please consider checking `flycheck-php-phpcs-executable`'s version and fallback checker definition by removing `--stdin-path` option and adding `:standard-input nil`.

May have relation with #921 and #991.

**Comment by lunaryorn** [comment]
I am sorry but that is not an option for us.  If we were to do this for one checker we had to do it for all checkers and things would quickly get out of hand and become a mess.

We will not try and support older versions of phpcs. 

Please copy the old definition of phpcs which works with 1.4 to your configuration.
