### ISSUE TITLE
Licensing of sphinx documentation

### ISSUE THREAD

**Issue by spwhitton** [flycheck/flycheck#1059]
The old texinfo manual was dual-licensed GFDL-1.3+ or CC-BY-SA-4.0.  How about the new *.rst files?  I can't find any statement of their licensing status.  Thanks.

**Comment by lunaryorn** [comment]
They are CC-BY-SA 4.  See our [CLA](https://github.com/flycheck/flycheck/blob/master/.github/CLA.md), or the [License section in our README](https://github.com/flycheck/flycheck#license) or [on the website](http://www.flycheck.org/en/latest/#licensing):

> You may copy, distribute and/or modify the Flycheck documentation under the terms of the Creative Commons Attribution-ShareAlike 4.0 International Public License. See Creative Commons Attribution-ShareAlike 4.0 International for a copy of the license.

**Comment by spwhitton** [comment]
Thanks for your reply!  Sorry I didn't think to look at the CLA.

**Comment by lunaryorn** [comment]
@spwhitton You're welcome.
