### ISSUE TITLE
Unitialized variable

### ISSUE THREAD

**Issue by sebastianv89** [flycheck/flycheck#1069]
Flycheck reports an error that does not exist for my c project. flycheck-verify-setup reports that clang is used as a syntax checker, but when I compile (with clang), the compiler gives no error, which leads me to believe that this is an issue in flycheck (and not in clang).

I know: there is an easy workaround (use N-1 as index), but I'd rather not make these changes throughout my (working!) code just to make flycheck happy.

This is the smallest code example I could think of (error reported in last line of foo):
```
#include <stdlib.h>
#include <stdio.h>

#define N 2

void foo(int *, int*);
void foo(int *sum, int *a) {
    size_t i;
    *sum = a[0];
    for (i = 1; i < N-1; ++i) {
        *sum += a[i];
    }
    *sum += 2*a[i]; /* Uninitialized variable: i [uninitvar] */
}

int main(void) {
    int sum;
    int a[N] = {1,2};
    
    foo(&sum, a);
    printf("%i\n", sum);

    return 0;
}
```

I could not reproduce this with emacs -Q as I don't have flycheck there

M-x flycheck-verify-setup:
```
Syntax checkers for buffer flycheck.c in c-mode:

  c/c++-clang
    - predicate:  t
    - executable: Found at /usr/bin/clang

  c/c++-gcc
    - predicate:  t
    - executable: Found at /usr/bin/gcc

  c/c++-cppcheck
    - predicate:  t
    - executable: Found at /usr/bin/cppcheck

Flycheck Mode is enabled.
```

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
```

M-x emacs-version:
```
GNU Emacs 24.3.1 (x86_64-pc-linux-gnu, GTK+ Version 3.10.7) of 2014-03-07 on lamiak, modified by Debian
```
M-x flycheck-version:
```
Flycheck version: 0.25.1
```

**Comment by cpitclaudel** [comment]
Hi,

Thanks for the report! Flycheck's only source of errors and warnings are checkers, so the error is coming from a checker; my guess is that you're not compiling with the same flags, and thus that Flycheck is reporting more warnings than your default build configuration.

You can use `C-c ! C-c` to get the full command line and output of the checker. In your case, the error is being reported by cppcheck.

**Comment by sebastianv89** [comment]
You're right, running cppcheck on my file gives the same error. So it's a bug in cppcheck, not in flycheck :)
