### ISSUE TITLE
Feature request: a checker which reports warnings for FIXME, TODO comments in code

### ISSUE THREAD

**Issue by ackalker** [flycheck/flycheck#1083]
It would be nice to have a Flycheck checker which reports all comments which have any of the words `FIXME`, `TODO` etc. as warnings, and perhaps comments with the word `BUG` in them as errors.
I've seen this functionality in other editors and IDEs, and I think it would be nice to have in Emacs, too.
Given Emacs' powerful syntax tables, I don't think it woud be very hard to implement.

**Comment by ackalker** [comment]
The EmacsWiki hosts a [fixme-mode.el](https://www.emacswiki.org/emacs/fixme-mode.el) which could be useful as a starting point.

**Comment by cpitclaudel** [comment]
Hmm. I wonder how discoverable such a thing would be.  If it was a separate package, people could install it and it would be enabled by default after installation; but if it was part of Flycheck, we probably wouldn't want to enable it by default: some checkers already report TODOs and FIXMEs by themselves.

In any case, the code would indeed probably not be too hard to write; do you want to take a shot at it? I don't think syntax tables would play a big role in it, though.  One of the difficulties is that it would be synchronous, which might introduce unpleasant lags.  Or it could be asynchronous (running in a separate instance of Emacs), but then detecting comments would be hard.

**Comment by ackalker** [comment]
With regards to discoverability: I'm not asking for the checker to be part of the Flycheck package, a separate package is fine with me, less bloat for people who do not use this feature. I opened the issue here because it seems like a good central place for people looking for features, at least better than posting on Twitter or some random personal blog which no-one has heard about.

Regarding syntax tables: you're probably right, I'm thinking more of hooking into the fontification machinery myself: tracking when comments are created or changed, then scanning the resulting comments for keywords.

If I have some spare time, I might look into this (same with the Awk checker ;) ), but if someone wants to beat me to it, be my guest.

**Comment by lunaryorn** [comment]
I think that this syntax checker is out of scope for Flycheck.  It's got a very narrow scope—I'm not sure whether there's broad consensus that TODOs should be shown through the same interfaces as errors.  IntelliJ doesn't do that—which is my gold standard for IDEs—and I can't remember VisualStudio doing it either.

I believe it'd be best if this was a separate package so I'm taking the liberty to close this issue as "wontfix".  Please feel free to continue the discussion nonetheless.

As far as spare time's concerned please don't count on us.  As you can easily see there's so much to do in Flycheck itself; we don't really have the time for that.  I'm sorry.
