### ISSUE TITLE
Flycheck won't run after installing jslint

### ISSUE THREAD

**Issue by drodrigo** [flycheck/flycheck#1086]
Hello everyone!

I'm trying to run flycheck for javascript:

1 - I installed both jslinter and jshinter (globablly)

2 - I enabled flycheck globally as well (global-flycheck-mode)

3 - It didn't work so I found this guide on how to use flycheck for js files: https://www.emacswiki.org/emacs/Flycheck, I followed all steps but it doesn't seem to work. 

But I'm pretty sure flycheck works because it's giving me warnings for html files... I've been googling and trying different things but nothing seems to work, I'd expect a list of warnings for each js file, am I missing something simple here?

Thanks!

**Comment by lunaryorn** [comment]
@drodrigo Flycheck does not provide built-in support for jslint.  We support [eslint, jshint, and standard](http://www.flycheck.org/en/latest/languages.html#javascript).  If you'd like to use jslint with Flycheck following tips from the EmacsWiki please understand that you are on your own:

> Please be aware that the Flycheck maintainers to not support or endorse any of the following content. Use at your own risk.

jshint should work though.  Could you show us a screenshot of the buffer that pops up when you type `C-c ! v` in a Javascript buffer?

**Comment by drodrigo** [comment]
Hello @lunaryorn 

I see I don't mind using another linter, that was just the first link I've found while googling.

This is the screenshot:

![screen shot 2016-09-12 at 19 25 05](https://cloud.githubusercontent.com/assets/4576630/18455196/dff7a850-791e-11e6-96c6-fb52c36756f8.png)


I also ran jshint -v  to see if it was installed and I got this: jshint v2.9.3.

**Comment by cpitclaudel** [comment]
Looks like Flycheck can't find jshint. Can you try running the command `which jshint` in a terminal?  What does it show?

**Comment by lunaryorn** [comment]
I presume you're running a GUI Emacs on OS X?  Then be aware that GUI applications on OS X run in a different environment than your shell.  In particular they have a default `$PATH` which excludes some important directories for binaries such as `/usr/local/bin/`.

The [exec-path-from-shell](https://github.com/purcell/exec-path-from-shell) package is a popular way to work around this issue:  It makes Emacs copy the `$PATH` from your shell setup.

Please install and setup this package, restart Emacs, and see whether it can now find `jshint`.

**Comment by drodrigo** [comment]
Thanks a lot @cpitclaudel  and @lunaryorn!

It's working now,  using exec-path-from-shell.

I'm a completely Emacs newbie so it didn't sound obivous to me that using GUI Emacs would be a bad idea.

Thanks again for your help :)

**Comment by lunaryorn** [comment]
@drodrigo Oh, a GUI Emacs is a great idea.  I definitely recommend to stick to it; you'll have a better Flycheck experience in a GUI Emacs.  That's just an unfortunate interaction between Emacs and OS X that you've got to be aware of.

**Comment by lunaryorn** [comment]
I'm happy that the issue is solved now!  Have fun using Emacs!
