### ISSUE TITLE
Why be told this？ And How to solve it？

### ISSUE THREAD

**Issue by moyotar** [flycheck/flycheck#1088]
## when I create a buffer below and typed something, I was told "Suspicious state from syntax checker c/c++-cppcheck：checker c/c++-cppcheck return non zero exit code 53， but no errors from output checker definition probably flawed"

//my test.cpp
#include "stdio.h"

int main()
{
  
}

**Comment by cpitclaudel** [comment]
Hi there,

Please adjust the formatting of your post :) 
Additionally, please post the result of `C-c ! v` and `C-c ! C-c` and pick `c/c++-cppcheck`; this will help diagnosing.

Thanks!

**Comment by moyotar** [comment]
Hi, is the formatting you mentioned my code‘s formatting? If it's yes, I'm sorry because I don't know how to insert code with formatting in my post. 

As for your advice to diagnosing, I followed it and got this: 

"cppcheck" "--quiet" "--xml-version=2" "--inline-suppr" "--enable=style" "-x" "c++" "d:/test.cpp"
Compilation exited abnormally with code 53

**Comment by lunaryorn** [comment]
@moyotar It's the whole formatting, not just the code.  Please don't use excessive formatting: There's no need to put your text as a headline.  As for code formatting please take a look at [Github's markup guide](https://guides.github.com/features/mastering-markdown/) or use the "Code" button ("<>") right above the text input.

Please use the "Edit" button to edit your comments and correct the markup, and please take care to format your future comments properly.

**Comment by lunaryorn** [comment]
@moyotar Furthermore, please be aware that we [do not support Windows](http://www.flycheck.org/en/latest/user/installation.html#windows-support).  We may be able to help you, but if this turns out to be a Windows-specific issue we cannot help you.

**Comment by moyotar** [comment]
//test
`printf`

**Comment by moyotar** [comment]
```cpp
//my test.cpp
#include "stdio.h"

int main()
{

}
```

**Comment by moyotar** [comment]
@lunaryorn Ok, I knew flycheck doesn't support Windows at first through the manual. It doesn't really matter because it can still check syntax. And now, I have known how to insert code which is really cool. Thanks!
