### ISSUE TITLE
Add :enabled property to syntax checkers

### ISSUE THREAD

**Issue by lunaryorn** [flycheck/flycheck#1089]
Add a new `:enabled FUNCTION` property to syntax checkers which behaves like `:predicate` except that it's only called the first time a syntax checker is to be used in a buffer.  If the function returns a non-nil value the checker is put in a whitelist (i.e. a buffer-local variable) to prevent further invocations of `:enabled`, and if it returns nil it's put into `flycheck-disabled-checkers` to prevent any further use of it.

This function would allow for more expensive checks whether a syntax checker is available.

Follow up of a [Gitter discussion](https://gitter.im/flycheck/flycheck?at=57d9193da0e8dbb04f377d6a) and #1085.

**Comment by lunaryorn** [comment]
@Simplify I've taken the liberty to assign this issue to you but please feel free to ping me if you don't get to implement it.  I can add it as well tomorrow evening—though, if you'd take it, I'd spend the evening on #1072 😎

**Comment by Simplify** [comment]
yes, I'll take this one, great opportunity to dig dipper into flycheck.

**Comment by Simplify** [comment]
`flycheck-may-use-checker (checker)` is executed every time or only once for every buffer? If only once we can skip maintaining white-listed buffer-list for every checker.

**Comment by lunaryorn** [comment]
@Simplify It runs every time.
