### ISSUE TITLE
Julia linter revisited

### ISSUE THREAD

**Issue by jpfairbanks** [flycheck/flycheck#1091]
I saw a 2 issues about julia support #502 #510. The performance of the julia linter is much better now. https://github.com/tonyhffong/Lint.jl/issues/156#issuecomment-247472017. Can we reopen this discussion in light of the changes to both julialint and flycheck?

**Comment by cpitclaudel** [comment]
Hi @jpfairbanks,

I'd be very happy to see a Julia linter in Flycheck. There are basically two ways to get there:

1. A built-in checker.  This would have to be a simple checker that we can run repeatedly (as opposed to a persistent server).  Consecutive runs should be reasonably fast (I don't mind too much if the first run is a bit slower, but back in the early days of Julia just starting the interpreter took multiple seconds, every time).

2. A separate package.  That one can use a server and get better performance.

I can happily assist with 1.  If that doesn't work sufficiently well, 2 is something that I would probably do if I started looking at Julia again, but I don't know if/when that would happen.

Would you like to try and write a checker definition for Julia (in the style of (1))? It should not take more than a few lines of code, and we'll be happy to assist :)

**Comment by jpfairbanks** [comment]
Yeah I can work on it. What code do I need to write? Where is the docs for that, and an example?
I can get the inprocess version done if it is much less work and then if the performance isn't good enough then work on the server-client version.

**Comment by cpitclaudel** [comment]
Cool. The general docs are here: http://www.flycheck.org/en/latest/; the dev manual was not ported to our new format yet, but you can [download an offline copy of the old one](http://www.flycheck.org/en/latest/_downloads/flycheck.html)

**Comment by lunaryorn** [comment]
@jpfairbanks You may also take a look at the code in #510, or look at previous pull requests for new syntax checkers like #1070 or #1084.  Generally, the Flycheck source itself is the best example for syntax checker definitions—we've got a lot of built-in checkers, each of them is a good example for a syntax checker definition :blush:

**Comment by gdkrmr** [comment]
https://github.com/gdkrmr/flycheck-julia

**Comment by cpitclaudel** [comment]
@gdkrmr Any reason to make this a separate package instead of a PR here?

**Comment by gdkrmr** [comment]
There is no linter using `flycheck-define-generic-checker` in `flycheck`, so I took `flycheck-ocaml` as a template for the general package structure.
Apart from that I have no real reason, if you want to I can make a PR.

**Comment by cpitclaudel** [comment]
Good point.  I'd like to at least add the extension to http://www.flycheck.org/en/latest/community/extensions.html, though; can you make a PR to https://github.com/flycheck/flycheck/blob/master/doc/community/extensions.rst ? :)

**Comment by gdkrmr** [comment]
So you would prefer this to remain a separate package?

**Comment by cpitclaudel** [comment]
Yes, I think so :) I looked at the code, and it's a bit larger than what we usually have in Flycheck.

**Comment by gdkrmr** [comment]
ok, no problem. Should I make the PR to the community extensions now, or wait until I have the whole thing in the emacs repositories (melpa, etc.)?

**Comment by cpitclaudel** [comment]
Waiting for MELPA sounds good. Thanks!

**Comment by gdkrmr** [comment]
Just a thought: The julia server uses the following json format:

https://github.com/steelbrain/linter/blob/master/docs/examples/standard-linter-v2.md

Maybe you want to include this into flycheck, this way you might be able to facilitate the integration of linters that are written for atom.

**Comment by cpitclaudel** [comment]
This could be a good idea; would you like to give it a go?

**Comment by gdkrmr** [comment]
I already have the basic function: https://github.com/gdkrmr/flycheck-julia/blob/master/flycheck-julia.el#L150 it is probably just a matter of including it and renaming it.
https://github.com/gdkrmr/flycheck-julia/blob/master/flycheck-julia.el#L176 is also required to actually create the json object from a string, but should probably be included into the json package.

**Comment by cpitclaudel** [comment]
Instead of https://github.com/gdkrmr/flycheck-julia/blob/master/flycheck-julia.el#L176 , wouldn't `json-read-from-string` work?

Looking at that function, I'm not sure it's large enough to warrant inclusion, but I'm happy to consider a PR.  For example, this:

```
:level (cond
                     ((equal (cdr (assoc 'severity it)) "error")   'error)
                     ((equal (cdr (assoc 'severity it)) "warning") 'warning)
((equal (cdr (assoc 'severity it)) "info") 'info))))
```

is just `(intern  (cdr (assoc 'severity it)))`, really, or at worst `(assoc (cdr (assoc 'severity it)) '(("error" . error) ("warning" . warning) ("info" . 'info)))`

The rest of the code could also be simplified a lot using `let-alist`.

I think you'd find backquotes (`` ` ``) useful too, instead of repeating `setf` (as in ` (setf (alist-get '"show_code" query-list) t)`).

**Comment by gdkrmr** [comment]
I appreciate the help, this is my first `elisp` project, so I am sure that there is a lot of code that can be improved and I will try to include as much as I can.

**Comment by gdkrmr** [comment]
`json-read-from-string` does not work, because the JSON is included inside `[...]`.

**Comment by cpitclaudel** [comment]
Hum? `(json-read-from-string "[1,2,3]")` works for me :)

**Comment by gdkrmr** [comment]
If I remember right, I tried it and it did not work.

**Comment by cpitclaudel** [comment]
Can you show an example?

**Comment by gdkrmr** [comment]
actually you are right, thanks, less code :-) I was pretty sure that I tried that.

**Comment by gdkrmr** [comment]
https://github.com/melpa/melpa/pull/4817

No idea why the tests failed, I did not get a reply yet.

**Comment by robbyoconnor** [comment]
I opted to kill the jade checker because it's more or less deprecated...

**Comment by cpitclaudel** [comment]
There is now a MELPA package for Julia, so closing this issue :)
