### ISSUE TITLE
Use approved reviews as part of our review process

### ISSUE THREAD

**Issue by lunaryorn** [flycheck/flycheck#1094]
Recently Github shipped [code reviews](https://github.com/blog/2256-a-whole-new-github-universe-announcing-new-tools-forums-and-features), a new feature which lets you explicitly approve pull requests or request further changes.  Through protected branches we can now require that there's at least one approved review and no requests for changes for each pull request.

I'd like to incorporate this feature into our review and approval process. My idea is to

* keep LGTM.co to say *"this change is a good addition to add to Flycheck"*, and
* use code reviews to say *"this pull request adheres to our style rules, meets our technical requirements, and works correctly"*, i.e. is *technically sound*.

IOW, separate the "this is a good idea" part of approval from the "this is a good implementation" part.  The former decision would still be left for maintainers (i.e. @cpitclaudel and me currently), but the latter would be available to all contributors, i.e. anyone who's currently got write access to our repo could approve pull requests.

The purpose of this change is to give the language teams and contributors the ability and authority to review changes they're interested independently, so that we as maintainers would only have to steer the general direction of Flycheck but not necessarily be involved in any change to language support.

My aim is to give contributors more impact and influence—it's their project, too, after all—to increase their involvement, while still keeping a guard against scope creep and maintain our fundamental principles (see #1093).

@flycheck/maintainers @flycheck/contributors I'd like to hear your feedback.  I'm particularly interested in whether any of our @flycheck/contributors would use this and review pull requests that they're interested in or that touch the language whose team they are member of.

**Comment by lunaryorn** [comment]
PS: My own personal goal with this move is to take a step back from Flycheck: I simply can't be involved in every single pull request anymore.   

Many of the changes to syntax checkers are beyond me to review—I use but a tiny percent of all the languages that Flycheck supports—and I simply do not have the time to really test every single change made to Flycheck. 

In the past months I've mostly just tried to catch up with the open issues and pull request, and most of the time failed to keep up.  I'd like to get more people involved so that I can shift my focus from PRs for new syntax checkers or languages to the important architectural changes in Flycheck (i.e. #1072 or #774).

**Comment by fmdkdd** [comment]
So if I understand correctly, we shift LGTM.co to mean "this is good idea to work on" rather than "this is a good implementation".  But wouldn't the maintainers want to check the final form of the PR as well before merging?  Any collaborator could merge after an initial LGTM if the technical review is done, even if the final implementation does not meet the maintainers criteria.

So what about a process where maintainers first greenlight a PR, then collaborators can deal with the technical review, then when no changes are required anymore maintainers take a final look and merge?

A benefit of that process it that it would help avoid wasting volunteer's time and goodwill.  Volunteer hours are precious, and we don't want to let them work on something just to say "well, I'm sorry but that wasn't such a good idea in the first place".  A greenlight would help minimize the occurrences of such situations.

And maintainers would still have control over the scope and have final say.  They would still have to look at every PR though.

**Comment by lunaryorn** [comment]
@fmdkdd Yes, that is my plan, for I want the freedom *not* to care for the final technical details of a pull request.  I'd like to maintain control over the scope, I'd like to make sure that I can still reject features which I think do not fit Flycheck, but I do not feel the need to control every single aspect of its implementation anymore.  

Over the past months a bunch of awesome people joined Flycheck, and I trust you to make the right choices 😎  And then, I'm just a contributor as you are—if I'm interested in the nitty gritty details I can still give a PR a technical review and block it by requesting changes.

I presume that initially I'll be doing that a lot, just like now—because partly I still care, partly because I can't just leave you in the cold with technical reviews.  But I'd like to allow for gradually shifting responsibility to contributors.

My idea is also that an initial LGTM serves as a clear commitment to add a change.  In other words a LGTM would commit ourselves to merge a pull request, barring technical issues.

**Comment by fmdkdd** [comment]
@lunaryorn Then I understood you clearly. I sympathesize with your need to step back a bit, and this seems like a good way to maintain guidance over the project.  LGTM.

**Comment by lunaryorn** [comment]
@cpitclaudel What do you think?

**Comment by manuel-uberti** [comment]
If I may share my opinion, I completely understand you, @lunaryorn, and your reasons behind this proposal. LGTM.

**Comment by cpitclaudel** [comment]
I think I like this approach :)

**Comment by lunaryorn** [comment]
Great, thanks for you feedback @fmdkdd @manuel-uberti @cpitclaudel 

I'll make a pull request with the corresponding changes to our documentation, and edit the Github settings once that is done.

**Comment by rski** [comment]
>keep LGTM.co to say "this change is a good addition to add to Flycheck", and
>use code reviews to say "this pull request adheres to our style rules, meets our technical requirements, and works correctly", i.e. is technically sound.
I really like this, but maybe it's kind of counter intuitive and should be made explicit for the benefit of people who haven't submitted PRs before.

**Comment by lunaryorn** [comment]
@rski We'll document that in our contributor's guide, of course.
