### ISSUE TITLE
Display errors in window title

### ISSUE THREAD

**Issue by Wilfred** [flycheck/flycheck#1095]
I use the minibuffer for eldoc, so I've started using flycheck-pos-tip to show the flycheck error at point. However, this popup sometimes hides code that I want to see whilst typing.

How about adding support for showing errors in the window title, in a similar style to the minibuffer? Would you be open to adding this to flycheck, or does it belong in an external package?

**Comment by lunaryorn** [comment]
@Wilfred Hello.  Thanks for reporting this issue.

I'm not sure what you have in mind, though.  Emacs doesn't have "window titles" as far as I know—there are "buffer names" and there is the "frame title".  Which ones do you mean?

Could you perhaps produce an annotated screenshot of a GNU Emacs frame to point out where you'd like to show error messages?

**Comment by Wilfred** [comment]
Sorry, yes, I meant frame title.

Here's a mockup:

![flycheck_frame_title](https://cloud.githubusercontent.com/assets/70800/18637075/339aaefa-7e59-11e6-88c4-614d40d4983c.png)

**Comment by lunaryorn** [comment]
@Wilfred That's a very nice idea, but I think it's beyond our scope.  There's `frame-title-format` which lets you put arbitrary content in the frame title, but that's a user option and not for us to change.

I'm sorry but you'll have to implement it yourself.  It shouldn't be too difficult as you can essentially write a function that returns the first line of the error at point if any, i.e. `(car (split-string (flycheck-error-format-message-and-id (car (flycheck-overlay-errrors-at-point (point)))) "\n"))` minus any nil checks, and put that into an [`(:eval …)` element](https://www.gnu.org/software/emacs/manual/html_node/elisp/Mode-Line-Data.html).  Should you decide to make a package of it we'll happily help you, and provide a repository within the Flycheck organisation if you're interested.

But it's not something that could become part of Flycheck in my opinion.  I'm closing as `wontfix`.

**Comment by Wilfred** [comment]
Thanks :)

I'll send a docs PR with a URL when I've got something working.

**Comment by Wilfred** [comment]
FWIW, I've finally got around to releasing a package that does this: https://github.com/Wilfred/flycheck-title

**Comment by lunaryorn** [comment]
@Wilfred Awesome, loving it 😍  Could you ping me again on this discussion when it's up on MELPA?  I'd like to add it to our list of extensions, and probably also to my own configuration :blush:

**Comment by Wilfred** [comment]
We're up on MELPA! http://melpa.org/#/flycheck-title :blush:
