### ISSUE TITLE
How to disable evil-mode in *Flycheck errors* buffer

### ISSUE THREAD

**Issue by 0x4ec7** [flycheck/flycheck#1096]
Hi,

I am using both evil-mode and flycheck-mode, when I enter flycheck errors buffer, keys are binded to evil-mode, I cannot use q for quitting. 

How to turn-off-evil-mode just in *Flycheck errors* buffer?

Thanks!

**Comment by lunaryorn** [comment]
@0x4ec7 There's `flycheck-error-list-mode-hook` which runs when creating the error list.  I guess you could hook `turn-off-evil-mode` here.

That said, please understand that cannot support evil-mode.  I'm closing this issue as `invalid`.

**Comment by 0x4ec7** [comment]
Hi @lunaryorn, that's what i needed, thanks a lot!

**Comment by lunaryorn** [comment]
@0x4ec7 You're welcome; I'm happy that I could help :blush:
