### ISSUE TITLE
Document buffer local bindings for flycheck-checkers

### ISSUE THREAD

**Issue by lunaryorn** [flycheck/flycheck#1097]
#1072 will remove manual syntax checker selection with `C-c ! s` because the semantics are hard to get right in combination with stages.

To replace this feature let's support, document and encourage buffer-local bindings for `flycheck-checkers`, notably with Directory Variables, so that people can just put their preferred choice of checkers in a `.dir-locals.el` and don't worry about disabling, etc.

After #1072, see project.

**Comment by cpitclaudel** [comment]
We didn't complete #1072, so I don't think we need to keep this open.
