### ISSUE TITLE
Make it possible to show longer ID

### ISSUE THREAD

**Issue by Mekk** [flycheck/flycheck#1101]
**The problem**

I use flycheck for python code, where it wraps pylint. In default configuration it shows error (in `*Flycheck errors*` as sth like: 
`
   87   5 warning  no-... Method could be a function (python-pylint)
`
I find fourth column (ID, `no...` in this case) problematic. It is useful – I need this identifier whenever I want to disable given message (by inserting it into ~/.pylintrc or making steering comment like `# pylint:disable=no-self-use`) or simply google for details. But it is so heavily truncated that it is unreadable.

So, please, make it somehow possible to see whole `ID` of error/warning I look at.

**Suggested solutions**

Below a few ideas (from imperfect but probably simple to implement, to more difficult):
1. For time being I simply edited `flycheck-error-list-format` in `flycheck.el`, changing id column spec to `("ID" 15 t)`. It's not perfect (lost space on checkers without identifier), but much better (whole `no-self-use` fits, and for longer messages prefix is long enough to distinguish). Unfortunately I must re-edit this variable on every flycheck upgrade.
   
    So, it would be nice, if some parts of this variable (column widths?, column widths and names?) could be customizable, or at least easily modifiable from .emacs (say by being put into simpler, non-const variable).
2. Even better, if ID colum width could be matched to the context - expanded to sth like 15-20 chars for backends which use long IDs, truncated to few chars for modes/backends which use short numerical codes, hidden for backends which do not apply them at all. This could be either configurable by backend (say, backend somehow reports "I don't use ID"/"I use short IDs"/"I use long IDs") or just calculated dynamically from actual errors (just make column wide enough to fit longest code, with some limit)

**Related suggestions**

Whenever ID is truncated, three characters (three dots) are used to signal the fact. Especially in 5 chars case this does not make sense. Unicode … (three-dot character) takes one char. Not sure whether this is possible to modify from your code level but maybe tabulated list has some arg somewhere. Or maybe ID could be truncated this way before being fed to list…

**Comment by lunaryorn** [comment]
Thank you for reporting this issue.  I understand that it's a nuisance, but to me it's not important to fix to be honest: It affects only a single syntax checker, which I don't use personally.   Personally I'll not fix this anytime time soon.

While it'd be great if the error list automatically changed column widths according to the content that's probably hard to implement since there's no support for this in Tabulated List Mode.

I'd be great if you could research to find out whether that's possible, and maybe open a pull request.  If not I'd also be very happy to review a pull request that makes the format customizable.  

For now, you could either switch to numeric IDs in pylint, or use [`M-0 C-c ! w`](http://www.flycheck.org/en/latest/user/error-interaction.html#key-M-0%20C-c%20!%20w) to copy the error ID at point.

**Comment by cpitclaudel** [comment]
Hi @Mekk,

As a side note, I use pylint as well, and in general I just mouse over the error that I want to suppress.  This makes it easy to see what the error id is.

**Comment by cpitclaudel** [comment]
> Whenever ID is truncated, three characters (three dots) are used to signal the fact. Especially in 5 chars case this does not make sense. Unicode … (three-dot character) takes one char. Not sure whether this is possible to modify from your code level but maybe tabulated list has some arg somewhere. Or maybe ID could be truncated this way before being fed to list…

See `truncate-string-ellipsis`: you want to `(setq-local truncate-string-ellipsis "…")` in the error list.

**Comment by cpitclaudel** [comment]
> While it'd be great if the error list automatically changed column widths according to the content that's probably hard to implement since there's no support for this in Tabulated List Mode.

Hmm. I'm not sure about this.  Some error IDs are long, and most of the time I don't care about the id of an error.

What about setting a mouseover text on error IDs instead? I'll open a PR.

**Comment by lunaryorn** [comment]
> See truncate-string-ellipsis: you want to (setq-local truncate-string-ellipsis "…") in the error list.

Should we make that the default?

**Comment by cpitclaudel** [comment]
Hmm.  I'm not sure.  We'd have to check that it doesn't cause alignment problems (it works for me because my default font includes '…', but I don't know how it would behave otherwise. @Mekk, can you check?

**Comment by x-ji** [comment]
Is there a way to fix the width of `id` column to be much longer than the default? Apparently this doesn't only occur with `pylint`: I'm having this issue with `eslint` for Javascript as well. Was just going to post an issue before seeing this one on top of the issue list.

**Comment by x-ji** [comment]
I should be able to manually set the by changing the number in `flycheck-error-list-format` right?

**Comment by cpitclaudel** [comment]
> I should be able to manually set the by changing the number in flycheck-error-list-format right?

Right.

**Comment by lunaryorn** [comment]
@cpitclaudel I'd say we should just try.  I don't think that many people still run Emacs on TTYs that aren't capable of unicode, and I don't think that there are many fonts that lack the ellipsis character.

**Comment by lunaryorn** [comment]
> Actually I suggest using a larger default value in the file... A lot of "id"s are actually text descriptions instead of numbers, and that's a better way to help the user as well, I'd say.

Why can you say that?  How many syntax checkers did you check?

> Also, the right-hand side of the error list display usually still has a lot of space left.

How large is your screen?

**Comment by x-ji** [comment]
@lunaryorn Well apparently both `pylint` and `eslint` are used by the majority in Python and Javascript respectively, which are extremely popular languages.

1920 x 1080. Even after increasing the column width here I still have 1/3 of space left.

I disagree that id is not useful. It helps people to locate the relevant section in the styleguide, which has longer explanations than a one-liner.

Anyways, if you decide not to do so, I guess you may at least add a section in README/quick start guide to tell people how to change the column width by themselves, if they want to, or make that option easily customizable. AFAIK currently they'll have to look through the source code themselves, if I'm not mistaken.

**Comment by cpitclaudel** [comment]
@x-ji Did you try putting your mouse over the error id? We've just pushed an update that shows the full id as a tooltip.  Does that help, or would you rather always see the full error id?

**Comment by cpitclaudel** [comment]
At this point we've implemented two workarounds to mitigate this issue. @Mekk, @x-ji, can comment on whether these are sufficient? :)

**Comment by Mekk** [comment]
a) truncate-string-ellipsis doesn't work on Emacs 24.5.1 (mule-util.el as distributed with this version does not support this variable yet). Once I downloaded newer version from https://raw.githubusercontent.com/emacs-mirror/emacs/master/lisp/international/mule-util.el  it works nicely, 2 letters more.

b) I do not quite understand what "help-echo" change brings (is it sth emacs-version related?)

c) I still would be happier if ID column width could be bigger (customizable or fit to mode). For my personal use I keep editing flycheck-error-list-format to increase this number.

**Comment by cpitclaudel** [comment]
> b) I do not quite understand what "help-echo" change brings (is it sth emacs-version related?)

The usual wording for this is "mouse-over tooltip", I think :) IOW, you can now put your mouse on a warning and see it untruncated.

**Comment by aminorex** [comment]
(package-install 'flycheck) gave me

> In flycheck-error-list-mode:
> flycheck.el:3889:15:Warning: assignment to free variable
>     `truncate-string-ellipsis'

so I changed setq-local to:

  (setq truncate-string-ellipsis "…")
  (make-local-variable 'truncate-string-ellipsis)

and it works for me now.

**Comment by cpitclaudel** [comment]
@aminorex I think this is fine; it's just the byte-compiler not being very smart.

**Comment by eflanigan00** [comment]
Any update on making the ID column larger? Or placing some variable that allows the user to set the width? The tooltip is a nice feature but I'd like to see the full ID.  If you are trying to save space you can truncate the Level and use W for warning, E for Error, I for info.

**Comment by fmdkdd** [comment]
@eflanigan00 The width of the ID column is set in `flycheck-error-list-format`:
```elisp
(defconst flycheck-error-list-format
  `[("Line" 5 flycheck-error-list-entry-< :right-align t)
    ("Col" 3 nil :right-align t)
    ("Level" 8 flycheck-error-list-entry-level-<)
    ("ID" 6 t)
    (,(flycheck-error-list-make-last-column "Message" 'Checker) 0 t)]
  "Table format for the error list.")
```
Changing that value is enough to get the result you want.

Granted, that's a `defconst`, so you'd have to modify the source.  The better way is to override the `tabulated-list-format` value for the errors list buffer.  Since it's a derived mode,  there's a hook for that:
```elisp
  (add-hook 'flycheck-error-list-mode-hook
            (lambda ()
              (setq tabulated-list-format '[("Line" 5 flycheck-error-list-entry-< :right-align t)
                                            ("Col" 3 nil :right-align t)
                                            ("Level" 8 flycheck-error-list-entry-level-<)
                                            ("ID" 20 t)
                                            (#("Message (Checker)" 0 9
                                               (face default)
                                               9 16
                                               (face flycheck-error-list-checker-name)
                                               16 17
                                               (face default))
                                             0 t)])))
```
Not the most friendly, but it works.

I'm not against making the width configurable.  The straightforward option would be to use that new variable in the definition of `flycheck-error-list-format`.  The variable would only have an effect when you load flycheck however, so you couldn't adjust it aferwards.  Dynamically changing the width would be more involved.

Feel free to send a PR!

**Comment by cpitclaudel** [comment]
> Granted, that's a defconst, so you'd have to modify the source.

Not really, you can `setq` a `defconst` just fine.  So you could adjust `flycheck-error-list-format` in a `with-eval-after-load` block.

**Comment by fmdkdd** [comment]
> Not really, you can setq a defconst just fine.

Emacs-lisp is crazy.  I did not even try, thinking "Well, it wouldn't be const if you could change it".  Thank you for correcting :)

I'd say it's an acceptable workaround.

**Comment by zoechi** [comment]
Is there some better solution now (it's almost 10 years after all)?
With lsp-mode this is an issue in every language.
