### ISSUE TITLE
flycheck Fortran question

### ISSUE THREAD

**Issue by wadudmiah** [flycheck/flycheck#1103]
I have added the following option in my ~/.emacs file so that it uses the Fortran 2008 standard when checking syntax using Flycheck (as suggested in http://www.flycheck.org/en/latest/_downloads/flycheck.html#Fortran):

`(flycheck-gfortran-language-standard 2008)`

When I load emacs, I get the following error messages:

```
Warning (initialization): An error occurred while loading `/home/wadud/.emacs':
Symbol's function definition is void: flycheck-gfortran-language-standard
```

Any help will be greatly appreciated.
Regards, Wadud.

**Comment by lunaryorn** [comment]
@wadudmiah `flycheck-gfortran-language-standard` is a user option, not a function, and it's value is a string, so you'd have to use `(setq flycheck-gfortran-language-standard "2008")`. 

If you are not familiar with Emacs Lisp we recommend to use the Customize interface via `M-x customize-variable RET flycheck-gfortran-language-standard`.  Please also take a look at the [Introduction to Emacs Lisp](https://www.gnu.org/software/emacs/manual/eintr.html).

**Comment by wadudmiah** [comment]
Hi lunaryorn,

thanks for answering my question which has fixed the issue. I am not familiar with Lisp at all and need to read up on it more. 

Thanks again,
Wadud.
