### ISSUE TITLE
[Flake8] show descriptive warning in modeline if version < 3.0

### ISSUE THREAD

**Issue by thisch** [flycheck/flycheck#1107]
Since you have updated the required version of flake8 to 3.0 for the python checker in the master branch, it would be nice if an error/warning is shown in the modeline if the installed flake version is < 3.0. ATM you get the `flake8: error: no such option: --stdin-display-name` error, which is hard to understand if you don't know that you need to update flake8 The version checking also applies to other flycheck checkers, of course.

**Comment by lunaryorn** [comment]
@thisch I'm sorry, but as a policy we do not show such warnings for syntax checkers; version checks would cause to much maintenance effort and quickly lead to accumulated technical debt.  

Please downgrade Flycheck, or copy the flake8 definition from older releases, and please follow Flycheck's changelog for notifications about breaking changes.
