### ISSUE TITLE
RFC: Removing the :safe predicate of flycheck-disabled-checkers 

### ISSUE THREAD

**Issue by cpitclaudel** [flycheck/flycheck#1109]
Hi there,

`flycheck-disabled-checkers` currently has a `:safe` predicate set to `#'flycheck-symbol-list-p`.  This doesn't seem ideal: it lets files re-enable checkers that the user had explicitly disabled. For example, if one of our users has enabled `flycheck-global-mode` but disabled e.g. the emacs lisp checker because it is unsafe, then any ELisp file can re-enable the unsafe checker simply by setting `flycheck-disabled-checkers` as a file-local variable.

Data point: there *are* a few examples of people using this variable file-locally on Github, so this change could create a slight inconvenience for these people.  See https://github.com/search?p=5&q=flycheck-disabled-checkers+local+variables&ref=searchresults&type=Code&utf8=%E2%9C%93

Do we have strong objections to just marking this variable as risky?

**Comment by lunaryorn** [comment]
@cpitclaudel I would not want to do that, for I presume that the typical use of this variable is via directory variables—which you wouldn't find on GitHub for typically you don't commit `.dir-locals.el` to the repository.

To me `flycheck-disabled-checkers` is not a safety measure; it's for user configuration.  If we care for security we should make that explicit, i.e. mark insecure syntax checkers as such and ask the user in advance whether they'd like to use insecure syntax checkers in the current buffer.  The whitelist variable behind that choice would be `:risky`, but it'd also overrule any other configuration, so Flycheck wouldn't use any insecure syntax checker not in the whitelist.

We've already got a [milestone for this topic](https://github.com/flycheck/flycheck/milestone/10), but to me personally that's low priority.   If anyone takes it I'm happy to merge stuff, but I won't start working on it any time soon, at least not before https://github.com/flycheck/flycheck/milestone/11 and https://github.com/flycheck/flycheck/milestone/5.

**Comment by cpitclaudel** [comment]
Ok :) Let's close this then.
