### ISSUE TITLE
Previously working setup now raises flake8 error

### ISSUE THREAD

**Issue by el-ethan** [flycheck/flycheck#1112]
After updating some Emacs packages yesterday, I now get this error every time a Python buffer is modified if `flycheck-mode`/`global-flycheck-mode` is enabled:

    Suspicious state from syntax checker python-flake8: Checker python-flake8 returned non-zero exit code 2, but no errors from output: Usage: flake8 [options] input ...

    flake8: error: no such option: --stdin-display-name

    Checker definition probably flawed.

Here are the results of `flycheck-verify-setup`:

    python-flake8
        - predicate:          t
        - executable:         Found at /usr/bin/flake8
        - configuration file: Not found

    python-pylint
        - predicate:          nil
        - executable:         Not found
        - configuration file: Not found

    python-pycompile
        - predicate:  t
        - executable: Found at /usr/bin/python

    Flycheck Mode is enabled.  Use C-u C-c ! x to enable disabled
    checkers.

    --------------------

    Flycheck version: 30snapshot (package: 20160927.141)
    Emacs version:    24.5.1
    System:           x86_64-unknown-linux-gnu
    Window system:    x

And the results of running `flycheck-compile` in a Python buffer with `python-flake8` as the checker:

    flake8 --format\=default --stdin-display-name /home/ethan/Dropbox/development/miniquadmaps/flywithme/topspots/views.py - < /home/ethan/Dropbox/development/miniquadmaps/flywithme/topspots/views.py
    Usage: flake8 [options] input ...

    flake8: error: no such option: --stdin-display-name
    
    Compilation exited abnormally with code 2 at Tue Sep 27 10:43:07

I have not changed any configuration in my init file, and the only configuration I have for `flycheck` is:

    (use-package flycheck
      :init
      (global-flycheck-mode))

I am on Ubuntu 16.04, my Emacs version is `24.5.1`, and my `flycheck-version` is `30snapshot (package: 20160927.141)`. 

Finally, in case it is useful, here is my `flake8` version information:

    2.5.4 (pep8: 1.7.0, mccabe: 0.2.1, pyflakes: 1.1.0) CPython 3.5.2 on Linux

Any idea what is going on? Is this an issue with `flycheck`? With `flake8`? With something else? I am able to reproduce this issue when opening Emacs with the `-Q` option, running `M-x package-initialize` and `M-x flycheck-mode`. Please let me know if I can provide any more information that would be helpful for diagnosis. Thank you!

**Comment by cpitclaudel** [comment]
Your flake8 is out of date :) Thanks for the detailed issue write-up, though!

**Comment by lunaryorn** [comment]
See #1107 and #1078. The latest Flycheck release requires Flake8 3.

**Comment by el-ethan** [comment]
Thank you for the quick responses! `sudo pip install flake8 --upgrade` got me up to `flake8` version `3.0` and everything works again!

**Comment by spencerahill** [comment]
Not sure who is in charge of the conda builds for flake8, but it would be nice to update those to version 3.  The latest version of flake8 on conda is 2.5.1 (for python 2.7, 3.4, and 3.5, via `conda search flake8`).  

I ended up with this error and it took me a while to figure it out, because I had incorrectly assumed that the version on conda would be sufficiently new.  Thanks!

**Comment by lunaryorn** [comment]
@spencerahill Ok, great.
