### ISSUE TITLE
choosing a different Fortran compiler

### ISSUE THREAD

**Issue by wadudmiah** [flycheck/flycheck#1117]
Hi again, 

I was wondering if you could get Flycheck to use a different Fortran compiler? At the moment, it uses gfortran and wondered whether Flycheck could be configured to use Intel Fortran or NAG Fortran. 

Thanks in advance,
Wadud.

**Comment by lunaryorn** [comment]
@wadudmiah Provided that these compilers have the same command line interface and error output as `gfortran` you can run `M-x flycheck-set-checker-executable RET fortran-gfortran RET /path/to/intel/fortran/compiler`.  Internally this command sets the option `flycheck-fortran-gfortran-executable` which you can change in your init file or customize for global changes.

If the command line interfaces are different then we'd new separate syntax checker definitions.

**Comment by wadudmiah** [comment]
Hi Sebastian, the command line arguments for Intel and NAG Forrtan are very different for gfortran, so I think I will just keep gfortran for now. I think gfortran's error checking capabilities have improved a lot over the years. 

Cheers,
Wadud.
