### ISSUE TITLE
Require normal merges for pull requests

### ISSUE THREAD

**Issue by lunaryorn** [flycheck/flycheck#1118]
Currently we let contributors choose whether to squash/rebase-merge or merge normally.  Now, @cpitclaudel realized that the former two options naturally loose commit signatures which is a bad thing.

Should we disable squash and rebase merges and instead require normal merges for all pull requests?  The upside is that normal merges preserve commit signatures and provide nice references to pull requests in graph logs, but the downside is that we would always need to ask contributors to cleanup their commit history, i.e. squash commits, fix typos, write commit messages according to our style guide, etc…

@flycheck/contributors @flycheck/maintainers Your opinions?

**Comment by fmdkdd** [comment]
I'm in favor of normal merges, as it preserves the PR history.  

I don't understand the downside however.  Even when squash-merging, wouldn't the code already need to match the style guide?  In other words, as it stands now, a contributor code is always merged as it stands when there are no more changes requested.  I don't think I've seen you or @cpitclaudel cherry-pick pull requests.

So, no change on that front.  Though it certainly requires more work from the contributors, but I would argue it's good practice anyway.

**Comment by aaronjensen** [comment]
> I'm in favor of normal merges, as it preserves the PR history.

I'm not sure I follow this. It doesn't preserve the PR history if we ask them to manually rebase and squash. If we do a squash-merge then the PR has its history as it happened and what we get in master is more clean.



> Now, @cpitclaudel realized that the former two options naturally loose commit signatures which is a bad thing.

To play devil's advocate, why is this a bad thing? Few people sign their commits (we're not requiring it are we?). Not only that, but if we use the github interface *at all* we will have unsigned commits--the merge commit will be unsigned. For us to really embrace signed commits we would need to merge manually on our own machines.

**Comment by lunaryorn** [comment]
@fmdkdd We didn't cherry-pick PRs recently, though I did that in the past, before we opened up to more contributors, but I do occasionally use a squash-merge to explicitly write my own commit message that clarifies the intend of the change.  If I had intended a normal merge I'd have asked to contributor to rewrite their commit message in these cases.  To me it's fine either way, but to the contributor it's more work.

And I'm not so much concerned about a PR history—most of it isn't really relevant later on.  But I care about clear commits with self-contained changes, and that will require contributors to rewrite their history before we merge.  

@aaronjensen For sure, but given that we have so few signatures we shouldn't throw away any should we?  Signatures increase the trust in our repo—we don't require them yet, but we may at some point (like we may require 2FA for all members of our Github org at some point as well), and we do already require signed release tags.

**Comment by spwhitton** [comment]
https://joeyh.name/blog/entry/our_beautiful_fake_histories/

**Comment by fmdkdd** [comment]
@aaronjensen I meant that, to me, a commit history is more interesting if it retains a trace of the PR through merge commits, hence I favor normal merge over rebasing.  The history of the PR itself, how it evolved after code reviews, will always be forfeit anyway since the current policy is to squash, either by force-pushing the PR branch or using squash-merge.

On a related note, I don't really know what's the custom for pushing to pull requests in flycheck, or if there is one.  Sometimes I've added new commits, then rebased and force-pushed when the PR was done so it could be merged.  Other times I've amended and force-pushed to the PR branch.  Is there a favoured way to do it?  If we do require normal merges, I guess we should state up front how these should play out, since contributors will have to deal with it.

**Comment by lunaryorn** [comment]
@fmdkdd As long as we're reviewing the PR do whatever you like best, whatever you are comfortable with.  As far as Flycheck is concerned it's fine if you clean up only just before merging.

Of course we'll document our merge policy, for maintainers and for contributors.  I think it's very important that new contributors in particular get a clear idea how a pull request proceeds and what we expect at each stage.  So yes, whatever policy we end up with, it'll be in the contributor's guide and in the PR message template.  

My secret dream would be a bot that automatically adds a comment to each new pull request that contains detailed instructions about how to proceed, including a review checklist, etc. but I haven't found any service for that and we've got more urgent issues anyway :blush:

**Comment by cpitclaudel** [comment]
I'm not a big fan of bushy git histories  In most cases, the way I use a PR is to get a second pair of eyes on the code that I write, just like I would send a patch to a mailing list before applying it in other projects.  Recording this as a merge seems unnecessary to me.

My vote would be to go for squash and merge (or rebase and merge when there's a single commit) for typical PRs from external contributors.  For devs, I think preserving the signatures is a great feature, so I'd favor cherry-picking.

I'm fine with going all-merge though.  But I'd still like to squash before merging.  This makes it much nicer to look at the history of a change, and this is something I do pretty often to understand how code came to be what it is.  Knowing that all steps on the path are good steps is a useful feature :)

**Comment by aaronjensen** [comment]
> The history of the PR itself, how it evolved after code reviews, will always be forfeit anyway since the current policy is to squash, either by force-pushing the PR branch or using squash-merge.

If we use squash-merge we still maintain the history in the pull-request itself (on the pull-request page, in the secret pr branch), we just lose it on master. To be honest though I wouldn't argue that this is a huge value, the history of an individual branch itself, if they're so reasonably small that we'd want to squash it probably isn't that valuable in practice.

> My vote would be to go for squash and merge (or rebase and merge when there's a single commit) for typical PRs from external contributors.

I agree. For single commits are rebase and merge the same as squash and merge? Or does rebase and merge actually create a merge commit?

> For devs, I think preserving the signatures is a great feature, so I'd favor cherry-picking.

Do signatures survive cherry picking? I would think that the integrity of the commit would include the parent. Maybe I'm misunderstanding, or maybe we're just effectively talking about fast-forward merges here.

> like we may require 2FA for all members of our Github org at some point as well

👍  I'm for that today. W/o a way to do verified commits/merges via github (which I realize would be tricky) I wouldn't vote for requiring verified commits (is this a setting yet? or would we just have to police it?)

**Comment by cpitclaudel** [comment]
> I agree. For single commits are rebase and merge the same as squash and merge? Or does rebase and merge actually create a merge commit?

Squash and merge modifies the commit message (it adds the issue number), even for single commits.

> > For devs, I think preserving the signatures is a great feature, so I'd favor cherry-picking.

> Do signatures survive cherry picking? I would think that the integrity of the commit would include the parent. Maybe I'm misunderstanding, or maybe we're just effectively talking about fast-forward merges here.

My suggestion is that devs can cherry-pick and re-sign. But you're right that the current GitHub model doesn't let us do this (only members with direct push access can, and only for their own commits). Hmm...
