### ISSUE TITLE
Remove the dash dependency

### ISSUE THREAD

**Issue by swsnr** [flycheck/flycheck#1127]
As soon as we require Emacs 25 for Flycheck we might be able to replace all instances of `-when-let` and `-if-let` from dash with the corresponding `when-let`/`if-let` from `subr-x` and thus finally get rid of `dash.el` so as to limit ourselves to built-in libraries.

**Comment by Fuco1** [comment]
Just be aware that they behave a bit differently, so simple regexp-replace might break things (I think binding order is different as well as the behaviour with multiple bindings).

**Comment by lunaryorn** [comment]
@Fuco1 In how far are they different?

As for the "single tuple thing" I actually like that.  I know that Flycheck's code uses the flat `-when-let` in a couple of places, but in hindsight I'd not have used it.  `let` doesn't have a flat-form either, so for consistency `when-let` shouldn't have one as well.

**Comment by Fuco1** [comment]
Well, in dash you had to use the star form to bind multiple forms (that was the only way actually) and it always runs sequential.  It seems subr now does the same.  But ISTR it used the classic `let` way to bind the variables.  And there is no "parallel" version now.

So aside for the single tuple thing it seems to work the same.  Hmm.

**Comment by swsnr** [comment]
This issue wasn't updated in a long time, and I am no longer interested, so I'm closing this issue to clean up my issues list.
