### ISSUE TITLE
Cannot find golang 

### ISSUE THREAD

**Issue by nitingupta910** [flycheck/flycheck#1131]
I'm using go 1.7.1 and have some vendored packages (like google.golang.org/grpc). However, when flycheck is enabled in go-mode, it always complains about packages like google.golang.org/grpc  not found:
```
Ignored `error` returned from `could not import google.golang.org/grpc (cannot find package "google.golang.org/grpc" in any of:`

could not import google.golang.org/grpc (cannot find package "google.golang.org/grpc" in any of:
```

M-x flycheck-verify-setup:
```
Syntax checkers for buffer main.go in go-mode:

  go-gofmt
    - may enable: yes
    - executable: Found at /usr/bin/gofmt

  go-golint
    - may enable: yes
    - executable: Found at /home/ngupta/bin/golint

  go-vet
    - may enable:  yes
    - predicate:   t
    - executable:  Found at /usr/bin/go
    - go tool vet: present

  go-build
    - may enable: yes
    - predicate:  t
    - executable: Found at /usr/bin/go

  go-test
    - may enable: yes
    - predicate:  nil
    - executable: Found at /usr/bin/go

  go-errcheck
    - may enable: yes
    - predicate:  t
    - executable: Found at /home/ngupta/bin/errcheck

  go-unconvert
    - may enable: yes
    - predicate:  t
    - executable: Found at /home/ngupta/bin/unconvert

Flycheck Mode is enabled.  Use C-u C-c ! x to enable disabled
checkers.

--------------------

Flycheck version: 30snapshot (package: 20161004.1257)
Emacs version:    25.1.50.1
System:           x86_64-pc-linux-gnu
Window system:    x
```

M-x emacs-version:
```
GNU Emacs 25.1.50.1 (x86_64-pc-linux-gnu, GTK+ Version 3.18.9) of 2016-09-20
```

I'm using glide to fetch vendor packages:
https://github.com/Masterminds/glide

**Comment by nitingupta910** [comment]
My $GOPATH/src was a symlink which was probably confusing emacs lisp side of scripting (since running various go tools directly from CLI always worked). I copied over the src folder to GOPATH and now it's all working. Closing the issue.

**Comment by imdaveho** [comment]
This issue is not resolved. I have the same issue. glide creates a ./vendor folder with all the dependencies in the project directory (not $GOPATH). You would install dependencies with `glide get` or `glide install` and this has nothing to do with the src directory in $GOPATH.

For example, I have go-mysql-driver as a dependency fetched with glide. Once I import it with emacs, Flycheck gives me an error that it can't find the package and says it's looked in the global src and the $GOPATH src...but it had not checked the project root's vendor directory.

Here is a view of my project directory:
```
<project-name>/
    |- .gitignore
    |- .glide
    |- glide.lock
    |- glide.yaml
    |- main.go
    |- source/
         |- example-pkg/
            |- example.go
    |- vendor/
        |- github.com/go-mysql-driver/mysql/...
    |- workspace ($GOPATH)/
        |- github.com/imdaveho/<symlink-to-source-directory>/example-pkg/example.go

main.go
-------------------
package main

import (
    "github.com/imdaveho/source/example-pkg"
    "database/sql"
    _ "github.com/go-mysql-driver/mysql"    <--- Flycheck Error!!!!
)

func main() {
    ...
}

example.go
-------------------
package example

import "fmt"

func ExecExample() {
    fmt.Println("Hello, World!")
}
```
