### ISSUE TITLE
systemd unit checker

### ISSUE THREAD

**Issue by holomorph** [flycheck/flycheck#1135]
i feel silly for having written this, but here you go! I just realized systemd-analyze had this, but in my brief testing: the line numbers the tool outputs are questionable, but the messages are useful and accurate.
```
(flycheck-define-checker systemd-analyze
  "A systemd unit checker using systemd-analyze(1).

See URL `https://www.freedesktop.org/software/systemd/man/systemd-analyze.html'."
  :command ("systemd-analyze" "verify" source-original)
  :error-patterns
  ((error line-start "["
          (file-name) ":" line "] " (message) line-end))
  :modes (systemd-mode))
```

**Comment by cpitclaudel** [comment]
Looks very nice, thanks!  I think we'd be happy to include this by default with Flycheck.  However, can you package this snippet as a pull request, with corresponding updates to the manual?

Thanks!

**Comment by manuel-uberti** [comment]
Interesting indeed, please open a PR. :+1:
