### ISSUE TITLE
Javascript-eslint not working 

### ISSUE THREAD

**Issue by zimski** [flycheck/flycheck#1137]
Hello guys,

I have some trouble to run `javascript-eslint` on my project.
The get this issue after updating all my packages, I am using (spacemacs)

```
Syntax checkers for buffer httpheaders.js in js2-mode:

  javascript-eslint (disabled)
    - may enable:  Automatically disabled!
    - executable:  Found at /home/zimski/.nvm/v0.12.7/bin/eslint
    - config file: missing

  javascript-jshint (disabled)
    - may enable:         yes
    - executable:         Found at /home/zimski/.nvm-fish/v0.12.7/bin/jshint
    - configuration file: Found at "/home/zimski/.jshintrc"

  javascript-gjslint (disabled)
    - may enable:         Automatically disabled!
    - executable:         Not found
    - configuration file: Not found

  javascript-jscs (disabled)
    - may enable:         Automatically disabled!
    - executable:         Not found
    - configuration file: Not found

  javascript-standard (disabled)
    - may enable: Automatically disabled!
    - executable: Not found

Flycheck Mode is enabled. Use SPC u C-c ! x to enable disabled checkers.

--------------------

Flycheck version: 31snapshot (package: 20161012.433)
Emacs version:    24.5.2
System:           x86_64-unknown-linux-gnu
Window system:    x
```

JsHint is working but Impossible to run eslint

When i am forcing to use `eslint` by `M-x flycheck-select-checker javascript-eslint`
I get this
```
Syntax checker in buffer  *Flycheck checkers* in help-mode:

  javascript-eslint
    - major mode:  `help-mode' not supported
    - may enable:  Automatically disabled!
    - executable:  Found at /home/zimski/.nvm/v0.12.7/bin/eslint
    - config file: missing

Flycheck cannot use this syntax checker for this buffer.

Flycheck Mode is disabled. Use SPC u M-x flycheck-disable-checker to enable
disabled checkers.

--------------------

Flycheck version: 31snapshot (package: 20161012.433)
Emacs version:    24.5.2
System:           x86_64-unknown-linux-gnu
Window system:    x
```

I have `.eslintrc` in the root of the folder but flycheck can't find it

My OS is Ubuntu 16.04

Thx for your help !

**Comment by Simplify** [comment]
Hi @zimski ,

Please make sure that your ESlint configuration is valid. Run `eslint --print-config .` in your project directory. If your configuration is in error, you will see that in output. 

Flycheck will run same command once you open new js2 buffer to determine is ESlint can be used. Also, Flycheck does not search for your config file, we left that to ESlint. 

As side note, `.eslintrc` is deprecated, use [JSON or YAML format](http://eslint.org/docs/user-guide/configuring#configuration-file-formats).

**Comment by zimski** [comment]
Thanks for your quick reply

I verified my `eslintrc` config and it's ok
I execute `eslintrc -c .eslintrc file.js`  and it's OK

Btw, I am using an old version of eslint with an old version of node :)
```
node --version : v0.12.07
eslint --version: v1.10.1
```

**Comment by Simplify** [comment]
Yeah, I saw `Found at /home/zimski/.nvm/v0.12.7/bin/eslint` in your issue, that's why I edited my comment and asked about ESlint version. 

You need to use ESLint that supports `--print-config` option. That is at least version 2.0.0.

**Comment by zimski** [comment]
Thank a lot man, you saved my code ! :)

Have a good day

**Comment by Simplify** [comment]
Hey, you welcome :)
