### ISSUE TITLE
Column Navigation

### ISSUE THREAD

**Issue by nordlow** [flycheck/flycheck#1138]
Output from some checkers, such as Rust's, can for code such as

```Rust
fn add(x : i32, y : i32, z : i64) -> i64 {
    return x + y + z;
}

fn main() {
    let w = add(1, 2, 3i64);
}
```
look like

```
     6  12 error    E0308  mismatched types (expected i64, found i32) (rust)
     6  12 error    E0277  the trait bound `i32: std::ops::Add<i64>` is not satisfied (trait `i32: std::ops::Add<i64>` not satisfied) (rust)
     6  12 info     E0277  the following implementations were found: (rust)
     6  12 info     E0277  <i32 as std::ops::Add> (rust)
     6  12 info     E0277  <&'a i32 as std::ops::Add<i32>> (rust)
     6  12 info     E0277  <i32 as std::ops::Add<&'a i32>> (rust)
     6  12 info     E0277  <&'b i32 as std::ops::Add<&'a i32>> (rust)
     6  20 error    E0308  mismatched types (expected i32, found i64) (rust)
```

that is, errors can occur on multiple specific columns on the same line. `flycheck-previous-error` and `flycheck-next-error` doesn't respect this. It would be nice if it did, preferrably by moving the cursor to the specific column for the current diagnostics message.

**Comment by lunaryorn** [comment]
I'm not sure whether I can follow you.  Could you please try to provide an example that illustrates the behaviour you expect, in contrast to the behaviour you see?

In particular how would you like Flycheck to behave with the example you've seen and what do you see instead?

**Comment by nordlow** [comment]
Next/previous-error canont currently move the cursor in my source code to a specific column. This is especially important if two different messages occur on the same line but with different columns.

**Comment by lunaryorn** [comment]
@nordlow What's your `flycheck-highlighting-mode`?

**Comment by nordlow** [comment]
Hang on, I'll check...

**Comment by nordlow** [comment]
It's set to `symbols`.

Correction: It's not the navigation that doesn't work. It is the highlighting in the buffer *Flycheck errors*" that is slightly faulty; It always highlights all the errors on the current line not just the one on the current column i just navigate to (in this case line 6, column 20. Ok?

**Comment by lunaryorn** [comment]
@nordlow That's intentional.  See #490 and https://github.com/flycheck/flycheck/commit/41287ede4e8d849afc47f979828bab24a05775aa

We consistently highlight all errors for the current line because that's more predictable and easier to understand, in my opinion.  

Typically all errors on the current line are connected anyway, and thus are all relevant to fixing the issue on the current line.  In your example all messages are a followup of the same underlying error.  

It's very rare that there are really two distinct unconnected errors on the same line.

**Comment by nordlow** [comment]
Ok, I'll let it go then, Thanks.
