### ISSUE TITLE
Running executables inside Docker containers

### ISSUE THREAD

**Issue by pennersr** [flycheck/flycheck#1142]
I am looking for a well-defined way to use linter executables that run inside a Docker container, instead of running on the host OS. This way, you can keep your host OS clean.

Conceptually, I would simply like to use something like this...

`/usr/local/bin/docker-compose exec web /code/somewhere/node_modules/.bin/eslint`

... as a `flycheck-javascript-eslint-executable`, defined in my `.dir-locals.el`. Now, that won't work as `flycheck-executable-find` won't be able to find this executable. How would one go about setting this up, preferably without having to go through the trouble of creating a custom flycheck checker?

**Comment by lunaryorn** [comment]
I don't know.  I'm not sure whether that's even possible—can docker see temporary files on the host system?  Or receive standard input from the host system?

You can use your own function for `flycheck-executable-find` and use `flycheck-command-wrapper-function` to wrap the docker command around the syntax check command.  That's a start, I guess, but how to go from there on I don't know.  You're on your own.

In the end there's no well-defined way to use Docker with Flycheck, and I don't think there ever will be.  It's just too much of a corner case.

Closing as `wontfix`.  Sorry.

**Comment by AfsmNGhr** [comment]
I've concept for this workflow in development environment. More details see into [dockemacs](https://github.com/AfsmNGhr/dockemacs). ![wrappers](https://camo.githubusercontent.com/3513313178220c12982949076b1ed59d844c7bb3/68747470733a2f2f692e696d6775722e636f6d2f776d44764a62712e706e673f31)
I wrote wrappers for linter's executable as [example](https://github.com/AfsmNGhr/dockemacs/blob/master/sbin/rubocop).

Also I've trying write custom flycheck checker for [dockerized linter](https://github.com/AfsmNGhr/flycheck-ruby-dockerized-rubocop/blob/master/flycheck-ruby-dockerized-rubocop.el).
Current, I have a problem with replacing remote path to local path in a final output.

Alternatively, might use relative paths in the linter output (as pylint rules).

I would be glad if my workings turned into full-fledged working linters without wrappers.

**Comment by minikN** [comment]
@AfsmNGhr Have you found a working solution yet? Using `lsp-docker` use language servers inside container, would be awesome to do the same thing with linters to keep the host OS clean.
