### ISSUE TITLE
haskell-stack-ghc ERT tests fail because stack exits 1

### ISSUE THREAD

**Issue by spwhitton** [flycheck/flycheck#1146]
I'm not sure whether this is a bug, but it might be, so I'm filing an issue to track it.

The haskell-stack-ghc tests are failing [on the Debian CI platform](https://ci.debian.net/packages/f/flycheck/unstable/amd64/):

       FAILED  flycheck-define-checker/haskell-stack-ghc/complete-chain
       FAILED  flycheck-define-checker/haskell-stack-ghc/literate
       FAILED  flycheck-define-checker/haskell-stack-ghc/syntax-error
       FAILED  flycheck-define-checker/haskell-stack-ghc/type-error

The failure looks like this:

        (error "stack exited with status 1")

But isn't stack supposed to exit with status 1 when it detects a syntax error?  I tried running the checker manually, as it is defined in flycheck.el:

    hephaestus ~/src/flycheck/test/resources/language/haskell % stack ghc -- -Wall -no-link -outputdir ~/tmp -x hs SyntaxError.hs
    Run from outside a project, using implicit global project config
    Using resolver: lts-5.16 from implicit global project's config file: /home/spwhitton/.stack/global-project/stack.yaml
    [1 of 1] Compiling Main             ( SyntaxError.hs, /home/spwhitton/tmp/Main.o )
    
    SyntaxError.hs:3:1: parse error on input ‘module’
    hephaestus ~/src/flycheck/test/resources/language/haskell % echo $?
    1

Does the test need to be modified to accept an exit value of 1?  Thanks.

**Comment by lunaryorn** [comment]
Was a flaw in the stack checker, fixed.  

Sorry for the inconvenience.

**Comment by spwhitton** [comment]
Thanks.  Patch applied, and flycheck 30 on its way into Debian unstable.

-- 
Sean Whitton

**Comment by lunaryorn** [comment]
@spwhitton Cheers, thanks.
