### ISSUE TITLE
Puppet-lint doesn't behave well with buffers that don't visit files

### ISSUE THREAD

**Issue by rski** [flycheck/flycheck#1148]
When a buffer does not correspond to a file, puppet-lint doesn't behave very nicely and it causes a "suspicious syntax checker" error.  Not a big issue and easily worked-around (just do C-x C-s).

**Comment by lunaryorn** [comment]
@rski Maybe the checker just needs a corresponding predicate?  Will you take a look?

**Comment by lunaryorn** [comment]
@rski Thanks a lot!
