### ISSUE TITLE
Various test suite failures

### ISSUE THREAD

**Issue by spwhitton** [flycheck/flycheck#1163]
Hello,

[Various tests are failing against Debian unstable](https://ci.debian.net/packages/f/flycheck/unstable/amd64/).  I won't have time to fix this anytime soon, so filing an issue in case someone has time.

Thanks.

**Comment by lunaryorn** [comment]
@spwhitton I'm sorry; I don't have time either 😞

**Comment by fmdkdd** [comment]
@spwhitton Should be good?  I see green thumbs on the CI log after 30-3.

**Comment by spwhitton** [comment]
@fmdkdd Thank you for your interest.  Unfortunately, the test are
passing only because I commented out large swaths of the test suite.

-- 
Sean Whitton

**Comment by fmdkdd** [comment]
@spwhitton Hah.  Sorry to hear that.  I managed to fix a few of them with #1187, but that won't affect the Debian CI until the next release (right?).

**Comment by spwhitton** [comment]
@fmdkdd It won't affect it even after the next release unless I
uncomment the tests.  I wasn't planning to do that because they are so
fragile.  But thank you for your work.

-- 
Sean Whitton

**Comment by fmdkdd** [comment]
@spwhitton I see.  Let's keep this issue open then.  Thank you for maintaining Flycheck for Debian.

**Comment by fmdkdd** [comment]
Hey @spwhitton we are now running most integration tests on our CI again, thanks to #1462.

You may be able to re-enable those integration tests on your end, should you want to do so.

**Comment by spwhitton** [comment]
Hello,

On Fri, Jun 01 2018, fmdkdd wrote:

> Hey @spwhitton we are now running most integration tests on our CI
>again, thanks to #1462.
>
> You may be able to re-enable those integration tests on your end,
> should you want to do so.

Thank you for the ping, but given how often new upstream versions of
tools hit Debian unstable, I'd prefer to leave them switched off.
They're flakier for us than for you :)

-- 
Sean Whitton

**Comment by fmdkdd** [comment]
>  given how often new upstream versions of tools hit Debian unstable,

Yeah, that's also why we use a stable release on our side.  I'll be closing this though, since there's not much more we can do on our side.  Feel free to re-open if you feel otherwise.
