### ISSUE TITLE
I'm stepping down as maintainer

### ISSUE THREAD

**Issue by lunaryorn** [flycheck/flycheck#1177]
Dear Flycheck contributors and users,

I've been maintaining Flycheck ever since I started it three years ago.

It has been a pleasure, but also a burden.  A burden that has now become too heavy for me to bear.  I feel that lately Flycheck has taken a disproportionate share of my free time, time that I do not want to spent on Flycheck anymore.  There are other reasons as well, which I will probably explain in a separate blog post in due time.

But right now all I would like to say is that I am stepping down as Flycheck maintainer with immediate effect.

I will retain ownership of the Github organisation until my successor appears, but I will not watch its repositories anymore, and I will not work on incoming issues and pull requests.

I am actively looking for a successor; please mention me in this thread if you would like to take over and work with @cpitclaudel as Flycheck's new maintainer.

----

I hope that much of Flycheck already works without me; we have documentation, and we have a couple contributors who take care of specific parts of Flycheck and review pull requests. I am confident that Flycheck will continue to be successful without me.

The only things that I still hold exclusively are the flycheck.org domain which I shall probably keep until someone else comes up who is willing to pay for it, and the @emacs_flycheck Twitter account, which I am willing to hand over to @cpitclaudel or my successor, whoever wants to take it.

It has been a great pleasure and honour to work with you, and I would like to thank all Flycheck contributors and users for their passion and their support.

I am sorry.

**Comment by mgudemann** [comment]
Hi @lunaryorn,

thank you for all the time and work you spent on Flycheck. It's a great project, used by many people everyday. All the best for you.

**Comment by manuel-uberti** [comment]
Sad news, @lunaryorn.

You and all the contributors made Flycheck one of the greatest Emacs packages out there.

Thanks for all the effort you put into Flycheck, all the support and the advices.

**Comment by fmdkdd** [comment]
You have nothing to be sorry about @lunaryorn, as you have dedicated a lot of your time to make a very useful package of the highest quality.  You always took the time to outline your reasoning, to carefully weight alternatives, to thoroughly review pull requests, and you made sure everyone had a chance to contribute, making Flycheck a great project to work on. 

I wish you all the best.

**Comment by cpitclaudel** [comment]
Hey @lunaryorn and everyone,

There's something bittersweet about this announcement, but no apologies are needed.  You've managed to assembled a great team of core contributors for fast-moving languages, and we're inheriting a well-documented, well-tested, and robust codebase. I have little doubts that the transition will be smooth.

You've also laid out a pretty clear definition of the goals of Flycheck as a project, and you're stepping down at a time when Flycheck doesn't suffer from significant issues that would require large rewriting efforts.  That, too, makes me feel pretty confident about the the transition.

I think there are a few questions that the remaining contributors need to solve, and your input could be useful on these:

* Do we want to keep the Gitter chatroom? I for one can't guarantee a presence in there.
* What do we do with the open significant feature branches? The main one is the new priority system for checkers, and my vote would be to set it aside for at least a little while.
* What do we do with currently open pull requests? Some of them were blocked by the upcoming integration of the new checker chaining system, but I don't have time to complete the work in that branch at the moment, so I'd vote for merging these new checkers before that..

There's one last question that we should seriously consider: do we want to merge Flycheck into Emacs?  Flycheck could be an ELPA project, and I'm sure it would be a welcome replacement for Flymake.  This would ease maintenance significantly, but IIRC @lunaryorn hasn't signed the ELPA paperwork, and had reservations about the core Emacs community.  A situation similar to that of Org, however, could be profitable for us (we would stay on Github, keep our Coc and our community, but we'd also be able to tap into the experience of the Emacs core developers.

The last question is the only one that requires significant involvement from @lunaryorn, AFAICT; that's a pretty good sign :)

A a personal note: Sebastian, I can't wait to see what you come up with next! Remember that the success of a free software project is in no small part defined by the ability of its maintainer to step down, so congrats :)

**Comment by Simplify** [comment]
Hi @lunaryorn,

I'm sad about your decision but I understand it. Your dedication and attention to details, your critical view on every pull request made not only Flycheck one of the best packages that can be used in GNU Emacs, but also made many of us better in different ways. I'm sure that whatever you are going to do next, It's going to be golden.

**Comment by mgudemann** [comment]
@cpitclaudel 

didn't do much, so my opinion shouldn't weight too much, still here's my take on this

> * Do we want to keep the Gitter chatroom? I for one can't guarantee a presence in there.

I never used it and communication over issues is enough in my opinion

> * What do we do with the open significant feature branches? The main one is the new priority system for checkers, and my vote would be to set it aside for at least a little while.

+1

> * What do we do with currently open pull requests? Some of them were blocked by the upcoming integration of the new checker chaining system, but I don't have time to complete the work in that branch at the moment, so I'd vote for merging these new checkers before that..

+1

For me, having support for many checkers seems more important. I wouldn't even mind not having any chaining, but something like a menu that shows available (and maybe unavailable) checkers and let's me select them one at a time.

**Comment by rski** [comment]
This saddens me a lot, @lunaryorn, you are one of the best programmers I've had the pleasure to work on code with. Flycheck and Puppet are two of my four most used modes in Emacs, along with company and Python. Thank you for everything. 
Losing you from the Emacs ecosystem is a loss, but at least from my side it's very understandable that you want to leave. There is nothing to be sorry about. :-)
I wish you the best in everything else that you wish to pursue.

>Do we want to keep the Gitter chatroom? I for one can't guarantee a presence in there.

I have never been in there to be honest, there is only enough time in the day to keep up with channels and chats and whatnot.

**Comment by fmdkdd** [comment]
> Do we want to keep the Gitter chatroom? I for one can't guarantee a presence in there.
I've used it a couple of times, to ask about tests or implementation before working on a PR.  I find it practical to have a separate channel for these kind of questions, to avoid noise in Github issues.  But it's only useful if there are people able to answer.  I have no warmth for Gitter itself.

> What do we do with the open significant feature branches?
We continue working on them as time allows.

> What do we do with currently open pull requests?
Idem.  For those that were blocked by the new chaining system, is there any downside to let me them through now and adapt them to the new system later?

> do we want to merge Flycheck into Emacs
That's a tough one.  According to flycheck/flycheck#801 at least, it seems @lunaryorn was strongly against it.  I have no opinion on the core Emacs community, other that I *have* seen some emacs-devel threads where the discussion was not always as civil as I would have hoped it to be.  @lunaryorn made sure that Flycheck was a welcoming place to contribute, and we should be careful as to not step back in that direction.

That being said, you are proposing that we could still maintain our code of conduct and continue working on Github.  What does "merging Flycheck into Emacs" would precisely entail then?  Are we just talking about signing a waiver?  Would we have to make adjustments to Flycheck based on feedback from core developpers?  What exactly do we gain?  What would change?

I like the way how Flycheck operates now.  Granted, with @lunaryorn retiring, we'll have to pull our weight to prevent the project from stalling.  But there's nothing preventing willing Emacs contributors to help with maintaining Flycheck by submitting paches right here.  So unless there are clear benefits to merging (or getting into ELPA) without hidden downsides, I would side for status quo.

**Comment by fap-** [comment]
I'm sad to see you go. You did much good for the Emacs community.
Thank you!

**Comment by lunaryorn** [comment]
Thank you folks for your warm and kind words ❤️ I'm fluttered and deeply moved.  It's been such a pleasure and honour to work with you, and help make our little space in Emacs land a little more cosy, comfortable and convenient. :blush:

----

@cpitclaudel I would not like to provide input on the questions that you raise, for it's not my responsibility anymore, and I would not like to push you into a direction that is wrong or convince of something that turns out to be a bad idea in the end.

I can only speak for myself in that I can explain the reasons I had for some of these things.  I started a new chaining system because the current one doesn't scale well to many checkers, and became a burden for me to maintain.  For the same reason I held back the open PRs for new checkers: I feared that they'd be hard to squeeze into the existing system.

But those were decisions I made from my own personal estimations.  It might well be that you come to different conclusions and see different advantages and drawbacks.  

So feel free to do with these whatever you please.  And who knows, maybe I'll be back some days a a regular contributor and continue some of the work I've left behind.  I just need a break now, and can't make any promises :blush:

----

As for moving Flycheck to Emacs however things are a bit more intricate.  Whether to push into that direction or not is not my choice anymore, and I'll not suggest one way or the other.  In past I refused because I do not see the benefits of such a step outweight the considerable effort both in collecting assignment from past contributors and and keeping track of assignments for future contributors, and I feared that copyright assignments might be a high barrier to contributors, but you may see this differently, and that's absolutely fine.

Personally however I am not willing to sign a copyright agreement with the FSF, for a couple of reasons.  My reservations against the FSF in its current form go so far that I'd rather let Flycheck die if no maintainer was left to work on it than moving it into Emacs, and it'd require so desparate and surprising an argument to convince me otherwise that I can't even think of anything that could possibly do that :wink:

I would prefer though not to speak publicly about this topic any further. If you're interested I'll answer to a private mail to anyone who's interested, or join a private IRC channel or chatroom to explain my postion to people that I trust—which of course includes all of you folks; I'm just not going to talk about this topic with any random stranger from the internet.

I'm fully aware that this effectively keeps Flycheck out of Emacs short of a full rewrite, as my code and thus my copyright extends to all areas and parts of Flycheck.  I am sorry about this, and about the complications my position causes, but to me my reasons not to sign an agreement with the FSF are more important than Flycheck itself, at least as long as the FSF continues in its current form and with its current staff and people.

**Comment by samrayleung** [comment]
@lunaryorn i hear that you are gonna stop to maintaining flycheck,and i want to come to here to say "thank you ,thanks again for you great work".Flycheck is gorgeous ,thanks for your giving.wish you all the best.

**Comment by Simplify** [comment]
Is there a general consensus about what to do with merging new checkers pull requests and new chaining system? Personally, I'll like to see at least some of them merged. Maybe we can meet in Gitter and discuss this and some other current issues.

**Comment by cpitclaudel** [comment]
I'd like to merge all the ones that seem straightforward (no complex chaining). Bonus points if the person submitting them can commit to maintaining the recipe.

**Comment by Simplify** [comment]
@cpitclaudel Thanks for clarification :)

**Comment by DonaldJT** [comment]
Ok. I'll be the new maintainer-in-chief.  
### I will make Flycheck great. It will be so great you won't believe.

**Comment by fmdkdd** [comment]
Re: the gitter chatroom.  I just went there, and I noticed a few users are still using it to ask questions. We are still advertising the room in the README and in the manual.  I haven't seen these users open issues afterwards, so there may be bugs we are missing on because of that.

Personally, I'd rather have all discussion happening in issues and PR.  Is anyone planning on checking the Gitter room or should we close it and refer users to the issue tracker?

**Comment by lunaryorn** [comment]
Hi folks, since I've finally left Emacs and do not plan to return any time soon I'll no longer assume any responsibility for Flycheck.  However, I still control the following things:

- flycheck.org.  I opened #1257 to discuss the future of the domain. I'd like to transfer it to a current maintainer.
- flycheck@lunaryorn.com which is the public and billing mail of the GitHub org.  I can't transfer this address as it's my personal domain, but it's not getting any traffic anyway, so I'll just delete some time soon, so please **change the mail addresses associated with Flycheck**, i.e. the public mail and the billing mail.

I'd also like to be removed from the organisation.  I think @cpitclaudel is already administrator there's no need to replace me.

**Comment by lunaryorn** [comment]
I'd appreciate a response :blush: /cc @cpitclaudel @fmdkdd

**Comment by fmdkdd** [comment]
@lunaryorn I don't have any administrative rights; I replied in #1257, and @cpitclaudel should be able to address the second point.

On a related note, we should probably update the couple of places that mention you as maintainer (in Flycheck.el and the manual), if only to prevent you from getting bugged about bug reports :-)

How do you wish to be styled?  "Former maintainer"?  "Founder, former owner and former maintainer"?  And do you wish to leave your email address in there as well?

**Comment by lunaryorn** [comment]
I do not care; as far as I'm concerned you can just remove me.  😊

**Comment by fmdkdd** [comment]
Well, removing you was certainly not my intention.  But good to have your opinion on the matter.

**Comment by lunaryorn** [comment]
@fmdkdd Would you mind if I made you an owner of the Flycheck org to replace me?  I'd like to leave the org soon, eg, early July, and delete the "flycheck@lunaryorn.com" address which is the current billing address (there's no billing for Flycheck's org, of course, but GitHub wants a mail address here).

**Comment by fmdkdd** [comment]
@lunaryorn I don't mind at all, on the contrary.  Glad to be of help.

**Comment by lunaryorn** [comment]
@fmdkdd Thanks; you're now an owner of the organsation, and I removed myself :)

**Comment by fmdkdd** [comment]
@lunaryorn Thanks; and your address is no longer the one used for billing the organization.  Is there something else you need to take care of (beside the domain name)?

**Comment by lunaryorn** [comment]
@fmdkdd Thanks :)  There's nothing left to do as far as I can see; I'll close this issue.
