### ISSUE TITLE
Custom parser stopped working

### ISSUE THREAD

**Issue by feklee** [flycheck/flycheck#1178]
The following setup worked flawlessly, until a recent update:

    ;; JSLint support for Flycheck:
    (require 'flycheck)
    (defun my-parse-jslinter-warning (warning)
      (flycheck-error-new
       :line (1+ (cdr (assoc 'line warning)))
       :column (1+ (cdr (assoc 'column warning)))
       :message (cdr (assoc 'message warning))
       :level 'error))
    (defun my-jslinter-error-parser (output checker buffer)
      (mapcar 'my-parse-jslinter-warning
              (cdr (assoc 'warnings (aref (json-read-from-string output) 0)))))
    (flycheck-define-checker javascript-jslinter
      "A JavaScript syntax and style checker based on using JSLinter.
    
    See URL `https://github.com/tensor5/JSLinter'."
      :command ("c:/Users/Felix/AppData/Roaming/npm/jslint" "--raw" source)
      :error-parser my-jslinter-error-parser
      :modes (js-mode js2-mode js3-mode))

The command line tool `jslint` comes from the [JSLinter][1] package.

Now, when I edit JavaScript files, nothing gets marked up anymore. I already did `flycheck-verify-setup` and everything was green. Furthermore, I looked at the `*Messages*` buffer, but there is no output from flycheck.

Any idea what could be the issue?

[1]: https://github.com/tensor5/JSLinter

**Comment by cpitclaudel** [comment]
Please try C-c ! C-c, select your checker, and show the output.

**Comment by feklee** [comment]
```
-*- mode: compilation; default-directory: "c:/Temp/" -*-
Compilation started at Thu Dec 15 12:39:06

"c:/Users/Felix/AppData/Roaming/npm/jslint" "--raw" "c:/Temp/board_factory.js"
[{"file":"c:/Temp/board_factory.js","option":{"browser":true,"maxlen":80},"stop":true,"warnings":[{"name":"JSLintError","column":7,"line":6,"code":"unexpected_trailing_space","message":"Unexpected trailing space."},{"name":"JSLintError","column":7,"line":6,"code":"expected_a_b","a":";","b":"define","message":"Expected ';' and instead saw 'define'."},{"name":"JSLintError","column":8,"line":15,"code":"todo_comment","a":"(comment)","message":"Unexpected TODO comment."},{"name":"JSLintError","column":4,"line":33,"code":"expected_identifier_a","a":"}","message":"Expected an identifier and instead saw '}'."}]}]
Compilation finished at Thu Dec 15 12:39:07
```

**Comment by cpitclaudel** [comment]
Hmm. Seems to work fine here.  Can you share an example file, too?

**Comment by feklee** [comment]
Per request, `example.js`:

    some garbage

If I do `C-c ! C-c` with that file open, then I get:

    -*- mode: compilation; default-directory: "c:/Temp/" -*-
    Compilation started at Sat Jan 21 17:25:08
    
    "c:/Users/Felix/AppData/Roaming/npm/jslint" "--raw" "c:/Temp/example.js"
    [{"file":"c:/Temp/example.js","option":{},"stop":false,"warnings":[{"name":"JSLintError","column":0,"line":0,"code":"undeclared_a","a":"some","message":"Undeclared 'some'."},{"name":"JSLintError","column":4,"line":0,"code":"expected_a_b","a":";","b":"garbage","message":"Expected ';' and instead saw 'garbage'."},{"name":"JSLintError","column":5,"line":0,"code":"undeclared_a","a":"garbage","message":"Undeclared 'garbage'."},{"name":"JSLintError","column":12,"line":0,"code":"expected_a_b","a":";","b":"(end)","message":"Expected ';' and instead saw '(end)'."}]}]
    Compilation finished at Sat Jan 21 17:25:09

So the checker works. Only nothing is underlined.

I started emacs using `runemacs.exe -Q`, and then I executed:

    (require 'package)
    (setq package-load-list
          '((epl t) (pkg-info t) (dash t) (flycheck t)))
    (package-initialize)
    
    (require 'flycheck)
    (defun my-parse-jslinter-warning (warning)
      (flycheck-error-new
       :line (1+ (cdr (assoc 'line warning)))
       :column (1+ (cdr (assoc 'column warning)))
       :message (cdr (assoc 'message warning))
       :level 'error))
    (defun my-jslinter-error-parser (output checker buffer)
      (mapcar 'my-parse-jslinter-warning
              (cdr (assoc 'warnings (aref (json-read-from-string output) 0)))))
    (flycheck-define-checker javascript-jslinter
      "A JavaScript syntax and style checker based on using JSLinter.
    
    See URL `https://github.com/tensor5/JSLinter'."
      :command ("c:/Users/Felix/AppData/Roaming/npm/jslint" "--raw" source)
      :error-parser my-jslinter-error-parser
      :modes (js-mode js2-mode js3-mode))

Finally, after loading `example.js`, I ran `flycheck-mode`.

*Any idea what else I can check?*

Emacs version: GNU Emacs 25.1.1 (x86_64-w64-mingw32) of 2016-11-15

**Comment by feklee** [comment]
Output of `my-jslinter-error-parser`:

    ([cl-struct-flycheck-error nil nil nil 1 1 "Undeclared 'some'." error nil] [cl-struct-flycheck-error nil nil nil 1 5 "Expected ';' and instead saw 'garbage'." error nil] [cl-struct-flycheck-error nil nil nil 1 6 "Undeclared 'garbage'." error nil] [cl-struct-flycheck-error nil nil nil 1 13 "Expected ';' and instead saw '(end)'." error nil])

**Comment by fmdkdd** [comment]
@feklee I can reproduce given your example and your custom checker.  No errors indeed.

I suspect that is because your are constructing the error with `flycheck-error-new` but never giving any `buffer` value.  My understanding is that flycheck collects the errors, but filters them out since they are not associated with any buffer.

I can make it work by setting buffer to `(current-buffer)`, which is the default for the constructor `flycheck-error-new-at`:

```
(defun my-parse-jslinter-warning (warning)
  (flycheck-error-new
   :line (1+ (cdr (assoc 'line warning)))
   :column (1+ (cdr (assoc 'column warning)))
   :message (cdr (assoc 'message warning))
   :level 'error
   :buffer (current-buffer)
   :checker 'javascript-jslinter))
```
(`:checker` should also be set, at the very least to avoid the `nil` in the error list)

Let us know if that works for you.

**Comment by feklee** [comment]
@fmdkdd thanks, your suggested change does the trick!

That is, if added in my main configuration. With the minimal startup configuration explained above, errors still are not highlighted. So there’s something missing, but that’s another issue.

**Comment by fmdkdd** [comment]
@feklee Right, I forgot that I also added `javascript-jslinter` to the list of registered checkers with:
```
(add-to-list 'flycheck-checkers 'javascript-jslinter)
```
for the minimal configuration.  Otherwise, flycheck won't pick up on this checker.

Glad it works for you.

**Comment by feklee** [comment]
I see, thanks again! In my main configuration, I don’t add the checker to `flycheck-checkers` either. Instead I select it explicitly using `flycheck-select-checker`:

    ;; JavaScript mode:
    (add-to-list 'auto-mode-alist '("\\.jsx?\\'" . js-mode))
    (defun my-js-mode-hook ()
      (define-key js-mode-map [f4] 'flycheck-next-error)
      (define-key js-mode-map [(shift f4)] 'flycheck-previous-error)
    
      ;; js2-mode-like indentation - see also: http://stackoverflow.com/a/11480120
      (require 'js2-mode)
      (setq indent-line-function 'js2-indent-line)
    
      (flycheck-select-checker 'javascript-jslinter)
      (flycheck-mode))
    (add-hook 'js-mode-hook 'my-js-mode-hook)
