### ISSUE TITLE
LGTM.co has been discontinued

### ISSUE THREAD

**Issue by fmdkdd** [flycheck/flycheck#1179]
Argh.  I was wondering why LGTM was not picking up in #1171.  It seems the service is discontinued: https://lgtm.co/.

It seems we can host it ourselves, but I don't think we have any dedicated machine for that.

The other option is to get rid of it.  Or at least disable the hook, since it currently prevents PRs to be merged.  It does not necessarily throws a wrench into the rules introduced in #1094, it's just that LGTMs checks won't be enforced automatically anymore.
 
@cpitclaudel, what's your take on that?

**Comment by cpitclaudel** [comment]
I think we should remove the hook.  Do you have sufficient permissions to do that? If not, I'll do it.  Thanks for investigating the issue.

**Comment by fmdkdd** [comment]
No it doesn't look like I can (I have no "settings" tab).

**Comment by cpitclaudel** [comment]
Ok, should be done now :)

**Comment by fmdkdd** [comment]
Yep!  Thanks.

Should we remove the `.lgtm` file?  Or do we keep it around just in case?

**Comment by cpitclaudel** [comment]
Please remove it :)
