### ISSUE TITLE
Eslinter cannot be launched: Flycheck cannot use this syntax checker for this buffer

### ISSUE THREAD

**Issue by PinkFLoyd92** [flycheck/flycheck#1181]
I am using Emacs 25.1. I am actually trying to activate eslinter but It keeps showing me the following message: "Flycheck cannot use this syntax checker for this buffer".
Image showing the weird message from flycheck:
[https://postimg.org/image/5n5rn3mk3/](url)

It seems like everything is fine, how can i solve this?

**Comment by cpitclaudel** [comment]
It says `disabled` in red at the top of the window; did you disable it?

**Comment by PinkFLoyd92** [comment]
I did not disable it. I also used the  "--print-config" flag and it was successful. The config file is valid. I changed the executable link as you recommend  `"node_modules/.bin/eslint" `and my variable `flycheck-disabled-checkers` has just the "javascript-jshint" linter.

![eslinterversion](https://cloud.githubusercontent.com/assets/8844096/21413345/89aca460-c7c4-11e6-9f0c-636a0e14e0c3.jpg)
![eslintererror](https://cloud.githubusercontent.com/assets/8844096/21413346/89adfaf4-c7c4-11e6-8313-b5c9b145b623.jpg)

I just want to enable it, but flycheck just does not let me to do it... And in the second picture it seems like everything is fine.

**Comment by Simplify** [comment]
If there is `(disabled)` printed, `eslint` is or disabled in your Emacs configuration or for current buffer. That `may enable: yes` and `configuration file: found` indicate that `eslint` can be used, but it's disabled.

Did you try to enable `eslint` using instructions in your last screenshot? Does `eslint` works after that?

**Comment by PinkFLoyd92** [comment]
Well, I just enabled it. It works after running `SPC u C-c ! x` and selecting eslint. Sorry for the inconvenience.
![screenshot 54](https://cloud.githubusercontent.com/assets/8844096/21428469/378f27b6-c828-11e6-85d9-b992d893ba69.jpg)
