### ISSUE TITLE
Our stance on backward-compatibility and testing

### ISSUE THREAD

**Issue by fmdkdd** [flycheck/flycheck#1190]
As far as I can tell, our stance on backward-compatibility is "we don't make any guarantees on backward-compatibility".

The maintainers guide states:
> Breaking changes may occur at any point.

And, in discussions, @lunaryorn has stated multiple times (see [there](https://github.com/flycheck/flycheck/issues/893#issuecomment-189722781), [there](https://github.com/flycheck/flycheck/issues/623) and [there](https://github.com/flycheck/flycheck-rust/pull/43#issuecomment-254750397)) that backward-compatibility was not a goal of flycheck.

Though, in fact, if backward-compatibility *could* be retained at a small maintenance cost, then it was.  Otherwise, the priority has always been given to supporting the latest version of external checkers, since it meant less maintenance overhead for us.  This is a reasonable position from a maintainer's point of view, and an adequate compromise for users.

So my first question is: what is our position on backward-compatibility?  Do we forego it completely?  Do we try to maintain backward-compatibility whenever possible?  Or do we want to increase the maintenance effort by keeping multiple parsers for different version of a checker?

As both a user and contributor, the middle-ground position of best-effort suits me well.  If we do follow it, it should be stated in the Contributor's guide as future reference.  And it brings me to my next point.

### Backward-compatibilty testing
We do have a test suite, that while not exhaustive, helps in catching regressions.  However, our integration tests are deeply tied to the checker output.  The issue has come up in #1187 for GHC: the latest version has a slightly different message format.  While the error-parser *is* backward-compatible, the integration test is not.

If we do aim for a best-effort regarding backward-compatibility, our tests should reflect that as well.  There are two requirements to that: 1) instead of updating tests whenever a checker output changes, we would need to explicitely version the tests, and drop the older ones as needed; and 2) it would be good to instruct the CI to actually run the integration tests in order to catch regressions.

Currently the only integration tests we run are the Elisp ones.  I could not find any reasoning as to why we do not run all the tests (maybe installing all the checkers is a hassle?).

What is you take on that?

**Comment by cpitclaudel** [comment]
We used to have a virtual machine for checkers, but it was very costly to maintain (keeping up with versions of 30+ languages and runtimes.  We dropped that a few months ago.

My feeling is that we should keep backwards compatibility every time it's trivial.  A slightly more complex regexp is OK, but anything beyond that is probably too much (doing version detection to add a flag would most likely be too much, for example).

This holds especially for compilers of languages that are not updated frequently, like those distributed by Debian, for example.  On the other hand, if the checker is an node or pypy package that's trivial to update, we shouldn't bother.

**Comment by fmdkdd** [comment]
Thanks for clarifying.  I'll see about making that position stands out in the contributing docs.

**Comment by fmdkdd** [comment]
For reference (since I don't always know where to look up these), here is a way to check for the version of a package shipping in (e.g., GHC):

- Debian: https://tracker.debian.org/pkg/ghc
- Ubuntu: https://launchpad.net/ghc    (cross-reference with [this](https://en.wikipedia.org/wiki/Ubuntu_version_history) to know the latest LTS)
- Fedora: https://apps.fedoraproject.org/packages/ghc-compiler (this one is confusing though, since no GHC package matches the release numbers from upstream)

There's also this: https://pkgs.org/download/ghc for a table with all the data (a pity we can't see you can only see one distro at once...).

For OSX, I expect most users use something akin to Homebrew, so they can always update to the latest release from upstream.

**Comment by cpitclaudel** [comment]
Very nice

**Comment by cpitclaudel** [comment]
@fmdkdd do you still want to update the docs on this?

**Comment by fmdkdd** [comment]
I've added a paragraph in the style guide for reviewing using your examples (#1717).
