### ISSUE TITLE
Allow custom actions in error explainers

### ISSUE THREAD

**Issue by marsam** [flycheck/flycheck#1192]
Currently [flycheck-error-list-explain-error](https://github.com/flycheck/flycheck/blob/e02ec2a2/flycheck.el#L4163-L4173) calls `flycheck-display-error-explanation` with the output of the checker's error-explainer, but there are checkers which doesn't provide a command to see the description of a error code.

for example `shellcheck` wiki has the description of its error codes, so I want to make something like:

```diff
modified   flycheck.el
@@ -9124,6 +9124,10 @@ flycheck-shellcheck-supported-shells
   (lambda (errors)
     (flycheck-remove-error-file-names
      "-" (flycheck-dequalify-error-ids errors)))
+  :error-explainer
+  (lambda (err)
+    (-when-let (error-code (flycheck-error-id err))
+      (browse-url (format "https://github.com/koalaman/shellcheck/wiki/%s" error-code))))
   :modes sh-mode
   :predicate (lambda () (memq sh-shell flycheck-shellcheck-supported-shells))
   :verify (lambda (_)
```

or with the `eslint` checker:

```diff
modified   flycheck.el
@@ -7669,6 +7669,10 @@ flycheck-eslint-config-exists-p
                      (flycheck-error-message err))))
             (flycheck-sanitize-errors errors))
     errors)
+  :error-explainer
+  (lambda (err)
+    (-when-let (error-code (flycheck-error-id err))
+      (browse-url (format "http://eslint.org/docs/rules/%s" error-code))))
   :enabled (lambda () (flycheck-eslint-config-exists-p))
   :modes (js-mode js-jsx-mode js2-mode js2-jsx-mode js3-mode rjsx-mode)
   :next-checkers ((warning . javascript-jscs))
```

If you think is a good idea, I can prepare a pull request

**Comment by fmdkdd** [comment]
Yes and yes!  When we added the error-explainer it was mostly with rust in mind, but we made it generic in the hope that other checkers could benefit.  I opened #1134 to discuss that, but it never got traction.

Please do open up a PR 👍

**Comment by cpitclaudel** [comment]
Hi @marsam , do you want to have a new look at this? I think your proposal was quite sound, and the PR should be rather simple (if the error explainer returns nil, we don't need to show the output)
