### ISSUE TITLE
selecting checker with erlang-mode is too broad

### ISSUE THREAD

**Issue by massemanet** [flycheck/flycheck#1198]
flycheck (not unreasonably) tries to run all buffers with erlang-mode through the erlang compiler. Alas, it is quite common to have files that use erlang-mode but does not compile (e.g. header and config files).
  Adding something like this;
```:predicate (lambda () (string-suffix-p ".erl" (buffer-name)))```
  to ```flycheck-define-checker``` improves things.

**Comment by cpitclaudel** [comment]
Thanks, this sounds like a good idea. I don't have much erlang experience, however, so I can't comment on the technical part.  Can you open a PR with this change, and an adequate new entry? For bonus points, pinging the original author of the elixir checker for confirmation would be awesome.

Thanks!
