### ISSUE TITLE
Add checkers for ng2-mode

### ISSUE THREAD

**Issue by Ehrax** [flycheck/flycheck#1200]
Hey there,

Flycheck works really well for me so far. One thing i would like to use is the checkers `typescript-tide` and `typescript-tslint` in [ng2-mode](https://github.com/AdamNiederer/ng2-mode).

Those checkers are enabled in `typescript-mode`, but not in `ng2-mode`, but `ng2-mode` depends on `typescript-mode`, so I think this should be enabled...

**Comment by Simplify** [comment]
You can add that in your Emacs config file:

```
(flycheck-add-mode 'typescript-tslint 'ng2-ts-mode)
(flycheck-add-mode 'typescript-tide 'ng2-ts-mode)
```

You may want to do that also for `ng2-html-mode`. 

We can add `ng2-ts-mode` for `typescript-eslint`, but `typescript-tide` is not part of Flycheck. Please open PR [there](https://github.com/ananthakumaran/tide).

**Comment by Ehrax** [comment]
thank you very much,

when i tried to inizialize this i could not find functions for it.
Now everything is working perfect :)

Thanks 👍
