### ISSUE TITLE
Linter (?) does not understand sep keyword argument of print

### ISSUE THREAD

**Issue by ZelphirKaltstahl** [flycheck/flycheck#1221]
This might be a linter issue. I just got flycheck running and I noticed a wrong "problem" the linter highlights:

![image](https://cloud.githubusercontent.com/assets/11130348/23342533/c10d4000-fc5c-11e6-9bb3-cd04bff45c06.png)

It seems it does not know about the keyword argument `sep` of the `print` function. When I hover over the highlighted problem, a tool tip tells me: `invalid syntax`.

Should I create this issue in a linter's repository?
(How do I figure out which linter is used for a specific highlighted problem in the code?)

**Comment by fmdkdd** [comment]
It might be a linter issue indeed.

If you bring up the error list (`C-c ! l`) the linter (we call them checkers) is after the message.

**Comment by ZelphirKaltstahl** [comment]
It was a `pycompile` issue. When I switched to flake8, it went away.

**Comment by fmdkdd** [comment]
You might want to report it to `pylint`.
