### ISSUE TITLE
Add check-declare-function checker for emacs-lisp

### ISSUE THREAD

**Issue by darkfeline** [flycheck/flycheck#1229]
`check-declare-function` will ensure `declare-function` functions are actually declared in the indicated files, which the compiler does not check.  Since `declare-function` is used to silence compilation warnings for undefined functions, it would be nice to have a checker verify the `declare-function` uses.

**Comment by cpitclaudel** [comment]
Nice idea :) Though I wonder why the compiler doesn't do that.  Shouldn't it?

**Comment by darkfeline** [comment]
I think `declare-function` can also used to declare functions in a file that would exist at runtime, but not compile time.  It's sort of like how you only need the library headers to compile a C program, but the library itself may not be needed at compile time.

So in the general case the compiler shouldn't check it.

**Comment by fmdkdd** [comment]
@darkfeline Do you want to send a PR for this?

**Comment by darkfeline** [comment]
https://github.com/flycheck/flycheck/pull/1286
