### ISSUE TITLE
Not finding executable

### ISSUE THREAD

**Issue by petey33** [flycheck/flycheck#1243]
Hi,

I am trying to get eslint to work with flycheck. 

Eslint (v3.19.0) is working from everywhere in terminal. But when I execute flycheck-checker I get the message below  (executable not found). Do I need a config file before flycheck looks for an executable? I tried that by adding a dummy .eslintrc in home folder.  But it is still not working. 

I really appreciate any help you can provide.

>  javascript-eslint (disabled)
>     - major mode:  `js2-mode' supported
>     - may enable:  Automatically disabled!
>     - executable:  Not found
>     - config file: missing
> 
> Flycheck cannot use this syntax checker for this buffer.
> 
> Flycheck Mode is enabled.  Use C-u C-c ! x to enable disabled
> checkers.
>
> Flycheck version: 31snapshot (package: 20170415.1006)
> Emacs version:    24.5.1
> System:           x86_64-pc-linux-gnu
> Window system:    x

**Comment by cpitclaudel** [comment]
Do you start emacs from the terminal ? If not, did you set your path in your .bashrc instead of your .profile?

**Comment by petey33** [comment]
@cpitclaudel: Thank you very much! I start emacs from the unity launcher in Ubuntu. Starting emacs from the terminal solved the issue.
