### ISSUE TITLE
Add Java checker

### ISSUE THREAD

**Issue by kpuputti** [flycheck/flycheck#125]
Syntax check using [javac](http://docs.oracle.com/javase/6/docs/technotes/tools/solaris/javac.html).

**Comment by calve** [comment]
For the record, Facebook released [Infer](https://github.com/calve/flycheck-infer), a static analyser for java.

I started to write a package to integrate it to flycheck at https://github.com/calve/flycheck-infer.

**Comment by cpitclaudel** [comment]
@calve If the definition is simple enough to be of general use to all Java + Emacs users, feel free to submit this checker to flycheck itself, once it works well :) You may also want to look at what people are doing with https://github.com/senny/emacs-eclim.
