### ISSUE TITLE
False error-reports in Python mod

### ISSUE THREAD

**Issue by zeka0** [flycheck/flycheck#1252]
After uninstalled the old Anaconda2, I installed Anaconda3.
But I later found spacemacs Python mode is reporting errors that is false.
Here is a screenshot:
![default](https://cloud.githubusercontent.com/assets/13997167/25991318/555e6a82-3735-11e7-9d5a-599412614ea8.PNG)

You can see, at line 13, it reports that 
_**"standard import "import os" comes before "import tensorflow as tf" "**_
at line 21, it reports:
**_"no module 'python' in 'tensorflow' "_**, but I have that package, I have verified it in python _console.
and the weird thing is, at line 25, it reports:
_**"invalid constant name: 'sess' "**_
And line 52, 51, 28 report the same error.

My specs:
emacs-version-25.0.50.1
flycheck-version-0.26snapshot
operating system: Windows 10 64bit
Any ideas?

**Comment by cpitclaudel** [comment]
This doesn't look like a bug to me. Flycheck runs external checkers — when these report errors, Flycheck displays them to you. You can use `C-c ! C-c` to run pylint on its own and see its output.

Please feel free to reopen if you feel that Flycheck should do something differently.

**Comment by zeka0** [comment]
Well I disagree with you. The program shown above is absolutely fine, because I have ran it on Pycharm(a python IDE) and no errors are reported(on the same PC). 
What caught me thinking is that, maybe it's the warning levels? You know, when display some minor errors(not fatal ones) in the code depending on the warning levels.

**Comment by cpitclaudel** [comment]
> I can't re-open the issue cause you closed it, not me, though I wish to.

Woops, sorry.

> Well I disagree with you. 

Sorry, I'm not sure which part you disagree with :/

> The program shown above is absolutely fine, because I have ran it on Pycharm(a python IDE) and no errors are reported(on the same PC).

Does PyCharm run pylint? Otherwise, I'm not sure I understand the comparison… Flycheck doesn't know anything about Python: it just calls out to pylint or pycompile.  The errors you're seeing come from pylint — if you want to see different errors, or customize the errors that you see, then you should create a pylint configuration file (but this independent of Flycheck)

I hope this makes sense; if not, please do try `C-c ! C-c` and select `pylint` as I suggested above, and see if that clarifies it :)

**Comment by zeka0** [comment]
I did run Pylint before I commented 6 hours ago, and also ran python-check, but didn't pay much attention to it I admit.
Now I have re-ran Pylint, found Flycheck indeed just reports what Pylint reported.
But the weird thing is, Pylint has reported errors that python-check didn't.
I guess I need to consult Pylint developers.

**Comment by zeka0** [comment]
Sorry to bother you again sir.
Could you tell me how to disable using Flycheck in Python mode?

**Comment by cpitclaudel** [comment]
Please check our manual :) you want to customize flycheck-disabled-checkers, I think.

**Comment by forrestchang** [comment]
@cpitclaudel @zeka0 

I have the same problem.

But I ran pylint use C-c ! C-c. It didn't show any errors.

![image](https://user-images.githubusercontent.com/7857126/35914670-10edec44-0c3f-11e8-8289-63580343b49c.png)
![image](https://user-images.githubusercontent.com/7857126/35914702-2e167bd8-0c3f-11e8-8def-4ace328d444d.png)

**Comment by fmdkdd** [comment]
@forrestchang If you look into the flycheck error list (`M-x flycheck-list-errors`), you should see from which checkers these errors are coming from.

**Comment by forrestchang** [comment]
@fmdkdd Thanks! I have already fixed this problem. This problem occurs because I use the wrong pylint.
