### ISSUE TITLE
flycheck-error-new-at nil message skips the error

### ISSUE THREAD

**Issue by wyuenho** [flycheck/flycheck#1264]
Using the flycheck 20170601.608 from Melpa, and flycheck-flow, I've discovered that Flow parse errors don't show up in the buffer. After some debugging, it seems that the [`message-desc` from this check sometimes will be `nil`, and that is pass to `(flycheck-error-new-at)` as the `MESSAGE` optional parameter](https://github.com/lbolla/emacs-flycheck-flow/blob/master/flycheck-flow.el#L87-L93). When it's `nil`, flycheck just decided to not show the error at all.

My question is, if it's an optional parameter, shouldn't flycheck highlight the error anyway?

**Comment by fmdkdd** [comment]
`flycheck-relevant-error-p` will filter out any error with an empty message.

I guess the intent is that you *can* create a `flycheck-error` object without a message, but the flycheck code that's interested in displaying errors to the user won't display any empty message, because frankly there is no point in reporting the error without it.

**Comment by wyuenho** [comment]
But the code in question has an `id`? That's part of the printed message.

As a side note, how come the message parameter for `(fly-error)` isn't documented?

**Comment by fmdkdd** [comment]
If the `id` is intended to be displayed, then it could be added to the `message` parameter as well.

As for the missing documentation, it's certainly an oversight.  I've got a drive-by fix in #1249.

**Comment by wyuenho** [comment]
What I'm saying is, the `id` of the error is already displayed if the message is not nil. Since there's no point of displaying the same string twice, the checker will have to take it out of the flycheck-error object depending on whether the message is nil. This makes writing an error parser quite awkward.

**Comment by cpitclaudel** [comment]
@wyuenho this sounds reasonable. Would you like to propose a patch to display errors that have a non-nil id but no message?

**Comment by wyuenho** [comment]
So I was looking at #1249, Flow appears to return multiple messages for the same error as well. So grouping them may actually be a better solution. If that PR makes it in, maybe flycheck-flow can be less awkward.

**Comment by fmdkdd** [comment]
@wyuenho We merged #1249, does this help `flycheck-flow`?

**Comment by wyuenho** [comment]
I've stopped using Flow, but I'll close this anyway. I believe flycheck-flow can be rewritten to take advantage of the new change in #1249
