### ISSUE TITLE
Flycheck (wrong-type-argument wholenup nil) on Startup

### ISSUE THREAD

**Issue by jamessral** [flycheck/flycheck#1265]
Upon upgrading my elpa packages, my flychecker stopped working by complaining about both `Error while checking sytnax automatically (wrong-type-argument wholenup nil)` and about exceeding the max-specpdl-size.

## Tried
I tried uninstalling all of my flycheck packages and reinstalling them.  I then tried deleting all of my flycheck packages manually and reinstalling.

Next, I commented everything except my `(add-hook 'after-init-hook 'global-flycheck-mode)`.  Even with this, it shows the error on every file I open and every change I make

I am on the most recent version of MacOs

Here is the stack trace with `toggle-debug-on-error`
```
Debugger entered--Lisp error: (wrong-type-argument wholenump nil)
  signal(wrong-type-argument (wholenump nil))
  flycheck-buffer()
  flycheck-buffer-automatically(idle-change)
  flycheck-handle-idle-change()
  apply(flycheck-handle-idle-change nil)
  timer-event-handler([t 22836 51834 902280 nil flycheck-handle-idle-change nil nil 0])
```

**Comment by jamessral** [comment]
In reverted flycheck to an older version and it just works (version from 2016)

**Comment by cpitclaudel** [comment]
Sorry for the delay. This is a surprising error.
I can't reproduce this locally yet, but your help (if you have time) would be most welcome.  Can you reproduce the problem if you run `flycheck-buffer` manually?  Can you instrument flycheck-buffer and see which part fails (let me know if you need directions)?  Could you bisect to find the faulty commit?
Thanks a lot for the report; sorry I don't have a better answer just yet!

**Comment by jamessral** [comment]
No worries. I should be able too soon. I was away for a bit.

**Comment by jamessral** [comment]
Running flycheck-buffer manual yields "Wrong type argument: wholenump, nil" even in the scratch buffer at start. Updating to the latest flycheck brings this issue and rolling back to a 2016 version still fixes it. I will have to investigate into which 2016 version.

**Comment by fmdkdd** [comment]
@jamessral If you could `git bisect` the exact commit, that would be a great help.  Also, can you report your Emacs version (`C-c ! v`)?

**Comment by jamessral** [comment]
Version: `GNU Emacs 25.2.1 (x86_64-apple-darwin13.4.0, NS appkit-1265.21 Version 10.9.5 (Build 13F1911)) of 2017-04-21`
I will have to bisect later today

**Comment by jamessral** [comment]
In my elpa folder, it looks like I have two dated versions of flycheck. The one that does not seem to work is `flycheck-20170626.1707` and the other is `flycheck-20160912.814`

**Comment by fmdkdd** [comment]
@jamessral Any update?  Did you manage to bisect to a commit that makes a difference?  I cannot reproduce locally either, but I suggest you try to reproduce the error in [`emacs -Q`](https://www.lunaryorn.com/posts/reproduce-bugs-in-emacs-q) and let us know how it goes.

**Comment by jamessral** [comment]
I no longer get this issue. It was the result of a starter-kit package. Sorry for the late reply

**Comment by fmdkdd** [comment]
Thanks for the update :)
