### ISSUE TITLE
Flychecker message  cant use Flychecker in this buffer for ruby-mode

### ISSUE THREAD

**Issue by andrew-oko-odion** [flycheck/flycheck#1267]
Flycheck works excellently well on Emacs CLI but does not work with Emacs  GUI 
for ruby-mode I keep getting the message `can't use Flychecker in this buffer` 

M-x flycheck-verify-setup 
Syntax checkers for buffer posts_controller.rb in ruby-mode:
  chef-foodcritic
    - predicate:  nil
    - executable: Not found

  ruby-rubocop
    - predicate:  nil
    - executable: Not found

  ruby-rubylint
    - predicate:  nil
    - executable: Not found

  ruby
    - predicate:  t
    - executable: Found at /usr/bin/ruby

  ruby-jruby
    - predicate:  nil
    - executable: Not found

Flycheck Mode is enabled.

Emacs Version
`GNU Emacs 24.5.1`

Ruby Version
`ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux]`

Operating System 
`Linux (Debian)`

Flycheck Version
`0.23` 

RVM Version 
rvm 1.29.1

**Comment by cpitclaudel** [comment]
My crystal ball tells me that you're (probably) on macOS, that you run the GUI emacs from a menu/launcher, and that your favorite ruby checker isn't in your path when you run the GUI emacs. Is that correct? If so, see https://github.com/flycheck/flycheck/issues/1243

**Comment by andrew-oko-odion** [comment]
Thanks `@cpitclaudel`  you are very right. 
when I lunched `Emacs` from terminal it worked well.
Please how can I fix this permanently for I open my apps form the `launcher`?
You also made mention of setting path in .profile 
what path should I set in .profile?

**Comment by cpitclaudel** [comment]
See https://github.com/purcell/exec-path-from-shell :)

**Comment by cpitclaudel** [comment]
Did that work?

**Comment by fmdkdd** [comment]
Closing since this seems to be a user configuration issue.  Feel free to re-open if Flycheck is in cause in any way.
