### ISSUE TITLE
The issue of perl checker with a large source file

### ISSUE THREAD

**Issue by OGAWAHirofumi** [flycheck/flycheck#1278]
To describe the issue, at first, "perl -wc" can do exit(255) without
reading all of inputed source if there are some kind of warnings.  So,
emacs's (process-send-region) signals 'file-error.

The details of issue is, 

This is partial strace of output of emacs(31773) and perl(31797).

[...]
;; emacs runs perl
31797 execve("/usr/bin/perl", ["/usr/bin/perl", "-w", "-c"], [/* 55 vars */] <unfinished ...>
[...]
;; emacs write source 64k (maximum of pipe size)
31773 write(14, "#!/usr/bin/perl\n#\n# For test:\n# "..., 152975 <unfinished ...>
31773 <... write resumed> )             = 65536
31773 write(14, "EOF\";\n\n                      See"..., 87439) = -1 EAGAIN (Resource temporarily unavailable)
;; perl reading source...
31797 read(0, "#!/usr/bin/perl\n#\n# For test:\n# "..., 8192) = 8192
31797 read(0, "}\n\n# Decide width of summary ima"..., 8192) = 8192
[...]
31773 write(14, "EOF\";\n\n                      See"..., 87439) = 8192
31797 read(0, "printf(\"%s_iops_c.dat\", kdevname"..., 8192) = 8192
31773 read(15,  <unfinished ...>
;; perl outputs warnings/errors
31773 <... read resumed> "Global symbol \"$unit\" requires e"..., 4096) = 283
;; perl exits
31797 exit_group(255)                   = ?
31797 +++ exited with 255 +++
31773 read(15, "", 4096)                = 0
;; emacs close pipes
31773 close(14)                         = 0
31773 close(15)                         = 0
;; ...continue write source, then got error
31773 write(-1, "d) = @_;\n\n    my @normalized_arg"..., 79247) = -1 EBADF (Bad file descriptor)

After this sequence, flycheck-buffer runs (error) part with
'file-error signal from process-send-region, and failed to display
warnings with following error.

Error while checking syntax automatically: (file-error "Writing to process" "Bad file descriptor" #<process flycheck-perl>)

On other hand, command line (or flycheck-compile) outputs this,

$ cat fsperf.pl | perl -wc
Global symbol "$unit" requires explicit package name (did you forget to declare "my $unit"?) at - line 1226.
Global symbol "$unit" requires explicit package name (did you forget to declare "my $unit"?) at - line 1232.
BEGIN not safe after errors--compilation aborted at - line 1315.

This is example source to reproduce the issue.
[fsperf.pl](https://github.com/flycheck/flycheck/files/1133267/fsperf.pl.txt)

**Comment by fmdkdd** [comment]
Thank you for the report.  I can reproduce with the given file.

Not sure what the fix should be though.  If perl exists early without reading all the input... how do we distinguish this case from a program that legitimely crashed?

Not using standard input in the `perl` checker works for me and the given file.

@cpitclaudel thoughts?

**Comment by OGAWAHirofumi** [comment]
[flycheck.diff.txt](https://github.com/flycheck/flycheck/files/1133593/flycheck.diff.txt)

Only if flycheck has no reason to check error from process-send-* after process exited,
Attached patch seems to work for me.

It ignores error if process exited already. Also, this will works for other checkers,
in the case of exiting at confused (without reading all inputs).

**Comment by fmdkdd** [comment]
Here is your patch reposted, in the interest of discussion:

```diff
--- flycheck.el.orig	2017-07-09 01:09:30.759556339 +0900
+++ flycheck.el	2017-07-09 16:23:56.483549272 +0900
@@ -4928,12 +4928,18 @@ contents in chunks via
 `flycheck--process-send-buffer-contents-chunked', which see.
 Otherwise use `process-send-region' to send all contents at once
 and rely on Emacs' own buffering and chunking."
-  (save-restriction
-    (widen)
-    (if flycheck-chunked-process-input
-        (flycheck--process-send-buffer-contents-chunked process)
-      (process-send-region process (point-min) (point-max))))
-  (process-send-eof process))
+  (condition-case err
+      (save-restriction
+        (widen)
+        (if flycheck-chunked-process-input
+            (flycheck--process-send-buffer-contents-chunked process)
+          (process-send-region process (point-min) (point-max)))
+        (process-send-eof process))
+    ;; We don't care error from process-send-* if it's after process exited.
+    ;; Then, we will check exit status of process instead.
+    (error
+     (when (process-live-p process)
+       (signal (car err) (cdr err))))))
```

I agree that dealing with error at this level might be better for other checkers that would behave like `perl`.  But I'm worried about the side effects of ignoring errors when the process exited.  I'm more comfortable with a local fix to the `perl` checker, but I'm open to more feedback on this.

**Comment by OGAWAHirofumi** [comment]
I'm still not sure why flycheck wants to know error of write even if target process exited though.
[because checker exited, so process-send-* will be error as normal behavior (since pipe closed).]

On other hand, if flycheck wants to ignore depending on checker, this might work like it.

[flycheck.diff](https://github.com/flycheck/flycheck/files/1133817/a.diff.txt)

```diff
--- flycheck.el.orig	2017-07-09 23:10:48.575139776 +0900
+++ flycheck.el	2017-07-09 23:29:58.869945642 +0900
@@ -4928,12 +4928,21 @@ contents in chunks via
 `flycheck--process-send-buffer-contents-chunked', which see.
 Otherwise use `process-send-region' to send all contents at once
 and rely on Emacs' own buffering and chunking."
-  (save-restriction
-    (widen)
-    (if flycheck-chunked-process-input
-        (flycheck--process-send-buffer-contents-chunked process)
-      (process-send-region process (point-min) (point-max))))
-  (process-send-eof process))
+  (condition-case err
+      (save-restriction
+        (widen)
+        (if flycheck-chunked-process-input
+            (flycheck--process-send-buffer-contents-chunked process)
+          (process-send-region process (point-min) (point-max)))
+        (process-send-eof process))
+    ;; We don't care error from process-send-* if it's after process
+    ;; exited, and checker wants to ignore send error.  Then, we will
+    ;; check exit status of process instead.
+    (error
+     (let* ((checker (process-get process 'flycheck-checker))
+            (type (flycheck-checker-get checker 'standard-input)))
+       (when (or (not (eq type 'ignore-error)) (process-live-p process))
+         (signal (car err) (cdr err)))))))
 
 (defun flycheck-start-command-checker (checker callback)
   "Start a command CHECKER with CALLBACK."
@@ -8199,7 +8208,7 @@ Relative paths are relative to the file
 See URL `https://www.perl.org'."
   :command ("perl" "-w" "-c"
             (option-list "-I" flycheck-perl-include-path))
-  :standard-input t
+  :standard-input ignore-error
   :error-patterns
   ((error line-start (minimal-match (message))
           " at - line " line
```

**Comment by cpitclaudel** [comment]
Sorry for the delay.  I'd be fine with a patch along the lines of the one posted @OGAWAHirofumi (thanks for the debugging and the suggestions!), but we should be more selective about the kind of error we catch.
I'd also feel safer if we made sure that we can't say "all clear" when the process exits early. Perhaps by forcing the exit code to something non-zero?

**Comment by OGAWAHirofumi** [comment]
To make sure, this should not ignore errors from checker process which exited early. This ignores emacs's pipe write (emacs try to write to closed pipe if checker was exited early.) to checker process. (If checker abnormally exited early, checker process handler should detect it instead of here?)

Even if so, do we want to care error of emacs's write, and reflect to checker result?

**Comment by cpitclaudel** [comment]
I think https://github.com/flycheck/flycheck/pull/1724 should fix this (after just a bit less than 3 years :disappointed:)

**Comment by OGAWAHirofumi** [comment]
Looks like it is working.

**Comment by cpitclaudel** [comment]
Thank you very much for testing @OGAWAHirofumi ; thank you even more for your patience :)

**Comment by eserte** [comment]
@cpitclaudel  I don't know if this is intended, but if I edit a file triggering this problem, then I get constantly this warning, which is somewhat annoying (and additionally the wording may be considered wrong):
```
Suspicious state from syntax checker perl: Flycheck checker perl returned (file-error "Writing to process" "Ungültiger Dateideskriptor" #<process flycheck-perl>), but its output contained no errors: - syntax OK

Try installing a more recent version of perl, and please open a bug report if the issue persists in the latest release.  Thanks!
```

(To reproduce, just create a .pl file with the content
 ```__END__``` followed by 65529 random characters)
