### ISSUE TITLE
Rust checker breaks in Rust Stable 1.19

### ISSUE THREAD

**Issue by AdamNiederer** [flycheck/flycheck#1288]
Using flycheck with rustc 1.19 installed will generate the following error

```
Suspicious state from syntax checker rust: Flycheck checker rust returned non-zero exit code 101, but its output contained no errors: error: the option `Z` is only accepted on the nightly compiler

Try installing a more recent version of rust, and please open a bug report if the issue persists in the latest release.  Thanks!
```

Switching to nightly or 1.18 works around the issue.

I suspect that one simply needs to remove the option on this line, but I haven't tested it.
https://github.com/flycheck/flycheck/blob/master/flycheck.el#L9165

More info regarding the disabling of `-Z`:
https://github.com/rust-lang/rust/pull/41751

Flycheck version: 31snapshot (package: 20170720.138)
GNU Emacs 25.2.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.22.16) of 2017-07-15

**Comment by BurntPizza** [comment]
Specifically, the functionality of the `-Z no-trans` option [was added](https://www.reddit.com/r/rust/comments/5ibr2a/cargo_check_has_been_merged_into_cargo_directly/) to cargo directly last year as `cargo check`. (not to be confused with [a crate](https://github.com/rsolomo/cargo-check) providing the same cargo subcommand, but which was simply a wrapper around `-Z no-trans`)

**Comment by fmdkdd** [comment]
Thanks for the heads up.  I've pushed a fix to master by removing `-Z no-trans`.  I will send a proper PR using `cargo check` later.

**Comment by fmdkdd** [comment]
PR: #1289.
