### ISSUE TITLE
*Flycheck error messages* buffer should have its own major mode

### ISSUE THREAD

**Issue by rgrinberg** [flycheck/flycheck#1294]
It would be nice if this buffer had its own major mode to easily create bindings & hooks.

**Comment by cpitclaudel** [comment]
Are you thinking of flycheck-error-list-mode?

**Comment by rgrinberg** [comment]
Hmm, that's right. I wonder why flycheck error buffer is in Fundamental mode when I hover over an error and get that popup. Enabling the mode manually works of course.

**Comment by cpitclaudel** [comment]
Ah, I misunderstood you then

**Comment by cpitclaudel** [comment]
You didn't mean the error list, right? You meant the buffer that pops up for long error messages?

**Comment by fmdkdd** [comment]
If you are talking about the buffer that opens for long error messages, you can define your own error function with `flycheck-display-errors-function`.  There you could activate whatever you want, then delegate the call to the original function?

**Comment by rgrinberg** [comment]
Yes, I misunderstood @cpitclaudel original comment. I see how `flycheck-display-errors-function` can be used to implement what I want but IMO it's a bit inconvenient and roundabout. For example, I want to add a quit hotkey to the long error messages popup. Seems like I'd have to go through a bit of boilerplate to accomplish that.

**Comment by cpitclaudel** [comment]
I wouldn't object to a patch that sets a custom mode in flycheck-display-error-messages

**Comment by fmdkdd** [comment]
@rgrinberg Do you want to send a PR for that?

**Comment by rgrinberg** [comment]
I'm not that competent at elisp but can give it a try.

**Comment by cpitclaudel** [comment]
This was done in #1638.

**Comment by cpitclaudel** [comment]
(Thanks again @rgrinberg)
