### ISSUE TITLE
Flycheck throws an error with coffeelint and control characters

### ISSUE THREAD

**Issue by AdamNiederer** [flycheck/flycheck#1298]
To reproduce: Press `C-q C-c` in any coffeescript buffer with flycheck and coffeelint enabled. Your coffeescript buffer will look like this:
```
^C
```

Flycheck will throw this error:

```
Suspicious state from syntax checker coffee-coffeelint: Flycheck checker coffee-coffeelint returned non-zero exit code 1, but its output contained no errors: <?xml version="1.0" encoding="utf-8"?>
<checkstyle version="4.3">
<file name="stdin">
<error line="1"
    severity="error"
    message="[stdin]:1:1: error: unexpected 

^; context: "
    source="coffeelint"/>
</file>
</checkstyle>

Try installing a more recent version of coffee-coffeelint, and please open a bug report if the issue persists in the latest release.  Thanks!
```
Versioning & Configuration:

```
Syntax checkers for buffer kek.coffee in coffee-mode:

  coffee
    - may enable: yes
    - executable: Found at /usr/bin/coffee

  coffee-coffeelint
    - may enable:         yes
    - executable:         Found at /usr/bin/coffeelint
    - configuration file: Found at "/home/redacted/.coffeelint.json"

Flycheck Mode is enabled.  Use C-u C-c ! x to enable disabled checkers.

--------------------

Flycheck version: 31snapshot (package: 20170721.911)
Emacs version:    25.2.1
System:           x86_64-unknown-linux-gnu
Window system:    x
```

```bash
$ coffeelint --version
1.16.0```

**Comment by fmdkdd** [comment]
Thanks for the report.

Looks like `flycheck-parse-checkstyle` cannot parse this correctly.  I'm not sure the XML output by `coffeelint` is correct though: are attribute values allowed to span multiple lines?

**Comment by fmdkdd** [comment]
Setting `flycheck-xml-parser` to `flycheck-parse-xml-region` instead of `libxml-parse-xml-region` fixes it.

So it looks like the bug is with libxml which does not like some escape characters.

@cpitclaudel, should this go to the Emacs bug tracker?

**Comment by cpitclaudel** [comment]
Can you provide a copy of the input that doesn't parse? Calling libxml-parse-xml-region works fine for me :/ (though it drops the newlines)

**Comment by fmdkdd** [comment]
With the following in an empty buffer and eval `libxml-parse-xml-region (point-min) (point-max)`, I get `nil`, while `flycheck-parse-xml-region` returns `(foo nil "^C")`.

```
<foo>

</foo>
```
This is character 0x3, but Github seems to eat them for display and turn them into 0xfffd, so you cannot copy the above to your buffer.  You can get them in the raw comment (when going to "Edit comment"), or use `C-q C-c` directly.

I don't know which behavior is correct though (maybe XML doesn't allow control characters?).

**Comment by fmdkdd** [comment]
@cpitclaudel While we are on the topic of libxml, did you manage to reproduce using the input above?

**Comment by cpitclaudel** [comment]
Same here, and libxml is doing the right thing: https://stackoverflow.com/questions/404107/why-are-control-characters-illegal-in-xml-1-0

It's a coffeelint bug, essentially: coffeelint is producing malformed output, and libxml is appropriately refusing to parse it. We *could* report the xml-parse-region bug (it should reject the string, not parse it), but maybe leniency is acceptable here.

**Comment by fmdkdd** [comment]
Okay, not our bug then.  I agree that leniency seems more useful for `xml-parse-region`.  Although, we know that can't rely on it supporting control characters in the future as they might become more strict.
