### ISSUE TITLE
Disable typescript-tslint checker in node_modules

### ISSUE THREAD

**Issue by raxod502** [flycheck/flycheck#1309]
I use Flycheck with the `typescript-tslint` checker in my TypeScript/Node.js projects. One thing that annoys me is that whenever I jump-to-source into `node_modules`, Flycheck hangs for a bit and then disables `typescript-tslint` because the checker has reported several thousand errors. Now, since the code in `node_modules` is not my code, I don't actually need it to be linted, and the resulting warning is superfluous.

Is there a way I can customize Flycheck so that `typescript-tslint` is automatically disabled within a `node_modules` directory? I already know how to check this condition (`locate-dominating-file`), and where the information goes (`:predicate` in `flycheck-define-checker`). However, I'm not sure how to customize the `:predicate` of a syntax checker externally to Flycheck. Is this possible?

**Comment by fmdkdd** [comment]
> I'm not sure how to customize the :predicate of a syntax checker externally to Flycheck. Is this possible?

There is no proper API for that no.  But checkers are just symbols, so I guess you could just use look at `flycheck-checker-get` and use `set` instead.

Otherwise, you could just prevent `global-flycheck-mode` to turn on in the `node_modules` directory by putting a `.dir-locals.el` containing `flycheck-global-modes nil`.

**Comment by raxod502** [comment]
Your comment led me to find this internal usage of `flycheck-checker-get`:

```
(defun flycheck-register-config-file-var (var checkers)
  "Register VAR as config file var for CHECKERS.

CHECKERS is a single syntax checker or a list thereof."
  (when (symbolp checkers)
    (setq checkers (list checkers)))
  (dolist (checker checkers)
    (setf (flycheck-checker-get checker 'config-file-var) var)))
```

Which led me immediately to the following solution to my problem:

```
(with-eval-after-load 'flycheck
  (setf (flycheck-checker-get 'typescript-tslint 'predicate)
        (lambda ()
          (not (string-match-p "/node_modules/" default-directory)))))
```

To be honest, this seems like a perfectly good API to me. Should it be documented?

**Comment by fmdkdd** [comment]
Oh right, I forgot about `setf` :)

> Should it be documented?

Well, the trouble with recommending this way is that a `:predicate` on a checker is there for a reason.  Overriding it could lead to erratic behavior, so I would not recommend this approach unless users know what they are doing.  At the very least, you'd want to save the original value of `:predicate` and call it in your own version (this would also future-proof your workaround, in case `typescript-tslint` gains a default `:predicate`).   But using `.dir-locals.el` to override proper configuration variables remains less error-prone.

This issue also serves as documentation, in any case.

**Comment by cpitclaudel** [comment]
+1 @fmdkdd. I can think of two other solutions, though:

* If you're using `global-flycheck-mode`, the use advice to add your check to `flycheck-may-enable-mode`.  We could consider having an extra user-defined predicate in there, too.

* If you're using `(add-hook 'prog-mode-hook #'flycheck-mode)`, then add another hook to typescript-tslint that turns flycheck off in `node_modules`.

We discussed disabling Flycheck by default on large buffers. I expect that would catch most of the instances of your issue.

**Comment by raxod502** [comment]
Disabling `global-flycheck-mode` is a fine solution in my case, indeed. But what if the user wants errors to be highlighted, and just not style guide violations (since the code in question does not follow `tslint`)? Then simply disabling `global-flycheck-mode` or customizing via `flycheck-may-enable-mode` would not be sufficient.

I also maintain that `.dir-locals.el` can't really solve this problem, since an automated solution would require automatically creating/modifying/overwriting `.dir-locals.el` files in every `node_modules` directory, which seems to me like a problematic mode of operation.

> add another hook to typescript-tslint

Does Flycheck support per-checker hooks? I can't find any documentation about this.

**Comment by cpitclaudel** [comment]
> I also maintain that .dir-locals.el can't really solve this problem,

I agree with this :), if you want to disable flycheck in all node_modules folders.

> Disabling global-flycheck-mode is a fine solution in my case, indeed. But what if the user wants errors to be highlighted, and just not style guide violations (since the code in question does not follow tslint)?

> Does Flycheck support per-checker hooks?

bad phrasing, sorry.  I meant something like this (untested):

```elisp
(add-hook 'flycheck-mode-hook 
  (lambda () ;; Don't use a lambda, but you get the drift :)
    (when (… check that you're in node_modules folder…)
      (push 'flycheck-disabled-checkers 'typescript-tslint))))
```

**Comment by raxod502** [comment]
Oh nice, the idea about setting `flycheck-disabled-checkers` on `flycheck-mode-hook` is an excellent idea. The only disadvantage compared to using `:predicate` AFAICT is that it won't update automatically if the parent directory is renamed to `node_modules`, which is a perversely uncommon use case.

**Comment by cpitclaudel** [comment]
> The only disadvantage compared to using :predicate AFAICT is that it won't update automatically if the parent directory is renamed to node_modules, which is a perversely uncommon use case.

Indeed. I think that's consistent with our `:disabled` tag, so I'm not too worried :)
For that case you'd use advice on `flycheck-may-use-checker`.

But now that I think of it, can't you add advice on the `:predicate`, even?
As in, does something like this work?

```elisp
(advice-add :before-while ;; or :after-whille
            (flycheck-checker-get 'typescript-tslint 'predicate)
            (lambda () (… additional predicate here…)))
```

**Comment by raxod502** [comment]
> can't you add advice on the `:predicate`, even?

I don't think so, as the original `:predicate` is `nil` in this case and AFAIK you can't add an advice to a function value of nil. (Or at least I would expect you to get a `void-function` error when the advice delegates to the original definition.) But I could definitely be wrong about that.

**Comment by cpitclaudel** [comment]
Right, good point. We could consider changing `nil` predicates to `(lambda () t)`.  I wonder if that'd be worth it. Might be something to keep in mind if similar requests pop up :)
