### ISSUE TITLE
Readthedocs project ownership

### ISSUE THREAD

**Issue by lunaryorn** [flycheck/flycheck#1310]
Hi,

while organizing the transfer of flycheck.org to @mgudemann as per #1257 I realized that I'm still an administrator of the readthedocs project that builds and serves the site behind flycheck.org.

Since I'm not part of this project anymore I'd like to transfer the ownership of the readthedocs project as well: @fmdkdd, shall I transfer it to you?

**Comment by fmdkdd** [comment]
@lunaryorn Sure.  I need to register an account there first I guess?

**Comment by lunaryorn** [comment]
@fmdkdd I think so; I don't know whether it links to Github; my account there is like ages old :blush:

**Comment by fmdkdd** [comment]
@lunaryorn Seems you can't log in with Github, but you can link the Github account afterwards.  I have created an account `fmdkdd`.  You might be able to transfer now?

**Comment by lunaryorn** [comment]
@fmdkdd I added you to the project; it should now appear in your readthedocs dashboard.

Unfortunately I can't remove myself from the project.  Would you mind to remove me (lunaryorn) from the project, on <https://readthedocs.org/dashboard/flycheck/users/>?

**Comment by fmdkdd** [comment]
@lunaryorn Done.  And thanks for all your work, again :+1:

**Comment by mgudemann** [comment]
@fmdkdd hi, sorry for being late. Could you please add my account `mgudemann` to rtd, too.

**Comment by fmdkdd** [comment]
@mgudemann Done.  And thank you for hosting the domain, by the way ;)

**Comment by lunaryorn** [comment]
Thanks y'all 👍❤️

**Comment by cpitclaudel** [comment]
Thanks @lunaryorn and thanks @fmdkdd and @mgudemann :) Sorry for the delayed answer, too.
I think I was already an admin on that project, or maybe @fmdkdd just added me? In any case we're all good!
