### ISSUE TITLE
flycheck: shellcheck: Not following source

### ISSUE THREAD

**Issue by davidhedlund** [flycheck/flycheck#1313]
* What you did, and what you expected to happen instead

I have the following files:

/home/me/test_script
> #!/bin/bash
> source /home/me/test_source

/home/me/test_source
> #!/bin/bash
> foo="hello";

And I get this flycheck error message:
> Not following: /home/me/test_source was not specified as input (see shellcheck -x).

shellcheck error message (none):
> /home/me/.cabal/bin/shellcheck -x /home/me/test_script

* Whether and how you were able to [reproduce the issue in emacs -Q][emacsQ]: shellcheck didn't load with emacs -Q
* Your Flycheck setup from `M-x flycheck-verify-setup`

```
Syntax checkers for buffer youtube-dl-discogs in sh-mode:

  rpm-rpmlint (disabled)
    - may enable: Automatically disabled!
    - predicate:  nil
    - executable: Not found

  sh-bash
    - may enable: yes
    - predicate:  t
    - executable: Found at /bin/bash

  sh-posix-dash
    - may enable: yes
    - predicate:  nil
    - executable: Found at /bin/dash

  sh-posix-bash
    - may enable: yes
    - predicate:  nil
    - executable: Found at /bin/bash

  sh-zsh
    - may enable: Automatically disabled!
    - predicate:  nil
    - executable: Not found

  sh-shellcheck
    - may enable:           yes
    - predicate:            t
    - executable:           Found at /home/me/.cabal/bin/shellcheck
    - Shell bash supported: yes

Flycheck Mode is enabled.  Use C-u C-c ! x to enable disabled
checkers.

--------------------

Flycheck version: 30
Emacs version:    24.3.1
System:           x86_64-pc-linux-gnu
Window system:    x
```
* Your operating system: Trisquel GNU/Linux 7.
* Your Emacs version from `M-x emacs-version`: GNU Emacs 24.3.1 (x86_64-pc-linux-gnu, GTK+ Version 3.10.7) of 2014-03-07 on lamiak, modified by Debian
* Your Flycheck version from `M-x flycheck-version`: Flycheck version: 30

**Comment by davidhedlund** [comment]
Exactly which line(s) should I add to .emacs to make flycheck behave like shellcheck for source?

**Comment by cpitclaudel** [comment]
Can you try again on the latest Flycheck (from MELPA)? I think your problem should be fixed there. (https://github.com/flycheck/flycheck/pull/1256)

**Comment by davidhedlund** [comment]
@cpitclaudel Thanks, ```source``` is working fine in
> Flycheck version: 31alpha (package: 20170823.1732)

**Comment by cpitclaudel** [comment]
Thanks for testing!
