### ISSUE TITLE
Automatically find head files in working directory's sub-directory

### ISSUE THREAD

**Issue by cobblau** [flycheck/flycheck#1319]
I have a big C++ project that header files located in many sub-directory.
Can `flycheck` adds a new variable which can be used to find head files in working directory's sub-directory automatically?
Or by reading compilation info from compile_commands.json?

**Comment by fmdkdd** [comment]
Automatic detection of header files is out of scope for Flycheck itself.  

However, it is the exact purpose of [extensions](http://www.flycheck.org/en/latest/community/extensions.html).  You might want to look at [flycheck-irony](https://github.com/Sarcasm/flycheck-irony) and let us know if that fits your use case.
