### ISSUE TITLE
Display time consumed in checker

### ISSUE THREAD

**Issue by nordlow** [flycheck/flycheck#1326]
I would like to get information about how long it took for the current checker to complete, in my case when I hack on my D projects. This because I want to assert that I use the fastest compile-time constructs possible. Is this possible somehow? It would be supernice if I could get this information in the modeline, right beside the current `m/n` information.

**Comment by fmdkdd** [comment]
> Is this possible somehow?

I think we could make that an option, yes.  It could be useful when profiling as well.

> It would be supernice if I could get this information in the minibuffer, right beside the current m/n information.

Did you mean on the modeline, beside the `FlyC:5/18` lighter which reports the number of errors and warnings?  The minibuffer only displays the error message at point.

cc @cpitclaudel

**Comment by nordlow** [comment]
Yes, I mean to display it in the modeline.

Where should the timing and display code be inserted?

**Comment by fmdkdd** [comment]
> Where should the timing and display code be inserted?

If you want to submit a patch, my first instinct would be to record the starting time in `flycheck-start-current-syntax-check`, and the end time in `flycheck-finish-current-syntax-check`.
Alternatively, you could use the `flycheck-before-syntax-check-hook` and `flycheck-after-syntax-check-hook` to set the start and end times.

Displaying the difference should go in `flycheck-mode-line-status-text`, under the `finished` case.

**Comment by nordlow** [comment]
Should the time measured be a buffer-local variable?

**Comment by fmdkdd** [comment]
> Should the time measured be a buffer-local variable?

I think so yes. 

> If so what name do you suggest?

What about `flycheck-last-syntax-check-duration`?

> And what about multiple chained checkers?

If we are to display only one number, I think it should be the duration of the whole syntax checking phase, including all checkers in the chain.  For most languages (including D) there is only one checker anyway.

**Comment by nordlow** [comment]
Great. What do you think about the proposed format about?

**Comment by fmdkdd** [comment]
> What do you think about the proposed format above?

It looks fine, although there may be some recommandations against putting space in a mode lighter, as by convention spaces delimit modes.

In this case though, the time would only be displayed if the option has been enabled by the user explicitly (a `defcustom` which defaults to `nil`), so it should be fine to use a space.

**Comment by nordlow** [comment]
Made an initial hack here: https://github.com/flycheck/flycheck/pull/1327

**Comment by cpitclaudel** [comment]
I like this idea. But I wonder: since we already have the necessary hooks (`before-` and `after-syntax-check-hook`), would this make sense as a plug-in? Ideally, it'd wrap around existing mode line tweaks, making it compatible with other plugins that change the flycheck modeline format.

**Comment by fmdkdd** [comment]
@cpitclaudel Sure, we can do that.  We can review #1327 and put it in a separate repository once we agree on the specifics.

**Comment by nordlow** [comment]
Thanks.

**Comment by nordlow** [comment]
Thanks. Do you want anything from me at the time?

**Comment by fmdkdd** [comment]
> Ideally, it'd wrap around existing mode line tweaks, making it compatible with other plugins that change the flycheck modeline format.

@cpitclaudel It would be nice indeed if this extension could just append to whatever modeline text Flycheck already produces.  I'm not sure *how* to make this happen though: it seems `flycheck-status-emoji` overrides `flycheck-mode-line-status-text` completely for instance, so we cannot advise the function.

But maybe the intersection of people would activate both extension is empty, so that's fine.  `flycheck-color-mode-line` should be already compatible since it just changes a face, not the text.

**Comment by cpitclaudel** [comment]
Closing this.  As mentioned in the attached PR, this would be great as a separate package like the eoji modeline one, and we're happy to help if you run into issues.
