### ISSUE TITLE
Suspicious state from syntax checker javascript-eslint

### ISSUE THREAD

**Issue by Grox-Ni** [flycheck/flycheck#1330]
Hello,
 
Flycheck version: 31snapshot (package: 20170911.127)
Emacs version:    25.3.1(I am using Spacemacs with React layer)
System:           x86_64-apple-darwin16.4.0
Window system:    ns

I am opening a js file, and the flycheck is not working properly.

Error message is:

```

Suspicious state from syntax checker javascript-eslint: Flycheck checker javascript-eslint returned non-zero exit code 1, but its output contained no errors: can't resolve reference #/definitions/basicConfig from id #
can't resolve reference #/definitions/basicConfigOrBoolean from id #
can't resolve reference #/definitions/basicConfigOrBoolean from id #
<?xml version="1.0" encoding="utf-8"?><checkstyle version="4.3"><file name="/Users/grox/LintCode/LintCode/react/src/apps/problem/containers/ProblemListPage.js"><error line="19" column="26" severity="error" message="Multiple spaces found before &apos;style&apos;. (no-multi-spaces)" source="eslint.rules.no-multi-spaces" /></file></checkstyle>

Try installing a more recent version of javascript-eslint, and please open a bug report if the issue persists in the latest release.  Thanks!


```
I used yarn global to install node packages(like eslint) and have upgraded them all.

**Comment by fmdkdd** [comment]
It seems to me this is the same issue as #1323.  If so, the error really is from the react plugin for `eslint`, and a fix has already been issue from their side, as far as I understand.

**Comment by fmdkdd** [comment]
@Grox-Ni Have you tried updating `eslint-plugin-react` to 7.2 or later?  This should fix your issue.

**Comment by n3dst4** [comment]
I am getting the `Suspicious state from syntax checker` error on a minimal project with no eslint plugins. Seems like eslint always sets exit code 1 if any problems are found. I'm using `add-node-modules-path` from MELPA to get local `node_modules/.bin` on PATH.

Flycheck: 20171019.83
add-node-modules-path: 20170914.191
Emacs: GNU Emacs 25.3.1 (x86_64-w64-mingw32) of 2017-09-2

I've pushed my minimal repro repo here: https://github.com/n3dst4/eslint-exit-codes

I'm new to emacs and thus also flycheck, so if there's any more info I can provide or anything else I can do to help, let me know.

**Comment by fmdkdd** [comment]
@n3dst4 Thanks for the repro.  The relevant part is:
```
Suspicious state from syntax checker javascript-eslint: Flycheck checker javascript-eslint returned non-zero exit code 1, but its output contained no errors: <?xml version="1.0" encoding="utf-8"?><checkstyle version="4.3"><file name="c:/git/eslintfu/good.js"><error line="4" column="1" severity="error" message="Too many blank lines at the end of file. Max of 0 allowed. (no-multiple-empty-lines)" source="eslint.rules.no-multiple-empty-lines" /></file></checkstyle>
```
Here, it looks like Flycheck can't parse the output (i.e., finds no error), even though eslint reports some errors were found (via the non-zero exit code).

Flycheck uses the function `flycheck-parse-checkstyle` to parse the output of `eslint`, but there are two XML backends that can be used.  When I run it manually on this error, it parses fine.

So maybe it's the XML backend on Windows that has issues parsing this?  Can you try the following on your side:

1. Open a new buffer `C-x b foo RET`
2. Paste the following into it:
```emacs-lisp
(defun test-checkstyle ()
  (interactive)
  (goto-char (point-max))
  (let ((output (buffer-string)))
    (dolist (flycheck-xml-parser '(flycheck-parse-xml-region libxml-parse-xml-region))
      (insert (format "\n\n== Parsing with %s:\n%s" flycheck-xml-parser
                      (flycheck-parse-checkstyle output 'eslint (current-buffer)))))))
```
Put your cursor anywhere inside the function, then do `M-x eval-defun`.  This is a function that will try to parse a checkstyle string using both XML backends.
3. Erase the contents of the buffer (or make a new one, just make sure it is empty).
4. Paste the error reported by eslint from your repro:
```
<?xml version="1.0" encoding="utf-8"?><checkstyle version="4.3"><file name="c:/git/eslintfu/good.js"><error line="4" column="1" severity="error" message="Too many blank lines at the end of file. Max of 0 allowed. (no-multiple-empty-lines)" source="eslint.rules.no-multiple-empty-lines" /></file></checkstyle>
```
5. `M-x test-checkstyle`

Here are the contents of the buffer on my side when I do the above:
```
<?xml version="1.0" encoding="utf-8"?><checkstyle version="4.3"><file name="c:/git/eslintfu/good.js"><error line="4" column="1" severity="error" message="Too many blank lines at the end of file. Max of 0 allowed. (no-multiple-empty-lines)" source="eslint.rules.no-multiple-empty-lines" /></file></checkstyle>

== Parsing with flycheck-parse-xml-region:
([cl-struct-flycheck-error aroisetnr eslint c:/git/eslintfu/good.js 4 1 Too many blank lines at the end of file. Max of 0 allowed. (no-multiple-empty-lines) error eslint.rules.no-multiple-empty-lines nil])

== Parsing with libxml-parse-xml-region:
([cl-struct-flycheck-error aroisetnr eslint c:/git/eslintfu/good.js 4 1 Too many blank lines at the end of file. Max of 0 allowed. (no-multiple-empty-lines) error eslint.rules.no-multiple-empty-lines nil])
```

**Comment by n3dst4** [comment]
Aha, and when I do it I get:

```
<?xml version="1.0" encoding="utf-8"?><checkstyle version="4.3"><file name="c:/git/eslintfu/good.js"><error line="4" column="1" severity="error" message="Too many blank lines at the end of file. Max of 0 allowed. (no-multiple-empty-lines)" source="eslint.rules.no-multiple-empty-lines" /></file></checkstyle>


== Parsing with flycheck-parse-xml-region:
([cl-struct-flycheck-error foo eslint c:/git/eslintfu/good.js 4 1 Too many blank lines at the end of file. Max of 0 allowed. (no-multiple-empty-lines) error eslint.rules.no-multiple-empty-lines nil])

== Parsing with libxml-parse-xml-region:
nil
```

**Comment by fmdkdd** [comment]
You can try to force the the XML parser used by Flycheck with `(setq flycheck-xml-parser 'flycheck-parse-xml-region)` in your config.

Then you can try to use eslint on a buffer see if that makes a difference.

But, Flycheck should already have set the correct value and detected that libxml2 was not available.

**Comment by fmdkdd** [comment]
Great!  I'm surprised the auto-detection of the XML backend failed, but at least you can override it.

**Comment by cpitclaudel** [comment]
@n3dst4 You're on Windows, right?  I think this bi of the Emacs source code explains it:

```c
DEFUN ("libxml-parse-xml-region", Flibxml_parse_xml_region,
       Slibxml_parse_xml_region,
       2, 4, 0,
       doc: /* Parse the region as an XML document and return the parse tree.
If BASE-URL is non-nil, it is used to expand relative URLs.
If DISCARD-COMMENTS is non-nil, all HTML comments are discarded. */)
  (Lisp_Object start, Lisp_Object end, Lisp_Object base_url, Lisp_Object discard_comments)
{
  if (init_libxml2_functions ())
    return parse_region (start, end, base_url, discard_comments, false);
  return Qnil;
}
```

```c
static bool
init_libxml2_functions (void)
{
#ifdef WINDOWSNT
  if (libxml2_loaded_p ())
    return true;
  else
    {
      HMODULE library;

      if (!(library = w32_delayed_load (Qlibxml2)))
	{
	  message1 ("libxml2 library not found");
	  return false;
	}

      if (! load_dll_functions (library))
	goto bad_library;

      Vlibrary_cache = Fcons (Fcons (Qlibxml2, Qt), Vlibrary_cache);
      return true;
    }

 bad_library:
  Vlibrary_cache = Fcons (Fcons (Qlibxml2, Qnil), Vlibrary_cache);

  return false;
#else  /* !WINDOWSNT */
  return true;
#endif	/* !WINDOWSNT */
}
```

I expect your Emacs was compiled with libxml2 support, but Emacs can't find the appropriate DLL.  Just downloading the `emacs-…-deps.zip` package for your version of Emacs should work.  Do you see "libxml2 library not found" in your *Messages* buffer?

@fmdkdd I'm not sure what the appropriate way to detect libxml availability; maybe we should ask? Or maybe it's enough to try both:

```elisp
(if (and (fboundp 'libxml-parse-region)
         (with-temp-buffer
           (insert "<xml />")
           (libxml-parse-xml-region (point-min) (point-max))))
    #'libxml-parse-region
  #'xml-parse-region)
```

**Comment by n3dst4** [comment]
@cpitclaudel correct, and it turns out the x64 builds of emacs are community driven and they don't bundle the deps (as you note). For the sake of anyone finding this thread in future, I've just downloaded a batteries-included x64 build for windows from https://github.com/zklhp/emacs-w64/releases and it works perfectly. I repeated @fmdkdd's `test-checkstyle` and it worked with both parsers.

**Comment by fmdkdd** [comment]
Nice bit of spelunking!

>  I'm not sure what the appropriate way to detect libxml availability; maybe we should ask? 

Trying to actually parse with it seems fine.  It seems a bit involved of a test though (since it runs when loading flycheck), I'd rather have something faster if there is an alternative.

**Comment by cpitclaudel** [comment]
> I'd rather have something faster if there is an alternative.

Yup. Should I ask on emacs-devel?

We could cache the result of the check, and delay the actual check until the xml parser is first called, too.

**Comment by fmdkdd** [comment]
> Should I ask on emacs-devel?

Please do.

> delay the actual check until the xml parser is first called, too.

Yes, that might be best solution in the end.

**Comment by cpitclaudel** [comment]
> Please do.

I did, and it doesn't seem there's a good solution beyond the proposal above.
This got me wondering: should we just always start with libxml and fall back to xml-parse-region (unless flycheck-parse-xml-region is customized to tell us otherwise)?
This would also solve cases where xml-parse-region is more tolerant to malformed input than libxml-parse-xml-region.

**Comment by fmdkdd** [comment]
(Link to the [emacs-devel thread](https://lists.gnu.org/archive/html/emacs-devel/2017-10/msg00687.html))

>  should we just always start with libxml and fall back to xml-parse-region 

Don't you mean the other way around?  I believe we already start with libxml if it is present.

I guess libxml is more performant, but since it's not available everywhere, it can cause surprises.  
I would be in favor of adding the improved detection of libxml, but delaying the test until the first call to the xml parser.

If the emacs-devel thread suggests a better way to detect it, then we'll just substitute the test.

**Comment by cpitclaudel** [comment]
> Don't you mean the other way around? I believe we already start with libxml if it is present.

No, I meant to use the following function for parsing:

```elisp
(defun flycheck--parse-xml-region (beg end)
  (or (and (fboundp 'libxml-parse-xml-region)
           (libxml-parse-xml-region beg end))
      (xml-parse-region beg end))
```

**Comment by fmdkdd** [comment]
@cpitclaudel Yeah, that looks fine.  Do you want to make the PR?

**Comment by cpitclaudel** [comment]
Will do. Is it just me though, or does eslint actually print usage information when passed an empty file on the command line?

```
$ touch a.js
$ eslint --format=checkstyle --stdin --stdin-filename a.js < a.js
eslint [options] file.js [file.js] [dir]

Basic configuration:
  -c, --config path::String

      Use
      configuration
      from
      this
      file
      or
      shareable
      config
  --no-eslintrc

      Disable
      use
      of
      configuration
      from
      .eslintrc
  --env [String]

      Specify
      environments
  --ext [String]

      Specify
      JavaScript
      file
      extensions
      -
      default:
      .js
[… lots more output …]
$ echo $?
0
```

What's up with that? And how come we never noticed it? (libxml returns nil on failure, but xml-parse-region actually raises errors)

**Comment by fmdkdd** [comment]
> What's up with that? 

Sounds like a bug to me, or at least, an non-intuitive result.

> And how come we never noticed it?

`nil` is the same thing as no error in this case, right?  I have `libxml` support, so I guess it was always silent when running the integration tests on my end.

**Comment by cpitclaudel** [comment]
> nil is the same thing as no error in this case, right? I have libxml support, so I guess it was always silent when running the integration tests on my end.

Right, same here :)

I'll open an eslint issue

**Comment by cpitclaudel** [comment]
https://github.com/eslint/eslint/issues/9515
