### ISSUE TITLE
Disable flycheck-display-error-at-point by timer

### ISSUE THREAD

**Issue by Pitometsu** [flycheck/flycheck#1332]
How can I disable `flycheck` behaviour  automatically display errors at point by timeout?
Just want to see it with `C-c ! h` on demand.

**Comment by Pitometsu** [comment]
My current hacky workaround:

```
(defadvice flycheck-display-error-at-point-soon
    (after flycheck-display-error-at-point-soon-advice activate compile)
  (flycheck-cancel-error-display-error-at-point-timer))
```

**Comment by fmdkdd** [comment]
I don't think we offer any option to toggle it off.  But your workaround seems fine to me.  You could also redefine `flycheck-display-error-at-point-soon` to be a no-op, or remove it from `post-command-hook` after `flycheck-mode` loads.

Changing the delay value to 0 or negative values just triggers the function immediately.

**Comment by Pitometsu** [comment]
@fmdkdd thanks,

something like that?
```elisp
(defun flycheck-display-error-at-point-soon ()
  "No-op placeholder")

(defun init-flycheck-hook ()
  (remove-hook 'post-command-hook 'flycheck-display-error-at-point-soon)
  (remove-hook 'focus-in-hook 'flycheck-display-error-at-point-soon))

(add-hook 'flycheck-mode-hook 'init-flycheck-hook)
```

**Comment by fmdkdd** [comment]
@Pitometsu Exactly.  Though only one of them would be necessary.  Thanks for putting the code explicitly for fellow future travelers who would have the same issue :)

**Comment by Pitometsu** [comment]
@fmdkdd thank you, issue solved for me, keeping it open up to your decision according to necessity of implementing such option (to toggle it).

**Comment by fmdkdd** [comment]
Thanks.  At this point, I don't feel a variable would bring any benefit over these simple workarounds.

**Comment by Pitometsu** [comment]
Okay, looks like that fix not full. Despite that messages now doesn't appears automatically when cursor on item, it appear yet right after editing.

**Comment by fmdkdd** [comment]
Which workaround were you using?

>  it appear yet right after editing.

Do you mean, you edit, then the syntax checking takes places, and the message appears?  `flycheck-display-error-at-point` is called when a syntax checks finish, so that might be the cause.  I don't think you can workaround this one reliably.

Maybe a variable is warranted after all!

**Comment by Pitometsu** [comment]
@fmdkdd yeah, looks like it caused by flycheck-finish-current-syntax-check which call flycheck-display-error-at-point. The whole function overriding isn't feels right.

Would you accept PR with such defcustom?

**Comment by Pitometsu** [comment]
My main motivation for this option is speed-up scrolling/navigation.
When I read/edit not very clean code it's very annoying, when it freezing for a moment from time to time to show warning which take half of screen.

**Comment by fmdkdd** [comment]
> Would you accept PR with such defcustom?

Sure, since the workarounds cannot completely disable this behavior.  I think the simplest way to do that would be to add an early exit in `flycheck-display-error-at-point` if the newly added defcustom is true.

> BTW, is it be correct to disable flycheck-idle-change-timer as well in case of inhibit automatically messages?

If you mean that we should also prevent the timer to be set/cleared when the defcustom is true, then I agree.  In fact, ideally, we should just remove the `post-command-hook` for `display-error-at-point-soon`, since there's no point to let it run.  Although, in that case, changing the defcustom value back to `nil` would not reinstate the hook.

WDYT @cpitclaudel?

**Comment by Pitometsu** [comment]
Another day, another profiling…
<img width="734" alt="screen shot 2017-10-20 at 8 16 08 pm" src="https://user-images.githubusercontent.com/2434691/31833646-ec6d9296-b5d3-11e7-87f8-fff96c5db1bf.png">

**Comment by cpitclaudel** [comment]
Can you post a copy of the profile, instead of a screenshot? I'm having trouble understanding what's so slow.

**Comment by cpitclaudel** [comment]
(You can use `profiler-report-write-profile` to save a profile to disk)

**Comment by Pitometsu** [comment]
Original issue should be fixed now by https://github.com/flycheck/flycheck/pull/1342
Sorry, looks like performance problem was not depend on flycheck, fixed it for myself.

**Comment by Pitometsu** [comment]
@cpitclaudel 

Maybe another problem here, but to avoid creating unnecessary issues, posting it here.
CPU profiling results (top):

```
- flycheck-handle-signal                                        13815  72%
 - seq-do                                                       13806  72%
  - mapc                                                        13806  72%
   - flycheck-safe-delete                                       13806  72%
    - delete-file                                               13801  72%
     - apply                                                    13801  72%
      - ad-Advice-delete-file                                   13801  72%
       + projectile-project-root                                13549  71%
```

**Comment by cpitclaudel** [comment]
Looks like I missed that last message after the issue was closed.  Hmm.  This seems to be time spent in projectile; it would be good to understand what projectile does when we delete a file.
