### ISSUE TITLE
wrong-number-of-arguments

### ISSUE THREAD

**Issue by gour** [flycheck/flycheck#1335]
* What you did, and what you expected to happen instead

Start editing my init.el and Debugger produced backtrace.

* Whether and how you were able to [reproduce the issue in emacs -Q][emacsQ]

I typed '(use' when I want to install some new stuff via use-package - it's 100% reproduceable here.

* Your Flycheck setup from `M-x flycheck-verify-setup`

Syntax checkers for buffer init.el in emacs-lisp-mode:

  emacs-lisp
    - may enable: yes
    - predicate:  t
    - executable: Found at /usr/bin/emacs

  emacs-lisp-checkdoc
    - may enable: yes
    - predicate:  t
    - executable: Found at /usr/bin/emacs

Flycheck Mode is enabled.  Use C-u C-c ! x to enable disabled
checkers.

--------------------

Flycheck version: 31snapshot (package: 20170902.312)
Emacs version:    25.3.1
System:           x86_64-redhat-linux-gnu
Window system:    x

* Your operating system

x86_64 GNU/Linux (Fedora f26)

* Your Emacs version from `M-x emacs-version`

GNU Emacs 25.3.1 (x86_64-redhat-linux-gnu, GTK+ Version 3.22.19) of 2017-09-15

* Your Flycheck version from `M-x flycheck-version`

Flycheck verson: 31snapshot (package 20170902.312)

Here is the backtrace (just cleaned from control characters):

Debugger entered--Lisp error: (wrong-number-of-arguments #[(ad--addoit-function buffer) "\306\203\307
\306\310#\202)\207" [ad-return-value ac-completing ac-flycheck-poll-completion-end-interval ac-flycheck-poll-completion-end-timer ad--addoit-function buffer nil run-at-time flycheck-handle-idle-change] 4] 1)
  ad-Advice-flycheck-handle-idle-change(#[257 "\300!\205r\211q\210\301 \210\302\303!)\207" [buffer-live-p flycheck-clear-idle-change-timer flycheck-buffer-automatically idle-change] 3 ("/home/gour/.emacs.d/elpa/flycheck-20170902.312/flycheck.elc" . 101645)])
  apply(ad-Advice-flycheck-handle-idle-change #[257 "\300!\205r\211q\210\301 \210\302\303!)\207" [buffer-live-p flycheck-clear-idle-change-timer flycheck-buffer-automatically idle-change] 3 ("/home/gour/.emacs.d/elpa/flycheck-20170902.312/flycheck.elc" . 101645)] nil)
  flycheck-handle-idle-change()
  apply(flycheck-handle-idle-change nil)
  timer-event-handler([t 22986 10204 335670 nil flycheck-handle-idle-change nil nil 416000])

but not sure whether it is related to #1324  and/or #1265?

**Comment by cpitclaudel** [comment]
Thanks. Just to confirm: this isn't in Emacs -Q, right? What else do you have in your config?
Also, can you try with the latest FLycheck? I think this was fixed on 2017-09-11 in https://github.com/flycheck/flycheck/pull/1321

**Comment by gour** [comment]
> Thanks. Just to confirm: this isn't in Emacs -Q, right? 

Ahh..correct.

> What else do you have in your config?

Lpt of stuff. :-)

> Also, can you try with the latest Flycheck? I think this was fixed on 2017-09-11 in #1321

You're right - update to 20170911.127 fixes it! Thank you.
