### ISSUE TITLE
Trouble configuring flycheck to use .eslintrc.js local to project

### ISSUE THREAD

**Issue by sunwukung** [flycheck/flycheck#1338]
I've recently moved to a new role which uses Windows, and I'm struggling to reconfigure flycheck to work with some of the idiosyncracies of that environment. One of those is that flycheck seems unable to work with the eslint configuration file that resides in each project's root at ./.eslintrc.js - and extends a module within that projects node_modules folder. Here is my setup: 

```
Syntax checkers for buffer stuff.js in rjsx-mode:

  javascript-eslint (disabled)
    - may enable:  Automatically disabled!
    - executable:  Found at c:/Dev/devtools/bin/npm/eslint.cmd
    - config file: missing or incorrect

  javascript-jshint (disabled)
    - may enable:         Automatically disabled!
    - executable:         Not found
    - configuration file: Not found

  javascript-jscs (disabled)
    - may enable:         Automatically disabled!
    - executable:         Not found
    - configuration file: Not found

  javascript-standard (disabled)
    - may enable: Automatically disabled!
    - executable: Not found

Flycheck Mode is enabled.  Use C-u C-c ! x to enable disabled
checkers.

--------------------

Flycheck version: 31snapshot (package: 20170911.127)
Emacs version:    25.2.1
System:           x86_64-w64-mingw32
Window system:    w32
```
I believe the javascript-eslint checker has located the file but is unable to parse it? 
I've run eslint on the command line from the root directory of the project and it works as expected

JFTR - I have flycheck working on my homesetup (MacOS) using a global .eslint file #

**Comment by fmdkdd** [comment]
Keep in mind we don't officially support Windows; as we cannot test Flycheck on it.

You may have to get debug the `javascript-eslint` checker in order to find out what is working differently between your home setup on your Windows box.  I would start with `flycheck-eslint-config-exists-p`.

**Comment by sunwukung** [comment]
Sure - although I am not sure if this is a windows specific issue, since it can locate the eslint executable. I suspect the issue is more about the format of the eslint file itself, as it extends a private repository of linting rules. I'm not sure how the checker works - does it just delegate to the eslint in the OS?

**Comment by Simplify** [comment]
Hi @sunwukung,

In Flycheck we let `eslint` to find right config file. However, on every new buffer we "ask" `eslint` if config is valid. If not, we disable checker. Try running in `eslint` executable with `--print-config .` inside the directory where your JS file is located. If your configuration is valid you should get JSON output from that command. If not, that is the reason why flycheck disables eslint checker.

**Comment by sunwukung** [comment]
Hi,

I ran this command

```
eslint --print-config ./.eslintrc.js
```
and the output was json as expected
the project directory looks like this

```
.eslintrc.js
node_modules/
- eslint
- eslint-config-airbnb
- eslint-plugin-react
-eslint-plugin-import
-eslint-plugin-jsx-a11y
```

Interestingly, I made a dummy project with a similar structure, but replaced the .eslintrc.js with an eslintrc.js (note the omission of the dot) and it works. So I believe the problem may be that emacs cannot see dotfiles on windows?

**Comment by Simplify** [comment]
Hi,

As said, nor Flycheck nor GNU Emacs are looking for your `.eslintrc.js`, with or without dot. We let `eslint` do that (see link below how eslint finds config file). We do not specify `-c` option when executing `eslint` from Flycheck.

According to [eslint config file documentation](https://eslint.org/docs/user-guide/configuring#configuration-file-formats), that dot is required. My guess is that when you removed dot from filename, `eslint` stopped using that file, and uses some other configuration, probably from your home directory `C:\Users\<your-username>\.eslintrc.*`.

**Comment by sunwukung** [comment]
No, you're right - I misreported. 

I copied the .eslintrc.js to the test project and linting works - but then when I open files in the other project, it doesn't. My next port of call is copying the package.json between the projects to see if it's an issue with that

**Comment by sunwukung** [comment]
A-ha! I've managed to reproduce the error! When the project looks like this it works

```
file-to-lint.js
.eslintrc.js
/node-modules 
```
it works

however, if the file-to-lint is nested then it no longer works i.e 

```
.eslintrc.js
/node-modules
/src
- file-to-lint.js
```

**Comment by sunwukung** [comment]
The issue was this: 

the .eslintrc.js file looked like this

```
module.exports = {
  "extends": path.resolve('./node_modules/our-linting/.eslintrc.json'),
  },
}
```

and it needed to be this: 

```
module.exports = {
  "extends": path.resolve(__dirname, './node_modules/our-linting/.eslintrc.json'),
  },
}
```

thanks for your patience

**Comment by Simplify** [comment]
Np, I'm glad that you found the problem :)

**Comment by siegy22** [comment]
@Simplify Sorry to bump such an old issue but I hope you can help me out.

I configured my flycheck to be able to lint with eslint with the eslint which is installed in the `node_modules` folder: https://github.com/siegy22/dotfiles/blob/master/spacemacs#L435-L452

Now if I open up any `.js` file inside the project, it can't find my `.eslintrc.js` which is located in the project's root:

```
  javascript-eslint (disabled)
    - may enable:  Automatically disabled!
    - executable:  Found at /Users/siegy/projects/contracts/node_modules/eslint/bin/eslint.js
    - config file: missing or incorrect
```

Any ideas? 🤔
