### ISSUE TITLE
flycheck 30 tests broken with buttercup 1.9

### ISSUE THREAD

**Issue by spwhitton** [flycheck/flycheck#1341]
Hello,

With the latest released version of Flycheck (30), the test are broken with Buttercup 1.9.  See:

https://ci.debian.net/packages/f/flycheck/unstable/amd64/
https://tests.reproducible-builds.org/debian/rb-pkg/unstable/amd64/flycheck.html

Please consider making a new release addressing these failures.  Thanks!

**Comment by fmdkdd** [comment]
Thanks for the heads-up.  We have indeed fixed the issue in #1320.  I guess you could apply that patch on the Debian version, but on the other hand, we are probably overdue for a release.

WDYT @cpitclaudel ?

**Comment by cpitclaudel** [comment]
Sounds like a great idea :) And a good occasion to exercise our release setup.

**Comment by fmdkdd** [comment]
Done: Flycheck 31 is out.

**Comment by spwhitton** [comment]
And uploaded to Debian unstable.  Thanks!
