### ISSUE TITLE
Can't work after byte compiled

### ISSUE THREAD

**Issue by netjune** [flycheck/flycheck#1352]
emacs: 25.3
flycheck: 0.25.1

When not byte compiled, it works well.

----------------------------------------------------------
Debugger entered--Lisp error: (void-variable symbol)
  signal(void-variable (symbol))
  flycheck-buffer()
  flycheck-buffer-automatically(idle-change)
  flycheck-handle-idle-change()
  apply(flycheck-handle-idle-change nil)
  timer-event-handler([t 23026 45939 158780 nil flycheck-handle-idle-change nil nil 0])
------------------------------------------------------------

It seems that the problem happens in 'real-predicate' for backend.

**Comment by cpitclaudel** [comment]
Thanks for the report ! Can you provide a slightly more detailed recipe ? How did you byte-compile ? Did you install from source ? What setup are you using ? Which back end ?

**Comment by netjune** [comment]
Find the reason now. 'enable-local-variables' should be set to t before running 'byte-recompile-directory'. So close this. Thank you.
