### ISSUE TITLE
Show checker name in message

### ISSUE THREAD

**Issue by sadhu89** [flycheck/flycheck#1358]
I use 2 different checkers for the same filetype and I would like to add the name of the checker on the flychecks's message. Is this possible to configure?

**Comment by fmdkdd** [comment]
You should already see the checker name in the error list.  But if you want to see the checker name in the minibuffer, you can customize `flycheck-display-errors-function`, and reuse mostly the code of `flycheck-display-error-messages` but call a variant of `flycheck-error-format-message-and-id` to also include the checker name.  Look at `flycheck-error-format` below to see how the checker name is pretty printed.
