### ISSUE TITLE
Flycheck displaying error when no error is flycheck error list

### ISSUE THREAD

**Issue by imcvampire** [flycheck/flycheck#1359]
# Welcome

* What you did, and what you expected to happen instead
I open a normal js file, and flycheck show some error in main buffer but nothing in error list. If I run eslint in terminal, there is no error too

![screenshot_2017-11-13_15-05-13](https://user-images.githubusercontent.com/9426721/32715287-390aea46-c884-11e7-9630-ce3fc36d6526.png)

* Whether and how you were able to [reproduce the issue in emacs -Q][emacsQ]
* Your Flycheck setup from `M-x flycheck-verify-setup`
```
Syntax checkers for buffer admins.js in js2-mode:

  javascript-eslint
    - may enable:  yes
    - executable:  Found at /path/to/folder/node_modules/eslint/bin/eslint.js
    - config file: found

  javascript-jshint (disabled)
    - may enable:         yes
    - executable:         Found at /usr/bin/jshint
    - configuration file: Not found

  javascript-jscs (disabled)
    - may enable:         Automatically disabled!
    - executable:         Not found
    - configuration file: Not found

  javascript-standard (disabled)
    - may enable: Automatically disabled!
    - executable: Not found

  drupal-phpcs (disabled)
    - may enable: Automatically disabled!
    - predicate:  nil
    - executable: Not found

Flycheck Mode is enabled. Use SPC u C-c ! x to enable disabled checkers.

--------------------

Flycheck version: 32snapshot (package: 20171026.610)
Emacs version:    25.3.1
System:           x86_64-pc-linux-gnu
Window system:    x
```
* Your operating system: Linux 
* Your Emacs version from `M-x emacs-version`: GNU Emacs 25.3.1
* Your Flycheck version from `M-x flycheck-version`: 32snapshot (package: 20171026.610)

**Comment by fmdkdd** [comment]
Are you sure these underline are coming from Flycheck, and not `js2-mode`?  Try to disable flycheck and see if they are still here.

**Comment by Simplify** [comment]
Yeah, that may be the problem. I think that js2-mode uses jslint internally.

**Comment by Simplify** [comment]
If it helps, you can disable warnings about missing semicolomns and trailing comma by setting [some settings to nil](https://github.com/mooz/js2-mode/blob/master/js2-mode.el#L293). All of your problems in screenshot are related to those two.

**Comment by imcvampire** [comment]
@fmdkdd Thank you! Those come from `js2-mode`

@Simplify Thank you for the nice idea. I fixed my problem
