### ISSUE TITLE
Checker for GitLab CI

### ISSUE THREAD

**Issue by rassie** [flycheck/flycheck#1375]
[GitLab CI](https://about.gitlab.com/features/gitlab-ci-cd/) has a CI definition file called (by default) `.gitlab-ci.yml`, which can be checked as YAML, but can also be validated by an [API call](https://docs.gitlab.com/ce/api/lint.html) to a GitLab instance (e.g. gitlab.com).

Could this checker be implemented? (Ideally, the GitLab instance would be configurable to avoid thrashing gitlab.com)

**Comment by Simplify** [comment]
You could implement checker for this, but I doubt that anything what calls external service will be part of main Flycheck. 

Use `yaml-mode` for `:modes` in checker and implement `:predicate` to check if file is `.gitlab-ci.yml`. `chef-foodcritic` does something similar, but it does not check for file but directory structure. 

Your command is `curl` i guess. [omnisharp-emacs](https://github.com/OmniSharp/omnisharp-emacs) used to do that before, check their older source code.

You'll need to implement parsing of errors from response. Their API page is not helpful, I don't see any example with errors with line/column numbers in example output. There are few examples in Flycheck source for parsing of JSON (including tests) that can be used as reference. 

To avoid constantly making calls to GitLab you can set Flycheck to do it [only on save](http://www.flycheck.org/en/stable/user/syntax-checks.html#variable-flycheck-check-syntax-automatically) for example.

**Comment by cpitclaudel** [comment]
Indeed this shouldn't be too hard to do, likely as a separate package; we don't have anyone in the team currently who will work on it, so I'll close this.

**Comment by rassie** [comment]
Oh wow, that's an old ticket of mine! Just for the record: there is a package at https://gitlab.com/joewreschnig/gitlab-ci-mode-flycheck which does exactly that and which I'm using. It's not perfect, but does the job.

**Comment by cpitclaudel** [comment]
Beautiful! Thanks for the update.
