### ISSUE TITLE
Use proselint for mail-mode

### ISSUE THREAD

**Issue by philip-bl** [flycheck/flycheck#1377]
Is there a reason why the **proselint** checker is not enabled for **mail-mode** which is used for writing emails? I would like to use it. How can I do it? I was unable to find the answer on flycheck's website.

* Your Emacs version from `M-x emacs-version`
GNU Emacs 25.1.1 (x86_64-pc-linux-gnu, GTK+ Version 3.22.11) of 2017-09-15, modified by Debian
* Your Flycheck version from `M-x flycheck-version`
31

**Comment by fmdkdd** [comment]
> Is there a reason why the proselint checker is not enabled for mail-mode

No particular reason other than no-one thought to add it yet.  

> How can I do it? I was unable to find the answer on flycheck's website.

You can use `flycheck-add-mode` in your configuration for that.  I agree that this should be mentioned on the website.

Though in this case, it seems fine to me to include this as a default.  WDYT @cpitclaudel ?

**Comment by cpitclaudel** [comment]
No strong feelings either way.  There's a bunch of modes where proselint might be relevant (but then again so could other checkers?).

So +0.5 from me :) And happy to merge a patch. @philip-bl, do you want to provide one?

**Comment by philip-bl** [comment]
@cpitclaudel I don't

**Comment by fmdkdd** [comment]
Let's leave it at that then :)
