### ISSUE TITLE
Flycheck doens't work with latest nightly Rust compiler

### ISSUE THREAD

**Issue by kngwyu** [flycheck/flycheck#1378]
In Cargo project, flycheck always report no error if using latest compiler (nightly 2017-12-25).
I checked that with a bit older compiler(toolchain nightly-2017-12-24-x86_64-unknown-linux-gnu),
flycheck works properly.
However,  the output of `cargo rustc --message-format=json ` to stdout of both of two compilers are exactly same, so I have no idea why this bag happens(sorry).

To test latest compiler,  
`rustup toolchain install nightly`or if youv'e installed, just`rustup update` and `rustup default nightly`.
To test a bit older one,
`rustup toolchain install nightly-2017-12-24`
`rustup default nightly-2017-12-24`

**Comment by fmdkdd** [comment]
Okay, thanks for the heads up.  I will try to look into it.

**Comment by fmdkdd** [comment]
Can reproduce with:

```
nightly-x86_64-unknown-linux-gnu unchanged - rustc 1.24.0-nightly (cddc4a62d 2017-12-26)
```

**Comment by kngwyu** [comment]
Thanks.
I will try to explore the cause of this problem depending on my environment.

**Comment by fmdkdd** [comment]
What I found on my end for now is that there does not seem to be any significant changes between the stable and nightly version in `cargo rustc`.  However, when looking at the errors Flycheck parses, there *does* seem to be a difference between the two versions in file names.  Ultimately, the nightly version will produce file names that do not match the buffer filename.

We should probably switch to get absolute filenames from the JSON output anyway.

**Comment by fmdkdd** [comment]
What I've witnessed is that the filenames produced by nightly are relative to the Cargo.toml file, and previously they were not.

One way to fix it is to add the `working-directory` property:

```
  :working-directory (lambda (_)
                       (-when-let (file (buffer-file-name))
                         (locate-dominating-file file "Cargo.toml")))
```

With this added, nightly works fine.

**Comment by kngwyu** [comment]
Adding `working-directory` property worked!
Many thanks.

**Comment by cpitclaudel** [comment]
Do we need the null-check? Or do we only call working-directory when we have a `buffer-file-name`?

**Comment by fmdkdd** [comment]
@cpitclaudel The null check is probably redundant with `:enabled`, but I wasn't sure.

Concerning this bug, I'll look into making a proper PR once I've found the corresponding change in nightly.

**Comment by ArulselvanMadhavan** [comment]
@fmdkdd Thanks for looking into this. Waiting for a release with the fix.
