### ISSUE TITLE
How do I turn on global-flycheck-mode?

### ISSUE THREAD

**Issue by ReimuXMX** [flycheck/flycheck#1380]
Hello, and sorry for my poor English:

On your official website, enabling `global-flycheck-mode` should do something like this:
```emacs-lisp
(add-hook 'after-init-hook #'global-flycheck-mode)
```

But I have seen this:
```emacs-lisp
(add-hook 'after-init-hook 'global-flycheck-mode)
```

Which of them is the **most** correct? I hope to some official statement.

I don't know anything about emacs-lisp ... if that's silly, sorry!

Thank you very much!

**Comment by cpitclaudel** [comment]
The website is correct :) The first form is better. The second one works too, though. http://endlessparentheses.com/get-in-the-habit-of-using-sharp-quote.html

**Comment by ReimuXMX** [comment]
Thanks!
