### ISSUE TITLE
Remote .rubocomp.yml over Tramp breaks ruby-rubocop checker

### ISSUE THREAD

**Issue by garrett-davidson** [flycheck/flycheck#1387]
I'm currently working on a rails project on a remote machine using Tramp. When I add a .rubocop.yml configuration file to my rails project, Flycheck stops working.

Output of `flycheck-verify-checker`:

     ruby-rubocop
    - major mode:         `enh-ruby-mode' supported
    - may enable:         yes
    - executable:         Found at /usr/local/bin/rubocop
    - configuration file: Found at #("/scp:192.168.0.147:/home/garrett/.../.rubocop.yml" 1 4 (tramp-default t))

Output of `flycheck-buffer`:

    Suspicious state from syntax checker ruby-rubocop: Flycheck checker ruby-rubocop returned non-zero exit code 2, but its output contained no errors: Configuration file not found: /scp:192.168.0.147:/home/garrett/.../.rubocop.yml

    Try installing a more recent version of ruby-rubocop, and please open a bug report if the issue persists in the latest release.  Thanks!

It looks like Flycheck is passing the full Tramp path to RuboCop running on the remote machine, RuboCop does not understand.

Both Flycheck and RuboCop were installed by and are up to date according to MELPA.

**Comment by fmdkdd** [comment]
Checking files over Tramp is not officially supported.  If it works, then that's mostly by a stroke of luck ;)

In this case, `rubocop` takes your buffer via `stdin`, so it shouldn't be an issue.  However, the config file is found via `flycheck-locate-config-file` (even though it's a Tramp filepath), and given as-is to `rubocop`, which doesn't know how to deal with it.

Is the configuration file on the remote machine, or local?  Remember that Flycheck calls `rubocop` on the local machine, so the executable needs to be able to access the config file.

**Comment by garrett-davidson** [comment]
Flycheck has worked great over Tramp so far, until I added the config file. 

The config file is on the remote machine, in the root of the project directory. Does RuboCop happen to allow passing a config file via stdin as well? Or alternatively, could Flycheck run RuboCop on the remote machine and use local (to the remote machine) paths?

**Comment by fmdkdd** [comment]
> Does RuboCop happen to allow passing a config file via stdin as well

I don't use it, so I can't answer that with confidence.  However, you could just copy the configuration file to your machine before checking.  Or, you could do it dynamically: write a function that grabs the config file for the project your are in, copy it to `/tmp/.rubocop.yml` on the local machine, and run it in `flycheck-before-syntax-check-hook` for instance.

> Or alternatively, could Flycheck run RuboCop on the remote machine and use local (to the remote machine) paths?

I'm not sure.  We use `start-process` to run the actual command, and I see there is also `start-file-process` which looks like it's more suited to running remote processes.  In any case, you could probably hack it by providing a local `rubocop` version that's just a wrapper for an `ssh` call, but... you'd have to try :)

**Comment by garrett-davidson** [comment]
Those sound like pretty good solutions. Thanks for the help!
