### ISSUE TITLE
flycheck for groovy gets stuck, high cpu usage

### ISSUE THREAD

**Issue by philiparvidsson** [flycheck/flycheck#1395]
# How to reproduce:

1. Open Emacs
2. Open .groovy-file
3. Activate groovy-flycheck
4. Look at cpu usage

# Details

Windows 10
Emacs 25.3.1
Latest flycheck
JRE 9 (with java.exe in path, otherwise it doesn't seem to happen!)

# More info

https://github.com/Groovy-Emacs-Modes/groovy-emacs-modes/issues/106

**Comment by cpitclaudel** [comment]
Thanks for the report! And sorry for the trouble. How odd.
I don't run windows, so your debugging help will be much appreciated. Does the same thing happen when you run the checker explicitly with C-c ! C-c? What if you interrupt the check using C-u C-c ! C? Does that return things to normal? What about when you run the checker by hand from the command line? And is it just one file, or any file? If you set M-x toggle-debug-on-quit and then press C-g while emacs is stressing you CPU, what does the backtrace say? And, does Emacs freeze while the CPU usage is high?

**Comment by philiparvidsson** [comment]
* *Does the same thing happen when you run the checker explicitly with C-c ! C-c?*
**This seems to do nothing.**

* *What if you interrupt the check using C-u C-c ! C?*
**This kills the cmd.exe process running at 100% CPU usage, so everything returns to normal (though flycheck obviously doesn't check anything).**

* *What about when you run the checker by hand from the command line?*
**Can you tell me how to do that?**

* *And is it just one file, or any file?*
**Any Groovy source file.**

* *If you set M-x toggle-debug-on-quit and then press C-g while emacs is stressing you CPU, what does the backtrace say?*
**No idea if I did this correct. I did the following:**
  - M-x toggle-debug-on-quit
  - Load Groovy-file (issue occurs)
  - Press C-g

  **Nothing happens except Emacs says "Quit" in the mode line.**

* *And, does Emacs freeze while the CPU usage is high?*
**No, I can still work as I normally would (though flycheck is waiting for the checker process to complete, which never happens)**

**Comment by cpitclaudel** [comment]
Great, thanks a lot! It looks like Groovy is spinning endlessly then.
C-c ! C-c is flycheck-compile; can you try M-x flycheck-compile, and select groovy at the prompt?
This will run the checker in a separate window, and print the command explicitly; then you'll be able to copy that command into a terminal.

**Comment by philiparvidsson** [comment]
Oddly enough, that does not spin the cpu, but rather says unrecognized command:

![image](https://user-images.githubusercontent.com/1163299/35774148-d6a45b10-0967-11e8-9206-aaef5613192e.png)

**Comment by cpitclaudel** [comment]
Hm. What happend if your run (press the Windows key + R) that .bat command?

**Comment by philiparvidsson** [comment]
Same thing, it says unrecognized command.

**Comment by philiparvidsson** [comment]
When I leave flycheck to start it on its own, it spawns this process:

![image](https://user-images.githubusercontent.com/1163299/35779754-9ec1bc40-09d2-11e8-83da-e2d5c1c54546.png)

I.e. groovy instead of startGroovy.

**Comment by cpitclaudel** [comment]
That's fairly confusing.  Do you know where this .bat thing comes from? What does `groovy` point to exactly?
I'm not sure how C-c ! C-c can run something different from the background runner.

**Comment by philiparvidsson** [comment]
The bat files are inside the groovy bin directory (part of the groovy dist for windows).

**Comment by cpitclaudel** [comment]
Thanks. But what does the `groovy` executable look like? Is it just a batch file calling another batch file? What does i contain exactly?

**Comment by philiparvidsson** [comment]
![image](https://user-images.githubusercontent.com/1163299/35780843-1b1d6316-09e2-11e8-88d9-9766d1fffe5b.png)

**Comment by philiparvidsson** [comment]
Ok, so it's calling startGroovy.bat, which has a few loops. They might be the culprit

**Comment by philiparvidsson** [comment]
startGroovy.bat: https://pastebin.com/3yZDfpRG

**Comment by philiparvidsson** [comment]
For anyone curious, I've narrowed down the problem to the following:

![image](https://user-images.githubusercontent.com/1163299/36324858-14f0a598-1356-11e8-8544-6d2ce0f73cab.png)

The first check is correct (so the bat does NOT jump to win9xME_args), but the second one fails, so it passes straight through to win9xME_args anyway. Forcing a jump to 4NT_args removes the freeze, but gives another error.

This is obviously not an issue with flycheck-groovy but I'm leaving this here if anyone else experiences the same issue and ends up here.

**Comment by fmdkdd** [comment]
Nice debuggin!

I'm curious though: what does `%eval[2+2]` return if not `4`?

**Comment by philiparvidsson** [comment]
It's not evaluated and only gives "eval[2+2]" without the percent sign back

**Comment by fmdkdd** [comment]
Aw, I was expecting something more exotic.

In any case, is this solved for you, or is there something else?

**Comment by philiparvidsson** [comment]
It's not solved but it's also not a flycheck issue, so you're free to close this.

**Comment by fmdkdd** [comment]
Keep us posted if you find a solution :)
