### ISSUE TITLE
Question: How to handle errors triggered by changes in other files?

### ISSUE THREAD

**Issue by juergenhoetzel** [flycheck/flycheck#1402]
[flycheck-fsharp](https://github.com/fsharp/emacs-fsharp-mode/blob/master/flycheck-fsharp.el) uses a generic checker. 

Modifications to the project file might trigger/remove errors in the current buffer
But, because the current buffer is not modified it  [doesn't get flychecked. 
](https://github.com/fsharp/emacs-fsharp-mode/issues/158).

**Comment by fmdkdd** [comment]
I think #1308 should fit your use case as well.

Otherwise, Flycheck does not have project-wide checking capabilities.  I *really wish* it had, but it's far from a trivial change.

**Comment by juergenhoetzel** [comment]
> I think #1308 should fit your use case as well.

Exactly. Thanks for pointing this out :+1:

**Comment by fmdkdd** [comment]
That PR could use some help BTW ;)
