### ISSUE TITLE
Update Flymake comparison

### ISSUE THREAD

**Issue by fmdkdd** [flycheck/flycheck#1403]
Flymake has been rewritten for Emacs 26.  It's worth taking the time to go through our [Flycheck versus Flymake](http://www.flycheck.org/en/latest/user/flycheck-versus-flymake.html) in-depth comparison to take these changes into account.

I'd like to make that page a fair comparison between these two solutions, as it should help users decide which one to pick.

The NEWS item is light on information, but I've seen [this thread](https://lists.gnu.org/archive/html/emacs-devel/2017-09/msg00953.html) with a few items worth checking out.

I'll try to build Emacs 26 and take Flymake for a spin this week.

@joaotavora Would you agree to take a look at that comparison to make sure that Flymake is fairly represented?

**Comment by joaotavora** [comment]
> @joaotavora Would you agree to take a look at that comparison to make sure that Flymake is fairly represented?

Sure thing!

Oh and let me know in the emacs bug tracker if you find any problems (also CC me in the bug report).
