### ISSUE TITLE
Disable after-change-functions hook

### ISSUE THREAD

**Issue by rgrinberg** [flycheck/flycheck#1405]
Flycheck adds a pesky hook to after-change-functions even though I've set flycheck to only syntax checking on save. Is there anyway to prevent flycheck from add this hook? Or even better, have flycheck be smart enough about getting rid of it.

**Comment by cpitclaudel** [comment]
Not sure about pesky ones, but regular hooks added by Flycheck are fairly easy to remove: just register a function of your own in flycheck-mode-hook and call remove-hook from there.

You could also edit flycheck-hooks-alist.

Jokes aside though, what's wrong with that hook?

**Comment by rgrinberg** [comment]
It still seems a bit weird that those hooks are being registered in the first place. I'd like flycheck to only run on save to minimize impact on performance, so this stuff can get in the way.

But here I've ran into a concrete problem with evil's global replace. I get weird errors like this sometimes:

```
evil-replace-match: Match data clobbered by buffer modification hooks
```

And I'm pretty sure flycheck is at fault here.

**Comment by cpitclaudel** [comment]
I don't expect this hook to be costly, but I'd be happy to work on it if I'm wrong about this.

The save-match-data call is there to prevent precisely the kind of error that you're seeing. error, so I wouldn't expect FL to be the cause. We could have overlooked something else, though.

Can you turn the hook off, and report if the problem goes away or if you notice a performance improvement?

**Comment by rgrinberg** [comment]
OK, you're right. 	I'm actually not sure why the `save-match-data` is needed there in the first place, since the function is using `string-match-p` in the first place.

**Comment by fmdkdd** [comment]
We could not add the hooks if they are not needed.  We tried to do that in #1342, but the trouble is that if the user changes the value of `flycheck-check-syntax-automatically`, if we don't add the hooks back, the value has no effect until the user also re-triggers `flycheck-mode`.

There is a way to detect a change to the variable, and then add the hooks, but the solution of #1342 seemed to me as adding too much complexity for a non-obvious benefit.

But if you can provide convincing profiling data that these hooks are an issue, then we'll definitely look into it.

>  I'm actually not sure why the save-match-data is needed there in the first place, since the function is using string-match-p

I'd say you are right in this case, but I'd rather have it in there than remove it, and forget to add it back when it is actually needed.

**Comment by rgrinberg** [comment]
> We could not add the hooks if they are not needed. We tried to do that in #1342, but the trouble is that if the user changes the value of flycheck-check-syntax-automatically, if we don't add the hooks back, the value has no effect until the user also re-triggers flycheck-mode

How about adding a check for the value of this variable in the hook itself before doing anything? There is an already such a check for `flycheck-mode`. And if possible, switch the order of the `when` and `save-match-data` macros as an optimization.

**Comment by fmdkdd** [comment]
> How about adding a check for the value of this variable in the hook itself before doing anything? 

That check already happens in `flycheck-buffer-automatically`, so we would end up duplicating checking the variable to avoid the `string-match-p` call.  We could, but I still think it's speculative.

> switch the order of the when and save-match-data

That one would probably be okay, yes.  But we have established that `save-match-data` was not a cause of bug, so if it's only for performance reasons... I would still prefer hard data over just removing functions.

**Comment by cpitclaudel** [comment]
> switch the order of the when and save-match-data macros as an optimization.

Sure, if we can produce evidence that this is an optimization.
As far as I can tell, this check should always succeed: `flycheck-handle-change` is only registered when Flycheck is active.
I'd much rather find cases in which Flycheck is actually slow, and fix these :)

> I'm actually not sure why the save-match-data is needed there in the first place, since the function is using string-match-p

That function also calls `flycheck-buffer-automatically`.  Unless we prove (and document) that neither that nor anything it calls modified the match data, we need that `save-match-data`

> There is a way to detect a change to the variable, and then add the hooks

I think that's Emacs25-only.  We could use a defcustom hook, but I'd really like to see an actual problem before we start looking for solutions :)

**Comment by cpitclaudel** [comment]
Should we keep this open?

**Comment by rgrinberg** [comment]
You can close this.

**Comment by cpitclaudel** [comment]
Thanks
