### ISSUE TITLE
archlinux, when editing ~/.xmonad/xmonad.hs, flycheck always report missing module

### ISSUE THREAD

**Issue by MasterCsquare** [flycheck/flycheck#1408]
however, it can compile. I workaroud this by replace -no-link with -dynamic, i'm not sure whether it's a bug.

**Comment by fmdkdd** [comment]
cc @flycheck/haskell

**Comment by sergv** [comment]
@MasterCsquare Can you please provide an example that reproduces the problem?

**Comment by MasterCsquare** [comment]
ok, when execute
`ghc -Wall -no-link ~/.xmonad/xmonad.hs`(the command from flycheck.el)
i got the error like this:

/home/mas/.xmonad/xmonad.hs:1:1: error:
    Could not find module ‘XMonad’
    There are files missing in the ‘xmonad-0.13’ package,
    try running 'ghc-pkg check'.
    Use -v to see a list of the files searched for.
  |
1 | import XMonad
  | ^^^^^^^^^^^^^
...
...
/home/mas/.xmonad/xmonad.hs:26:1: error:
    Could not find module ‘Data.Tree’
    There are files missing in the ‘containers-0.5.10.2’ package,
    try running 'ghc-pkg check'.
    Use -v to see a list of the files searched for.
   |
26 | import Data.Tree
   | ^^^^^^^^^^^^^^^^

i got some infomation from this [link](https://bbs.archlinux.org/viewtopic.php?id=230166)

then i installed ghc-static
and the error for import Data.Tree was gone
but the module from XMonad still missing 
because there was no static lib for XMonad in official repo
so i replaced -no-link with -dynamic

**Comment by purcell** [comment]
Which is your `ghc`? In the general case, it's probably not reasonable to expect that in the absence of any information about the build context of `xmonad.hs` flycheck would be able to figure out where the libraries that file references might be installed. You might consider adding a simple Cabal or Stack config file in the `~/.xmonad.hs` directory for this purpose.

**Comment by MasterCsquare** [comment]
recently, i migrate to stumpwm. so it's no longer a problem :)
And you thought it's not reasonable to expect flycheck to find the right  references.
close.
