### ISSUE TITLE
Emacs freezes when opening up a haskell file with flycheck on

### ISSUE THREAD

**Issue by heartb1t** [flycheck/flycheck#1417]
I installed `flycheck` a couple days ago and I really love it, but whenever I open up a Haskell file, with [[https://github.com/haskell/haskell-mode/][haskell-mode]] on, Emacs would just freeze. I tried opening up `htop` to see if there was any `stack` process running, but that is not the case. I can unfreeze Emacs by typing `C-g` repeatedly, and it says `flycheck` is on, but no syntax checking is provided; although, whever I start typing something it freezes again until I stop it with `C-g`. I can't get an output for `M-x flycheck-verify-setup` because, again, it freezes until I repeatedly type `C-g`. I had `flycheck-haskell` installed and removed it, but nothing changed. The same exact issue repeats itself with `emacs -Q`. I could grab this error message from the `*Messages*` buffer (this was suggested by a member of the `flycheck` Gitter chat), it said:

```
Error in post-command-hook (flycheck-perform-deferred-syntax-check): (quit)
Waiting for process to die...done
Quit
```

Operating system: Void Linux
Flycheck version: 32snapshot (package: 2018224.1046)
GNU Emacs 25.3.1 (x86_64-unknown-linux-gnu, X toolkit) of 2017-12-16

**Comment by cpitclaudel** [comment]
Thanks for the report! Sorry about the issue.
It would help a lot if you could provide a backtrace, which you can get by running M-x toggle-debug-on-quit before reproducing the issue, and pressing C-g while it occurs.

**Comment by heartb1t** [comment]
Sure!

This is the backtrace of the usual Emacs:
```
Debugger entered--Lisp error: (quit)
  call-process("/usr/bin/stack" nil #<buffer  *temp*-788737> nil "path" "--project-root")
  apply(call-process "/usr/bin/stack" nil #<buffer  *temp*-788737> nil ("path" "--project-root"))
  process-lines("/usr/bin/stack" "path" "--project-root")
  flycheck-haskell--find-default-directory(haskell-stack-ghc)
  flycheck-compute-working-directory(haskell-stack-ghc)
  #[0 "\303\300!\203
```

Do you want me to do the same for `emacs -Q`?

**Comment by cpitclaudel** [comment]
Great, thanks. Can you try just running M-: (process-lines "/usr/bin/stack" "path" "--project-root")? Does it hang?

**Comment by heartb1t** [comment]
It does. I also ran the backtrace on this command, but its only the process call:

```
Debugger entered--Lisp error: (quit)
  call-process("/usr/bin/stack" nil #<buffer  *temp*-381832> nil "path" "--project-root")
  apply(call-process "/usr/bin/stack" nil #<buffer  *temp*-381832> nil ("path" "--project-root"))
  process-lines("/usr/bin/stack" "path" "--project-root")
  eval((process-lines "/usr/bin/stack" "path" "--project-root") nil)
  eval-expression((process-lines "/usr/bin/stack" "path" "--project-root") nil)
  funcall-interactively(eval-expression (process-lines "/usr/bin/stack" "path" "--project-root") nil)
  call-interactively(eval-expression nil nil)
  command-execute(eval-expression)
```

**Comment by fmdkdd** [comment]
cc @flycheck/haskell

**Comment by cpitclaudel** [comment]
Thanks. Last step, can you open a shell in the same folder as your haskell file and run `"/usr/bin/stack" "path" "--project-root"`?

**Comment by heartb1t** [comment]
This is the output of `/usr/bin/stack path --project-root`: `/home/<user>/.stack/global-project` where <user> is my username.

**Comment by cpitclaudel** [comment]
OK, fascinating. So `(process-lines "/usr/bin/stack" "path" "--project-root")` hangs, but running `/usr/bin/stack path --project-root` in a shell doesn't; is that right?

I don't use stack, and my first attempt to use it wasn't very successful… 

```
$ "/usr/bin/stack" "path" "--project-root"
Run from outside a project, using implicit global project config
Using latest snapshot resolver: lts-10.7
Writing implicit global project config file to: /home/clement/.stack/global-project/stack.yaml
Note: You can change the snapshot via the resolver field there.
Downloaded lts-10.7 build plan.    
AesonException "Invalid flag name: \"bytestring--lt-0_10_4\""
```

… but I can still suggest trying a few things.  One possibility is that stack is waiting for some form of input from Emacs — it shouldn't, because there's no pipe for it to read from, but that could confuse it. 

Can you try the following?

- Confirm that you can reproduce the hang with `M-! "/usr/bin/stack" "path" "--project-root" RET` rather than `call-process`.
- Try running this command with M-& instead of M-: ; what does the output say?

Thanks!

**Comment by heartb1t** [comment]
Well, magically it is working now, Emacs is not hanging anymore and `flycheck` is enabled, go figure... But Haskell files are slower to edit than other languages, and that has to do with `flycheck` because when I disable it it comes back to normal.

**Comment by cpitclaudel** [comment]
Huh. How odd.
Can you get a profile? M-x profiler-start, do some editing, then M-x profiler-report and M-x profiler-report-write-profile

**Comment by heartb1t** [comment]
[profiler.txt](https://github.com/flycheck/flycheck/files/1773412/profiler.txt)

Is this what you wanted? I found it really odd the way the info is layed out on the file.

**Comment by cpitclaudel** [comment]
Yes, this is perfect. Please turn off helm, telephone-line, and flyspell and check whether the problem persists.

**Comment by cpitclaudel** [comment]
Oh, wit, this isn't perfect; what you sent is a memory profile; I need a CPU profile :)

**Comment by heartb1t** [comment]
[profiler-cpu.txt](https://github.com/flycheck/flycheck/files/1777020/profiler-cpu.txt)
[profiler-mem.txt](https://github.com/flycheck/flycheck/files/1777021/profiler-mem.txt)

I did both but appearently I didn't send the memory one. I did them again now.

**Comment by cpitclaudel** [comment]
Thanks.  How odd.
The memory profile doesn't show anything particularly striking.  auto-revert-buffers is taking a lot of time, though, an flyspell is causing some redisplays, so my next suggestion would be to turn off all minor modes and reactivate them one by one until you find the culprit.  Does that sound feasible?

**Comment by nchisholm** [comment]
I had the same issue. Emacs was hanging every time I tried to open a Haskell file with flycheck-mode enabled. Following the steps above produced similar debug output. Then, it was magically fixed after running `/usr/bin/stack path --project-root`. I do not think I experienced a hang when I ran the same command through `process-lines` (but now I can't reproduce this to make sure). I noticed that during the hangs, an `xz`/`tar` process was consuming significant CPU.

This haskell-mode issue might be of interest: haskell/haskell-mode/issues/1526. It says something about haskell-mode trying to download things via stack (which would maybe explain why `xz` was running). I wonder if flycheck-mode is somehow triggering this behavior.

---

As far as the sluggishness mentioned by @heartb1t, I am also experiencing some of that. It goes away when FlyCheck is disabled, and I do not experience sluggishness when editing other types of files (e.g. python) with FlyCheck enabled.

I have profiled on my system with other minor modes disabled, too.
[profile-cpu-ngc.txt](https://github.com/flycheck/flycheck/files/1844782/profile-cpu-ngc.txt)

I hope this is useful and thanks for looking into this.

**Comment by sergv** [comment]
@nchisholm looking at your profile I notice that `linum-mode` consumes 37% of cpu time. I wonder whether things will go faster for you if you disable line numbers and try again?

**Comment by nchisholm** [comment]
I was able to work around the slow behavior disabling the `haskell-stack-ghc` checker. When FlyCheck then falls back to `haskell-ghc`, I do not notice any slowdown, and FlyCheck seems to work normally.

Note that I am new to both Haskell and Emacs, so I am unsure if my specific setup is the problem. I have not used Stack, so I might not have it properly configured. I am also using only dynamic versions of the Haskell libraries (as are provided in the Arch Linux repositories). Thus, I need to compile everything with `ghc -dynamic ...` or else `ghc` will not even find the basic `Prelude` module. Likewise, I must to include `-dynamic` in `flycheck-ghc-args` or else the checker will fail to function. (Strangely, `haskell-stack-ghc` worked even before I set this flag—although it was slow.)

**Comment by sergv** [comment]
The `stack path` may perhaps download a `ghc` for you the first try you run it with your default config. Running `stack path` from command line should also reproduce this behaviour. Once downloaded, it won't re-download it again so arguably waiting a bit the first time is a possible solution. Another solution may be to actually configure stack and disable downloading of ghc altogether.

Unfortunately, for stack-based projects there's no clear solution but to ask the tool for it's build paths! Linking against `stack` package (which has around 150 depedencies) just to get a directory where build artifacts are stored is probably not a lightweight solution. It will also not play well with philosophy of `flycheck-haskel` do use only packgaes bundled with `ghc` to get project's configuration. So the issue here is to sort out `stack path` slowness - `flycheck-haskell` cannot help but to call to it. That being said, it should call `stack path` only infrequently and cache the result for the same project, so it should get better the second time?

**Comment by fmdkdd** [comment]
> arguably waiting a bit the first time is a possible solution. Another solution may be to actually configure stack and disable downloading of ghc altogether.

Is there any way for us to check if `stack` is configured, and just warn the user and disable the checker?  Freezing users' Emacs is bad, since they could have unsaved work in another buffer.  We are not running `stack path` asynchronously here, so we should be extra careful not to run any command that takes more than 500ms.

**Comment by sergv** [comment]
I'm not aware of a way to check whether `stack` is configured, but we certainly can just look for a directory containing `stack.yaml` file - it should be a project's root most of the time. There's also an option to point to `stack.yaml` file by a `STACK_YAML` environment variable, but I think that's not as widespread and could be added later when someone actually requests that.

**Comment by fmdkdd** [comment]
> we certainly can just look for a directory containing stack.yaml file - it should be a project's root most of the time.

The `rust-cargo` checker does that using the `:enabled` property, so the checker is disabled if a `Cargo.toml` file cannot be found.  We can certainly do that for `haskell-stack-ghc` as well.  It seems we already have some logic for finding a `stack.yaml` file in `flycheck-haskell--find-default-directory`, so it would mostly be a matter of extracting that.

**Comment by purcell** [comment]
`stack` can also work correctly outside a project directory, so only enabling the checker if we find a `stack.yaml` would be the wrong solution IMO. Probably we should add one or both of `--no-install-ghc`/`--skip-ghc-check` the the command in question.

**Comment by fmdkdd** [comment]
> Probably we should add one or both of --no-install-ghc/--skip-ghc-check the the command in question.

We should avoir installing GHC from a synchronous process inside Emacs.  But we should warn users if `stack` cannot be used because GHC is not installed.  Is there a way to do that?
