### ISSUE TITLE
tslint not locating package.json correctly

### ISSUE THREAD

**Issue by xdl** [flycheck/flycheck#1420]
I have tslint configured for Flycheck and it's reading in the correct tslint.json file:

```
Syntax checker in buffer Navigation.tsx in web-mode:

  typescript-tslint
    - major mode:         `web-mode' supported
    - may enable:         yes
    - executable:         Found at /Users/xiaodili/dev/myapp/node_modules/tslint/bin/tslint
    - configuration file: Found at "/Users/xiaodili/dev/myapp/tslint.json"

Flycheck can use this syntax checker for this buffer.

Flycheck Mode is enabled.  Use C-u C-c ! x to enable disabled
checkers.

--------------------

Flycheck version: 32snapshot (package: 20180224.1046)
Emacs version:    25.3.1
System:           x86_64-apple-darwin13.4.0
Window system:    ns
```

However, I get the following errors:

```
     1  36 warning  no-im… Module 'material-ui' is not listed as dependency in package.json (typescript-tslint)
     2  24 warning  no-im… Module 'react' is not listed as dependency in package.json (typescript-tslint)
     4  18 warning  no-em… An empty interface is equivalent to `{}`. (typescript-tslint)
```

Despite having listed these modules as dependencies in the `package.json` file in the root of my project. When I run tslint on the terminal for that file, I get:

```
node_modules/tslint/bin/tslint src/components/Navigation.tsx

ERROR: src/components/Navigation.tsx[4, 18]: An empty interface is equivalent to `{}`.
```

Which suggests that Flycheck's tslint isn't able to pick up the package.json location. I had a quick Google and was wondering if it might be related to this issue: https://github.com/w0rp/ale/issues/1101 but my elisp isn't solid enough to dig into this.

**Comment by fmdkdd** [comment]
If the issue is about picking up implicit dependencies in the same folder as the source file being checked, then yes, it's likely that is the cause.

In flycheck.el, can you change the `source` to `source-inplace` in the `:command` property of `typescript-tslint` (about [here](https://github.com/flycheck/flycheck/blob/master/flycheck.el#L10153))?  Evaluate that (`C-M-x` with the cursor inside the checker definition) and try to see if that fixes the issue.

**Comment by xdl** [comment]
Thanks @fmdkdd, changing `source` to `source-inplace` has fixed the issue, thanks so much! Will you include this change in a future release?

**Comment by fmdkdd** [comment]
> Will you include this change in a future release?

WDYT @flycheck/typescript ?  Would checking using a temporary file in the same folder as the source file have any ill effects?

**Comment by cpitclaudel** [comment]
Wouldn't it be enough to change the working directory?

**Comment by fmdkdd** [comment]
> Wouldn't it be enough to change the working directory?

Could be.  But couldn't it also have adverse effects?

Also, we would have to first determine the correct working directory, which may or may not be trivial (but I don't use typescript/tslint, so maybe just locating `package.json` is enough?).

**Comment by Simplify** [comment]
> WDYT @flycheck/typescript ? Would checking using a temporary file in the same folder as the source file have any ill effects?

Don't think so, not for `tslint`. Maybe for `typescript-tide` package, but I doubt. @xdl do you use `typescript-tide` and if so, did you run into any problems when testing `source-inplace`?
We try this. If we run into any problems we can always revert and ask users to set `no-implicit-dependencies` to false.

> Also, we would have to first determine the correct working directory, which may or may not be trivial (but I don't use typescript/tslint, so maybe just locating package.json is enough?).

Yes, we already do this for `javascript-eslint` checker. IMHO every javascript or typescript project should have set working directory where `package.json` is anyway. Try this first?

**Comment by xdl** [comment]
Hi @Simplify, yep I was using the Tide (https://github.com/ananthakumaran/tide) package when I came across the issue, and which using `source-inplace` fixed.

**Comment by fmdkdd** [comment]
> IMHO every javascript or typescript project should have set working directory where package.json is anyway. Try this first?

Maybe it's the better option, yes.  Can you make a PR for that?  With a test case for `no-implicit-dependencies`, that would be perfect :)

**Comment by Simplify** [comment]
it did not work, I'll make PR for `source-inplace`.
