### ISSUE TITLE
command detection cannot handle rbenv shims

### ISSUE THREAD

**Issue by kaikuchn** [flycheck/flycheck#1447]
Hey folks,

I recently updated all my packages and am now seeing warnings about suspicious state for the ruby-reek syntax checker. Flycheck does find a ruby-reek executable, albeit in a different Ruby version, and thus enables the syntax checker. When it then tries to call the executable a `command not found` with exit status 127 is returned hinting that in another installed Ruby version the command is available.

It seems that the availability check of the command cannot deal with rbenv shims. This is only a problem if in one of the installed ruby versions the executable exists. By deleting it from that version I can circumvent this problem.

Here's the flycheck-verify-setup output that already includes the requested version information:

```
Syntax checkers for buffer foo.rb in ruby-mode:

  chef-foodcritic (disabled)
    - may enable: Automatically disabled!
    - predicate:  nil
    - executable: Not found

  ruby-rubocop
    - may enable:         yes
    - executable:         Found at /Users/kaikuchn/.rbenv/shims/rubocop
    - configuration file: Not found

  ruby-reek
    - may enable:         yes
    - executable:         Found at /Users/kaikuchn/.rbenv/shims/reek
    - configuration file: Not found

  ruby-rubylint (disabled)
    - may enable:         Automatically disabled!
    - executable:         Not found
    - configuration file: Not found

  ruby
    - may enable: yes
    - executable: Found at /Users/kaikuchn/.rbenv/shims/ruby

  ruby-jruby
    - may enable: Automatically disabled!
    - executable: Not found

Flycheck Mode is enabled. Use SPC u C-c ! x to enable disabled checkers.

--------------------

Flycheck version: 32snapshot (package: 20180326.836)
Emacs version:    25.3.1
System:           x86_64-apple-darwin17.0.0
Window system:    ns
```

Edit: Rbenv provides [a way to check](https://github.com/rbenv/rbenv#rbenv-which) if the currently active ruby version does have the executable.

**Comment by fmdkdd** [comment]
I'm confused.   How do you call `reek` when rbenv shims are in use.  Isn't just `reek`?  In other words, how should flycheck invoke `reek` in this case?

**Comment by fmdkdd** [comment]
Thanks for the explanation.  Flycheck simply looks up for `reek` on your `PATH` and calls that if it is found.  We can see that Flycheck found the `reek` shim created by rbenv and called that.  The call failed because `reek` is not installed for the currently active ruby version. 

Now, what did you want Flycheck to do in this case?  Did you expect it to run the checker?  Or did you just want it to mark the checker as disabled (because the executable is in fact, not available)?

**Comment by kaikuchn** [comment]
The latter, I'd want it to mark the checker as disabled. Otherwise I'd install the executable/gem for the corresponding Ruby version.

I realise that it is somewhat unfortunate that rbenv's shims effect these false positives for command availability and if you think that it is out of scope for flycheck to handle such curious behaviour I'd actually agree. However, I thought I should raise this issue just to make you aware of it.

In my case I was able to remove that other Ruby version entirely since I did not use it anymore and thus got rid of the warning.

**Comment by fmdkdd** [comment]
Thanks, that's crystal clear now.  Sorry for being a bit slow today.

We certainly could catch these shims if we wanted to.  Two obvious ways are:

1. Enhance `flycheck-find-checker-executable` to call `rbenv` to determine whether the executable is a shim (and the true executable is available).  The obvious problem with that is that there's no point doing this check for most of the checkers.
2. Add an `:enabled` predicate to the ruby checkers that will call `rbenv which` to determine whether the executable is available (if it's a shim).  We already do similar checks for, e.g., `cargo clippy`.

I think going with 2) would fit nicely with Flycheck.

How do we know whether an executable is an rbenv shim?  Is checking that it sits in `RBENV_ROOT` enough?

**Comment by kaikuchn** [comment]
Yes, I think checking whether the executable sits in `RBENV_ROOT/shims` is the the best way to determine if the executable is an rbenv shim. All shims are in that directory and it is the directory that rbenv prepends to the path. Maybe @mislav - the maintainer of rbenv - can quickly confirm this or suggest a better way?

While I cannot construe a reason for any other executables contained within the `RBENV_ROOT` directory (e.g., `RBENV_ROOT/versions/2.5.0/bin/reek`) to be resolved via the PATH it is not unthinkable, therefore I'd argue that `RBENV_ROOT/shims` is safer.

**Comment by fmdkdd** [comment]
Can you tell me what does `rbenv which` return when the executable is not available in the current Ruby version?

**Comment by kaikuchn** [comment]
Yeah, as you can see in the source code here
https://github.com/rbenv/rbenv/blob/master/libexec/rbenv-which#L53 It exits
with code 127 if the executable does not exist in the current ruby version.
It may also exit with 1 if the ruby version that the user wants to use
isn't even installed. The latter is a broken setup though.. so pretty much
nothing works in that case anyway.

fmdkdd <notifications@github.com> schrieb am Di., 10. Apr. 2018 um
18:35 Uhr:

**Comment by mislav** [comment]
I would advise against hardcoding knowledge about rbenv into any tool, including this one. Rbenv is designed to work exclusively via its existence your PATH without any cooperation of tooling.

The case of an executable being present in one Ruby version while not being present in others is a tricky one. The easiest solution in most cases is to install the gem in Ruby versions where it's missing.

```sh
for version in `rbenv versions --bare`; do
  RBENV_VERSION=$version bash -c 'rbenv which reek 2>/dev/null || gem install reek' 
done
```
