### ISSUE TITLE
elixir/dogma linter has been deprecated

### ISSUE THREAD

**Issue by fapdash** [flycheck/flycheck#1448]
Dogma has been [deprecated](https://github.com/lpil/dogma/commit/e0f55c27ec3053be0313ac93f3d036437ee590a1) in the beginning of this year.
Currently I'm getting an error when I'm trying to use dogma but this could be a problem with my setup.
Would be good if someone else could confirm if dogma is still working with the latest Elixir version, otherwise it should probably be removed from flycheck.

**Comment by fmdkdd** [comment]
Thanks for the heads-up!

**Comment by fmdkdd** [comment]
@flycheck/elixir What do you think?  Should we drop dogma now, or should we wait longer?  I'm seeing that [Debian Stretch includes Elixir 1.3](https://packages.debian.org/stretch/elixir), but I don't know if it's common for users to install the latest version.

**Comment by aaronjensen** [comment]
IMO drop it, if someone wants to continue using it they could release it as a standalone package.

**Comment by kthelgason** [comment]
I agree, not much reason to keep dogma support around. The circles I travel in tend to track new elixir versions pretty closely.

**Comment by fapdash** [comment]
What about picking up https://github.com/flycheck/flycheck/issues/1062 again then?
Otherwise plain flycheck comes with no checker for elixir.
