### ISSUE TITLE
'javascript-eslint checker doesn't lint GraphQL files with eslint-pluging-graphql

### ISSUE THREAD

**Issue by viniciussbs** [flycheck/flycheck#1452]
> * What you did, and what you expected to happen instead

I've tried to lint a GraphQL file using ESLint. I'm using the [eslint-pluging-graphql](https://github.com/apollographql/eslint-plugin-graphql). I'm able to lint a .graphql file running this command line:

```
$ node_modules/.bin/eslint app/ config/ tests/ --ext .js --ext .graphql
```

If I run the command line without the `--ext` argument, my GraphQL files are not linted; only my JS files are, [as expected](https://github.com/apollographql/eslint-plugin-graphql#graphql-literal-files).

```
$ node_modules/.bin/eslint app/ config/ tests/
```

On Emacs, my JS files are linted as expected. My GraphQL files are not. So I've put this to add `graphql-mode` to `javascript-eslint` checker:

```elisp
(with-eval-after-load 'flycheck
  (flycheck-add-mode 'javascript-eslint 'graphql-mode))
```

![image](https://user-images.githubusercontent.com/245791/38784611-b98a4fc0-40ea-11e8-9b42-32c977540d55.png)

I also have the `flycheck-eslint-args` set. I'm just waiting the new release on MELPA with #1360.

```elisp
(setq flycheck-eslint-args '("--ext" ".js" "--ext" ".graphql"))
```

When I run `(flycheck-checker-get 'javascript-eslint 'command)`, the result is the expected:

```elisp
("eslint" "--format=json" (option-list "--rulesdir" flycheck-eslint-rules-directories) "--stdin" "--stdin-filename" source-original)
```

I've tried to use `setf` to set a new command for `javascript-eslint` checker that passes the `--ext` argument as suggested in #1360, but nothing changed.

What am I missing?

> * Your Flycheck setup from `M-x flycheck-verify-setup`

![image](https://user-images.githubusercontent.com/245791/38784469-9747b62a-40e8-11e8-8bf1-358bb400ef07.png)

I have the same result before and after changing the checker command as suggested on #1360:

```elisp
(setf (flycheck-checker-get 'javascript-eslint 'command)
      '("eslint" "--format=json" (option-list "--rulesdir" flycheck-eslint-rules-directories) "--ext" ".js" "--ext" ".graphql" "--stdin" "--stdin-filename" source-original))
```

> * Your operating system

OS X

> * Your Emacs version from `M-x emacs-version`

GNU Emacs 25.2.1 (x86_64-apple-darwin16.7.0, NS appkit-1504.83 Version 10.12.6 (Build 16G29))
 of 2017-08-10

> * Your Flycheck version from `M-x flycheck-version`

32snapshot (package: 20180412.841)

**Comment by cpitclaudel** [comment]
Hmm. Can you show what flycheck-verify-setup says in on a JS file in the same folder as your .graphql files?  Does it work fine? Or does it also complain about missing binaries & config files?

**Comment by viniciussbs** [comment]
It works fine like any other JS file in the project. This is from a brand new JS file from the same folder of the .graphql file used to take the previous prints:

![image](https://user-images.githubusercontent.com/245791/38785612-203c0832-40f8-11e8-8d0c-8b6b85c61b9c.png)

**Comment by viniciussbs** [comment]
OK, it's not an issue.

In a .js file:
- `(flycheck-checker-executable 'javascript-eslint)` evaluates `"eslint"`
- `(funcall flycheck-executable-find "eslint")` evaluates `"/Users/vinicius/Projects/vzon-web/node_modules/.bin/eslint"`

In a .graphql file:
- `(flycheck-checker-executable 'javascript-eslint)` evaluates `"eslint"`
- `(funcall flycheck-executable-find "eslint")` evaluates `nil` 

The real issue is that I use the package `add-node-modules-path` to add `node_modules/` to my `PATH` and I was doing that only on `js2-mode-hook`. Adding a hook for `graphql-mode` solved the issue.

So, for those who want to lint .graphql files using ESLint, you will need:

- https://github.com/apollographql/eslint-plugin-graphql configured properly;
- install `eslint` globally or hook `add-node-modules-path` to `graphql-mode`;
- `(flycheck-add-mode 'javascript-eslint 'graphql-mode)` after load `flycheck`;
- `(setq flycheck-eslint-args '("--ext" ".js" "--ext" ".graphql"))`.
