### ISSUE TITLE
Stylelint checkers complain on empty buffers with the latest version of stylelint

### ISSUE THREAD

**Issue by ghost** [flycheck/flycheck#1458]
It seems that the latest stylelint will return exit code 2 on empty input ([the code in stylelint](https://github.com/stylelint/stylelint/blob/master/lib/cli.js#L479-L482) and [the related code in meow](https://github.com/sindresorhus/meow/blob/master/index.js#L81-L84) which is the argument parser used by stylelint).

This causes the three stylelint checkers (css-stylelint, scss-stylelint and less-stylelint) report "Suspicious state from syntax checker" on empty buffers with newer versions of stylelint.

I added a predicate function for the checkers myself which solved this problem, but I am not sure if this is the right way. (Actually I do not quite understand why we need check an empty buffer.)

Thanks!

**Comment by cpitclaudel** [comment]
That behavior makes sense when processing actual files, but is it also intended for stdin?
If it is indeed intended, we can fix it easily by adding a predicate.

(We chec empty buffers because some checkers, like the elisp one, report interesting information on them)

**Comment by pengjiz** [comment]
I am not sure if this is intended, but it seems that both cases are always handled together. I also think empty sdtin may not be considered as "misuse". Maybe I should report this to stylelint.

Thanks!

**Comment by fmdkdd** [comment]
@pengjiz Please do report the issue there, and keep us posted.

**Comment by LeeiFrankJaw** [comment]
I got the same problem with [mypy](https://github.com/python/mypy).  It returns exit status 2 for non-existent file.

    $ mypy temporary.py
    mypy: can't read file 'temporary.py': No such file or directory

And what I got in Emacs when creating a new file is the following.

    Suspicious state from syntax checker python-mypy: Flycheck checker python-mypy returned non-zero exit code 2, but its output contained no errors: mypy: can't read file '/home/lei/Playground/temporary.py': No such file or directory
    
    Try installing a more recent version of python-mypy, and please open a bug report if the issue persists in the latest release.  Thanks!

**Comment by LeeiFrankJaw** [comment]
I found the relevant discussion [here](https://github.com/python/mypy/issues/2119).  Can anyone tell me how to use `--shadow-file` to solve the problem?

**Comment by fmdkdd** [comment]
@LeeiFrankJaw you probably want to check out #1354, or wait for it to be merged.
