### ISSUE TITLE
Checking uses `exec-path`, but `flycheck-compile` uses $PATH

### ISSUE THREAD

**Issue by joewreschnig** [flycheck/flycheck#1461]
Split off from the discussion of using npx at #1428:

If I have a project-local executable e.g. `eslint` in `node_modules/.bin`, I can add that directory to my `exec-path` to make the checker work (and green in `flycheck-verify-setup`). But, running `flycheck-compile` fails because `compilation-start` shells out, and the directory is not in my `$PATH`.

In my own Emacs Lisp code I've worked around this by always calling `executable-find` before running anything with shells out.

This occurs in Flycheck 20180509.845 (and probably all earlier versions).

**Comment by fmdkdd** [comment]
> In my own Emacs Lisp code I've worked around this by always calling executable-find before running anything with shells out.

So you get the absolute path to the program using `exec-path`, and pass it to the shell, is that it?

**Comment by joewreschnig** [comment]
> So you get the absolute path to the program using exec-path, and pass it to the shell, is that it?

Right. Usually I try to do it as late as possible before calling the command, in case something else also wants to override `exec-path`.

**Comment by fmdkdd** [comment]
Ok, thanks for confirming.  I agree that we should eliminate the discrepancy between `flycheck-compile` and what happens with `flycheck-verify-setup` (which reflects `flycheck-buffer`).  Your method would be a good start I think.

**Comment by cpitclaudel** [comment]
Thanks for the report.  Two years later, I have a PR at #1707
