### ISSUE TITLE
Add a `reload` button in C-c ! v, and improve UI of disabled checkers

### ISSUE THREAD

**Issue by cpitclaudel** [flycheck/flycheck#1465]
The new disabled checks (checking once when a buffer is opened) are cheaper than our previous approach (checking for availability on every checker run), but there are also more opaque to users.  One of the worst cases is opening the verification windows and getting all green, with the checker still disabled.

There are a few improvements I can think of:

- [ ] Add a `reload` button to the C-c ! v window, available if the checker is disabled but all its checks pass.
- [ ] Improve the Flycheck modeline tooltip to point to C-c ! v

I wonder how well it would work to record a copy of the output of `verify` when we disable a checker; it would make some debugging easier.

(I recently realized that the change to enabled introduces a stronger dependency on how hooks are ordered when opening a new buffer: if we run before a minor mode gets a change to set things up properly, we risk incorrectly disabling Flycheck)

(Edited to add: I don't think the above is true anymore.  We run enabled checks the first time we try to check the buffer, which is when all minor modes have been enabled.  We still have the issue that many checkers don't include all information in the verify-setup part.)

**Comment by fmdkdd** [comment]
> One of the worst cases is opening the verification windows and getting all green, with the checker still disabled.

Such cases should be treated as serious bugs, and we should strive to avoid them.

>  Add a reload button to the C-c ! v window, available if the checker is disabled but all its checks pass.

I'd rather have a `report bug` button so we can fix it.  These should not happen under any circumstances.

> (I recently realized that the change to enabled introduces a stronger dependency...

Ah, yes, that might be the cause for some of these "all green but disabled" cases.  We should definitely track these down and fix the root issues.

**Comment by cpitclaudel** [comment]
> Such cases should be treated as serious bugs, and we should strive to avoid them.
> I'd rather have a report bug button so we can fix it. These should not happen under any circumstances.

No, they are quite common: the conditions can have changed between the initial `:enabled` check when the source code buffer was opened and the time the verification buffer was populated.

For example, I might open a buffer in a programming language I don't commonly use, then realize I'm missing the checker, install it, and open C-c ! v to confirm that everything is OK. At that point I just see all green and still the checker is disabled. It's not obvious at that point that M-x revert-buffer is that way to go.

Of course, `:predicate` conditions generally don't have that problem.

**Comment by fmdkdd** [comment]
Ok, I see the issue.  `verify-setup` shows you the results of the checks *at the time you run the command or revert the buffer*; it doesn't show why the checkers were disabled.  The checks done by `verify-setup` and `:enabled` often are the same, but what differs between the two is the time at which they are run.

If we make this mismatch clear in `verify-setup`, then it's ok.  If we record the reasons why the checkers was disabled and show them along the results of `:verify`, it would help clear things up.

However, another solution is simply to recheck the `:enabled` predicates when running `verify-setup`.  This way, the results of `:verify` *would be the reasons* why the checker is still disabled.  An implicit `restart` button if you will.

**Comment by cpitclaudel** [comment]
@m-cat thanks, these are great points, and I think they deserve a separate issue.  Your example with shell-script mode is particularly good, so I'd recommend also adding that there, along with any ideas or mock-ups of what might make things better. :)
