### ISSUE TITLE
Use Emacs 27's new JSON-parsing primitives

### ISSUE THREAD

**Issue by cpitclaudel** [flycheck/flycheck#1471]
From the changelog at https://github.com/emacs-mirror/emacs/blob/a37166eb80458e87880893e7b8aa98a2a7ce394b/etc/NEWS#L27:

```
** The new configure option '--with-json' adds support for JSON using
the Jansson library.  It is on by default; use 'configure
--with-json=no' to build without Jansson support.  The new JSON
functions 'json-serialize', 'json-insert', 'json-parse-string', and
'json-parse-buffer' are typically much faster than their Lisp
counterparts from json.el.
```

We could feature-check for these and use them if available.

**Comment by bk322** [comment]
(note: one need to `sudo apt install libjansson-dev` on deb-based linux for this to work; also `./configure` shows `Does Emacs use -ljansson? yes` if that was found)
