### ISSUE TITLE
Please Consider Updating 'Flycheck versus Flymake' Page 

### ISSUE THREAD

**Issue by tareefdev** [flycheck/flycheck#1474]
Emacs 26.1 had been released last week, and it introduces a rewritten Flymak, so it would be a great to update [this page](http://www.flycheck.org/en/latest/user/flycheck-versus-flymake.html), to reflect new changes in both, Flycheck and Flymake

**Comment by cpitclaudel** [comment]
Already in progress at https://github.com/flycheck/flycheck/pull/1412 :)

**Comment by tareefdev** [comment]
Oh! great :)
