### ISSUE TITLE
Add proselint support for org-mode

### ISSUE THREAD

**Issue by delaanthonio** [flycheck/flycheck#1488]
Currently, the supported [modes](https://github.com/flycheck/flycheck/blob/master/flycheck.el#L8657) for proselint are `text-mode`, `markdown-mode`, `gfm-mode`, and `message-mode`. Can we also add `org-mode` to the list? `org-mode` is arguably one of the most important text modes for emacs, so it would be great to see it on the list.

**Comment by cpitclaudel** [comment]
Sounds like a good idea! But how well does proselint cope with org-mode's syntax?

**Comment by delaanthonio** [comment]
While I haven't looked into this extensively, org-mode's syntax doesn't appear to cause any issues. I've ran the linter from the command line on some of my org files and it gives feedback as expected. Since the org-mode documents are plain text, I don't see why it would cause any issues.

**Comment by cpitclaudel** [comment]
> While I haven't looked into this extensively, org-mode's syntax doesn't appear to cause any issues.

Great!  Would you like to prepare a PR to add org-mode to proselint's modes?

> Since the org-mode documents are plain text, I don't see why it would cause any issues.

Org mode files often include code snippets, bits of LaTeX and HTML, markup like `~…~` and `*…*`, paths to included files, etc; an org-aware tool would know not to run on these, but I imagine proselint likely does run there.

**Comment by darosio** [comment]
Mind also this simple case:
** TODO Any Task
results into: "Annotation left in text. [misc.annotations]" error message.

**Comment by cpitclaudel** [comment]
As mentioned, I'd be happy to review a PR for this, provided we can find a way to reduce false-positives.  In the meantime, it should be enough to call `(flycheck-add-mode 'proselint 'org-mode)`
