### ISSUE TITLE
How to add variables to :command argument on flycheck-define-checker?

### ISSUE THREAD

**Issue by marceloslacerda** [flycheck/flycheck#1489]
I'm trying to make a checker but flycheck wont take variables inside the :command argument, why is that?

    (flycheck-define-checker postgresql
      "A postgresql syntax checker using psql."
      :command
      ("psql"
            "-U"
            postgresql-flycheck-user
            "-d"
            postgresql-flycheck-database)
      :error-patterns
        ((error line-start (file-name) ":" line ": error: " (message) line-end))
      :modes sql-mode
        )

The error message:
    flycheck-define-command-checker: Invalid command argument postgresql-flycheck-user in syntax checker postgresql

**Comment by fmdkdd** [comment]
Look at the documentation of the `:command` argument in `flycheck-define-command-checker`, and in particular at `flycheck-substitute-argument`.  Or look at how other checkers pass variables.

You probably want to write `("psql" (option "-U" postgresql-flycheck-user) ...`

**Comment by marceloslacerda** [comment]
It was exactly that.
