### ISSUE TITLE
Migrate readthedocs to SSL

### ISSUE THREAD

**Issue by fmdkdd** [flycheck/flycheck#1490]
readthedocs now supports SSL with custom domains (https://github.com/rtfd/readthedocs.org/issues/2652).  According to [the docs](https://docs.readthedocs.io/en/latest/alternate_domains.html#cname-ssl), we just have to point the `www.flycheck.org` CNAME to `readthedocs.io` instead of `readthedocs.org`.

@mgudemann Can you update the CNAME?

**Comment by mgudemann** [comment]
@fmdkdd sorry, hadn't seen this issue before. I asked my provider to do the change. Is it ok now?

**Comment by fmdkdd** [comment]
@mgudemann Thanks, the DNS looks good on my side.  I'm waiting for the certificate to be issued by readthedocs now.  Shouldn't take more than a few hours.

**Comment by fmdkdd** [comment]
Had to remove/add the custom domain in the readthedocs interface to trigger the creation of the certificate.  All is in order now.  We had a mixed-content warning caused by an HTTP MELPA badge, which I fixed.  I also triggered a build manually because the Github outage has frozen webhook.

After that:

![flycheck-ssl](https://user-images.githubusercontent.com/340129/47304991-72ed7280-d628-11e8-8b0e-df55ab0cf2cf.png)

Mission accomplished.  Thanks @mgudemann!

**Comment by mgudemann** [comment]
@fmdkdd good to hear!

**Comment by lk-geimfari** [comment]
@fmdkdd Hey! Can you please tell me if you had to do something besides specifying `CNAME` to enforce HTTPS on custom domain?

I have bought a domain on Namecheap and it's how DNS host records look like:
<img width="1157" alt="screenshot 2018-12-15 at 23 04 25" src="https://user-images.githubusercontent.com/15812620/50046969-e60de500-00bd-11e9-9649-8e50abab921a.png">

And it works fine, but still without HTTPS and when I try to use HTTPS I got this:
<img width="1096" alt="screenshot 2018-12-15 at 23 06 55" src="https://user-images.githubusercontent.com/15812620/50046985-240b0900-00be-11e9-9697-bb45e9d737cb.png">

Can you, please, tell me what I do wrong and what do you do to solve this problem (as I can see in the screenshot above, you've solved it)? Thanks!
