### ISSUE TITLE
Use stylelint `unix` formatter (since 9.5.0)

### ISSUE THREAD

**Issue by ybiquitous** [flycheck/flycheck#1494]
stylelint added `unix` formatter in <https://github.com/stylelint/stylelint/pull/3524>.
Maybe I think that this feature will be released in stylelint 9.5.0 soon. 💪 

I hope that this makes Flycheck code more light and clear. 😄 

https://github.com/flycheck/flycheck/blob/f6f091949cdaf89f228af46f1562c1438e2b1890/flycheck.el#L6843

```diff
-(defconst flycheck-stylelint-args '("--formatter" "json")
+(defconst flycheck-stylelint-args '("--formatter" "unix")
```

Please give me feedbacks!

Thanks.

**Comment by cpitclaudel** [comment]
Thanks! Can you clarify what's wrong with the JSON formatter, and why we'd want to change to the new `unix` format?

**Comment by ybiquitous** [comment]
I think that `:error_patterns` can be used for stylelint [such as RubCop](https://github.com/flycheck/flycheck/blob/f6f091949cdaf89f228af46f1562c1438e2b1890/flycheck.el#L9378) instead of [`flycheck-parse-stylelint`](https://github.com/flycheck/flycheck/blob/f6f091949cdaf89f228af46f1562c1438e2b1890/flycheck.el#L6863).

But when users are using older stylelint version, this `:error_patterns` will cause an error...

**Comment by ybiquitous** [comment]
If Flycheck doesn't have a feature to switch `:error_patterns` and `flycheck-parse-stylelint ` by different stylelint versions (e.g. `9.4` and `9.5`),
maybe we should give up implementing by this new `unix` formatter. 😢 

If this assumption is correct, please close this issue. 🙏

**Comment by cpitclaudel** [comment]
> I think that :error_patterns can be used for stylelint such as RubCop instead of flycheck-parse-stylelint.

OK, understood :) But in fact we usually prefer to use JSON or XML instead error-patterns.  The reason is that regular expressions tend to be more brittle, especially with uncommon file names (e.g. file names containing quotes, newlines, colons, etc.), or when messages contain newlines.

> But when users are using older stylelint version, this :error_patterns will cause an error...

In general this isn't a big issue: we only commit to supporting the latest version of each tool.  In this case, though, I think I'd prefer staying with JSON.  Does that make sense?

**Comment by ybiquitous** [comment]
Yes, I understand it! 👍 
Staying with JSON seems better to me. I close this.

Thank you very much for your polite reply! 😄

**Comment by cpitclaudel** [comment]
Thanks for opening the issue!
