### ISSUE TITLE
How to disable Emacs Lisp warning "You should have a section marked ;;;Commentary"

### ISSUE THREAD

**Issue by ChoppinBlockParty** [flycheck/flycheck#1502]
In every Lisp file of mine or third party package I have a warning "You should have a section marked ;;;Commentary". Is it possible to disable that?

**Comment by fmdkdd** [comment]
If you are writing an actual Emacs Lisp package, you probably want to add a `Commentary` section.

Otherwise, I don't think there is a toggle to disable *just that warning* without also disabling other package-header related warnings.

**Comment by cpitclaudel** [comment]
I think it would be a reasonable feature request (using report-emacs-bug) :) Flycheck just displays these warnings produced by checkdoc.
