### ISSUE TITLE
Opening any python file takes 3-4 seconds

### ISSUE THREAD

**Issue by dmitry-saritasa** [flycheck/flycheck#1503]
Fedora 28 4.17.19-200.fc28.x86_64
Pyenv with Python 3.6.6
GNU Emacs 26.1 (build 1, x86_64-redhat-linux-gnu, GTK+ Version 3.22.30) of 2018-06-26
Flycheck version: 32snapshot (package: 20180823.826)
Spacemacs with python-mode (both are latest)

Syntax checkers for buffer urls_backend.py in python-mode:

```
  python-flake8
    - may enable:         yes
    - executable:         Found at /home/dmitry/.pyenv/shims/python
    - configuration file: Not found
    - `flake8' module:    Found at "/home/dmitry/.pyenv/versions/cam/lib/python3.6/site-packages/flake8/__init__.py"

  python-pylint
    - may enable:         Automatically disabled!
    - executable:         Found at /home/dmitry/.pyenv/shims/python
    - configuration file: Not found
    - `pylint' module:    Missing

  python-pycompile
    - may enable: yes
    - executable: Found at /home/dmitry/.pyenv/shims/python

  python-mypy
    - may enable:         yes
    - predicate:          t
    - executable:         Found at /home/dmitry/.pyenv/shims/mypy
    - configuration file: Not found

Flycheck Mode is enabled. Use M-m u C-c ! x to enable disabled checkers.

--------------------

Flycheck version: 32snapshot (package: 20180823.826)
Emacs version:    26.1
System:           x86_64-redhat-linux-gnu
Window system:    x
```

# Problem

Every time I open the file with .py extension - I get 3-5 seconds delay
secondary visit of the same file - 0 seconds (buffer opened)
During that time I see ? ? ? popping up in the footer of spacemacs and then by the time the file is loaded - they're gone.

**Any ideas?**

**Comment by fmdkdd** [comment]
Without more information, it's hard to say where the problem is coming from.  Here are a few things you could try:

1. Reproduce under `emacs -Q` or with a minimal configuration.

2. Get the command flycheck executes for `flake8` with `flycheck-compile` (C-c ! c), and execute it in the same directory on the terminal.  Do you see the same delay here?  If you do, then the issue might stem from `flake8`.

3. Activate the profiler (`M-x profiler-start`), reproduce the slowdown and then `M-x profiler-report` and `M-x profiler-report-write-profile`. You want a CPU profile report, not a memory one.

**Comment by dmitry-saritasa** [comment]
1. Ok I have installed a fresh spacemacs, and just added a single python layer
https://github.com/syl20bnr/spacemacs#install

2. I get the long delays for each file I open.

3. emacs -Q doesn't load any packages and any .py file I open is opened instantly

4. Flake8 time 
```➜ time flake8 apps/jobs/models.py
flake8 apps/jobs/models.py  0.82s user 0.26s system 101% cpu 1.067 total
```
5. Emacs profile:
[emacs.profile.1.gz](https://github.com/flycheck/flycheck/files/2377349/emacs.profile.1.gz)

### Any ideas?

**Comment by dmitry-saritasa** [comment]
I have found the reason, this is unrelated to flycheck.
https://github.com/syl20bnr/spacemacs/issues/11317

@cpitclaudel @fmdkdd thanks for your prompt help guys!
