### ISSUE TITLE
Error from mypy is not displayed

### ISSUE THREAD

**Issue by bdc34** [flycheck/flycheck#1506]
* What you did, and what you expected to happen instead
Started emacs, opened a python file, created some code that would cause  mypy error, expected it to be displayed by flycheck. The error was not displayed by flycheck in either the py buffer or flycheck-list-errors. The error was visible in flycheck-compile python-mypy and from running mypy on the command line.

* Whether and how you were able to [reproduce the issue in emacs -Q][emacsQ]
emacs -Q cannot reproduce the bug as flycheck is not setup.
emacs -Q with an eval of (add-hook 'after-init-hook #'global-flycheck-mode) also did not seem to setup flycheck mode.

* Your Flycheck setup from `M-x flycheck-verify-setup`
Syntax checkers for buffer metadata.py in python-mode:

  python-flake8
    - may enable:         yes
    - executable:         Found at /home/bdc34/.local/share/virtualenvs/arxiv-browse-fi6ItXWQ/bin/python
    - configuration file: Not found
    - `flake8' module:    Found at "/home/bdc34/.local/share/virtualenvs/arxiv-browse-fi6ItXWQ/lib/python3.6/site-packages/flake8/__init__.py"

  python-pylint
    - may enable:         yes
    - executable:         Found at /home/bdc34/.local/share/virtualenvs/arxiv-browse-fi6ItXWQ/bin/python
    - configuration file: Found at "/home/bdc34/workspace/arxiv-browse/.pylintrc"
    - `pylint' module:    Found at "/home/bdc34/.local/share/virtualenvs/arxiv-browse-fi6ItXWQ/lib/python3.6/site-packages/pylint/__init__.py"

  python-pycompile
    - may enable: yes
    - executable: Found at /home/bdc34/.local/share/virtualenvs/arxiv-browse-fi6ItXWQ/bin/python

  python-mypy
    - may enable:         yes
    - predicate:          t
    - executable:         Found at /home/bdc34/.local/share/virtualenvs/arxiv-browse-fi6ItXWQ/bin/mypy
    - configuration file: Found at "/home/bdc34/workspace/arxiv-browse/mypy.ini"

Flycheck Mode is enabled.  Use C-u C-c ! x to enable disabled
checkers.

--------------------

Flycheck version: 32snapshot (package: 20180907.1319)
Emacs version:    25.3.1
System:           x86_64-pc-linux-gnu
Window system:    x

* Your operating system
```
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=17.3
DISTRIB_CODENAME=rosa
DISTRIB_DESCRIPTION="Linux Mint 17.3 Rosa"
```

* Your Emacs version from `M-x emacs-version`
`GNU Emacs 25.3.1 (x86_64-pc-linux-gnu, GTK+ Version 3.18.9) of 2018-02-01
`
* Your Flycheck version from `M-x flycheck-version`
`Flycheck version: 32snapshot (package: 20180907.1319)
`

### TEST FILE:
```
def something(x: str)->str:
    return None
```

### Result of flycheck-compile python-mypy
```
-*- mode: compilation; default-directory: "~/workspace/arxiv-browse/" -*-
Compilation started at Tue Sep 25 15:09:58

mypy --show-column-numbers --config-file /home/bdc34/workspace/arxiv-browse/mypy.ini /home/bdc34/workspace/arxiv-browse/xxx.py
xxx.py:2:5: error: Incompatible return value type (got "None", expected "str")

Compilation exited abnormally with code 1 at Tue Sep 25 15:09:59
```

### Result of flycheck-list-errors:
an empty list

### PIPENV
I'm running under pipenv by starting emacs from a pipenv shell. This is the only way I know of for flycheck to find the correct pipenv executables and venv. 

### Other checkers
flake8 seems to work fine. I don't recall seeing errors from other checkers.

### My .emacs flycheck code
```
(add-hook 'after-init-hook #'global-flycheck-mode)
(elpy-enable)
(when (require 'flycheck nil t)
  (add-hook 'elpy-mode-hook 'flycheck-mode))
(remove-hook 'elpy-modules 'elpy-module-flymake)


```

**Comment by fmdkdd** [comment]
The `python-mypy` checker will not run unless explicitly selected (see #1486).

**Comment by bdc34** [comment]
Thank you. I'll get #1486 immediately.
