### ISSUE TITLE
Flycheck Emacs Lisp in Org-mode babel source blocks

### ISSUE THREAD

**Issue by matthew-piziak** [flycheck/flycheck#1507]
I want to have Flycheck syntax checking when I am editing Emacs Lisp code in a literal Org-mode file using babel `SRC` blocks.

However the `flycheck-emacs-lisp` checker predicate has the following to say:

> Ensure that we only check buffers with a backing file. For buffers without a backing file we cannot guarantee that file names in error messages are properly resolved, because `byte-compile-file' emits file names relative to the directory of the checked file instead of the working directory. Hence our backwards-substitution will fail, because the checker process has a different base directory to resolve relative file names than the Flycheck code working on the buffer to check.

So whenever I try to launch the checker I get `predicate: nil` in `flycheck-verify-setup`.

This is definitely a drawback in the literate-programming style. Is there a way to work around it so that source blocks can be checked?

**Comment by cpitclaudel** [comment]
Thanks for the suggestion. Can you check https://github.com/flycheck/flycheck/pull/1426? I think it's closely related

**Comment by matthew-piziak** [comment]
I believe it's exactly related.

> Even though editing real files whose filenames do not conform to their respective languages' toolchains' requirements is not expected to be a common use case, this situation can apply when editing code in transient buffers created by Emacs, such as those created by Org-Babel's `org-edit-src-code`.

**Comment by cpitclaudel** [comment]
I created a PR for this.

**Comment by cpitclaudel** [comment]
> Is this the intended behavior?

Possibly, depending on your value of flycheck-emacs-list-load-path
