### ISSUE TITLE
Cannot enable emacs-lisp flychecker

### ISSUE THREAD

**Issue by beetleb** [flycheck/flycheck#1509]
I just installed flycheck. When I go to a .el file and run flycheck-verify-setup I get:

```
Syntax checkers for buffer anagram.el in emacs-lisp-mode:

  emacs-lisp (disabled)
    - may enable: Automatically disabled!
    - predicate:  t
    - executable: Not found

  emacs-lisp-checkdoc (disabled)
    - may enable: Automatically disabled!
    - predicate:  t
    - executable: Not found

Flycheck Mode is enabled.  Use C-u C-c ! x to enable disabled
checkers.

--------------------

Flycheck version: 32snapshot (package: 20180907.1319)
Emacs version:    26.1
System:           x86_64-w64-mingw32
Window system:    w32
```

I didn't know Emacs lisp would require a binary...? Or is it that Emacs needs to be in my $PATH?

Same problem with emacs -Q

(Yes, I know I'm using Windows...)

**Comment by fmdkdd** [comment]
>  Or is it that Emacs needs to be in my $PATH?

It does, yes.  Flycheck will call Emacs asynchronously, like any other checker.

**Comment by beetleb** [comment]
I tried ensuring emacs is in my path and still get the error. What command is it trying to call? If I run a M-x shell and run that command, would that be a reasonable test on whether it is in my path?

**Comment by fmdkdd** [comment]
> M-x shell and run that command, would that be a reasonable test on whether it is in my path?

Keep in mind that what is in your system PATH and what PATH Emacs is seeing might be different.  You should check both.

**Comment by fmdkdd** [comment]
The command itself isn't relevant I think: being able to call `emacs` should be enough.

**Comment by cpitclaudel** [comment]
I think there's something fishy here. For Emacs, unless other checkers, we don't usually go through the PATH, IIRC; instead, we use the path of the current Emacs executable, as returned by `invocation-directory` and `invocation-name`.  @beetleb, what value does `flycheck-this-emacs-executable` have for you? You can check with `C-h v flycheck-this-emacs-executable RET`.

**Comment by fmdkdd** [comment]
Oh right, this was hidden below `emacs-lisp-checkdoc`... why is that necessary?

**Comment by cpitclaudel** [comment]
It makes things more consistent: if you build and run Emacs 24, you want to get the Flycheck warnings computed by Emacs 24, even if Emacs 25 is the one that's in your path as "emacs".  I imagine it's not so uncommon to test things across multiple versions of Emacs for package devs, and on macOS IIRC the default Emacs in $PATH is a really old one, too.

**Comment by beetleb** [comment]
@cpitclaudel 

The value of `flycheck-this-emacs-executable` is `c:/Users/myuserid/Documents/Programs/emax64-bin-20180529/emax64/bin/emacs`. 

This sounds right.

**Comment by cpitclaudel** [comment]
Thanks. Can you confirm what the following forms return (use `M-:` to execute each snippet)?

- `(flycheck-find-checker-executable 'emacs-lisp)` ⇒ `nil`, I expect
- `(flycheck-checker-executable checker)` ⇒ `"c:/Users/myuserid/Documents/Programs/emax64-bin-20180529/emax64/bin/emacs"`, hopefully
- `flycheck-executable-find` ⇒ `executable-find`, probably
- `(funcall flycheck-executable-find (flycheck-checker-executable checker))` ⇒ `nil`, likely
- `(executable-find (flycheck-checker-executable checker))` ⇒ `t`, likely

I imagine your results will diverge from the ones I crystal-balled; where the divergence occurs is what will help us track the issue down.

Thanks for your patience :)

**Comment by beetleb** [comment]
In order:

1. Gives nil
2. Debugger launches: (void-variable checker)
3. flycheck-default-executable-find
4. Debugger (same problem)
5. Debugger (same problem)

Do you have a typo? Don't I need to define ``checker``?

**Comment by cpitclaudel** [comment]
Ouch. I updated the post, sorry.

**Comment by beetleb** [comment]
I updated my response with the answers.

**Comment by cpitclaudel** [comment]
OK. Last experiment: what happens if you run `(setq flycheck-executable-find 'executable-find)`? Does the problem persist?

If not, the issue is likely https://github.com/flycheck/flycheck/pull/1485

**Comment by beetleb** [comment]
That seems to have fixed the problem. Should I put that in my init.el?

```
Syntax checkers for buffer atbash-cipher.el in emacs-lisp-mode:

  emacs-lisp (disabled)
    - may enable: yes
    - predicate:  t
    - executable: Found at c:/Users/myuserid/Documents/Programs/emax64-bin-20180529/emax64/bin/emacs.exe

  emacs-lisp-checkdoc (disabled)
    - may enable: yes
    - predicate:  t
    - executable: Found at c:/Users/myuserid/Documents/Programs/emax64-bin-20180529/emax64/bin/emacs.exe

Flycheck Mode is enabled.  Use C-u C-c ! x to enable disabled checkers.

--------------------

Flycheck version: 32snapshot (package: 20180907.1319)
Emacs version:    26.1
System:           x86_64-w64-mingw32
Window system:    w32
```

**Comment by cpitclaudel** [comment]
For now, yes. Hopefully @CyberShadow can have a look soon.
Hey @CyberShadow! The change in #1485 seems to break things for some users.  Could you have a look? :relaxed:

**Comment by CyberShadow** [comment]
Certainly. It looks like the following happened:

- `flycheck-checker-executable` returns the Emacs path without the `.exe` extension.
- The extension is optional on Windows - `executable-find` will add it when it is absent on an absolute path.
- `flycheck-default-executable-find` can't handle an extension-less path because `file-executable-p` wants a full path, including extension.

I'll be back with a suggested fix after coffee.

**Comment by CyberShadow** [comment]
Fix (with tests): https://github.com/flycheck/flycheck/pull/1512
