### ISSUE TITLE
How can I know that flycheck has found a checker?

### ISSUE THREAD

**Issue by re-mx** [flycheck/flycheck#1510]
Hello, and sorry for my poor English.

As stated in the title, I need to determine if flycheck has found a checker. What should I do?

* Your operating system
```
Arch Linux @ Linux kernel 4.18.12
```
* Your Emacs version from `M-x emacs-version`
```
GNU Emacs 26.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2018-07-05
```
* Your Flycheck version from `M-x flycheck-version`
```
Flycheck version: 32snapshot (package: 20180907.1319)
```

Thanks.

**Comment by cpitclaudel** [comment]
Hi there,

Can you try `(flycheck-find-checker-executable checker)`? For example, `(flycheck-find-checker-executable 'rust)`

**Comment by re-mx** [comment]
But this seems a bit too complicated for JavaScript...
After all, JavaScript has several checkers...

I see the method of Mr. purcell, I don't know if it works:
```
(autoload 'flycheck-get-checker-for-buffer "flycheck")
(if (flycheck-get-checker-for-buffer)
     (foo)
  (bar))
```

**Comment by re-mx** [comment]
It seems that the purcell solution is feasible... I will close this issue.
