### ISSUE TITLE
Can't use eval to define the command name in :command

### ISSUE THREAD

**Issue by DamienCassou** [flycheck/flycheck#1515]
Thank you for flycheck, it's awesome. 

I have a problem to define a checker though:

```emacs
(flycheck-define-checker some-checker
  "Some comment."
  :command ((eval (some-func)) source))
  ...)
```

This is invalid because the `(eval ...)` form can't be used as first element of `:command`. If I add a string before, it works:

```emacs
(flycheck-define-checker some-checker
  "Some comment."
  :command ("command" (eval (some-func)) source))
  ...)
```

But that's not what I want as the command to use (and its arguments) depends on the value of another variable.

**Comment by fmdkdd** [comment]
Yes, the first argument must be a string which is the checker executable.  You can override it by setting `flycheck-some-checker-executable` after the checker definition though.  If `some-func` needs to be evaluated only when the checker is defined, this will work.

Do you want the `some-func` to be evaluated each time the checker is called rather?

**Comment by DamienCassou** [comment]
fmdkdd <notifications@github.com> writes:
> Do you want the `some-func` to be evaluated each time the checker is
> called rather?

yes: the result of evaluating `some-func` depends on the value of a
custom variable whose value might be different from a project to the
next.

-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by fmdkdd** [comment]
Could you use `flycheck-mode-hook` to call `some-func` to change the value of `flycheck-some-checker-executable`?

Otherwise, we may be able to support the `eval` syntax for the first argument as well.

**Comment by DamienCassou** [comment]
It seems to work but feels a little hackish. Also, I felt like `flycheck-before-syntax-check-hook` was more appropriate than `flycheck-mode-hook`.

```emacs
(flycheck-define-checker emacs-lisp-elsa
  "An Emacs Lisp checker using Elsa"
  :command ("cask"
            (eval (cdr (flycheck-elsa-command)))
            source-inplace)
  ...)

(defun flycheck-elsa--setup-executable ()
  "Configure `flycheck-emacs-lisp-elsa-executable'."
  (setq-local flycheck-emacs-lisp-elsa-executable
              (car (flycheck-elsa-command))))

(defun flycheck-elsa-setup ()
  "Setup Flycheck with Elsa."
  (interactive)
  (add-hook 'flycheck-before-syntax-check-hook #'flycheck-elsa--setup-executable))
```

What do you think?

**Comment by fmdkdd** [comment]
> What do you think?

Doesn't look that hackish to me!  Just be aware that `flycheck-define-checker` has a default `:enabled` function which disables the checker if the executable cannot be found.

**Comment by cpitclaudel** [comment]
Side note (sorry for not chiming in earlier): we could also allow functions instead of strings or nil as the value of `flycheck-*-executable`; I think that would be pretty clean.

**Comment by DamienCassou** [comment]
Clément Pit-Claudel <notifications@github.com> writes:
> Side note (sorry for not chiming in earlier): we could also allow functions instead of strings or nil as the value of `flycheck-*-executable`; I think that would be pretty clean.

yes. It could also be a list with the executable followed by its arguments.

-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by cpitclaudel** [comment]
@DamienCassou I'm going through old issues.  Sorry that this issue was allowed to linger for so long.  In your experience, is the hook enough in general? One advantage with that approach (letting client packages set the command directly) is that clients have control on how often the binary name should be checked (with eval, it would be every time, which might be costly).

**Comment by cpitclaudel** [comment]
Fun fact: the early implementation of Flycheck (7 years ago) used an eval form for the checker name.  It was changed to remove the eval with no justification in the commit:

```
8b61b9b62c617f27f07c454614012cfaf55457f8
Author:     Sebastian Wiesner
AuthorDate: Thu Nov 21 21:01:55 2013 +0100
Commit:     Sebastian Wiesner
CommitDate: Thu Nov 21 21:01:55 2013 +0100

Parent:     571a2005 Split Emacs command variable into executable and args
Follows:    0.15 (5)
Precedes:   0.16 (208)

Require plain strings for checker executables

The executable of a syntax checker command is not subject to
substitution anymore.

2 files changed, 48 insertions(+), 47 deletions(-)
doc/flycheck.texi | 21 +++++++++++-----
flycheck.el       | 74 +++++++++++++++++++++++++------------------------------
```

**Comment by DamienCassou** [comment]
I'm ok with what flycheck currently provides. It's not optimal but also not a big problem. Also, I don't have much experience defining checkers so I can't generalize. You may close the issue.

**Comment by cpitclaudel** [comment]
Alrighty :) Future visitors: please reopen if this an issue for you.
