### ISSUE TITLE
`r-lintr` checker should support ess-r-mode

### ISSUE THREAD

**Issue by ashiklom** [flycheck/flycheck#1517]
The `r-lintr` checker no-longer works with the current version of Emacs ESS. I _think_ this is because the `r-lintr` checker is configured around `ess-mode`, but as far as I can tell, recent changes to ESS (perhaps [this commit?](https://github.com/emacs-ess/ESS/commit/59686509231c03cf4af0bdcda855f42dc64cc98d)) changed the mode inheritance so `ess-r-mode` (the default mode for R scripts) is now separate from `ess-mode`.

When I changed the `r-lintr` `:mode` from `ess-mode` to `ess-r-mode` and reloaded the script, the checker started working again.

Incidentally, the new inheritance logic may allow you to simplify some of the `r-lintr` logic -- for instance, you may not need the `:predicate` that checks the current `ess-language` anymore.

**Comment by cpitclaudel** [comment]
Thanks a lot for this report. I'd love to merge a change along these lines. Would you like to open a pull request?

**Comment by ashiklom** [comment]
Closed via #1521.
