### ISSUE TITLE
go-vet is broken because "go vet tool" was deprecated

### ISSUE THREAD

**Issue by ysmolsky** [flycheck/flycheck#1523]
`go-vet` checker does not work anymore because `go vet tool` stopped working after recent refactoring s in `vet`. For more details see https://github.com/golang/go/issues/28869.

Also `-printfuncs`, `-shadow`, and `-tags` parameters are deprecated in `go vet`. `-all` is ignored.

One of proposed solutions is to use `go vet` instead of `go vet tool`. I have tried that locally. The problem is when the source file has syntax errors and `go vet` returns only those syntax errors and does not display vet warnings. Otherwise it works. 

Any ideas are welcome.

**Comment by ysmolsky** [comment]
ping @lunaryorn @mpolden @adamfaulkner

**Comment by fmdkdd** [comment]
@ysmolsky Please do not ping lunaryorn concerning Flycheck.  Rather, ping @flycheck/go to get the attention of our Go team.

Regarding the issue: from the original thread, it doesn't look like there is a consensus on a good solution.  I don't use Go however, so I'll leave you and our Go team to propose solutions.

**Comment by dominikh** [comment]
Is the only issue that `go vet` aborts on syntax errors? If that's the case that sounds acceptable to me. You won't get the full range of vet checks in the case of syntax (or type) errors, anyway.

Not like we have any other option beginning with Go 1.12.

**Comment by fmdkdd** [comment]
I've sent a PR to rename it to `go vet`.  Does this mean we now require Go 1.12 for `go vet` to work?

**Comment by ianlancetaylor** [comment]
Plain `go vet` should work for Go 1.5 and later.

**Comment by faaaar** [comment]
I update my go version to 1.12. And then I have the same problem. How to solve it?
![image](https://user-images.githubusercontent.com/12553862/53550593-02280b00-3b72-11e9-8edf-973e79f89be6.png)

**Comment by fmdkdd** [comment]
@faaaar Helping with #1525 would be a good start.

**Comment by nelhage-stripe** [comment]
fwiw I've worked around in `.emacs` by patching the command in-place:
```lisp
(let ((govet (flycheck-checker-get 'go-vet 'command)))
  (when (equal (cadr govet) "tool")
    (setf (cdr govet) (cddr govet))))
```

I'd love to see #1525 land, though!

**Comment by ccqpein** [comment]
Same issue, look forward #1525 merge.
