### ISSUE TITLE
Window with error details has only one line

### ISSUE THREAD

**Issue by emeiri** [flycheck/flycheck#1524]
Hi,

I've enabled flycheck using:

(use-package flycheck
  :ensure t
  :init
  (global-flycheck-mode t))

Flycheck runs ok and reports many issues in my python code. However, when I move the point to a line with some error I can only the first line in the detailed error message. The window that is opened below my buffer doesn't expand to display the entire message.

Here's the output from flycheck-verify-setup:

  python-flake8
    - may enable:         yes
    - executable:         Found at /usr/local/bin/flake8
    - configuration file: Not found

  python-pylint
    - may enable:         Automatically disabled!
    - executable:         Not found
    - configuration file: Not found

  python-pycompile
    - may enable: yes
    - executable: Found at /usr/bin/python

Flycheck Mode is enabled.  Use C-u C-c ! x to enable disabled
checkers.

--------------------

Flycheck version: 31
Emacs version:    25.2.1
System:           x86_64-pc-linux-gnu
Window system:    x

Thanks,

Etay

**Comment by cpitclaudel** [comment]
Hi! Thanks for the detailed report. Sorry to hear that you're having trouble. Do you think you could post a screenshot, too?

**Comment by emeiri** [comment]
![flycheck](https://user-images.githubusercontent.com/364174/49450429-a275ca00-f7e5-11e8-9905-c3f31927229f.JPG)

**Comment by cpitclaudel** [comment]
This seems to show the entire message, doesn't it?

**Comment by cpitclaudel** [comment]
Also, are you using elpy? It would help to try without it, to make sure that the issue is in Flycheck rather than in an interaction with Elpy.

**Comment by cpitclaudel** [comment]
Sorry for letting this issue fall through.  I need a full repro to be able to investigate the issue; maybe you could reopen this issue and post a minimal example if the problem persists?
