### ISSUE TITLE
can`t find boost file

### ISSUE THREAD

**Issue by signorinotang** [flycheck/flycheck#1528]
![d431f4d7-21ca-499a-b76f-bb882917885c](https://user-images.githubusercontent.com/8033759/50146211-38354d00-02ee-11e9-9226-55e1cb840908.png)

can`t not find file boost/asio.hpp
then  add
(setq flycheck-clang-include-path '("/usr/local/Cellar/boost@1.57/1.57.0/include"))

how to fix this !

**Comment by cpitclaudel** [comment]
Sorry that we missed this issue.  It looks like an include path issue, but it's hard to say without a full example. Feel free to reopen if this is still a problem.
