### ISSUE TITLE
Text going invisible for emacs 27

### ISSUE THREAD

**Issue by wkirschbaum** [flycheck/flycheck#1531]
Sometimes some of the text goes invisible. This only happens when flycheck-mode is enabled. 

I tested this in emacs -Q and only adding flycheck. It seems to only happen when there are 3 or more windows open. On emacs 26 everything works.

![flycheckissue2](https://user-images.githubusercontent.com/1431483/50400156-3277b580-078d-11e9-87f0-f0829c84ab69.gif)

```
Syntax checkers for buffer .bashrc in sh-mode:

  rpm-rpmlint (disabled)
    - may enable: Automatically disabled!
    - predicate:  nil
    - executable: Not found

  sh-bash
    - may enable: yes
    - predicate:  t
    - executable: Found at /usr/local/bin/bash

  sh-posix-dash
    - may enable: Automatically disabled!
    - predicate:  nil
    - executable: Not found

  sh-posix-bash
    - may enable: yes
    - predicate:  nil
    - executable: Found at /usr/local/bin/bash

  sh-zsh
    - may enable: yes
    - predicate:  nil
    - executable: Found at /bin/zsh

  sh-shellcheck
    - may enable:           yes
    - predicate:            t
    - executable:           Found at /usr/local/bin/shellcheck
    - Shell bash supported: yes

Flycheck Mode is enabled. Use C-u C-c ! x to enable disabled checkers.

--------------------

Flycheck version: 32snapshot (package: 20181214.1048)
Emacs version:    27.0.50
System:           x86_64-apple-darwin18.2.0
Window system:    ns
```

**Comment by cpitclaudel** [comment]
Thanks for the report. This looks rather odd.
Can you post the exact contents of that file? I've never seen this issue, but I'm not on macOS, so this could be platform-specific.

**Comment by wkirschbaum** [comment]
I realised I was on emacs master, pulled the latest and the issue seems to be resolved now. I suspect it was not related to flycheck.
