### ISSUE TITLE
Make it clear which checks are run, and in what order

### ISSUE THREAD

**Issue by m-cat** [flycheck/flycheck#1533]
Splitting out this issue from #1465.

Something the `verify-setup` buffer doesn't make clear is which checks are run and the order the checks are run in. This is illustrated nicely in `shell-script-mode` where `verify-setup` shows `sh-bash`, `sh-posix-dash`, `sh-posix-bash`, `sh-zsh`, and `sh-shellcheck`, all as enabled, but not all of which are run, nor is it at all clear the chain of ordering they run in.

It should be more clear and transparent as to what flycheck is actually doing. A simple use case is when I add a checker to the chain but I don't know if it worked until flycheck actually shows one of its errors -- and sometimes it never does, and can't even be sure if the checker is running.

Two ideas I have so far:
1. In the `verify-setup` buffer, add a new field for each checker (I'm thinking under "may enable") called "order" or "run order". The first check to run would have a value of `1`, the second `2`, and so on. Checks that are not run would display something like "not run" or "n/a" in red.
2. Beneath the checkers, display the check chain visually. Example: `emacs-lisp --> emacs-lisp-checkdoc --> emacs-lisp-package`, where each check name is a link as per usual.

We can even combine these ideas and implement both 😄 

Would be happy to assist with development of this once we decide on a plan 😄

**Comment by fmdkdd** [comment]
What do you think of #1478?

**Comment by m-cat** [comment]
Thanks, I hadn't seen that PR. It looks great, and would make flycheck much easier to use. I almost feel like you went back in time to address all of my concerns in this Issue 👍 

Is your PR currently blocked by something?

**Comment by fmdkdd** [comment]
> I almost feel like you went back in time to address all of my concerns in this Issue +1

Haha, I wish I had that power.

> Is your PR currently blocked by something?

It grew a bit in scope.  Otherwise, I lack free time to work on this mostly.  I really want to go back to it though.
