### ISSUE TITLE
(flycheck-next-error-pos 0) undefined behavior

### ISSUE THREAD

**Issue by erjoalgo** [flycheck/flycheck#1539]
`(flycheck-next-error-pos 0)` always returns `(point)`, which can be confusing. Would it be possible to either specify the behavior or to return something more reasonable, like one of the options below:

- throw an error
- specify range of acceptable values in the docstring
- default 0 to 1
- return nil

```Flycheck version: 32snapshot (package: 20181214.1048)```

**Comment by fmdkdd** [comment]
Hmmmm.  I don't know the reasons, but I'd be warry of changing that behavior.  I'm okay with specifying it though.

`0` returns `(point)`, unless `reset` is t in which case it returns `(point-min)`.

Why do you find it confusing?

**Comment by erjoalgo** [comment]
"Return the position of the next or previous error, or nil if there is none."

Without knowing whether `flycheck-next-error-pos` considers the `next-error` index to be zero-based or not, a caller might incorrectly interpret a non-nil return value as "there are flycheck errors" when there are none.

**Comment by fmdkdd** [comment]
> Also, I don't see the use of (point) or (point-min) as a return value when there may or may not be a next or previous flycheck error, but please correct if I'm wrong.

You are right that it isn't useful when calling the function from Elisp, since you can call `(point)` and `(point-min)`  directly.  The return value is eventually used by the interactive `flycheck-next-error` though, where the value of `(point)` and `(point-min)` may be useful.  Digging a bit into this, I think it echoes the behavior of `compilation-next-error-function`.  The variable `next-error-function` itself does not specify how to handle 0:

```elisp
(defvar next-error-function nil
  "Function to use to find the next error in the current buffer.
The function is called with 2 parameters:
ARG is an integer specifying by how many errors to move.
```

We could certainly change `flycheck-next-error-pos` while maintaining the current behavior for the interactive `flycheck-next-error` though.

**Comment by fmdkdd** [comment]
> then maybe flycheck-next-error shouldn't need to either.

It doesn't hurt to be more specific though.

> I noticed (compilation-next-error-function 0) returns t if there are compilation errors and (point) is on an error line, and throws an error otherwise.

That's reasonable behavior.  I'm fine going with that.  What do you think?

**Comment by erjoalgo** [comment]
I'm not too familiar with the flycheck code base or with packages that depend on it, so I would also want to avoid changing the current behavior significantly (e.g. signaling an error) and I would defer to maintainers like you on that.

Before knowing that the return value is consumed by `flycheck-next-error`, a behavior that would have be slightly more usable to me would be for `(flycheck-next-error-pos 0)` to return non-nil if there is either a previous or next error. But it seems that it is easy enough to construct such a predicate: 

```lisp
(or (flycheck-next-error-pos 1) (flycheck-next-error-pos -1))
```

So I would agree that there might be more risk than value in changing a behavior that useful internally` and may be used by other packages. I think maybe simply specifying the `0` behavior would be good enough to make things clearer.

**Comment by fmdkdd** [comment]
>  I think maybe simply specifying the 0 behavior would be good enough to make things clearer.

Good enough for me :+1:.  I've updated the docstring.  Thanks for bringing up this point.
