### ISSUE TITLE
State inconsistency in flycheck when switching environments with pyvenv

### ISSUE THREAD

**Issue by claytonlemons** [flycheck/flycheck#1542]
**OS**: Linux Mint 19
**Emacs version**: GNU Emacs 25.2.2 (x86_64-pc-linux-gnu, GTK+ Version 3.22.21) of 2017-09-22, modified by Debian
**Flycheck version**: 32snapshot (package: 20190108.351)

pyvenv and flycheck aren't playing nicely together. Here's what's happening:

1. Open python buffer
2. `M-x flycheck-verify-setup`
3. Observe:
   ```
     python-flake8 (disabled)
       - may enable:         Automatically disabled!
       - executable:         Found at /home/clemons/anaconda3/bin/python
       - configuration file: Found at "/home/clemons/Coding/test/.flake8rc"
       - `flake8' module:    Missing
   ```
4. `M-x pyvenv-workon`
5. Select conda environment that has flake8 module
6. `M-x flycheck-verify-setup`
7. Observe:
   ```
     python-flake8 (disabled)
       - may enable:         yes
       - executable:         Found at /home/clemons/anaconda3/envs/myenv/bin/python
       - configuration file: Found at "/home/clemons/Coding/test/.flake8rc"
       - `flake8' module:    Found at "/home/clemons/anaconda3/envs/myenv/lib/python3.7/site-packages/flake8/__init__.py"
   ```

Notice in step 7 that python-flake8 is disabled even though the flake8 module has been discovered in the `myenv` conda environment. And as expected, the value of flycheck-disabled-checkers is (python-flake8). So, it appears that flycheck is not reenabling the python-flake8 checker after changing python environments.

Workarounds:
- Run `M-x revert-buffer` in the python buffer after step 5
- Run steps 4 and 5 before step 1
- Write a hook (`pyvenv-post-activate-hooks`?) to reverify the checkers after pyvenv activates a new environment
  - Is there a more generic way to accomplish this without requiring flycheck to know about pyvenv?

Other thoughts:
- this may be related to #1416

**Comment by cpitclaudel** [comment]
Hi there,

Thanks for the report. I think this is expected (albeit annoying).  It stemps from the way Flycheck "caches" the result of some checker availability checks: the `flake8` checker has an `:enabled` property, which is only check when you open the buffer:

```
`:enabled FUNCTION'
     A function to determine whether to use the syntax checker in
     the current buffer.

     This property behaves as `:predicate', except that it's only
     called the first time a syntax checker is to be used in a buffer.
```

The fix would be to remove `flycheck-flake8` from `flycheck-disabled-checkers` in a pyvenv hook.  Another fix, on the flycheck side, would be to move the `:enabled` check into a `:predicate`.

**Comment by fmdkdd** [comment]
@cpitclaudel Another fix would be to add that `enable now` button we have been talking about in #1478.

**Comment by cpitclaudel** [comment]
I'm not sure. That would be an improvement, but ideally things should "just work".

**Comment by fmdkdd** [comment]
> ideally things should "just work".

I agree.  But we can hardly account for all the possible ways people set up their environments.   Currently we check for the executable when flycheck-mode is activated.  Switching to `:predicate` is wasteful if you check on newline.

Or we can document the function to add to the pyenv hook.

**Comment by cpitclaudel** [comment]
> Or we can document the function to add to the pyenv hook.

I think that would be perfect — or we could show the pyvenv people what to do, and with a bit of luck they would DTRT when flycheck is enabled.

**Comment by claytonlemons** [comment]
> Or we can document the function to add to the pyenv hook.

Is there a single 'reverify' function that one can just call? I'd be fine with that. It'd simplify the integration implementation in pwalsh/pipenv.el#47

**Comment by cpitclaudel** [comment]
Sorry for the delay.  I think what you did is fine :) (small suggestion: `dolist` might have made that loop shorter).

@fmdkdd , we should store the result of the `enabled` check in a separate variable, because as things are atm there's no way for us to tell whether a checker was added by us or by the user to `-disabled-checkers`.

**Comment by fmdkdd** [comment]
Okay so checkers that fail the `:enabled` test go to `-automatically-disabled-checkers`, `-disabled-checkers` is for manually disabled ones (and Flycheck does not remove checkers from that without user intervention).

Then, when reverting the verify-setup buffer, we could retry the `:enabled` tests after clearing `automatically-disabled-checkers`.

In the process, we extract a 'recheck enabled' function that makes the use case of pwalsh/pipenv.el#47 more straightforward (and does not much with `-disabled-checkers` in the process).

Is this it?
