### ISSUE TITLE
Type coercion can not check on tslint

### ISSUE THREAD

**Issue by yuanlai** [flycheck/flycheck#1543]
Following the guide step by step, I succeed setup the flycheck for tslint. 
The status list of flycheck
```
Syntax checkers for buffer Test.ts in typescript-mode:

  typescript-tslint
    - may enable:         yes
    - executable:         Found at /usr/local/bin/tslint
    - configuration file: Found at "*/tslint.json"

Flycheck Mode is enabled.  Use C-u C-c ! x to enable disabled
checkers.

--------------------

Flycheck version: 32snapshot (package: 20190211.1528)
Emacs version:    26.1
System:           x86_64-apple-darwin14.5.0
Window system:    ns
```
But when I make some test for it, it show some unexpected results for me, the code below
```
namespace Types {
    function Linear(currentValue: number, startValue: number): boolean {
        return currentValue + startValue;
    }
    const x1 = true;
    const x2 = 10;
    console.log(Linear(x1, x2));
}
```

Clearly the x1  and the return of Linear is a type coercion error, but the tslint not indicate it. Is it a bug or something I have missing to add?

**Comment by fmdkdd** [comment]
What does `tslint` report on this file if you call it on the command line?

**Comment by yuanlai** [comment]
I think tslint is just a format warmming instead of a grammer check, I change to `tide` mode for development.
