### ISSUE TITLE
eslint disabled in web-mode and js2-mode without apparent reason

### ISSUE THREAD

**Issue by billywade** [flycheck/flycheck#1545]
* What you did, and what you expected to happen instead

I tried to set up ```javascript-eslint``` for js2 and web modes. The config I'm working with right now is:

```
(use-package js2-mode
  :ensure t
  :config
  (add-to-list 'auto-mode-alist '("\\.js\\'" . js2-mode))
  (add-hook 'js2-mode-hook #'js2-imenu-extras-mode)
  (add-hook 'js2-mode-hook
            (defun my-js2-mode-setup ()
	      ;; (flycheck-mode t)
	      (when (executable-find "eslint")
		(flycheck-select-checker 'javascript-eslint)))))

(use-package company-tern
  :ensure t
  :config
  (add-to-list 'company-backends 'company-tern)
  (add-hook 'js2-mode-hook (lambda ()
                             (tern-mode)
                             (company-mode)))
  :diminish tern-mode)
```
Just sub in web-mode for js2-mode for web, the output has been the same.

* Your Flycheck setup from `M-x flycheck-verify-setup`
```
Syntax checker in buffer App.js in js2-mode:

  javascript-eslint (disabled)
    - major mode:  `js2-mode' supported
    - may enable:  yes
    - executable:  Found at /home/trey/git/link/node_modules/eslint/bin/eslint.js
    - config file: found

Flycheck cannot use this syntax checker for this buffer.

Flycheck Mode is enabled.  Use C-u C-c ! x to enable disabled
checkers.

--------------------

Flycheck version: 32snapshot (package: 20190213.1525)
Emacs version:    26.1
System:           x86_64-pc-linux-gnu
Window system:    x
```
Another error that came up:
```
Suspicious state from syntax checker javascript-eslint: Flycheck checker javascript-eslint returned non-zero exit code 2, but its output contained no errors: Value for 'config' of type 'path::String' required.

Try installing a more recent version of javascript-eslint, and please open a bug report if the issue persists in the latest release.  Thanks!
```
* Your Emacs version from `M-x emacs-version`
  GNU Emacs 26.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2018-07-05

* Your Flycheck version from `M-x flycheck-version`
  Flycheck version: 32snapshot (package: 20190213.1525)

Thanks!

**Comment by fmdkdd** [comment]
> Value for 'config' of type 'path::String' required.

Looks like `eslint` isn't happy with your config?

**Comment by billywade** [comment]
Huh, do you know if there's something that can figure out why eslint doesn't like it?

**Comment by cpitclaudel** [comment]
> but even after fixing them, no luck.

What's the new error message?

**Comment by billywade** [comment]
They were just missing node package errors. I installed the missing packages and eslint itself runs fine, but the same error as before, the ```suspicious state``` error, is still occurring.

**Comment by cpitclaudel** [comment]
That suspicious state error is an eslint message: "Value for 'config' of type 'path::String' required.".  Don't you see the same thing with eslint on the command line?

**Comment by billywade** [comment]
Not at all. Same file returns no errors, and if I introduce an error eslint catches and returns it.

**Comment by cpitclaudel** [comment]
Thanks. Can you show the output of `C-c ! C-c`?

**Comment by billywade** [comment]
Sure, thanks again for helping me out.

```
-*- mode: compilation; default-directory: "~/git/link/" -*-
Compilation started at Tue Feb 26 22:09:58

eslint --format\=json -c\ \~/.eslintrc --stdin --stdin-filename /home/trey/git/link/src/App.js < /home/trey/git/link/src/App.js
Value for 'config' of type 'path::String' required.

Compilation exited abnormally with code 2 at Tue Feb 26 22:09:58
```

**Comment by billywade** [comment]
It's probably referring to this. I couldn't figure out how to set it outside of custom-set-variables.

```
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(flycheck-eslint-args (quote ("-c ~/.eslintrc"))))
```

**Comment by cpitclaudel** [comment]
Ah, yes, that variable should be a list, not a single string

**Comment by billywade** [comment]
Oh, okay. How should I write it, and what should it consist of?

**Comment by cpitclaudel** [comment]
I would set it using M-x customize-variable, and you should separate the `-c` from the `eslintrc` part.  I would also double-check whether you actually need to pass this to eslintrc.  Finally, I'm not sure whether `~` will expand properly in this context.

**Comment by billywade** [comment]
Yup, didn't need that line. Thanks for all of your help.
