### ISSUE TITLE
Missing theme option to flycheck-perlcritic

### ISSUE THREAD

**Issue by LevPetrovitch** [flycheck/flycheck#1550]
Hi,
Currently, the `perlcritic` checker can only be configured through two options: the configuration file 
path and the severity level `flycheck-perlcritic-severity`.

A `flycheck-perlcritic-theme` variable, corresponding to the `--theme` option of the perlcritic command would be useful, allowing a programmer to have different policies for different projects without having to install multiple copies of perlcritic's configuration file. 

I'm by no means an expert in elisp, however looking at the code for defining and using `flycheck-perlcriticrc` the task doesn't seems very difficult (a part from the time. I know everything about never having enough time to code). So simple that I'd even agree to follow the timeless principle stating that 
"_Those whom require a feature are tasked to implement it_",  if you can trust me.

**Comment by fmdkdd** [comment]
Yeah sure, go ahead and make a PR adding that option.  :+1: 

You'll need to add a new variable, use it in the checker, and document it in `doc/languages.rst`.

**Comment by LevPetrovitch** [comment]
Good :) 
Working on it. I've a question about the documentation. 
As per Perl Critic documentation, using `--theme` sets the severity to 1, unless `--version` is given or is set in the configuration file. Do you feel that users should be remembered of that? Perl Critic users should be familiar with that

**Comment by fmdkdd** [comment]
@LevPetrovitch Your call.  I would lean on letting the Perl Critic documentation be the reference here.

**Comment by cpitclaudel** [comment]
Closed in https://github.com/flycheck/flycheck/commit/15705f2c0327a4ff9f71e04bcede7f78a6c089f8.
