### ISSUE TITLE
flycheck-fringe-bitmap-double-arrow is tiny on HiDPI screen

### ISSUE THREAD

**Issue by codesections** [flycheck/flycheck#1552]
Hi all—thanks for the great package!

I've recently run into a minor (but annoying) issue: the error/warning/info indicators in the right fringe are tiny on my display (see screenshot, depicting a normal 80-char line of text).  I am sure that this is due to the fact that my screen is a HighDPI screen; indeed, it appears that this is a [long-standing issue](https://www.reddit.com/r/emacs/comments/51wm7d/emacs_on_hidpi_displays/) with HDPI screens and flycheck.

That same link also describes how I can fix the issue, but I wanted to mention it here since it sounds like it's impacted others and it will only become more of an issue as HDPI screens become more common.

**Comment by cpitclaudel** [comment]
Hi @codesections; thanks for the report!
Since you have a high-dpi screen, would you like to prepare a patch and confirms that it works well for you? I'd be happy to review and merge it.

**Comment by codesections** [comment]
I'd be happy to, though I might be a bit slow/need review—I haven't coded any elisp before (I just started using emacs a few days ago; setting up flycheck was one of my first config tweaks.)

Also, how should the fix work?  If I were fixing it for my own system, I'd just increase the size of the bitmaps and then declare victory.  But, of course, that would result in icons that are twice as big as they should be for non-HDPI screens.  Are you imagining that flycheck would expose a variable that toggles different icon sizes?  Or that it somehow detects a HDPI screen?

**Comment by idanko** [comment]
@codesections @cpitclaudel Hello, and thank you for the potential improvement towards HiDPI age. I just wanna ping a bit and ask to not lost the topic. Regards

**Comment by cpitclaudel** [comment]
See https://github.com/flycheck/flycheck/pull/1742 for a solution using the margins instead of the fringes, which support truly scalable and anti-aliased indicators, instead of monochrome bitmaps.

**Comment by cpitclaudel** [comment]
Done in #1744 :)
