### ISSUE TITLE
python-flake8 and python-mypy have conflicting order / dependency setup

### ISSUE THREAD

**Issue by glyph** [flycheck/flycheck#1563]
The Python portion of the default value for `flycheck-checkers` reads:

```
    python-flake8
    python-pylint
    python-pycompile
    python-mypy
```

So `python-flake8` comes first, and is therefore what is automatically selected by `(flycheck-get-checker-for-buffer)`.

However, `python-flake8` specifies no `:next-checker`s, which means it's the last checker to run.

By contrast, `python-mypy` says `:next-checkers '(t . python-flake8)`.

This results in a very confusing situation where `M-x flycheck-verify-setup` shows both as fully green and ready to run, but only `flake8` actually runs.

There are a bunch of things I wish had gone differently about the process by which I discovered this:

1. First and foremost this specific problem shouldn't exist and the `:next-checker` relationship should be reversed to match the ordering in the list 😄
2. It seems that `flycheck-checkers` should, at some point, be topologically sorted based on this dependency ordering so that this never happens for any checkers.
3. Given the way flycheck works is by picking *one* checker as the one to run and then traversing the `:next-checkers` graph, `flycheck-verify-setup` should really *show that to me* so I can see which one is selected and which one will run next.

Thank you all for flycheck, it's really improved my Emacs editing experience, both in Python and Vue!

**Comment by fmdkdd** [comment]
Thank you for the feedback.  User experience reports like this are helpful, and yours is well written to boot.

I agree with all your points, and I believe #1478 should adress all of them.

**Comment by glyph** [comment]
Thanks @fmdkdd !
