### ISSUE TITLE
PATCH: doc/info.py for python3

### ISSUE THREAD

**Issue by tkita** [flycheck/flycheck#1570]
I use doc/elisp.py and doc/info.py when writing documentation.
I am very grateful for your work.

I wrote follow line in mydoc.rst
```rst
:infonode:`Multi-file Packages in GNU Emacs Lisp Reference Manual <(elisp) Multi-file Packages>`
```
that an error occurred.
> LookupError: 'hex' is not a text encoding;

I am using python 3.6.8, so I changed doc/info.py
It worked normally.
```diff
$ diff -u info-ORIG.py info.py
--- info-ORIG.py 2019-05-08 21:12: 25.890828159 + 0900
+++ info.py 2019-05-08 21: 12: 11.220971692 +0900
@@ -60,7 +60,7 @@
     elif char == ' ':
         return '-'
     else:
-        return '_00' + char.encode('hex')
+        return '_00' + char.encode().hex()

 def expand_node_name(node):
     """Expand ``node`` for use in HTML.
```

**Comment by cpitclaudel** [comment]
Thanks, that looks reasonable. Could you make a PR, so that we have proper authorship in the git log?

**Comment by tkita** [comment]
OK. I will do PR later.
best regards.

**Comment by fmdkdd** [comment]
Wait, I'm confused: is `encode('hex')` not working for 3.6 only?  We have been using 3.5 on the CI for a while, and it works there.  Or is the code in fact never called?
