### ISSUE TITLE
Error while checking syntax automatically: (void-variable mouse-wheel-down-event)

### ISSUE THREAD

**Issue by seagle0128** [flycheck/flycheck#1572]
Emacs 25.2
Ubuntu 18.04
Terminal (no GUI)

While opening some elisp files with `flycheck`, got this message:
`Error while checking syntax automatically: (void-variable mouse-wheel-down-event)`.

It disappears after disabling `flycheck-mode`.

![image](https://user-images.githubusercontent.com/140797/57435770-ce9fe600-7270-11e9-8db9-cfff25ce04ed.png)

**Comment by fmdkdd** [comment]
That's suspicious: there are no references to `mouse-wheel-down-event` in the flycheck code.  Maybe try with `M-x toggle-debug-on-error` to have a backtrace so we can see where this is coming from?

**Comment by seagle0128** [comment]
Hmm... It should be the issue of some hooks. Sorry for that! I am closing it. Thank you!
