### ISSUE TITLE
eslint overrides tslint in typescript mode

### ISSUE THREAD

**Issue by vincekd** [flycheck/flycheck#1585]
The `javascript-eslint` checker now runs by default with `typescript-mode` (since https://github.com/DamienCassou/flycheck/commit/8d74ac092dd213a7c5a77135eab903ca872dc717) which overrides my config to use `typescript-tslint`:
```
(with-eval-after-load "flycheck"
  (flycheck-add-mode 'typescript-tslint 'typescript-mode))
```

How do I disable `javascript-eslint` for `typescript-mode`, or make it prefer `tslint`?

Results of `flycheck-verify-setup`:
```
Syntax checkers for buffer test.ts in typescript-mode:

First checker to run:

  javascript-eslint
    - may enable:  yes
    - executable:  Found at /usr/local/bin/eslint
    - config file: found

Checkers that could run if selected:

  typescript-tslint  select
    - may enable:         yes
    - executable:         Found at /usr/bin/tslint
    - configuration file: Found at "/home/user/dev/project/tslint.json"

Flycheck Mode is enabled.  Use C-u C-c ! x to enable disabled
checkers.
```

**Comment by cpitclaudel** [comment]
You could add a hook to `typescript-mode-hook`:

```
(add-hook 'typescript-mode-hook
    (lambda () (setq-local flycheck-disabled-checkers '(javascript-eslint))))
``` 

But maybe we need a better default? I don't use either checkers these days, so I'll let others chip in.

**Comment by vincekd** [comment]
Also, it seems weird that this breaking change was introduced when `javascript-eslint` does not support typescript out of the box. Need to install special parser/plugins and update config.

**Comment by cpitclaudel** [comment]
Isn't tslint deprecated?

**Comment by vincekd** [comment]
yeah but they just decided a couple of months ago, and there are still a lot of issues to work out for a smooth migration.

https://github.com/palantir/tslint/issues/4534

**Comment by cpitclaudel** [comment]
Is there anything more that we should do here?

**Comment by zoechi** [comment]
I can't get rid of `Symbol’s value as variable is void: javascript-eslint`
when I try https://github.com/flycheck/flycheck/issues/1585#issuecomment-503276929
Any idea what I might do wrong?
