### ISSUE TITLE
Add support for new PHPs mode

### ISSUE THREAD

**Issue by cjohansson** [flycheck/flycheck#1589]
Hi!

Can you please add support for my new PHP mode PHPs ([phps-mode](https://github.com/cjohansson/emacs-phps-mode))?

The major-mode code is `phps-mode` and I have made a temporary flycheck integration [here](https://github.com/cjohansson/emacs-phps-mode/blob/master/phps-mode-flycheck.el) that I will remove once support is added in flycheck instead.

I can make a pull request for these changes if you prefer

**Comment by cpitclaudel** [comment]
Thanks! Can you clarify whether/why this flycheck definition is specific to phps-mode?

**Comment by fmdkdd** [comment]
Just a note: if you just want to add `phps-mode` to the `:modes` property of existing checkers, use `flycheck-add-mode` instead of redefining the checkers.  That would make your flycheck integration much simpler.

**Comment by cjohansson** [comment]
@cpitclaudel no there is no specific checker for phps-mode, I just want added support for phps-mode for those ordinary checkers for PHP that now support php-mode and php+-mode

**Comment by cjohansson** [comment]
@fmdkdd alright, I would prefer that the support was in the flycheck codebase instead of it being in my codebase, I'm planning to add my mode to MELPA and ELPA soon

**Comment by cpitclaudel** [comment]
Ah, then your code should just call flycheck-add-mode, as @fmdkdd suggested :)

**Comment by cjohansson** [comment]
Thanks, I solved it using that method instead, if anyone is curious my code is now:

```
(when (fboundp 'flycheck-add-mode)
    (flycheck-add-mode 'php 'phps-mode)
    (flycheck-add-mode 'php-phpmd 'phps-mode)
    (flycheck-add-mode 'php-phpcs 'phps-mode))
```
