### ISSUE TITLE
Flycheck won't enable eslint 6

### ISSUE THREAD

**Issue by DamienCassou** [flycheck/flycheck#1600]
To detect if flycheck-eslint should be enabled, the command `eslint --print-config .`  is executed. Eslint 6 has disabled passing a directory to `--print-config`: https://github.com/eslint/eslint/issues/11874. The solution is to pass a filename instead.

**Comment by cpitclaudel** [comment]
I think we already have https://github.com/flycheck/flycheck/issues/1593 :)
