### ISSUE TITLE
file loading slows down after emacs has been running a long time

### ISSUE THREAD

**Issue by DavidBiesack** [flycheck/flycheck#1602]
* What you did, and what you expected to happen instead

After Emacs has been running a long time (more than a day), loading new YAML files
with flycheck enable slows down, such that opening a .yaml file can take up
to 60 seconds or more. (files are 3-4,000 lines) 
is not Emacs is blocked while loading  the new file; I cannot use it for any
other activity.

Loading other file types is not slow.

On a new Emacs session, opening the same .yaml files is quick and works fine.
The problem only occurs after using emacs for a while - several days, having opened many .yaml files.

* Whether and how you were able to [reproduce the issue in emacs -Q][emacsQ]

no, this is impractical to run emacs -q for many hours/many files without my customizations;
flycheck is not enabled when running emacs -q

* Your Flycheck setup from `M-x flycheck-verify-setup`

yes
```
Syntax checkers for buffer openapi.yaml<products-api-def> in yaml-mode:

  yaml-jsyaml
    - may enable: yes
    - executable: Found at /Users/david.biesack/.nvm/versions/node/v8.12.0/bin/js-yaml

  yaml-ruby
    - may enable: yes
    - executable: Found at /usr/bin/ruby

Flycheck Mode is enabled. Use C-u C-c ! x to enable disabled checkers.

--------------------

Flycheck version: 31
Emacs version:    25.3.1
System:           x86_64-apple-darwin13.4.0
Window system:    ns
```

* Your operating system

macOS Mohave 10.14.5

* Your Emacs version from `M-x emacs-version`

GNU Emacs 25.3.1 (x86_64-apple-darwin13.4.0, NS appkit-1265.21 Version 10.9.5 (Build 13F1911)) of 2017-09-12

* Your Flycheck version from `M-x flycheck-version`

31

**Comment by cpitclaudel** [comment]
Thanks for the report.  Can you clarify what hints to the problem being caused by Flycheck?
What would be useful is to send a SIGUSR2 (`pkill -SIGUSR2 emacs`) to Emacs while it's unresponsive; this will produce a backtrace and show which function Emacs is stuck in.

**Comment by DavidBiesack** [comment]
This problem only started when I started using FlyCheck for these YAML files
(I'm editing OpenAPI definitions, so the YAML files are somewhat large).

I opened and then killed the same large yaml file many times (about 15) and noticed the slowdown start pretty quickly, and it also started to grow longer with each time I killed and opened the same file.
When I sent SIGUSR2 to emacs, my *Backtrace* shows
```
Debugger entered--Lisp error: (quit)
  apply(debug error (quit))
  edebug(error (quit))
  uniquify-get-proposed-name("openapi.yaml" "/Users/david.biesack/dev/openapi/organizations-api-def/src/openapi" 1)
  uniquify-rationalize-conflicting-sublist((...) "openapi.yaml" 0)
  uniquify-rationalize-a-list((...))
  uniquify-rationalize((...))
  uniquify-rationalize-file-buffer-names("openapi.yaml" "/Users/david.biesack/dev/openapi/invitations-api-def/src/openapi/" #<buffer openapi.yaml<2>>)
  uniquify--create-file-buffer-advice(...)
  apply(uniquify--create-file-buffer-advice ...)
  create-file-buffer("~/dev/openapi/invitations-api-def/src/openapi/openapi.yaml")
  find-file-noselect("~/dev/openapi/invitations-api-def/src/openapi/openapi.yaml" nil nil nil)
  find-file("~/dev/openapi/invitations-api-def/src/openapi/openapi.yaml")
  filemenu-visit-file-at-point-using(find-file)
  filemenu-find-file-at-point()
  funcall-interactively(filemenu-find-file-at-point)
  call-interactively(filemenu-find-file-at-point nil nil)
  command-execute(filemenu-find-file-at-point)
```
which implies it is not in Flycheck but in uniquify (I truncated the traceback args here, but they had long lists of repeated buffers). I tried multiple times and each time it had a similar backtrace.

I also ran `emacs` -q and installed Flycheck and enabled it with a yaml-mode hook and could not 
reproduce this slowdown. I'll see if I can figure out what's wrong with uniquify ... 

thanks for the assistance.

**Comment by cpitclaudel** [comment]
Good luck! I think you should try to get a few more backtraces — it's unlikely that uniquify is to blame.
