### ISSUE TITLE
C/C++-clang checker with Mac OSX Frameworks

### ISSUE THREAD

**Issue by ihowell** [flycheck/flycheck#1605]
I'm not sure if this is an issue with the tools Flycheck uses or how Flycheck uses the tools, so please feel free to tell me if I should go somewhere else for this. I am working on a project where I used OpenGL on Mac OS X Mojave and have Flycheck set up to use the `c/c++-clang` syntax checker. This checker runs clang with the argument `-cc1`, which as far as I can tell, doesn't play nice with OS X frameworks. So, I get the error:

    Error: .../GLFW/glfw3.h: `OpenGL/gl.h` file not found

But, the project still builds fine, it's just the syntax checking that is throwing an error. Is there anything I can do in my `.clang_complete` file (posted below) to make it work? Why is the `-cc1` argument necessary? What does it do?

Obligatory general info:

- OS: macOS Mojave 10.14.5

- M-x flycheck-verify-setup:

      Syntax checkers for buffer Trace.cpp in c++-mode:

      irony
        - may enable:   yes
         - predicate:    t
         - Irony Mode:   enabled
         - irony-server: Found at /Users/ihowell/.emacs.d/irony/bin/irony-server

       c/c++-clang
         - may enable: yes
         - executable: Found at /usr/bin/clang

       c/c++-gcc
         - may enable: yes
         - executable: Found at /usr/bin/gcc

       c/c++-cppcheck
         - may enable: yes
         - executable: Found at /usr/local/bin/cppcheck

      Flycheck Mode is enabled.  Use C-u C-c ! x to enable disabled checkers.

      --------------------

      Flycheck version: 32snapshot (package: 20190320.1026)
      Emacs version:    26.1.92
      System:           x86_64-apple-darwin18.5.0
      Window system:    mac

 - Emacs Version: GNU Emacs 26.1.92 (build 1, x86_64-apple-darwin18.5.0, Carbon Version 158 AppKit 1671.4) of 2019-04-02

 - Flycheck Version: Flycheck version: 32snapshot (package: 20190320.1026)

 - `.clang_complete`

```
-Iinclude
-Iresources
-DELPP_NO_DEFAULT_LOG_FILE
-DELPP_DISABLE_DEFAULT_CRASH_HANDLING
-DELPP_THREAD_SAFE
-DELPP_USE_STD_THREADING
-DELPP_FORCE_USE_STD_THREAD
-DDEBUG
-DIMGUI_IMPL_OPENGL_LOADER_GLEW
-DIMGUI_INCLUDE_IMGUI_USER_H
-Wall
-Wextra
-std=c++17
-Wl
-I/Library/Developer/CommandLineTools/usr/include/c++/v1
-I/Library/Developer/CommandLineTools/usr/lib/clang/10.0.1/include
-I/Library/Developer/CommandLineTools/usr/include
-I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include
-I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework
-I/usr/include
-I/usr/local/include
-Ilib
-Ilib/nativefiledialog/src/include
-Ilib/blackhole/include
-Ilib/stardust/include
-Llib/nativefiledialog/build/lib/Release
-Llib/nativefiledialog/build/lib/Release/x64
-L/System/Library/Frameworks
-L/Library/Frameworks
-L/usr/lib
-I/System/Library/Frameworks/OpenGL.framework/
-L/System/Library/Frameworks/OpenGL.framework/
-framework OpenGL
```

Edit: Forgot `.clang_complete`

**Comment by fmdkdd** [comment]
Flycheck checkers don't pass the `-cc1` flag (first time I've heard of it too!).  The verify-setup screen tells you `irony` is the first checker in your verify-setup, so it's the one that is used by Flycheck in C++ buffers. 

You should take the issue with the `irony` or `flycheck-irony` people.

If you do find a solution, please do answer back here, as that can help future users.  Thanks!

**Comment by ihowell** [comment]
Well, I found a work around, I just symlinked the `Headers` folder to `/usr/local/include`.
