### ISSUE TITLE
flycheck totally incapacitated in buffer with sed oneliner

### ISSUE THREAD

**Issue by bjd-pfq** [flycheck/flycheck#1608]
Linux foobar 4.15.0-55-generic #60~16.04.2-Ubuntu SMP Thu Jul 4 09:03:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

GNU Emacs 24.5.1 (x86_64-pc-linux-gnu, GTK+ Version 3.18.9) of 2017-09-20 on lcy01-07, modified by Debian

Syntax checkers for buffer fix-filenames in sh-mode:

First checker to run:

  sh-bash
    - may enable:    yes
    - predicate:     t
    - executable:    Found at /bin/bash
    - next checkers: sh-shellcheck

Checkers that may run as part of the first checker's chain:

  sh-shellcheck
    - may enable:           yes
    - predicate:            t
    - executable:           Found at /home/foobar/bin/shellcheck
    - Shell bash supported: yes

Checkers that are compatible with this mode, but will not run until properly configured:

  rpm-rpmlint (disabled)
    - may enable: Automatically disabled!
    - predicate:  nil
    - executable: Not found

  sh-posix-dash
    - may enable:    yes
    - predicate:     nil
    - executable:    Found at /bin/dash
    - next checkers: sh-shellcheck

  sh-posix-bash
    - may enable:    yes
    - predicate:     nil
    - executable:    Found at /bin/bash
    - next checkers: sh-shellcheck

  sh-zsh
    - may enable:    yes
    - predicate:     nil
    - executable:    Found at /usr/bin/zsh
    - next checkers: sh-shellcheck

Flycheck Mode is enabled.  Use C-u C-c ! x to enable disabled checkers.

--------------------

Flycheck version: 31
Emacs version:    24.5.1
System:           x86_64-pc-linux-gnu
Window system:    x

When I have a larger script file that contains the following line:

NEWFILE="$(echo -e "$f" | sed -e 's/\o311/É/g' -e 's/\o347/ç/g' -e 's/\o350/è/g' -e 's/\o351/é/g')"

flycheck is completely stifled: all other warnings and errors in that file are _not_ reported, i.o.w. it looks as if the script is completely clean and ok, or, in still other words: the above line seems to totally **incapacitate** flycheck.
As soon as I remove this line, all other warnings and errors turn up like they should (indicators in fringe, etc.).
Commenting out the line does _not_ alleviate the problem.

**Comment by cpitclaudel** [comment]
Can you clarify whether it incapacitate flycheck or the checker itself? What happens if you run shellcheck on the command line on that same file?

**Comment by bjd-pfq** [comment]
Hi.
I think  it is clearly a flycheck issue. When I delete the line, all indicators light up like a christmas tree -- as soon as I insert it again, all indicators disappear. 

Running shellcheck on the cli (the same one used in emacs) turns up the whole host of warnings (it's an old script and I use some old syntax).  So shellcheck parses the buffer nicely.

Btw., there are no warnings/errors reported on the line in question.

**Comment by bjd-pfq** [comment]
I have 'narrowed down' the behaviour to --as expected-- the four accented characters. As soon as I remove _all four_ of them, the christmas tree-effect occurs.

**Comment by bjd-pfq** [comment]
Probably redundant (because you can copy and paste the problematic line as given earlier), but here are the essential properties of the four characters as reported by emacs:

             position: 939 of 5803 (16%), column: 50
            character: É (displayed as É) (codepoint 201, #o311, #xc9)
    preferred charset: iso-8859-15 (ISO/IEC 8859/15)
code point in charset: 0xC9
               script: latin
               syntax: w 	which means: word
             category: .:Base, L:Left-to-right (strong), j:Japanese, l:Latin, v:Viet
             to input: type "C-x 8 RET HEX-CODEPOINT" or "C-x 8 RET NAME"
          buffer code: #xC3 #x89
            file code: #xC3 #x89 (encoded by coding system utf-8-unix)
              display: by this font (glyph code)
    xft:-PfEd-DejaVu Sans Mono-normal-normal-normal-*-10-*-*-*-m-0-iso10646-1 (#x8B)


             position: 956 of 5803 (16%), column: 67
            character: ç (displayed as ç) (codepoint 231, #o347, #xe7)
    preferred charset: iso-8859-15 (ISO/IEC 8859/15)
code point in charset: 0xE7
               script: latin
               syntax: w 	which means: word
             category: .:Base, L:Left-to-right (strong), j:Japanese, l:Latin
             to input: type "C-x 8 RET HEX-CODEPOINT" or "C-x 8 RET NAME"
          buffer code: #xC3 #xA7
            file code: #xC3 #xA7 (encoded by coding system utf-8-unix)
              display: by this font (glyph code)
    xft:-PfEd-DejaVu Sans Mono-normal-normal-normal-*-10-*-*-*-m-0-iso10646-1 (#xA9)


             position: 973 of 5803 (17%), column: 84
            character: è (displayed as è) (codepoint 232, #o350, #xe8)
    preferred charset: iso-8859-15 (ISO/IEC 8859/15)
code point in charset: 0xE8
               script: latin
               syntax: w 	which means: word
             category: .:Base, L:Left-to-right (strong), c:Chinese, j:Japanese, l:Latin, v:Viet
             to input: type "C-x 8 RET HEX-CODEPOINT" or "C-x 8 RET NAME"
          buffer code: #xC3 #xA8
            file code: #xC3 #xA8 (encoded by coding system utf-8-unix)
              display: by this font (glyph code)
    xft:-PfEd-DejaVu Sans Mono-normal-normal-normal-*-10-*-*-*-m-0-iso10646-1 (#xAA)


             position: 990 of 5803 (17%), column: 101
            character: é (displayed as é) (codepoint 233, #o351, #xe9)
    preferred charset: iso-8859-15 (ISO/IEC 8859/15)
code point in charset: 0xE9
               script: latin
               syntax: w 	which means: word
             category: .:Base, L:Left-to-right (strong), c:Chinese, j:Japanese, l:Latin, v:Viet
             to input: type "C-x 8 RET HEX-CODEPOINT" or "C-x 8 RET NAME"
          buffer code: #xC3 #xA9
            file code: #xC3 #xA9 (encoded by coding system utf-8-unix)
              display: by this font (glyph code)
    xft:-PfEd-DejaVu Sans Mono-normal-normal-normal-*-10-*-*-*-m-0-iso10646-1 (#xAB)

**Comment by cpitclaudel** [comment]
I can't reproduce the issue with the following file:

```
#!/usr/bin/env bash
f=1
NEWFILE="$(echo -e "$f" | sed -e 's/\o311/É/g' -e 's/\o347/ç/g' -e 's/\o350/è/g' -e 's/\o351/é/g')"
echo $NEWFILE
```

**Comment by bjd-pfq** [comment]
The problem is -- your file contains no errors or warnings!
Try this, which here displays the described behavour:

#!/usr/bin/env bash
f=1
NEWFILE="$(echo -e "$f" | sed -e 's/\o311/É/g' -e 's/\o347/ç/g' -e 's/\o350/è/g' -e 's/\o351/é/g')"
foo=`basename /`
echo $NEWFILE

The lne with 'foo' would normally issue two warnings from shellcheck:

 SC2034: foo appears unused. Verify it or export it.
 SC2006: Use $(..) instead of legacy `..`.

But flycheck displays no errors.
As soon as I remove the line, the warnings for 'foo' appear (plus some others).

**Comment by bjd-pfq** [comment]
Here's something new:
Running shellcheck from the cli on this smaller file, results in this:

$> shellcheck script
shellcheck: script: hGetContents: invalid argument (invalid byte sequence)

(Oddly enough, this _isn't_ displayed in the output from cli-shellcheck on the larger file!).
Hmm, maybe it _is_ shellcheck.
Do you get such an error from cli shellcheck?
My shellcheck is version: 0.3.7 .

**Comment by bjd-pfq** [comment]
I am considering this a shellcheck bug now.
You may close this one.
Thank you.

**Comment by cpitclaudel** [comment]
Thanks.
