### ISSUE TITLE
Can't get ESLint to work with nvm within Emacs

### ISSUE THREAD

**Issue by sooqua** [flycheck/flycheck#1612]
I tried this before but failed. I've got no problems when installing nodejs system-wide, but once I remove it and install node with [nvm](https://github.com/nvm-sh/nvm) instead, I get this error:
```
  javascript-eslint (disabled)
    - may enable:  Automatically disabled!
    - executable:  Found at /home/sooqua/code/js/test/node_modules/.bin/eslint
    - config file: missing or incorrect
```
Then I figured out I have to install [nvm.el](https://github.com/rejeep/nvm.el) to do the same as `source /usr/share/nvm/init-nvm.sh`, but for Emacs. So I installed it and did `(nvm-use "12.8.1")`. Then I press `<C-c>!s` and select javascript-eslint. Now I'm stuck with this very unhelpful error:
```
  javascript-eslint (disabled)
    - major mode:  `js2-mode' supported
    - may enable:  Automatically disabled!
    - executable:  Found at /home/sooqua/code/js/test/node_modules/.bin/eslint
    - config file: found
Flycheck cannot use this syntax checker for this buffer.
```
Everything seems ok, but for some reason _"Flycheck cannot use this syntax checker for this buffer."_
I'm using Arch Linux, nvm installed from [AUR package](https://aur.archlinux.org/packages/nvm/).
Emacs version: 26.2 ([Doom Emacs](https://github.com/hlissner/doom-emacs/))
Flycheck version: 32snapshot (package: 20190807.813)

**Comment by fmdkdd** [comment]
Did you try to enable the checker back with `C-u C-c ! x javascript-eslint RET`?

**Comment by sooqua** [comment]
That key combo disables a syntax checker on my Emacs installation. But I tried disabling and re-enabling it and it didn't work.

**Comment by fmdkdd** [comment]
Hmm curious.  If you did renable the checker with a prefix argument to `flycheck-disable-checker`, then the enabled check should have been reset.  Yet, it is still automatically disabled.

 I'm sorry I can't help more right now, but if you would like to investigate, you should look at the results of `flycheck-eslint-config-exists-p` and `flycheck-may-enable-checker 'javascript-eslint)` to find out what is going on.

**Comment by maliky** [comment]
I've had the same problem. 


Could it be the call on lines 8468 .. 8472 in flycheck.el v20190320.1026
```lisp
(defun flycheck-eslint-config-exists-p ()
  "Whether there is a valid eslint config for the current buffer."
  (let* ((executable (flycheck-find-checker-executable 'javascript-eslint))
         (exitcode (and executable (call-process executable nil nil nil
                                                 "--print-config" "."))))
    (eq exitcode 0)))
``` 

running ```eslint --print-config . ``` reports the following error:
```bash
Oops! Something went wrong! :(

ESLint: 6.3.0.

The '--print-config' CLI option requires a path to a source code file rather than a directory.
See also: https://eslint.org/docs/user-guide/command-line-interface#--print-config
```

So a solution could be to create a `tmp.js` and run `eslint --print-config tmp.js`

**Comment by jimmywongroo** [comment]
@sooqua Install eslint into your project and get [add-node-modules-path](https://github.com/codesuki/add-node-modules-path) setup. add-node-modules-path just puts all the executables in `node_modules/.bin` to your Emacs' `exec-path`, once it's there, flycheck's stock JS backends will be able to find the them.

**Comment by sooqua** [comment]
@jimmywongroo Doom Emacs does this for me:
https://github.com/hlissner/doom-emacs/blob/develop/modules/lang/javascript/autoload.el#L87
And the eslint executable is found in `node_modules/.bin` as seen in:
`executable:  Found at /home/sooqua/code/js/test/node_modules/.bin/eslint`

**Comment by sooqua** [comment]
> flycheck-eslint-config-exists-p

returns t

> flycheck-may-enable-checker 'javascript-eslint

returns nil

**Comment by gueorgui** [comment]
I'm also having this issue at the moment.

**Comment by cpitclaudel** [comment]
Sorry for letting this fall through.  Do you have a repro that I could run on my machine?

**Comment by Simplify** [comment]
Problem here is that `eslint` installed in `node_modules` requires different version of node than version installed globally (or `nvm`'s default) and does not run. I don't have this problem because I use `emacs` in terminal and can run `nvm use` before starting `emacs`. If I forget to do that, I would have same problem. GUI users have this problem for sure.

Easy solution is to add directory with specific node version to path in `.dir-locals.el`. That is what `nvm use` does. For example, if you want to use node `10.18.0`, you can create `.dir-locals.el` in your project's root with following:

```elisp
((nil . ((eval . (progn
                   (add-to-list 'exec-path (substitute-in-file-name "$HOME/.nvm/versions/node/v10.18.0/bin/"))
                   (add-to-list 'exec-path (concat (locate-dominating-file default-directory ".dir-locals.el") "node_modules/.bin/")))))))
```

This will:
* Add bin directory of required node installation to $PATH, so right version of node is used.
* Add node_modules's bin directory inside your project to $PATH, so right `eslint` version is found and used, assuming that you added `eslint` as dev dependency in your js project.

It's pain to change this file every time you upgrade node, so you may look for a way to look at `nvmrc` file. Other node version managers may use `.node-version` or something else. There may be a emacs package that does this for you.

@cpitclaudel I'm not sure that this is in scope of Flycheck.

**Comment by cpitclaudel** [comment]
Thanks a lot for the clarification.  Isn't there a package in emacs that does the proper `nvm use` etup, like pyvenv does for python?

**Comment by Simplify** [comment]
Quick search gave me this one: https://github.com/rejeep/nvm.el

User will end up still with `.dir-locals.el` in order to set `./node_modules/.bin` to path tho.

**Comment by cpitclaudel** [comment]
> User will end up still with .dir-locals.el in order to set ./node_modules/.bin to path tho.

nvm.el seems to do that too, doesn't it?  It seems to set exec-path.

**Comment by Simplify** [comment]
> > User will end up still with .dir-locals.el in order to set ./node_modules/.bin to path tho.
> 
> nvm.el seems to do that too, doesn't it? It seems to set exec-path.

It does that for $NVM_DIR/versions/<node-version-you-use>/bin but not for `./node_modules/.bin` inside your project where your needed executable will probably be (unless you install them all globally). It's outside of scope of that package.

**Comment by cpitclaudel** [comment]
Ah, snap

**Comment by cpitclaudel** [comment]
I do agree with you that this problem is outside the scope of Flycheck.  But in fact I just found add-node-modules-path, which I think is exactly the package we need.  So a combination of nvm.el + add-node-modules-path should fix this issue.

Feel free to reopen if that isn't enough.

**Comment by deepanshu44** [comment]
@cpitclaudel  I ran into this problem and after doing all of the above nothing seems to work in emacs 27 ubuntu 20 (nvm). Then what I did was removed flycheck and reinstalled it which SOLVED my problem. I upgraded to emacs from 26 to 27, maybe that seems to be source of problem. Even upgrading to 28 didn't removed the error. But finally sigh of relief.
