### ISSUE TITLE
Define a next-checker only for a specific filetype

### ISSUE THREAD

**Issue by kriansa** [flycheck/flycheck#1632]
## Checklist
- [x] I have searched existing issues and StackOverflow for solutions.
- [x] I have read the [Flycheck manual][].
- [x] I have read the [Troubleshooting Guide][].
- [x] I have checked my issue has not been reported yet.

## Problem description

I've been trying to enable two different linters on a given filetype, but these two checkers are not necessarily for the same file type. 

When I edit `.vue` files, I use web-mode. I added `javascript-eslint` to web-mode and it works like a charm. My problem comes to add `css-stylelint` as well. In order to do that, if I just use `flycheck-add-mode`, it won't automatically run after `eslint` because I would need to select which one to run. I add it to run as a next-checker for `eslint` (using `flycheck-add-next-checker`) then `css-stylelint` would run on every buffer that has `eslint` on, which is not desirable because they can be pure JS files.

Is there  a way of achieving that? I want to have two different checkers that run sequentially, but only for a specific filetype.

[Flycheck manual]:  https://www.flycheck.org/en/latest/user/troubleshooting.html
[Troubleshooting guide]:  https://www.flycheck.org/en/latest/user/troubleshooting.html

**Comment by cpitclaudel** [comment]
Hi there.  Neat question writeup, thanks!

> I add it to run as a next-checker for eslint (using flycheck-add-next-checker) then css-stylelint would run on every buffer that has eslint on, which is not desirable because they can be pure JS files.

I think css-stylelint would only run in those buffers in which it may run, which would be `css-mode` ones (the default) and `web-mode` ones (after you `flycheck-add-mode` it).  Isn't that OK?

If not, the right way to go is to define a major mode for your file type.  Look at define-derived-mode (it has great docs); something like this (untested):

```elisp
(define-derived-mode vue-mode web-mode "Vue mode")
(add-to-list 'auto-mode-alist '("\\.vue\\'" . vue-mode))
(flycheck-add-mode 'javascript-eslint 'vue-mode)
(flycheck-add-mode 'css-csslint 'vue-mode)
(flycheck-add-next-checker …)
```

**Comment by kriansa** [comment]
Hi @cpitclaudel ! Thanks for such a quick and detailed answer!

> I think css-stylelint would only run in those buffers in which it may run, which would be css-mode ones (the default) and web-mode ones (after you flycheck-add-mode it). Isn't that OK?

You are absolutely right. Although it shows up as a _next-checker_ for `eslint` when I use `flycheck-verify-setup`, it never runs - as I just tested. This solves my problem. Sorry for not testing it accurately before opening the issue.

> If not, the right way to go is to define a major mode for your file type. Look at define-derived-mode (it has great docs); something like this (untested):

This would be my go-to option if there was no other alternative. I'm new to Emacs but already amazed by the flexibility to solve problems with it. 😮 

Thank you Clément, I appreciate the effort and the pacience to dig into it!

**Comment by cpitclaudel** [comment]
> I'm new to Emacs

Welcome aboard! :ship:
