### ISSUE TITLE
Support for python 3.8 walrus operator

### ISSUE THREAD

**Issue by waqarsaleem** [flycheck/flycheck#1639]
python 3.8 incorporates [PEP 572 -- Assignment Expressions](https://www.python.org/dev/peps/pep-0572/), which results in the _walrus operator_, e.g. `(n := 42)`.

Flycheck version 31 does not recognize the walrus operator `:=` as a valid operator.

For example, using the walrus operator as in n`(n := 42)` results in
- `whitespace before ':' [E203]`
- `missing whitespace after ':' [E231]`.

**Comment by cpitclaudel** [comment]
Flycheck doesn't recognize Python code itself: it runs Python checkers like pylint, pyflakes, etc (use `C-c ! v` to see which).   You need to update the checkers and things will work fine.
