### ISSUE TITLE
Markdownlint-cli checker error parsing incorrect

### ISSUE THREAD

**Issue by bleggett** [flycheck/flycheck#1647]
## Checklist
- [X] I have checked existing issues for potential duplicates before creating this one.
- [X] I have read the [Troubleshooting guide][].

## Bug description
Get this error with the latest version of `markdown-cli`
![Screen Shot 2019-11-12 at 8 15 41 PM](https://user-images.githubusercontent.com/854255/68724418-6caa9b00-0589-11ea-9ff3-77bc211945fe.png)

## Steps to reproduce
1. `npm install -g markdown-cli`
2. Open a markdown file with a lint error
3. See error

## System configuration
```
Syntax checkers for buffer Contributing.md in markdown-mode:

First checker to run:

  markdown-markdownlint-cli
    - may enable:         yes
    - executable:         Found at /usr/local/bin/markdownlint
    - configuration file: Not found

Checkers that could run if selected:

  markdown-mdl  select
    - may enable:         yes
    - executable:         Found at /Users/blegget1/.rbenv/shims/mdl
    - configuration file: Not found

  proselint  select
    - may enable: yes
    - executable: Found at /usr/local/bin/proselint

Checkers that are compatible with this mode, but will not run until properly configured:

  textlint (disabled)
    - may enable:         Automatically disabled!
    - executable:         Not found
    - configuration file: Not found
    - textlint plugin:    @textlint/markdown

Flycheck Mode is enabled. Use SPC u C-c ! x to enable disabled checkers.

--------------------

Flycheck version: 32snapshot
Emacs version:    26.3
System:           x86_64-apple-darwin18.7.0
Window system:    mac

```

Emacs configuration:
- [ ] Plain Emacs / Custom configuration
- [ ] Spacemacs
- [X] Doom Emacs
- [ ] Other shared configuration

## Additional notes
This is almost certainly the offending change: https://github.com/igorshubovych/markdownlint-cli/commit/17b717ad9db1e2213db51811652a63496f7c7880

[Troubleshooting guide]:  https://www.flycheck.org/en/latest/user/troubleshooting.html

**Comment by cpitclaudel** [comment]
Fixed by https://github.com/flycheck/flycheck/pull/1648 (Github didn't pick up the magic words from the issue description). Thanks a lot!

**Comment by seagle0128** [comment]
The issue still exists in `flycheck-20191126.2142`. Does it work for you now?

**Comment by cpitclaudel** [comment]
Are you sure your mardownlint is up-to-date? See https://github.com/igorshubovych/markdownlint-cli/blob/c17b68f607587a9c3c006100533f7d208c1f3154/markdownlint.js#L138

**Comment by seagle0128** [comment]
@cpitclaudel I upgraded `markdownlint-cli` 0.21.0 and it does work. Thank you!

**Comment by czikus** [comment]
This problem seems to be back with 0.24.0. Some errors report the column, and some don't, e.g. :

```
test.md:22:2 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
test.md:27:4 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
test.md:28:15 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
test.md:33 MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 2; Actual: 3]
test.md:74 MD003/heading-style/header-style Heading style [Expected: setext; Actual: atx_closed]
```

**Comment by czikus** [comment]
Can this issue be re-opened or should I open a separate issue?
