### ISSUE TITLE
I wrote a flycheck checker for testdouble/standard (ruby)

### ISSUE THREAD

**Issue by julianrubisch** [flycheck/flycheck#1649]
Thank you for taking the time to improve Flycheck.

## Checklist
- [x] I have checked existing issues for potential duplicates before creating this one.

## Feature description
Allow standardrb to be used as a checker

## Additional context
I already wrote the checker here: https://github.com/julianrubisch/flycheck-standardrb
Since `standard` is mainly a wrapper around rubocop, this seems to work all right. I guess I just need some guidance on how it could be added into flycheck. Is it just a matter of forking, adding it to `flycheck.el` and proposing a PR or do you have some detailed process in place here?

**Comment by cpitclaudel** [comment]
> Is it just a matter of forking, adding it to flycheck.el and proposing a PR

That's right! Ideally with a few tests.

**Comment by julianrubisch** [comment]
Okay thanks! There’s just one point that’s a bit unclear here: the way standard works, it’s sort of mutually exclusive with rubocop because it uses an opinionated rubocop config that’s incompatible with the default one. 

How can this be handled? Read: it makes no sense to chain it after rubocop, it needs to run _instead_ of it.

**Comment by cpitclaudel** [comment]
In those cases, we'd merge the checker into FLycheck and keep rubocop the default; then if people disable rubocop they would get standard.

Alternatively, keeping standard as a separate package can increase its discoverability (you'd publish it on MELPA as a separate package, and users would know they need to enable it)

**Comment by julianrubisch** [comment]
Understood. Well I‘ll try to prepare a PR and wait for further feedback!

**Comment by fmdkdd** [comment]
We have a PR template for new checkers: https://github.com/flycheck/flycheck/blob/master/.github/PULL_REQUEST_TEMPLATE/new-checker.md

Unfortunately there's no convenient way to link to it via the Github UI!

**Comment by julianrubisch** [comment]
Thank you! Unfortunately, can’t get all tests passing. My ELISP ain’t good enough yet...

**Comment by julianrubisch** [comment]
I've added a PR here: https://github.com/flycheck/flycheck/pull/1658 ... I might need some help getting all tests passing, though...

**Comment by cpitclaudel** [comment]
Thanks, I finally looked into this.  There's one thing that confuses me.  StandardRB is incompatible with rubocop, and it seems to share its configuration and command line syntax and error patterns with rubocop.  Wouldn't it be enought o set the rubocop executable to standardrb to use it? Do we need a second checker definition?

**Comment by cpitclaudel** [comment]
Sorry, that message should have gone to the PR.

**Comment by cpitclaudel** [comment]
We're all done here :) The new checker was merged in #1658.
