### ISSUE TITLE
Added buplicate checkers as next-checker

### ISSUE THREAD

**Issue by conao3** [flycheck/flycheck#1661]
## Checklist
- [x] I have checked existing issues for potential duplicates before creating this one.
- [x] I have read the [Troubleshooting guide][].

## Bug description
Duplicate next-checker added.

## Steps to reproduce
1. Add `flycheck-package-setup` to `flycheck-mode-hook`.
2. Turn on/off `flycheck-mode` multi times
3. Duplicate next-checker added.

## Expected behavior
Duplicate next-checker not added.

## Screenshots
None.

## System configuration
```
Syntax checkers for buffer flycheck-indent.el in emacs-lisp-mode:

First checker to run:

  emacs-lisp
    - may enable:    yes
    - predicate:     t
    - executable:    Found at /home/conao/.local/bin/emacs
    - next checkers: emacs-lisp-checkdoc, emacs-lisp-package, emacs-lisp-package, emacs-lisp-package, indent-elisp, emacs-lisp-package, indent-elisp

Checkers that may run as part of the first checker's chain:

  emacs-lisp-checkdoc
    - may enable:    yes
    - executable:    Found at /home/conao/.local/bin/emacs
    - next checkers: emacs-lisp-package, emacs-lisp-package, emacs-lisp-package, emacs-lisp-package, indent-elisp

  emacs-lisp-package
    - may enable:    yes
    - next checkers: indent-elisp

  indent-elisp
    - may enable: yes
    - executable: Found at /home/conao/.local/bin/emacs

Checkers that are compatible with this mode, but will not run until properly configured:

  emacs-lisp-elsa
    - may enable: yes
    - predicate:  nil
    - executable: Found at /home/conao/.local/tools/cask/bin/cask

Flycheck Mode is enabled.  Use C-u C-c ! x to enable disabled
checkers.

--------------------

Flycheck version: 32snapshot (package: 20191125.1821)
Emacs version:    26.3
System:           x86_64-pc-linux-gnu
Window system:    x
```

Emacs configuration:
- [x] Plain Emacs / Custom configuration
- [ ] Spacemacs
- [ ] Doom Emacs
- [ ] Other shared configuration

## Additional notes
My customization for `flycheck-package` is below using [leaf](https://github.com/conao3/leaf.el)

``` emacs-lisp
(leaf flycheck-package
  :ensure t
  :hook ((flycheck-mode-hook . flycheck-package-setup)))
```

[Troubleshooting guide]:  https://www.flycheck.org/en/latest/user/troubleshooting.html

**Comment by fmdkdd** [comment]
But what is `flycheck-package-setup`?

The hook calls that function every time flycheck-mode is activated, which is intended.

**Comment by conao3** [comment]
flycheck-package developed by @purcell and placed [here](https://github.com/purcell/flycheck-package)
And `flycheck-package-setup` defined [here](https://github.com/purcell/flycheck-package/blob/d76e04009f2548581fc9e9a84f79f1a3112f1096/flycheck-package.el#L64-L71)

**Comment by purcell** [comment]
Yes, don't call `flycheck-package-setup` multiple times.

**Comment by conao3** [comment]
I misunderstanded `flycheck-package` installation code.
I guessed that this package was also set up with hooks, as other flycheck integrating packages set it up with hooks.
@purcell recommended below snippet. I fix my init.el. Sorry, your noise.
```emacs-lisp
(eval-after-load 'flycheck
  '(flycheck-package-setup))
```
