### ISSUE TITLE
Trouble running python flake8 from poetry virtual environment, after running "poetry shell"

### ISSUE THREAD

**Issue by hartzell** [flycheck/flycheck#1667]
## Checklist
- [x] I have searched existing issues and StackOverflow for solutions.
- [x] I have read the [Flycheck manual][].
- [x] I have read the [Troubleshooting Guide][].
- [x] I have checked my issue has not been reported yet.

## Problem description

I have a python virtual environment set up by poetry.  I've installed, via poetry, the python flake8 bits and e.g. `flake8 .` works.

`which` shows that I'm running the commands from the virtual environment

```
(.venv) (alice)[18:07:20]nvta-homework>>which python
/Users/hartzell/tmp/wemake-python-package/.venv/bin/python
(.venv) (alice)[18:07:31]nvta-homework>>which flake8
/Users/hartzell/tmp/wemake-python-package/.venv/bin/flake8
(.venv) (alice)[18:07:34]nvta-homework>>
```

When I start emacs from within that shell, e.g. `emacs foo/main.py & disown`

flake8 problems are highlighted, and when I run `C-c ! v` I get:

```
Syntax checkers for buffer main.py in python-mode:

First checker to run:

  python-flake8
    - may enable:         yes
    - executable:         Found at /Users/hartzell/tmp/wemake-python-package/.venv/bin/python3
    - configuration file: Not found
    - `flake8' module:    Found at "/Users/hartzell/tmp/wemake-python-package/.venv/lib/python3.7/site-packages/flake8/__init__.py"
```

as soon as I change anything in the file, causing flycheck to run flake8, I get this:

```
Suspicious state from syntax checker python-flake8: Flycheck checker python-flake8 returned non-zero exit code 1, but its output contained no errors: Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 201, in run_module
    mod_name, mod_spec, code = _get_module_details(mod_name)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 136, in _get_module_details
    raise error("No module named %s" % mod_name)
ImportError: No module named flake8

Try installing a more recent version of python-flake8, and please open a bug report if the issue persists in the latest release.  Thanks!
```

and if I run `C-c ! v` again, I see:

```Syntax checkers for buffer main.py in python-mode:

First checker to run:

  python-flake8
    - may enable:         yes
    - executable:         Found at /usr/local/bin/python3
    - configuration file: Not found
    - `flake8' module:    Missing
```

## Steps to reproduce

I don't have simple steps, I'm not sure what part of my configuration is tripping me up.

I'm hoping that there's a simple, obvious thing that I've overlooked and/or are screwing up, but if not I can try to come up with something that's reproducible.

My emacs dotfiles are at https://github.com/hartzell/.emacs.d

## Expected behavior

I'd like the flake8 checker to consistently use the flake8 from my virtual environment.

## System configuration

Here's the output when the buffer is initial displayed:

```
Syntax checkers for buffer main.py in python-mode:

First checker to run:

  python-flake8
    - may enable:         yes
    - executable:         Found at /Users/hartzell/tmp/wemake-python-package/.venv/bin/python3
    - configuration file: Not found
    - `flake8' module:    Found at "/Users/hartzell/tmp/wemake-python-package/.venv/lib/python3.7/site-packages/flake8/__init__.py"

Checkers that could run if selected:

  python-pycompile  select
    - may enable: yes
    - executable: Found at /Users/hartzell/tmp/wemake-python-package/.venv/bin/python3

  python-mypy  select
    - may enable:         yes
    - predicate:          t
    - executable:         Found at /Users/hartzell/tmp/wemake-python-package/.venv/bin/mypy
    - configuration file: Not found
    - next checkers:      python-flake8

Checkers that are compatible with this mode, but will not run until properly configured:

  python-pylint (disabled)
    - may enable:         Automatically disabled!
    - executable:         Found at /Users/hartzell/tmp/wemake-python-package/.venv/bin/python3
    - configuration file: Not found
    - `pylint' module:    Missing

Flycheck Mode is enabled.  Use C-u C-c ! x to enable disabled
checkers.

--------------------

Flycheck version: 32snapshot
Emacs version:    26.3
System:           x86_64-apple-darwin14.5.0
Window system:    ns
```

and here's the output after changing something in the buffer (causing the flake8 failure):

```
Syntax checkers for buffer main.py in python-mode:

First checker to run:

  python-flake8
    - may enable:         yes
    - executable:         Found at /usr/local/bin/python3
    - configuration file: Not found
    - `flake8' module:    Missing

Checkers that could run if selected:

  python-pycompile  select
    - may enable: yes
    - executable: Found at /usr/local/bin/python3

  python-mypy  select
    - may enable:         yes
    - predicate:          t
    - executable:         Found at /Users/hartzell/tmp/wemake-python-package/.venv/bin/mypy
    - configuration file: Not found
    - next checkers:      python-flake8

Checkers that are compatible with this mode, but will not run until properly configured:

  python-pylint (disabled)
    - may enable:         Automatically disabled!
    - executable:         Found at /usr/local/bin/python3
    - configuration file: Not found
    - `pylint' module:    Missing

Flycheck Mode is enabled.  Use C-u C-c ! x to enable disabled
checkers.

--------------------

Flycheck version: 32snapshot
Emacs version:    26.3
System:           x86_64-apple-darwin14.5.0
Window system:    ns

```

Emacs configuration:
- [x] Plain Emacs / Custom configuration
- [ ] Spacemacs
- [ ] Doom Emacs
- [ ] Other shared configuration

My emacs dotfiles are at https://github.com/hartzell/.emacs.d

## Additional notes

[Flycheck manual]:  https://www.flycheck.org/en/latest/user/troubleshooting.html
[Troubleshooting guide]:  https://www.flycheck.org/en/latest/user/troubleshooting.html

**Comment by cpitclaudel** [comment]
How puzzling. Sorry for the trouble!

Can you check what `M-: (flycheck-find-checker-executable 'python-flake8)` returns both before and after making changes to the file?  What about `(executable-find "python3")`?

**Comment by hartzell** [comment]
- flycheck-find-checker-executable
  - Before:
    /usr/local/bin/python3
  - After:
     /usr/local/bin/python3

- executable-find
  - Before:
      "/Users/hartzell/tmp/wemake-python-package/.venv/bin/python3"
  - After:
      /usr/local/bin/python3

**Comment by hartzell** [comment]
I have a wacky hypothesis that the first time flycheck is run, it's in the context of where I opened the file, which is the top of the python project directory (setup.cfg and pyproject.toml and *etc*...) and/but the later times it's somehow just running on the buffer, or in the file's directory or ....

**Comment by hartzell** [comment]
> I have a wacky hypothesis

Well, perhaps this is counter evidence: if I cd into the subdirectory and just run

```
emacs main.py
```

then I see the same behaviour (buffer seems correctly flake8-ed, changes that run flycheck lead to errors).

**Comment by hartzell** [comment]
Does flycheck run when the file is first opened or is something else running flake8 for me?

**Comment by hartzell** [comment]
Looks like it's an interaction with [exec-path-from-shell](https://github.com/purcell/exec-path-from-shell).

Commenting out my `use-package` call that enables it makes the flake8 stuff work.  I had it in there for a reason, but I'll cross that bridge when I remember what it was.

"You are in a maze of twisty little passages, all alike..."
