### ISSUE TITLE
global-flycheck-mode not working on spacemacs

### ISSUE THREAD

**Issue by zendevil** [flycheck/flycheck#1678]
flycheck-mode in individual buffers works. When doing ```M-x global-flycheck-mode```, the disabling works, but when enabling, it says enabled, but isn't really.

**Comment by fmdkdd** [comment]
Sorry, but without clear reproducing steps, it's hard to understand what exactly is wrong.  Please follow the [issue template](https://github.com/flycheck/flycheck/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) and reopen the bug.
