### ISSUE TITLE
Create many `flycheck_???.elc` file unexpectly.

### ISSUE THREAD

**Issue by zw963** [flycheck/flycheck#1689]
Create many `flycheck_???.elc` file since recent update.

![image](https://user-images.githubusercontent.com/549126/76377522-10fcec80-6386-11ea-8cdb-ee093c5f7838.png)

I never update my  flycheck config since this update.

```cl
(require 'flycheck)

(global-flycheck-mode)

(setq-default flycheck-disabled-checkers '(yaml-yamllint))
```

In fact, because i update to use emacs 27 same time, so, 
i am not sure if update emacs 27 cause this issue, but, anyway,
it anoise me alot, thank you.

Following is the git hash version which i used.

08345d38 - (HEAD -> master, origin/master, origin/HEAD) Merge pull request #1526 from xcambar/ember-template-lint(2 weeks ago,fmdkdd)

**Comment by cpitclaudel** [comment]
Thanks for the report.  Do you have a recipe to reproduce the issue?

**Comment by zw963** [comment]
Yes, it pretty easy to reproduce:

1.  emacs -Q ruby.el
we assume one function was defined in ruby.el
```
(defun hash3 ()
  (when (or (yas-ruby-insert-new-hash-p)
            (and (yas-rails-p) (yas-rails-not-routes-p)))
    (ruby-new-hash))
  (concat (unless (looking-back "{") ",") "\n"))
```

2. add load_path, and run following code in minibuffer
```el
(require 'flycheck)

(global-flycheck-mode)
```
3.  change above hash3 function to hash4

4. We get a new elc file `flycheck_ruby.elc`, created.

**Comment by zw963** [comment]
Following is my generated elc file content:

```
;ELC\0\0\0
;;; Compiled
;;; in Emacs version 27.0.90
;;; with all optimizations.

;;; This file uses dynamic docstrings, first added in Emacs 19.29.

;;; This file does not contain utf-8 non-ASCII characters,
;;; and so can be loaded in Emacs versions earlier than 23.

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;


(defalias 'hash4 #[nil "\300 \204\0\301 \203\0\302 \203\0\303 \210\304\305!?\205\0\306\307P\207" [yas-ruby-insert-new-hash-p yas-rails-p yas-rails-not-routes-p ruby-new-hash looking-back "{" "," "\n"] 2])
(provide 'ruby)
```

**Comment by cpitclaudel** [comment]
Thanks for your patience.  I think https://github.com/flycheck/flycheck/pull/1694 fixed this issue.  Can you try it?
