### ISSUE TITLE
Broken literate-haskell test

### ISSUE THREAD

**Issue by cpitclaudel** [flycheck/flycheck#1736]
@fmdkk, any idea why the Literate Haskell test is broken? I'm looking at https://travis-ci.org/github/flycheck/flycheck/builds/676362396 and the `(flycheck-get-checker-for-buffer)` test is failing, but I can't reproduce this locally.  I think you understand the testing setup better than I do ^^

**Comment by fmdkdd** [comment]
Sorry for the delay.   That error message is not super helpful.  Looks like you got it in #1735!

**Comment by cpitclaudel** [comment]
Yes I did, sorry for not closing this!
