### ISSUE TITLE
Exclude files/directories from reporting errors/warnings

### ISSUE THREAD

**Issue by zoechi** [flycheck/flycheck#1745]
## Checklist
- [ x] I have checked existing issues for potential duplicates before creating this one.

## Feature description

I was looking for a way to disable flycheck for dependencies, for example when I look up function parameters or otherwise investigate 3r-party dependencies.
A preferred way would be to provide a list of directories that should be ignored completely. I don't want to disable LSP for example, because I still want code navigation.

Similar to #723

**Comment by cpitclaudel** [comment]
Thanks. I think we could start with a custom function for this, and if there's enough interest will move it into Flycheck.

What about this?

```elisp
(defvar my-excluded-directory-regexps
  '(".git/"))

(defun my-flycheck-may-check-automatically (&rest _conditions)
  (or (null buffer-file-name)
      (let ((bufname (file-truename buffer-file-name)))
        (not (seq-some (lambda (re) (string-match-p re bufname))
                       my-excluded-directory-regexps)))))

(advice-add 'flycheck-may-check-automatically
            :after-while #'my-flycheck-may-check-automatically)
```

**Comment by cpitclaudel** [comment]
Gentle ping; does the snippet above work for you?

**Comment by zoechi** [comment]
@cpitclaudel  Thanks a lot for the reminder. 
I somehow missed your comment above.
I'll check it out and report back ASAP.

**Comment by zoechi** [comment]
Your suggestion works in Elisp, but in lsp-mode (Dart, TypeScript/Node.js) these settings do not seem to have any effect.


Would this support globs like `**/node_modules/`?
(I only tried with full path yet)

**Comment by cpitclaudel** [comment]
No sure about lsp; you'd have to ask there.  This supports regexps, not globs, so `.*/node_modules/`

**Comment by cpitclaudel** [comment]
Anything more needed here?

**Comment by zoechi** [comment]
I see. Thanks for the update.
