### ISSUE TITLE
Release Flycheck 32

### ISSUE THREAD

**Issue by cpitclaudel** [flycheck/flycheck#1754]
We've accumulated a huge list of improvements, added many new checkers, and fixed many long-standing issues since Flycheck 31, way back in 2017.  I think we are ready to release Flycheck 32! (and we already have a nice batch of improvements waiting for [Flycheck 33](https://github.com/flycheck/flycheck/pulls?q=is%3Aopen+is%3Apr+milestone%3A%22Flycheck+33%22).

Let's give ourselves a month of testing and bug-fixing, and aim for a release in early June.  If you find bugs in newly added functionality, please report it and add the Flycheck 32 milestone.

Bug fixes and documentation improvements can go to `flycheck-32`; we'll release from there.  New features can still be merged to `master`.

CC @flycheck/contributors.

**Comment by cpitclaudel** [comment]
I updated the Flycheck/Flymake comparison to mention the latest updates, in preparation for the release.

**Comment by rye** [comment]
Is there any strong aversion at this point to moving forward with the release? It appears that this is the only outstanding issue in the [Flycheck 32](https://github.com/flycheck/flycheck/milestone/12) milestone, which is why I ask.

I'll note that `lsp-mode`—which depends on `flycheck`—[is currently broken](https://github.com/emacs-lsp/lsp-mode/issues/1480) with the `melpa-stable` (`31`) version of `flycheck`; if nothing is standing in the way, I'm sure a new release would be much appreciated by us `melpa-stable` users. 🙂

I'd be happy to help in any way I can!

**Comment by yyoncho** [comment]
Ping here - at lsp-mode side we are using the new features(e. g. the ranges) and the result is that lsp-mode from melpa stable does not work with flycheck.

**Comment by cpitclaudel** [comment]
Sorry folks, like has gotten a bit crazy for me lately with work.  But I think Flycheck is essentially ready for release 32; it's just a matter of tagging and tarball-ing. What would be great is for someone to check that the process described in doc/contributor/maintaining.rst is up to date and the makefile is happy, and then I can try to run it soon.

**Comment by fmdkdd** [comment]
Last time I used the release script, it was pretty smooth sailing.

**Comment by brettlangdon** [comment]
Any updates on the release of 32?

**Comment by cowboyd** [comment]
@cpitclaudel Pretty much everybody is using snapshot releases anyway at this point. Is there anything more to be done than tag it? I'm happy to help in any way to get this over the finish line

**Comment by zbroyar** [comment]
If I have the flycheck-31 installed from the melpa-stable what's the best way to upgrade it to the latest version?

**Comment by mavit** [comment]
> What would be great is for someone to check that the process described in doc/contributor/maintaining.rst is up to date and the makefile is happy, and then I can try to run it soon.

It says, “In doubt just make a release.  We aim to release early and frequently”.  I think we can agree that that part is no longer in-line with reality :-)

In any case, I tried to follow the release process, and the instructions seem clear.  The script worked right up until the point where it tried to push to GitHub (which I don’t have permission to do, not being a maintainer).

**Comment by zbroyar** [comment]
For anyone interested:

I solved the flycheck errors problem by getting the latest version of the flycheck from github and simply replacing flycheck-ert.el and flycheck.el in my  ~/.emacs.d/elpa/flycheck-31 with git versions.

I know, it's dirty but it works.

**Comment by timwoj** [comment]
Ping on this issue. Is there any reason someone can't just push the buttons for this? It's been almost 4.5 years since the last release, and fixing the stable version for us lsp users would be nice.

**Comment by jordigh** [comment]
Another ping on this issue. Is flycheck unmaintained? No releases in 5 years seems like it's unmaintained. Do we need someone else to step in and take the lead?

**Comment by cpitclaudel** [comment]
We would actually live to get more volunteers and help with maintenance.  It's not unmaintained, in the sense that I'll fix any significant breakage if it pops up, and I'd love to welcome new leadership, but it's true that I have very little time. 

As for the release, it just hasn't been a priority for either of the maintainers, that's it.

**Comment by jordigh** [comment]
Thank you. I needed this fix, and now I can get it on melpa-stable: https://github.com/flycheck/flycheck/pull/1588

Just installed from melpa-stable and got my fix, yay.
