### ISSUE TITLE
Can't load package when edit golang code in org special edit mode

### ISSUE THREAD

**Issue by RaynorGu** [flycheck/flycheck#1782]
Emacs Version:  26.3(Spacemacs, layer go)
OS: Ubuntu and macOS
when editing golang code in org special edit mode, such error occurs:
![image](https://user-images.githubusercontent.com/7893714/82547199-ea301300-9b8b-11ea-975e-d7beea9288a3.png)

**Comment by suzuiyuegjy** [comment]
And when editing in normal go src file, everything is ok

**Comment by suzuiyuegjy** [comment]
![image](https://user-images.githubusercontent.com/7893714/82727914-fa78f700-9d1f-11ea-80da-650331ff04fc.png)
This change corrects the issue.

**Comment by cpitclaudel** [comment]
Hi there,

Sorry for the delay.  Thanks a lot for reporting the problem, and identifying the fix! I think it looks very reasonable.  Would you like to make a pull request?

**Comment by suzuiyuegjy** [comment]
@cpitclaudel ok, I would make a pr today
