### ISSUE TITLE
Adding support for Eldev

### ISSUE THREAD

**Issue by doublep** [flycheck/flycheck#1783]
This is not really a bug or a feature request, rather a question "how should I do X related to Flycheck in the best way?".

I want to integrate [Eldev](https://github.com/doublep/eldev) with Flycheck, so that packages that use Eldev automatically get full support (with dependencies etc.) from Flycheck. There already exists `flycheck-cask` for Cask, so why not add a small package for Eldev support? It would do practically the same thing, just for a different project manager.

Basically, as I understand, Elisp check works this way: internal child Emacs process is spawned, optionally with customized load path, and Flycheck tries to compile given `.el` file in it. For Cask, support package overrides variables like `flycheck-emacs-lisp-package-user-dir` with values suitable for the Cask-based project, so that declared dependencies are automatically used by Flycheck.

For Eldev I envision a better approach. Eldev has a command that launches Emacs with package dependencies in load path — if necessary, installing them first. Flycheck could use this command instead of lauching Emacs directly to achieve best possible integration with Eldev.

I managed to achieve this in a hackish way already:

    (defadvice flycheck-start-command-checker (around use-eldev activate)
      (if (and (eq checker 'emacs-lisp)
               (or (locate-dominating-file (buffer-file-name) "Eldev")
                   (locate-dominating-file (buffer-file-name) "Eldev-local")))
          (let ((original-command (flycheck-checker-get 'emacs-lisp 'command)))
            (setf (flycheck-checker-get 'emacs-lisp 'command)
                  `(,(executable-find "eldev")
                    ;; Workaround, will probably go into Eldev itself.
                    "--setup"
                    ,(prin1-to-string
                      '(advice-add #'eldev--package-dir-info :around
                                   (lambda (original)
                                     (eldev-advised (#'insert-file-contents :around (lambda (original &rest arguments)
                                                                                      (ignore-errors (apply original arguments))))
                                       (funcall original)))))
                    "emacs" "--" (eval flycheck-emacs-args)
                    (option "--eval" flycheck-emacs-lisp-check-declare nil
                            flycheck-option-emacs-lisp-check-declare)
                    "--eval" (eval (flycheck-emacs-lisp-bytecomp-config-form))
                    "--eval" (eval flycheck-emacs-lisp-check-form)
                    "--"
                    source-inplace))
            (unwind-protect
                ad-do-it
              (setf (flycheck-checker-get 'emacs-lisp 'command) original-command)))
        ad-do-it))

Basically, what I'm doing here is replacing `command` property on `emacs-lisp` checker. Everything else works without changes (there are a few wrinkles to solve later  e.g. in case file `Eldev` is corrupt). Changes to the command line I make are:

* replace the command itself (`/PATH/TO/emacs`) with `/PATH/TO/eldev` `[temp-workaround]` `emacs`;
* delete all `load-path` and `package-user-dir` manipulation.

Basically, my question is: is there or can there be added a better way to change the command executed by certain checker? Would the outlined way to integrate Eldev be acceptable or should I do something completely else?

**Comment by cpitclaudel** [comment]
Thanks for the question! Transforming the command is quite reasonable.  I think you should be able to make it work with `flycheck-command-wrapper-function` instead of advice, though; let me know if you need help with that.

**Comment by doublep** [comment]
Thank you, looks promising. However if I'm to modify a command line, I have to assume its structure, because modification is not trivial. Is that fine? Can assume that current command line used for checking Elisp will not change much?

**Comment by cpitclaudel** [comment]
Ah, I assumed you would just prefix the command with eldev.  If not, you can replace it wholesale with your own command (though at that point you might be better of with a separate checker)

**Comment by doublep** [comment]
A separate checker hardly would be a good idea, since I want to check Elisp files with normal Elisp syntax. Eldev is only their to provide dependencies, i.e. handle things like `;; Package-Requires: ((dash "2.12.1") (pkg-info "0.4") ...`. So, I don't want to duplicate Elisp checker, just tweak the issued command and working directory.

Anyway, I think I will manage from now on. There is an organizational question though: should I keep this on my account or would it be accepted to Flycheck organization? I see there are quite a few packages, and most importantly `flycheck-cask`, which is basically the same as what I want to write, only for a different project manager.

**Comment by cpitclaudel** [comment]
Happy to add you to the flycheck org if you'd like :) Otherwise your account can be good too.  In any case, we'd love a PR to add you to the list of third-party checkers!)

Thanks for your work :)  I will look at eldev!

**Comment by doublep** [comment]
Let me write something first ;)

I ran into another problem. Let's say in project root there is a directory `tests`. When Flycheck tries to compile a file in this directory, it issues a command to the tune of

    emacs ... --eval BYTE-COMPILER-FORM ... -- /PATH/project/tests/foo.el

For the way Eldev works, everything must be executed from `/PATH/project`, i.e. from the parent directory of `foo.el`. I achieved this by advising function `flycheck-compute-working-directory` in this way:

    (defun flycheck-eldev--compute-working-directory (checker)
      (when (eq checker 'emacs-lisp)
        (flycheck-eldev-find-root)))
    (advice-add #'flycheck-compute-working-directory :before-until #'flycheck-eldev--compute-working-directory)

I.e. for non-Eldev files it uses buffer file's directory as before.

However, Emacs reports errors without a path, something like `foo.el:10:5: Error: ...`. So, when `flycheck-fill-and-expand-error-file-names` recombines filename and directory it produces `/PATH/project/foo.el` instead of `/PATH/project/tests/foo.el` and of course error overlay is not created at the appropriate place then.

I'm not exactly sure how to solve this.

**Comment by cpitclaudel** [comment]
Instead of advising working-directory, try changing the :working-directory of the checker.   I'm 60% sure that this will be enough (because flycheck-emacs-lisp-bytecomp-config-form uses default-directory)

**Comment by doublep** [comment]
> Instead of advising working-directory, try changing the :working-directory of the checker.

It gives the same result. I think it is better to depend on advising since I already advise one other function. This also prevents a potential conflict with another package doing the same (advices can stack, but changing a property would not).

Anyway, I wrote the first version: [flycheck-eldev](https://github.com/doublep/flycheck-eldev). It doesn't work with the three-year-old stable version 31, so I declared 32 as a requirement. I see there is already an issue to finally release the version.

Turned out to be quite a bit more complicated than flycheck-cask, but it certainly gives better integration. Basically, as long as you have Eldev installed, you can just `git clone` any Eldev-based project, open any of its files in Emacs and Flycheck will already do what's correct, maybe after some ten seconds of downloading dependencies and initializing the checkout in the background.

If this looks acceptable in general, I can transfer the repository to this organisation.

**Comment by cpitclaudel** [comment]
> It gives the same result.

Hmm, that's not great.  Could you open a bug report for this, at least as a reminder to check what's going on?

> (advices can stack, but changing a property would not).

I think you can add-function on a place, so that should stack as well.  But I think your approach is quite good.  I've sent you an invite to join the flycheck org; you should be able to create the repo!  Welcome aboard :hugs:

**Comment by doublep** [comment]
Created an issue. Notoriously difficult to explain it.

About the new repository: can I submit a request to MELPA to package it, or are there some more steps to do first?

**Comment by cpitclaudel** [comment]
Thanks a lot

> About the new repository: can I submit a request to MELPA to package it, or are there some more steps to do first?

I think you're all set; sending an issue to MELPA is the next step :)

**Comment by doublep** [comment]
One last thing: can you please enable the new repository on Travis CI? I pushed file `.travis.yml`, but build is not triggered, so I guess repository is not activated.

**Comment by cpitclaudel** [comment]
Done, I think

**Comment by doublep** [comment]
Works, thank you. Guess this issue can be closed now.
