### ISSUE TITLE
Error while killing emacs

### ISSUE THREAD

**Issue by seagle0128** [flycheck/flycheck#1794]
- GNU Emacs 27.0.91
- macOS Catalina
- ivy-mode

All packages are the latest. The configurations are [Centaur Emacs](https://github.com/seagle0128/.emacs.d).

```elisp
Debugger entered--Lisp error: (error "Selecting deleted buffer")
  flycheck-global-teardown()
  kill-emacs()
  save-buffers-kill-emacs(nil)
  save-buffers-kill-terminal(nil)
  funcall-interactively(save-buffers-kill-terminal nil)
  call-interactively(save-buffers-kill-terminal nil nil)
  #f(compiled-function (cmd &optional record-flag keys special) "Execute CMD as an editor command.\nCMD must be a symbol that satisfies the `commandp' predicate.\nOptional second arg RECORD-FLAG non-nil\nmeans unconditionally put this command in the variable `command-history'.\nOtherwise, that is done only if an arg is read using the minibuffer.\nThe argument KEYS specifies the value to use instead of (this-command-keys)\nwhen reading the arguments; if it is nil, (this-command-keys) is used.\nThe argument SPECIAL, if non-nil, means that this command is executing\na special event, so ignore the prefix argument and don't clear it." #<bytecode 0x437529bb>)(save-buffers-kill-terminal nil nil nil)
  ad-Advice-command-execute(#f(compiled-function (cmd &optional record-flag keys special) "Execute CMD as an editor command.\nCMD must be a symbol that satisfies the `commandp' predicate.\nOptional second arg RECORD-FLAG non-nil\nmeans unconditionally put this command in the variable `command-history'.\nOtherwise, that is done only if an arg is read using the minibuffer.\nThe argument KEYS specifies the value to use instead of (this-command-keys)\nwhen reading the arguments; if it is nil, (this-command-keys) is used.\nThe argument SPECIAL, if non-nil, means that this command is executing\na special event, so ignore the prefix argument and don't clear it." #<bytecode 0x437529bb>) save-buffers-kill-terminal)
  apply(ad-Advice-command-execute #f(compiled-function (cmd &optional record-flag keys special) "Execute CMD as an editor command.\nCMD must be a symbol that satisfies the `commandp' predicate.\nOptional second arg RECORD-FLAG non-nil\nmeans unconditionally put this command in the variable `command-history'.\nOtherwise, that is done only if an arg is read using the minibuffer.\nThe argument KEYS specifies the value to use instead of (this-command-keys)\nwhen reading the arguments; if it is nil, (this-command-keys) is used.\nThe argument SPECIAL, if non-nil, means that this command is executing\na special event, so ignore the prefix argument and don't clear it." #<bytecode 0x437529bb>) save-buffers-kill-terminal)
  command-execute(save-buffers-kill-terminal)
```

**Comment by cpitclaudel** [comment]
Ouch, thanks for the report. Is this with Centaur Emacs out of the box? What files do you open? Does it happen with emacs -Q? Can you give a recipe?

**Comment by seagle0128** [comment]
It appears in both Centaur and vanilla Emacs. Honestly I don't know how to reproduce. It seems related to ivy, since the error message is printed by `ivy-read`, but the backtrace is about flycheck.

https://github.com/abo-abo/swiper/blob/387390b1026b7087bbb4df2e6b778ebe5d9e1b8d/ivy.el#L2143

**Comment by cpitclaudel** [comment]
Any chance you could try to see which part of your config causes it?

You could also add this to your .emacs, and see if that raises an error when you kill Emacs:

```
(advice-add #'flycheck-global-teardown :before
            (lambda (&rest args)
              (dolist (buffer (buffer-list))
                (unless (buffer-live-p buffer)
                  (error "Deleted buffer in buffer list: %S" buffer)))))
```

**Comment by doublep** [comment]
Looks rather like a buffer gets deleted in the process of shutting down. I.e. `(buffer-list)` returns buffers `X` and `X (some auxiliary stuff)` and while Flycheck shuts itselft down in buffer `X`, it kills the second auxiliary buffer in process. And then it tries to select it on the next loop iteration and fails.

**Comment by doublep** [comment]
Maybe that `delete-process` during interruption of ongoing checks can kill some buffers, like process output?

**Comment by cpitclaudel** [comment]
Ah, great point @doublep , that does sound possible.  Do you want to prepare a patch that just wraps the body of that loop in `when (buffer-live-p …)`?

**Comment by doublep** [comment]
Not really, I think it's easier if someone who can just commit immediately does it.

**Comment by cpitclaudel** [comment]
We don't usually commit directly — we record all changes in PRs and try to have another maintainer review.  Also, it gives proper credit.  But I can take care of making the PR if you want.

**Comment by czikus** [comment]
I'm experiencing the same issue. Anything I can do to help?

**Comment by cpitclaudel** [comment]
Hm, not sure why that PR was never merged.  Do you have the issue if you use the branch at https://github.com/flycheck/flycheck/pull/1796 ?

**Comment by czikus** [comment]
I can't test that right now, but since my backtrace indicates a problem in that same function, I can safely assume it will help.
