### ISSUE TITLE
Conda 4.8.3 Windows and python vs python3

### ISSUE THREAD

**Issue by dsyzling** [flycheck/flycheck#1797]
## Checklist
- [ x] I have checked existing issues for potential duplicates before creating this one.

## Feature description
Upgrading to Conda version 4.8.3 recently has exposed an issue regarding the migration to python 3 and how long will the binary interpreter should be referred to as python3 or just python. Creating a virtual environment with Conda under Linux python3 is symlinked to python (which is python 3.x). However under Windows the environment is created with just a python.exe interpreter. This means flycheck fails to configure flake8 and other linters/checkers because it can't find and execute the python interpreter. As you know this is currently defined as a fixed string in the checker definition. 

I've raised the issue with the Conda team (link below), I wanted to get their view as to whether they would choose to remove the symlink for linux for consistency. Judging by a similar discussion around pip3 vs pip some seemed to favour removing pip3 for plain pip as the official migration to python 3 has been completed. Irrespective there is an inconsistency between Windows and Linux for virtual environments. 
https://github.com/conda/conda/issues/9985

As a work around on Windows I can copy python.exe to python3.exe, but of course this has to be done for all environments created. Flycheck users will of course experience issues of checkers not being configured along with the confusion. 

Should the interpreter be configurable - i.e. a simple flycheck python interpreter custom variable that can then be swapped by the user so that python can be used instead of python3 if required going forward? I wondered if this would be sufficient rather than a more complicated solution?

**Comment by cpitclaudel** [comment]
> Should the interpreter be configurable - i.e. a simple flycheck python interpreter custom variable that can then be swapped by the user so that python can be used instead of python3 if required going forward?

Are you looking for `flycheck-python-pylint-executable` and the related variables for flake8, etc?

**Comment by dsyzling** [comment]
@cpitclaudel Yes I think I am :-)  Sorry for the confusion, I went through the source and saw the definition flycheck-define-checker python-flake8 and didn't realise there was a set of configuration variables to adjust the executable.
