### ISSUE TITLE
Error explainer incorrectly writing text to the source code buffer

### ISSUE THREAD

**Issue by danielmartin** [flycheck/flycheck#1800]
I'm observing some strange behaviour in a recent version of Flycheck when using the `clang-tidy` error explainer functionality in `lsp-mode.el`.

The problem I see is that the error explainer is writing text to the source code buffer. Inspecting recent PRs, I focused on this one: https://github.com/flycheck/flycheck/pull/1774. Here's what's happening:

1. Imagine an `:error-explainer` lambda that returns a string (https://github.com/flycheck/flycheck/pull/1774/files#diff-374cdd9563b826c712b1dc6a373a0bc1R2046). 

2. Flycheck gets the string from my error explainer at https://github.com/flycheck/flycheck/pull/1774/files#diff-374cdd9563b826c712b1dc6a373a0bc1R5319.

3. Flycheck then checks the type of the explanation it got. As it is a string, it evals this line: https://github.com/flycheck/flycheck/pull/1774/files#diff-374cdd9563b826c712b1dc6a373a0bc1R5614, which is using `insert`. This is basically inserting text in the current buffer, which is the source code buffer.

Is this expected behaviour, or I am missing something? Did you mean to print to the standard output instead (with `print` maybe)? To give you more context, our error explainer is a little bit more complex than the usual ones. It returns a "Loading..." string while we fetch a webpage asynchronously and update the error explainer buffer with a rendered webpage. See https://github.com/emacs-lsp/lsp-mode/blob/master/lsp-cpp.el#L137

Thank you.

**Comment by cpitclaudel** [comment]
Ouch, thanks very much.  It's a silly bug :/ Sorry for breaking your code.

That `insert` call should be wrapped in a `with-current-buffer`  (`print` would lose text properties, I think).  Do you want to make a PR, or should I?

**Comment by cpitclaudel** [comment]
Thanks a lot for the clear explanations, too.
