### ISSUE TITLE
make flycheck properly tramp-ignorant

### ISSUE THREAD

**Issue by jwalt** [flycheck/flycheck#181]
This is related to bug #54.

There is just one thing that prevents local checks to succeed. By 'local checks' I mean those that create local temporary files in /tmp via `source` instead of remote files via `source-inplace`. In other words, with the proposed change `html-tidy` works, but `emacs-lisp` still fails as before. Having `html-tidy` for direct remote editing of web content is very useful!

The only problem is that `flycheck-start-checker` uses `start-file-process`, which starts the checker on the remote machine (which obviously can't see the local temporary file).

Use `start-process` instead and you get working local checks (assuming the checker does not need access to other remote files). This is what I use in order to avoid changing flycheck.el, it's really as simple as using `start-process`:

``` lisp
(defadvice flycheck-start-checker (around flycheck-fix-start-process activate compile)
  "Make flycheck-start-checker use `start-process' instead of `start-file-process'."
  (let ((orig (symbol-function 'start-file-process)))
    (fset 'start-file-process (symbol-function 'start-process))
    (unwind-protect (progn ad-do-it)
      (fset 'start-file-process orig))))
```

By the way, I also looked into doing the reverse, adding proper TRAMP support to flycheck. Supporting that would be a little more involved, but comes with a crippling disadvantage: TRAMP is synchronous, i.e. at _every_ check Emacs would stall for several seconds. As a result, flycheck can't be made TRAMP-aware at all, at least not without serious effort (re-implementing parts of TRAMP in an asynchronous way).

For anyone wanting to do remote checks right now: You can write a shell script that copies `source` to the remote machine (again, `source-inplace` is not an option since access is synchronous) and then executes the checker remotely. Something along these lines:

``` sh
scp "$1" foo@bar:"$1"
ssh foo@bar gcc -fsyntax-only "$1"
```

If you need to know the original source directory, pass `source-original` as well and process it appropriately.

**Comment by unhammer** [comment]
Is flycheck supposed to turn itself off automatically for tramp files? Because when I tried to open a tramp file now, it tried checking, and the checker of course failed (saying `IOError: [Errno 2] No such file or directory: u'/scp:divvun:/Users/unhammer/org/flycheck_rapport.org'`).

**Comment by lunaryorn** [comment]
@unhammer Please open a new issue for this problem, and please follow our [Contribution guide](http://www.flycheck.org/contributing.html#bug-reports) on bug reports to make sure that all necessary information is included.  Thank you very much.
