### ISSUE TITLE
 flake8 ignore __main__ scope in function's scope [help]

### ISSUE THREAD

**Issue by avatar-lavventura** [flycheck/flycheck#1810]
I am using flycheck through `emacs`. I realize that when I create a variable it will be seen as already defined variable inside in any module.

I am getting following warning message for the following code: `F821 undefined name 'variable'`. // `variable` becomes color red.  

```
#!/usr/bin/env python3

def doo():
    print(variable)  # <= F821 undefined name 'variable'

if __name__ == "__main__":
    doo()
```

But if I create `variable` in `__main__` the warning message is gone, but still `variable` in undefined under the `doo()` function. 

```
#!/usr/bin/env python3

def doo():
    print(variable)


if __name__ == "__main__":
    variable = 100
    doo()
```

**[Q]** Is there any way to prevent this error message where main's scope would be ignore in functions' scopes?

------------

Setup:

```
(add-to-list 'auto-mode-alist '("\\.py\\'" . python-mode))
(require 'flycheck)
(require 'flycheck-mypy)

(add-hook 'python-mode-hook 'flycheck-mode) ;(add-hook 'after-init-hook #'global-flycheck-mode)
(add-hook 'python-mode-hook
          (lambda ()
            (setq flycheck-python-pylint-executable "~/venv/bin/pylint")
            (setq flycheck-pylintrc "~/.pylintrc")))
```

**Comment by cpitclaudel** [comment]
Thanks for your question! You'd have to ask the flake8 devs, since Flycheck just calls flake8 (and I don't know the answer, though I suspect the answer is no).
