### ISSUE TITLE
If flake8 is installed, pylint isn't ran.

### ISSUE THREAD

**Issue by sontek** [flycheck/flycheck#185]
Flake8 doesn't run pylint, so it would be nice to continue getting pylint errors even if flake8 is installed.

**Comment by choppsv1** [comment]
I have a script called pycheckers that runs both, the person claiming this isn't useful must not have tried using both at once for any amount of time. They do overlap but also catch different problems as well. If there's an easier way than definining my own checker and running a script I sure would appreciate it. :)

**Comment by mmcnl** [comment]
Hi @choppsv1, your `pycheckers` script sounds very useful. Would you mind sharing any of it?

**Comment by choppsv1** [comment]
@mmcnl sure, although I ended up doing as @lunaryorn suggested and copying the flake8 definition and creating a new one that chained pylint. Here's the code for that if you'd prefer to use it instead (I suggest doing this btw):
```
        (flycheck-define-checker python-flake8-chain
          "A Python syntax and style checker using flake8"
          :command ("flake8"
                     "--format=default"
                     (config-file "--config" flycheck-flake8rc)
                     (option "--max-complexity" flycheck-flake8-maximum-complexity nil
                       flycheck-option-int)
                     (option "--max-line-length" flycheck-flake8-maximum-line-length nil
                       flycheck-option-int)
                     "-")
          :standard-input t
          :error-filter (lambda (errors)
                          (let ((errors (flycheck-sanitize-errors errors)))
                            (seq-do #'flycheck-flake8-fix-error-level errors)
                            errors))
          :error-patterns
          ((warning line-start
             "stdin:" line ":" (optional column ":") " "
             (id (one-or-more (any alpha)) (one-or-more digit)) " "
             (message (one-or-more not-newline))
             line-end))
          :next-checkers ((t . python-pylint))
          :modes python-mode)

        ;; replace flake8 with new chaining one from above
        (setq flycheck-checkers (cons 'python-flake8-chain (delq 'python-flake8 flycheck-checkers)))
```
here's the pycheckers.sh script if you want to use that somewhere else (I'd suggest you don't use it in emacs since you still would have do define a new flycheck checker to call it which is the same amount of work as copying the elisp above which bypasses the need for pycheckers...)

pycheckers.sh:
```
#!/bin/bash 
args=`getopt r:8: $*`
if [ $? != 0 ]; then
    echo 'Usage: ...'
    exit 2
fi
set -- $args
for i; do
    case "$i"
    in
        -r)
            lintconf="$2"; shift;
            shift;;
        -8)
            flakeconf="$2"; shift;
            shift;;
    esac
done
if [[ $flakeconf  ]]; then
    flakeconf=" --config=$flakeconf "
fi
if [[ $lintconf  ]]; then
    lintconf=" --rcfile=$lintconf "
fi
flake8 $flakeconf "$2"
pylint $lintconf -r n --msg-template='{path}:{line}:{column}: {msg_id} {msg}' "$2"
```

**Comment by choppsv1** [comment]
@lunaryorn any chance of adding the ability to add chaining to a checker "after the fact" so that instead of having to redefine flake8 checker one could just modify it to be chainging?

**Comment by lunaryorn** [comment]
See flycheck-add-next-checker.

**Comment by choppsv1** [comment]
Hey that works great!

**Comment by mmcnl** [comment]
Thanks @choppsv1! Your `python-flake8-chain` checker code above works very well and does just what I was hoping.

**Comment by diasjorge** [comment]
@lunaryorn would you mind giving an example of how to do this using flycheck-add-next-checker?

**Comment by choppsv1** [comment]
@diasjorge here's how I used it: `(flycheck-add-next-checker 'python-flake8 'python-pylint)`
