### ISSUE TITLE
Explain error for sh-shellcheck is broken

### ISSUE THREAD

**Issue by Janfel** [flycheck/flycheck#1855]
## Checklist
- [x] I have checked existing issues for potential duplicates before creating this one.
- [x] I have read the [Troubleshooting guide][].

## Bug description
When calling `M-x flycheck-explain-error-at-point` on an error reported by `sh-shellcheck` (e.g. SC2129), you are directed to `https://github.com/koalaman/shellcheck/wiki/"SC2129"` (which doesn’t exist) instead of `https://github.com/koalaman/shellcheck/wiki/SC2129`. Note the quotation marks around the error code.

## Steps to reproduce
1. Open file `test.sh`.
2. Insert `echo $foo` to trigger a warning.
3. Call `M-x flycheck-explain-error-at-point` on the warning marker.
4. See error.

- [x] I have read https://emacs.stackexchange.com/questions/28429/how-do-i-troubleshoot-emacs-problems

## Expected behavior
I get directed to `https://github.com/koalaman/shellcheck/wiki/SC2129` instead of `https://github.com/koalaman/shellcheck/wiki/"SC2129"`.

## Screenshots
![image](https://user-images.githubusercontent.com/33464477/103240347-64a9e800-4950-11eb-83fc-3844d8d463db.png)

## System configuration
<details><pre>
Syntax checkers for buffer jshell-run in sh-mode:

First checker to run:

  sh-posix-dash
    - may enable:    yes
    - may run:       t
    - executable:    Found at /usr/bin/dash
    - next checkers: sh-shellcheck

Checkers that may run as part of the first checker's chain:

  sh-shellcheck
    - may enable:         yes
    - may run:            t
    - executable:         Found at /usr/bin/shellcheck
    - Shell sh supported: yes

Checkers that could run if selected:

  sh-posix-bash  select
    - may enable:    yes
    - may run:       t
    - executable:    Found at /usr/bin/bash
    - next checkers: sh-shellcheck

Checkers that are compatible with this mode, but will not run until properly configured:

  rpm-rpmlint (automatically disabled) reset
    - may enable: no
    - may run:    nil
    - executable: Not found

  sh-bash
    - may enable:    yes
    - may run:       nil
    - executable:    Found at /usr/bin/bash
    - next checkers: sh-shellcheck

  sh-zsh
    - may enable:    yes
    - may run:       nil
    - executable:    Found at /usr/bin/zsh
    - next checkers: sh-shellcheck

Flycheck Mode is enabled. Use SPC u SPC c ! x to enable disabled checkers.

--------------------

Flycheck version: 32snapshot
Emacs version:    27.1
System:           x86_64-pc-linux-gnu
Window system:    x
</pre></details>

Emacs configuration:
- [ ] Plain Emacs / Custom configuration
- [ ] Spacemacs
- [x] Doom Emacs
- [ ] Other shared configuration

[Troubleshooting guide]:  https://www.flycheck.org/en/latest/user/troubleshooting.html

**Comment by cpitclaudel** [comment]
Thanks a lot for the report!  I just pushed a fix.
