### ISSUE TITLE
Cygwin will create a file called NUL

### ISSUE THREAD

**Issue by KlRE** [flycheck/flycheck#1863]
Using flycheck with the c/c++-gcc checker from cygwin will create a NUL file in respective directory on Windows.

It can be reproduced by just opening or creating a .cpp file with flycheck enabled.

It probably should write to the null device.

**Comment by jcs090218** [comment]
I don't think this issue is from flycheck. I am also a Windows user, I would recommend you use Windows port from https://ftp.gnu.org/gnu/emacs/windows/ for less hassle.

**Comment by cpitclaudel** [comment]
Oh, that's annoying. But it sounds like an Emacs bug, or a setup issue: Flycheck uses the value of `null-device`, so if it uses the wrong one it means that Emacs is reporting the wrong one.  Can youc heck what null-device returns on your Emacs and report an Emacs bug if that value is incorrect?

**Comment by KlRE** [comment]
Hey, 
thanks for you answers.

I am actually using the Windows port. So, this NUL file is only created, when flycheck-mode is on in the current buffer. When I compile my file with gcc or g++ in Emacs no NUL file will be created. 
How can I check the value of `null-device` in Emacs?

I also found this link: https://www.emacswiki.org/emacs/NTEmacsWithCygwin#h5o-8. Maybe the cause is Cygwin? I don't fully understand the link, but I also tried flycheck with mingW and it didn't produce a NUL file.

**Comment by cpitclaudel** [comment]
Use `C-h v null-device RET` to check.

> When I compile my file with gcc or g++ in Emacs no NUL file will be created.

That's normal, because in that case output goes to object files; when running in flycheck we want to redirect the output to avoid creating spurious files.  Ironically, because of an Emacs set up issue, it seems that in your case we end up creating a `NUL` file instead (which is a bit crazy; I didn't think it was even possible to create such files on Windows)

**Comment by KlRE** [comment]
Thanks for your fast reply. I get 
> null-device is a variable defined in ‘files.el’.
> Its value is "NUL"

And in `files.el` it is set to `(defvar null-device (purecopy "/dev/null") "The system null device.")`

Yeah, It's kinda annoying, because this doesn't let me sync. My workaround is using another checker.
