### ISSUE TITLE
Flycheck faces

### ISSUE THREAD

**Issue by ItsNilDev** [flycheck/flycheck#1884]
How can I change the faces for flycheck Fringe & flycheck error? I want to make them bigger. I changed the settings for them
in customize-group but It doesn't do anything? any idea?

**Comment by cpitclaudel** [comment]
Fringe bitmaps are spacial (they are bitmaps, not faces); you can make them bigger by enlarging the fringes: https://github.com/flycheck/flycheck/pull/1744

Otherwise switch to using the margin indication style instead of the fringe indication style; that uses a face, so it can be resized.

Let me know if this helps.

**Comment by ItsNilDev** [comment]
@cpitclaudel I still didn't understand what I should do to make them bigger.. :(

**Comment by cpitclaudel** [comment]
Oh, sorry. The documentation is at https://www.flycheck.org/en/latest/user/error-reports.html?highlight=fringe#fringe-and-margin-icons ; you can set the fringe width with the commands at https://emacsredux.com/blog/2015/01/18/customizing-the-fringes/

**Comment by ItsNilDev** [comment]
I played a little bit with `(fringe-mode 4)` but that just doesn't make them bigger and that's not what I want.
and I could't figure that out.
I changed the indicator to margin that seemed to help a bit but they seem weird: 
![image](https://user-images.githubusercontent.com/61497342/119325185-e4d14100-bc95-11eb-86d7-1e62481cb707.png)
```lisp
;; Show indicators in the left margin
(setq flycheck-indication-mode 'left-margin)

;; Adjust margins and fringe widths…
(defun my/set-flycheck-margins ()
  (setq left-fringe-width 8 right-fringe-width 8
        left-margin-width 2 right-margin-width 0)
  (flycheck-refresh-fringes-and-margins))

;; …every time Flycheck is activated in a new buffer
(add-hook 'flycheck-mode-hook #'my/set-flycheck-margins) 
``` and this is the configuration that i'm using

**Comment by ItsNilDev** [comment]
Thanks a million! `(setq left-fringe-width 8)` did the job!
