### ISSUE TITLE
Error when saving a Rust document

### ISSUE THREAD

**Issue by Raghav-Dixit** [flycheck/flycheck#1897]
Doom Emacs v27.2

## Bug description
When I save a Rust document, I get this error:
```
Suspicious state from syntax checker rustic-clippy: Flycheck checker rustic-clippy returned 1, but its output contained no errors: error: no override and no default toolchain set

Try installing a more recent version of rustic-clippy, and please open a bug report if the issue persists in the latest release.  Thanks!
```

The file saves fine, but the rather lengthy error message comes up every time I save.

## Steps to reproduce
1. Run `cargo new testing` in the terminal
2. Open the src/main.rs in emacs
3. See error in minibuffer

## Screenshots
![image](https://user-images.githubusercontent.com/76796196/129299737-41589293-0008-41eb-b59d-e274010d3de6.png)

## System configuration
```
Syntax checkers for buffer main.rs<2> in rustic-mode:

First checker to run:

  rustic-clippy
    - may enable: yes
    - may run:    t
    - executable: Found at /usr/local/bin/cargo
    - Clippy:     Found
    - Cargo.toml: Found

Flycheck Mode is enabled. Use M-SPC u C-c ! x to enable disabled checkers.

--------------------

Flycheck version: 32snapshot
Emacs version:    27.2
System:           x86_64-apple-darwin18.7.0
Window system:    ns

```

Emacs configuration:
- [ ] Plain Emacs / Custom configuration
- [ ] Spacemacs
- [x] Doom Emacs
- [ ] Other shared configuration

## Additional notes
I just want to clarify: The file saves properly, and `cargo run` runs fine. It just shows the error.

I have seen answers to this question saying you need more RAM, but their message was slightly different, so I don't believe that.

**Comment by cpitclaudel** [comment]
I'm guessing `rustic-clippy` is part of the `rustic` package in Emacs?  In that case you should open a bug report there; it's not part of Flycheck out of the box.

The error message seems to say that your Rust install is too old?

**Comment by Raghav-Dixit** [comment]
Never mind. `M-x rust-mode` seems to solve it.

**Comment by brotzeit** [comment]
@Raghav-Dixit https://github.com/brotzeit/rustic#flycheck

> If you are using the stable toolchain you have to change the value:

```elisp
(setq rustic-flycheck-clippy-params "--message-format=json")
```
