### ISSUE TITLE
When following the install with :init (global-flycheck-mode) an syntax error appears.

### ISSUE THREAD

**Issue by BuddhiLW** [flycheck/flycheck#1903]
## Checklist
- [x] I have checked existing issues for potential duplicates before creating this one.
- [x] I have read the [Troubleshooting guide][].

## Bug description
`:init (global-flycheck-mode)` line throwing errors

## Steps to reproduce
1. Open file 'init.el'
2. Do '
```
(use-package flycheck
  :ensure t
  :init (global-flycheck-mode))
```
'
3. See error
```
Reverting buffer ‘editing.el’.
executing Emacs-Lisp code block...
Code block produced no output.
Error while checking syntax automatically: (user-error "[ERROR] Text can’t be ’nil’ or ’empty’")
```

Emacs configuration:
- [x] Plain Emacs / Custom configuration
- [ ] Spacemacs
- [ ] Doom Emacs
- [ ] Other shared configuration

**Comment by cpitclaudel** [comment]
There's something fishy with this example: how are you running Flycheck, and when does the error occur?  Can you get a backtrace?  There seems to be some org-related output in the error you're showing, and it talks about "editing.el", which doesn't appear in your example?

**Comment by jidicula** [comment]
What version of `use-package` are you using? In the v2 release, `:init` semantics mean that [anything in that hook will run _before_ the package loads](https://github.com/jwiegley/use-package#semantics-of-init-is-now-consistent). You may have to move the `global-flycheck-mode` into a `:config` block instead – I was having the same issue but I made that [change](https://github.com/jidicula/dotfiles/commit/cfffb56017caee994474cb10bb073c830a7b8016) to my `init.el` and stopped getting the warning.

**Comment by BuddhiLW** [comment]
Yes, that worked @jidicula!

Sorry I hadn't replied. I didn't know exactly how I should. @cpitclaudel 

Thank you for the support.
