### ISSUE TITLE
Buffer containing output of last Flycheck command performed on current-buffer

### ISSUE THREAD

**Issue by nordlow** [flycheck/flycheck#1905]
I'm looking for a buffer-local variable that contains the output of the last Flycheck performed. Is there such a variable?

**Comment by cpitclaudel** [comment]
There's flycheck-current-errors; does that work for your use case?

**Comment by nordlow** [comment]
> There's flycheck-current-errors; does that work for your use case?

Thanks, but I need the raw output.

**Comment by cpitclaudel** [comment]
Then no, there's no such variable.  You could advise `flycheck-parse-output`, maybe?

**Comment by nordlow** [comment]
> Then no, there's no such variable. You could advise `flycheck-parse-output`, maybe?

Ok, thanks. That suffices for now.
