### ISSUE TITLE
`flycheck-rust-cargo-has-command-p` returns `nil` incorrectly

### ISSUE THREAD

**Issue by PatrickNorton** [flycheck/flycheck#1916]
Thank you for taking the time to report an issue and improve Flycheck.  This template is for **actual bugs you observed**.  If you have trouble setting up Flycheck, or if you have a question, please use the relevant issue template instead.

## Checklist
- [x] I have checked existing issues for potential duplicates before creating this one.
- [x] I have read the [Troubleshooting guide][].

## Bug description
Running `(flycheck-rust-cargo-has-command-p "run")` (or any other Cargo command) returns `nil` when it should return `t`. This is because `flycheck-rust-cargo-has-command-p` uses `cargo --list` as a basis, which returns descriptions for each subcommand (ever since https://github.com/rust-lang/cargo/pull/9848). This means `(member command ...)` returns `nil`.

## Steps to reproduce
1. Run `(flycheck-rust-cargo-has-command-p "run")` with a sufficiently recent (>= 1.56) version of Cargo installed.
2. Observe that it returns `nil`

- [x] I have read https://emacs.stackexchange.com/questions/28429/how-do-i-troubleshoot-emacs-problems

## Expected behavior
The command should return `t` when the command is installed

Emacs configuration:
- [ ] Plain Emacs / Custom configuration
- [ ] Spacemacs
- [x] Doom Emacs
- [ ] Other shared configuration

[Troubleshooting guide]:  https://www.flycheck.org/en/latest/user/troubleshooting.html

**Comment by jimenezrick** [comment]
This patch works for me using plain Emacs (with my custom config).
