### ISSUE TITLE
cuda flycheck support "gencode" option

### ISSUE THREAD

**Issue by eyal0** [flycheck/flycheck#1926]
Thank you for taking the time to improve Flycheck.

## Checklist
- [x] I have checked existing issues for potential duplicates before creating this one.

## Feature description
An important option to the nvcc compiler is "gencode", so that the generated source code will match the architecture.  It should be configurable because the default will often be old and lead to compiler errors.

**Comment by eyal0** [comment]
I can write the PR but is anyone even maintaining flycheck anymore?  I don't want to write a PR if it'll never get accepted.

**Comment by cpitclaudel** [comment]
> anyone even maintaining flycheck anymore

Yes, but graduating and starting a new job tends to take time away from that :/

**Comment by eyal0** [comment]
No doubt. I see a big list of PRs already so I don't know if I should make one or not.

Maybe someone will help approve PRs so that this project can progress?

**Comment by cpitclaudel** [comment]
I think it would be very nice if you made the PR.  Ideally someone would go through the existing one to review them and then we could merge them straightforwardly.

**Comment by eyal0** [comment]
Okay I did it.  I don't know how to test it but it seems pretty simply and obvious.

**Comment by eyal0** [comment]
I appreciate all the efforts that you have made so far with flycheck!  :heart: I wish that I were better at elisp so that I could help you more.
