### ISSUE TITLE
Replace or remove checker: chef-foodcritic

### ISSUE THREAD

**Issue by webframp** [flycheck/flycheck#1935]
Hi there,

This is somewhat of an unimportant bug and somewhat of an enhancement request, so I went with the feature template.

## Checklist
- [X] I have checked existing issues for potential duplicates before creating this one.

## Feature description
In the Chef community `foodcritic` [has been deprecated as of 2019](https://blog.chef.io/goodbye-foodcritic/ )

As a result, any attempt to use or activate chef-foodcritic in a buffer results in this message:

```
Suspicious state from syntax checker chef-foodcritic: Flycheck checker
chef-foodcritic returned 1, but its output contained no errors: Foodcritic has
been deprecated. Use cookstyle instead, which provides over 200 Chef Infra cops
with autocorrection! For more details see
https://blog.chef.io/goodbye-foodcritic/
```

As the message indicates it is now replaced by [cookstyle](https://github.com/chef/cookstyle) which is an opinionated set of rules for rubocop.

## Describe alternatives you've considered

For now the best thing to do is disable foodcritic with something like: 

```scheme
(add-to-list 'flycheck-disabled-checkers 'chef-foodcritic)
```

Alternatively, as a replacement, a checker similar to `ruby-rubocop` could be implemented as the output is comparable

**Comment by niclan** [comment]
Having recently upgraded my laptop chef install (the old one was breaking) I too are now without foodcritic and in need of cookstyle support.

**Comment by bbatsov** [comment]
As cookstyle is just a wrapper around RuboCop it will be trivial to provide a checker for it.
