### ISSUE TITLE
Flycheck doesn't work with flake8>=5.0 , works with 4.0

### ISSUE THREAD

**Issue by velicanu** [flycheck/flycheck#1969]
## Checklist
- [x] I have checked existing issues for potential duplicates before creating this one.
- [x] I have read the [Troubleshooting guide][].

## Bug description
Flycheck doesn't work with the latest version of `flake8` , 5.0 and onwards, works just fine the previous 4.0 version.

## Steps to reproduce
Use a file like the following python file, `foo.py` , containing some linting errors:
```
def bar():
    x = "123"

    json.dumps({})
```

Using flake8 5.0:
```
$ pip install flake8==5.0
$ flake8 foo.py  # cli flake8 works just fine
foo.py:2:5: F841 local variable 'x' is assigned to but never used
foo.py:4:5: F821 undefined name 'json'
$ emacs foo.py  # no linting errors within emacs buffer, unexpected
```

## Expected behavior

Using flake8 4.0:
```
$ pip install flake8==4.0
$ flake8 foo.py  # cli flake8 works just fine
foo.py:2:5: F841 local variable 'x' is assigned to but never used
foo.py:4:5: F821 undefined name 'json'
$ emacs foo.py  # will show linting errors as expected
```

## Screenshots
See video below for a demonstration:

![flycheck](https://user-images.githubusercontent.com/5022772/183777508-e5d20892-2529-49d0-afef-e921aad18749.gif)

## System configuration
```
Syntax checkers for buffer foo.py in python-mode:

First checker to run:

  python-flake8
    - may enable:         yes
    - executable:         Found at /Users/velicanu/py39/.direnv/python-3.9.13/bin/python3
    - configuration file: Not found
    - `flake8' module:    Found at "/Users/velicanu/py39/.direnv/python-3.9.13/lib/python3.9/sit\
e-packages/flake8/__init__.py"
    - next checkers:      python-pylint, python-mypy

Checkers that may run as part of the first checker's chain:

  python-pylint
    - may enable:         yes
    - executable:         Found at /Users/velicanu/py39/.direnv/python-3.9.13/bin/python3
    - configuration file: Not found
    - `pylint' module:    Found at "/Users/velicanu/py39/.direnv/python-3.9.13/lib/python3.9/sit\
e-packages/pylint/__init__.py"
    - next checkers:      python-mypy

Checkers that could run if selected:

  python-pycompile  select
    - may enable:    yes
    - executable:    Found at /Users/velicanu/py39/.direnv/python-3.9.13/bin/python3
    - next checkers: python-mypy

Checkers that are compatible with this mode, but will not run until properly configured:

  python-pyright (automatically disabled) reset
    - may enable: no
    - executable: Not found

  python-mypy (manually disabled) enable
    - may enable:         yes
    - may run:            t
    - executable:         Found at /Users/velicanu/py39/.direnv/python-3.9.13/bin/mypy
    - configuration file: Not found

Flycheck Mode is enabled.  Use C-u C-c ! x to enable disabled
checkers.

--------------------

Flycheck version: 32snapshot (package: 20210825.1804)
Emacs version:    28.1
System:           x86_64-apple-darwin20.6.0
Window system:    nil
```

Emacs configuration:
- [x] Plain Emacs / Custom configuration
- [ ] Spacemacs
- [ ] Doom Emacs
- [ ] Other shared configuration

**Comment by velicanu** [comment]
flake8 folks suggested this may be due to running with `--append-config .flake8rc` .

https://github.com/PyCQA/flake8/issues/1661#issuecomment-1210916906

Trying to figure out how to test if that is the case.

**Comment by velicanu** [comment]
The following diff made `flake8>=5.0` work for me again, however I don't really understand what the `"python3" (eval (flycheck-python-module-args 'python-flake8 "flake8"))` is doing, so this is more a hint towards the fix instead a proposed fix.

<img width="714" alt="Screen Shot 2022-08-10 at 2 46 00 PM" src="https://user-images.githubusercontent.com/5022772/184026199-b99e781f-c92f-4e38-b678-4104407d2ebd.png">

**Comment by velicanu** [comment]
This is the underlying line that stopped working with `flake8>=5.0` https://github.com/flycheck/flycheck/blob/8541a61053bba1f2f31d0791e597cd3c78a21456/flycheck.el#L10549-L10550

```bash
python -c "import sys;sys.path.pop(0);import runpy;runpy.run_module('flake8')" foo.py  # produces no output with flake8>=5.0
```
 We may have to revert to calling flake8 directly instead of via runpy to support the latest versions.

**Comment by cpitclaudel** [comment]
Can you check whether https://github.com/flycheck/flycheck/pull/1968 (which I merged just two minutes ago) fixes it?

**Comment by cpitclaudel** [comment]
(Thanks for the report BTW; looks like the `__main__` file in flake8 got a bit stricter)

**Comment by velicanu** [comment]
> Can you check whether https://github.com/flycheck/flycheck/pull/1968 (which I merged just two minutes ago) fixes it?

Yup! That fixed it for me. Thanks for the fix!

**Comment by cpitclaudel** [comment]
Woohoo!  Thanks again for the report.  And thanks a lot @gaetano-guerriero
