### ISSUE TITLE
Add support for `ruff`

### ISSUE THREAD

**Issue by liebkne** [flycheck/flycheck#1974]
Thank you for taking the time to improve Flycheck.

## Checklist
- [x] I have checked existing issues for potential duplicates before creating this one.

## Feature description
Add support for [ruff](https://github.com/charliermarsh/ruff) (An extremely fast Python linter, written in Rust.).

**Comment by Yevgnen** [comment]
@mhvk Seems work for me!

**Comment by Paulswith** [comment]
> I don't know enough about `flycheck` to be sure this is enough, but the following in a separate `flycheck-ruff.el` (and then `(require 'flycheck-ruff)` does seem to work:
> 
> ```
> (require 'flycheck)
> 
> (flycheck-define-checker python-ruff
>   "A Python syntax and style checker using the ruff utility.
> To override the path to the ruff executable, set
> `flycheck-python-ruff-executable'.
> See URL `http://pypi.python.org/pypi/ruff'."
>   :command ("ruff"
>             "--format=text"
>             (eval (when buffer-file-name
>                     (concat "--stdin-filename=" buffer-file-name)))
>             "-")
>   :standard-input t
>   :error-filter (lambda (errors)
>                   (let ((errors (flycheck-sanitize-errors errors)))
>                     (seq-map #'flycheck-flake8-fix-error-level errors)))
>   :error-patterns
>   ((warning line-start
>             (file-name) ":" line ":" (optional column ":") " "
>             (id (one-or-more (any alpha)) (one-or-more digit)) " "
>             (message (one-or-more not-newline))
>             line-end))
>   :modes python-mode)
> 
> (add-to-list 'flycheck-checkers 'python-ruff)
> 
> (provide 'flycheck-ruff)
> ```
> 
> (based on https://github.com/Wilfred/flycheck-pyflakes and the flake8 bits of `flycheck`)

Cool!! I use Spacemacs and it works for me.

**Comment by rpeck** [comment]
Woo! It's working great!

It'd be so great if we had ruff's "quick fix" and "fix the whole buffer" features. Even after 36 years of emacs, I'm not elisp-enabled enough to knock that out quickly. :-(

**Comment by rpeck** [comment]
Something that might be an easy, incremental improvement is to add ruff to the UI menu (Python -> Checks -> Ruff). I'm not normally a menu guy, but this would be a nice add.

**Comment by mhvk** [comment]
Auto-fix would indeed be nice, but I'm afraid I'm not enough of an emacs expert to do that...

**Comment by vikigenius** [comment]
@rpeck You can get ruff's auto-fix if you use Ruff as an lsp-server instead of as a flycheck-checker

**Comment by mhvk** [comment]
@vikigenius  - that sounds very interesting! Do you have a snippet for enabling that?

**Comment by vikigenius** [comment]
Well, I use doom emacs so it already has lsp mode pre enabled and auto configured. As long as the lsp-mode is able to find a package called ruff-lsp in your Path (I typically have it installed in my venv) it automatically starts ruff alongside any other python language servers you may have.

**Comment by waveFrontSet** [comment]
Already noted that in the associated pull request: The `--format` option has been replaced by `--output-format` now. For convenience, here's how it currently works for me in Emacs Doom (config.el):
```lsp
(flycheck-def-config-file-var flycheck-python-ruff-config python-ruff
                              '("pyproject.toml" "ruff.toml" ".ruff.toml"))

(flycheck-define-checker python-ruff
  "A Python syntax and style checker using the ruff.
To override the path to the ruff executable, set
`flycheck-python-ruff-executable'.

See URL `https://beta.ruff.rs/docs/'."
  :command ("ruff"
            "check"
            (config-file "--config" flycheck-python-ruff-config)
            "--output-format=text"
            "--stdin-filename" source-original
            "-")
  :standard-input t
  :error-filter (lambda (errors)
                  (let ((errors (flycheck-sanitize-errors errors)))
                    (seq-map #'flycheck-flake8-fix-error-level errors)))
  :error-patterns
  ((warning line-start
            (file-name) ":" line ":" (optional column ":") " "
            (id (one-or-more (any alpha)) (one-or-more digit)) " "
            (message (one-or-more not-newline))
            line-end))
  :modes (python-mode python-ts-mode)
  :next-checkers ((warning . python-mypy)))

;; Python config: Use ruff + mypy.
(defun python-flycheck-setup ()
  (progn
    (flycheck-select-checker 'python-ruff)
    (flycheck-add-next-checker 'python-ruff 'python-mypy)
    ))
(after! flycheck
  (add-to-list 'flycheck-checkers 'python-ruff)
  (add-hook 'python-mode-local-vars-hook #'python-flycheck-setup 'append)
  )
```

**Comment by mhvk** [comment]
Thanks!
