### ISSUE TITLE
How are the docs being deployed?

### ISSUE THREAD

**Issue by jcs090218** [flycheck/flycheck#2004]
> 🔈 This is not a bug report, it's a question.

Are docs being deployed with CI (`Travis CI` or `GHA`)?

In the previous `.travis.yml`: (old)

https://github.com/flycheck/flycheck/blob/9db727590b8f038b91cd1360ead1706f50043d2a/.travis.yml#L83-L84

current `.github/workflows/docs.yml`: (new)

https://github.com/flycheck/flycheck/blob/484e9084205484c6ad9dfad1778d49d077a68685/.github/workflows/docs.yml#L30-L31

I don't think the org is using GitHub pages, so my question is, how are docs deployed now? 🤔

**Comment by cpitclaudel** [comment]
I think we are using GH pages; flycheck.org is just redirecting there.

**Comment by jcs090218** [comment]
Oh okay. I don't have the permission to see the settings, so I would have to guess it.

Does that mean we need to push back to this repo after the docs are built? 🤔

**Comment by cpitclaudel** [comment]
I'm very sorry.  I mixed things up between flycheck and another project.

We use readthedocs, which automatically rebuilds on every commit.  See https://github.com/flycheck/flycheck/blob/f8c679fff349850c80541a31de50009c3c15d4c9/doc/contributor/maintaining.rst#tooling-and-services 

I have admin access there if something needs to be changed.  I just added @bbatsov to it as well.

**Comment by jcs090218** [comment]
No worries! I should have read the documents more carefully! 😅 

Thanks for the quick reply though! ;)

**Comment by cpitclaudel** [comment]
Thanks so much for all your efforts!
