### ISSUE TITLE
Support for phpcs-changed in addition to php-cs

### ISSUE THREAD

**Issue by heydemoura** [flycheck/flycheck#2015]
## Checklist
- [x] I have checked existing issues for potential duplicates before creating this one.

## Feature description
Add support for using [phpcs-changed](https://github.com/sirbrillig/phpcs-changed) as a PHP checker.

## Describe alternatives you've considered
I considered just using `phpcs-changed` as an alias on the system for `phpcs`  but it didn't work well since it supports different options.

**Comment by bbatsov** [comment]
Fixed in #2015.
