### ISSUE TITLE
please update the flymake comparison

### ISSUE THREAD

**Issue by anarcat** [flycheck/flycheck#2023]
I've been using flycheck for a long time now, but I've heard flymake has been making some major improvements since Emacs 27. Some of those are covered by the [comparison page](https://www.flycheck.org/en/latest/user/flycheck-versus-flymake.html), but it seems this has aged quite a bit.

## Checklist
- [x] I have checked existing issues for potential duplicates before creating this one.

## Feature description

I would like to have an up-to-date comparison with flymake from Emacs, at least based on Emacs 27 but ideally 28 or current... 

## Describe alternatives you've considered

I have tried culling the information out of the internet myself, but I quickly felt out of my depth. I find it's difficult to figure out what exactly is supported by flymake, and in the brave new world of tree-sitter and LSP, I am not sure how to compare the two anymore in the first place.

## Additional context

What led me to reconsider is this quote from [Spotlight: Flycheck, a Flymake replacement](https://www.masteringemacs.org/article/spotlight-flycheck-a-flymake-replacement):

> So why switch away from Flymake? Well, before the advent of Emacs 27 and the renewed interest in Flymake, I’d argue because Flymake had atrophied for a long time. Nowadays the distinction is less clear. If running M-x flymake-mode works as you expect – this is doubly true if you’re using a Language Server client like eglot or LSP-mode – then you can just stick with Flymake. It works well. But, if you’re using an older version of Emacs, or if you want a package with nearly a decade’s worth of attention lavished on it, you may want to give Flycheck a shot.

Thanks!

**Comment by bbatsov** [comment]
The comparison was updated after the Flymake rewrite in Emacs 26, so I'll close this ticket. I've recently reflected also that Eglot has a hard depedency on Flymake, which we can't really do much about. 

In general there haven't been major changes to both Flycheck and Flymake in recent years.
