### ISSUE TITLE
PHP - Warning about A file should declare new symbols... 

### ISSUE THREAD

**Issue by so-o** [flycheck/flycheck#2034]
Can you tell me what is wrong with calling `require_once` before declaring a function?

```
<?php

require_once 'file.php';

function foobar() {
	return true;
}
```

`$ phpcs --report=checkstyle --standard=PSR1 foobar.php`

`A file should declare new symbols (classes, functions, constants, etc.) and cause no other side effects, or it should execute logic with side effects, but should not do both. The first symbol is defined on line 5 and the first side effect is on line 3." source="PSR1.Files.SideEffects.FoundWithSymbols".`

If the `require_once` is removed, no error.

`$ phpcs --version`
`PHP_CodeSniffer version 3.6.2 (stable) by Squiz (http://www.squiz.net)`

**Comment by cpitclaudel** [comment]
Thanks for the report.  You should ask the phpcs folks; we just redisplay the warning; we don't produce it.
