### ISSUE TITLE
Is CLA assistant working ?

### ISSUE THREAD

**Issue by dod38fr** [flycheck/flycheck#2042]
Hi

I've opened a [PR](https://github.com/flycheck/flycheck/pull/2041) last week. I'm supposed to agree to Flycheck's CLA with the help of your CLA asssistant.

So far, I've seen nothing in the PR or in my mails that would help me sign this CLA.

Did I miss something ?

Could you check what's going on ?

All the best

**Comment by bbatsov** [comment]
I'll look into this. I see that the list of people who signed has not been updated since Sep 2023. I don't see your name there. Can you try again?

**Comment by dod38fr** [comment]
My PR was merged. I dont' know how I could try again.

**Comment by bbatsov** [comment]
Guess we can close this issue then.

**Comment by dod38fr** [comment]
fair enough.
