### ISSUE TITLE
Consider downgrading seq dep version 

### ISSUE THREAD

**Issue by p4v4n** [flycheck/flycheck#2054]
The latest version of flycheck updated the seq dep version to 2.24.
The default seq version in emacs 26.1 is 2.20, 2.21 in emacs27.1 and 2.23 in emacs28.1.
The latest release breaks CI workflow of packages supporting older emacs versions without explicit version management.

**Comment by bbatsov** [comment]
Hmm, but seq.el is provided as a package on ELPA that works with older versions of Emacs, right? Unfortunately looking at the code (https://github.com/emacs-mirror/emacs/blob/master/lisp/emacs-lisp/seq.el), it's not clear which version of Emacs does 2.24 target exactly. 

Flycheck doesn't use anything from 2.24, so we can safely set this to 2.20. I'm just trying to understand better the problem, as I see that the CI builds are passing. 

>  The latest release breaks CI workflow of packages supporting older emacs versions without explicit version management.

I'm not sure I understand this part.

**Comment by p4v4n** [comment]
Context: I have noticed following issue when working on https://github.com/borkdude/flycheck-clj-kondo/pull/27 
```Dependency `seq' is built-in, but required version 2.24 is too new (only 2.21 available)```
Issue is reproducible with  
`eldev docker 27.1 -dtT test` in flycheck-clj-kondo main branch.

seq.el can be installed separately but that requires explicit work from all the packages that depend on flycheck.

**Comment by p4v4n** [comment]
Not sure if I am clear enough.
seq 2.24 might be compatible with older emacs versions but it is not in-built version so it has to be installed separately by any package that depends on flycheck.
Downgrading seq to 2.20 here will be a ideal fix as it is in line with the emacs 26.1 dependency here and will need no work from downstream package authors.

**Comment by bbatsov** [comment]
Yeah, I figured out what you meant when I saw the related ticket. It was my understand it's a best practice to have an explicit dependency on packages like `seq.el`, and because I've always done it, it took me a while to figure out what you meant. 

> Downgrading seq to 2.20 here will be a ideal fix IMO

Well, it essence that'd be same as removing the dep from the package manifest, so perhaps it'd best to actually do this. I'm guessing any affected package didn't list an explicit dependency, either.

**Comment by p4v4n** [comment]
seq.el for flycheck-clj-kondo is not a direct dependency so tracking the version there is not ideal. 
It will be great if tools like Eldev can automatically prefer the newer versions of indirect dependencies as well when there are similar conflicts. (Not sure how easy it is achieve though)
> I'm guessing any affected package didn't list an explicit dependency, either.

The new release with this change was only 4 days ago so probably no other package was affected yet.

**Comment by bbatsov** [comment]
Okay, I'll change the dep and I'll cut a new release later today.

**Comment by p4v4n** [comment]
Thanks!
