### ISSUE TITLE
Variable for keymap prefix.

### ISSUE THREAD

**Issue by proofit404** [flycheck/flycheck#213]
For example in projectile package we can setup projectile-keymap-prefix variable. Maybe it a good idea for flycheck too?

**Comment by CodeSwimBikeRunner** [comment]
@proofit404 good work on the pr!

How does one configure this ability? I am seeing none of those variables in any of my function searches "flycheck-mode-map" and "flycheck-keymap-prefix"

**Comment by cpitclaudel** [comment]
Use M-x customize-variable flycheck-keymap-prefix

**Comment by CodeSwimBikeRunner** [comment]
How do I set this then in the :config portion of the package?

**Comment by cpitclaudel** [comment]
`:config` is a `use-package thing? You'd have to check its docs, I don't use it. Sorry :/

**Comment by CodeSwimBikeRunner** [comment]
I found the section describing the variable and added this configuration, and can confirm that even when flycheck mode enabled, it said it said that key combination was undefined.
```
  (define-key flycheck-mode-map flycheck-keymap-prefix nil)
  (setq flycheck-keymap-prefix (kbd "C-l c"))
  (define-key flycheck-mode-map flycheck-keymap-prefix flycheck-command-map))
```
The only thing I can think of is is that I am using C-l in lsp-mode as the default prefix. All other packages I have configured have played happily with this.

**Comment by CodeSwimBikeRunner** [comment]
The issue was a combination of setting that weird variable. and adding that lisp configuration. Removing the custom variable, and adding the 3 lines from above worked. and I can access all of flycheck's great functionality with C-l c
