### ISSUE TITLE
Faster updates

### ISSUE THREAD

**Issue by JackKelly** [flycheck/flycheck#227]
I am really enjoying using `flycheck` in `Emacs24` to check my Python code as I write it.  However, I find that `flycheck` takes about 4 seconds update, which is a little slow for my tastes.  e.g. if I write an incorrect line then it takes about 4 seconds to spot the error.  Likewise, if I correct an error then it takes about 4 seconds to spot that I have fixed the error.

Is there a configuration option to increase the speed at which `flycheck` updates?

I have tried tinkering with `flycheck-check-syntax-automatically` and `flycheck-idle-change-delay` but to no avail.

I think my preferred behaviour would be for `flycheck` to update immediately after I save the buffer.  At the moment, it updates about 4 seconds after I save the buffer.

I am using pylint.

(But, overall, I really like flycheck - thanks so much for sharing such a great project!)

**Comment by kootenpv** [comment]
This a problem in 2016. When we compare to other languages, you get immediate responses. It really is pylint that's just very slow.
