### ISSUE TITLE
Alternate look & feel

### ISSUE THREAD

**Issue by syl20bnr** [flycheck/flycheck#273]
Hi Sebastian,

I recently worked on changing the look and feel of my Flycheck config:

This involved some changes in the `Solarized theme` [1] and a custom fringe bitmap in Flycheck (only one for all levels) [2].

![image](https://f.cloud.github.com/assets/1243537/1619530/42a0ee20-565a-11e3-87ce-ccb1c3969cde.png)

What do you think ?

syl20bnr

[1] https://github.com/syl20bnr/solarized-emacs/commit/64d3ff7cd198bdc06ad803b23334e839dec3a7f2
[2] https://github.com/syl20bnr/vimacs/blob/master/init-package/init-flycheck.el#L20

**Comment by ReneFroger** [comment]
I would like to add this to my flycheck setup. 

Note: I'm not using Spacemacs, but default Emacs. So if I might ask, what's the desired configuration in order to get  plain line instead waves?

**Comment by ReneFroger** [comment]
Nobody?

**Comment by lunaryorn** [comment]
@ReneFroger Customize the `:underline` property of the faces `flycheck-error`, `flycheck-warning` and `flycheck-info`.
