### ISSUE TITLE
Consider support for HTML tidy for HTML5

### ISSUE THREAD

**Issue by btipling** [flycheck/flycheck#292]
RIght now HTML5 elements show up as errors in flycheck, like the "main" element (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/main).

w3c has an experimental fork of  tidy for HTML5:

http://w3c.github.io/tidy-html5/
https://github.com/w3c/tidy-html5

**Comment by togakangaroo** [comment]
It's now 3 years later, just wondering what the recommended way of getting this properly is?

**Comment by lunaryorn** [comment]
@togakangaroo Just install a recent version of html-tidy (> 5.0).  It supports HTML 5 out of the box.
