### ISSUE TITLE
How to turn off certain warnings without disable the checker? 

### ISSUE THREAD

**Issue by magichowl** [flycheck/flycheck#309]
As the title, I enable the chktex checker for latex mode, and I want to turn off some warnings as I don't find any wrong.  

The feature can be achieved in command line:

chktex pathname -n 2

this means turn off the warning number 2

I've read the manual of flycheck, maybe it can do the same job by writing something in Syntax checker configuration file?  But I don't know how.

**Comment by khatchad** [comment]
@lunaryorn Is it possible to ignore a warning category (e.g., 6) by specifying it in the .chktex file?

**Comment by lunaryorn** [comment]
@khatchad I do not know; you'll need to find out yourself.

Please be aware that I stopped maintaining Flycheck, and ceased to use Emacs, so please don't ask me about Flycheck anymore.  Thanks.
