### ISSUE TITLE
FlyCheck Buffer only upon Buffer Save

### ISSUE THREAD

**Issue by nordlow** [flycheck/flycheck#330]
I've been using Flycheck in my D development for a couple of weeks now and I mostly love it. However I believe the default settings is little bit too disturbing when I'm writing my code.

More specifically I'm missing a generic FlyCheck option (for all modes) that enables flychecking of current buffer only upon buffer save.

Could this be achieved somehow?

**Comment by alimavrakis** [comment]
For anyone coming late to the party -- updated [link to the docs](http://www.flycheck.org/en/stable/user/syntax-checks.html#variable-flycheck-check-syntax-automatically)
