### ISSUE TITLE
Checkers for multi-language buffers

### ISSUE THREAD

**Issue by expez** [flycheck/flycheck#349]
The use case here is to allow flycheck to check syntax using different checkers for different regions of the same buffer.  E.g when writing HTML you'd want to run HTML checkers on most of the file, but in `<script>` elements containing javascript  you'd want to run javascript checkers.

I don't think determining what's what is Flycheck's job, instead modes like [web-mode](https://www.github.com/fxbois/web-mode) will be responsible for partitioning the buffer and making the right calls to flycheck.  They already have this information at hand, in order to perform proper syntax highlighting.

Is this something that is currently supported?  I only found mention of chaining checkers, but that seems to be a slightly different use-case.

**Comment by am** [comment]
4 years after and I would like to ping on this same request. Currently to edit [Vue Single file components](https://vuejs.org/v2/guide/single-file-components.html) I've been using [vue-mode](https://github.com/AdamNiederer/vue-mode). It works great but I couldn't make Flycheck to work. From what I can see this is still a limitation.

@fmdkdd is there any interest on supporting this feature?

Thank you

**Comment by fmdkdd** [comment]
@am What tool do you want to run on a `vue` file?

**Comment by am** [comment]
@fmdkdd I'm sorry for the late reply here didn't see the notification. 

About the tool, Vue file can have both, `html`, `css` (less, stylus, ...) and `javascript`, somewhat similar to what the original OP askes, in case of html, depending on the part of the file you are editing a different lint should kick-in.

**Comment by fmdkdd** [comment]
> depending on the part of the file you are editing a different lint should kick-in.

Ok I get it.  Well, I concur with lunaryorn above.  It's interesting, and would be happy to merge a PR implementing it, but I don't have the time to do it.

The best-case scenario is if, e.g., the CSS linter on a Vue file blissfully ignores the non-CSS parts.  If there are tools that work like this, then we can already include them in Flycheck without additional work.  If, on the other hand, the tools *do* expect CSS only, then we have to split the buffer in chunks, and send these chunks to the tool, which requires more thought.

**Comment by lzhoucs** [comment]
@am I am also using `vue-mode`. I added the following and flycheck works fine
```
  (add-hook 'vue-mode-hook 'flycheck-mode)
```
I am using eslint checker.
