### ISSUE TITLE
checker temp files in dedicated directory?

### ISSUE THREAD

**Issue by steckerhalter** [flycheck/flycheck#371]
I had problems a few times because flycheck uses temp files in the same directory as the source file. One issue was that org-mode exports would invoke flycheck and the created file would end up somewhere in the blob causing an error (because it had a .el ending).

Another problem is with magit-filenotify. the temp files trigger file notifications which slows down Emacs quite a bit (because there are so many changes).

Could flycheck place the temp files in `temporary-file-directory` or something like that? I would be happy also just to have a config option to enable this

**Comment by atfornes** [comment]
Hello, I am having this issue with Flycheck for javascript: (jshint + jscs) 

  @lunaryorn said:
  > Flycheck does not use in-place temporary files unless a syntax checker really needs it. For those who need it, there is no way to disable it, and I will not provide one.

When reading this comment, I would have liked to find which are those checkers who need it, specially if jshint or jscs are among them. I have already search in this github repo, but not found, if the checkers I am asking for need to create those temporary files at the directory.

The issue arise with the use of [gulp](http://gulpjs.com/), that detects file changes and among other tasks tries to compile files like flycheck_filename.js as javascript source files and fail.

A partial fix for the issues related with file searches by extension will be to change the file extension of the temporary files: ```flycheck_filename.js -> flycheck_filename.js.flychecktemp```. can this be done? I am happy to try to fix it this way and contrib here if it seams feasible and easy for a lisp noob.

See https://github.com/P2Pvalue/pear2pear/commit/50ace6404d6db4630eb19e7de6657995b311c655, also referenciated at #92 for the commit raising this issue

Thanks!

**Comment by lunaryorn** [comment]
@atfornes Search for `source-inplace` in syntax checker definitions.  Changing the extension won't work generally, though, because some tools are very peculiar about the file extension.

**Comment by atfornes** [comment]
thanks @lunaryorn, jshint checker definition do have ```source-inplace```. The reason seams to be the same as for eslint: it needs the route for finding the config files https://github.com/flycheck/flycheck/issues/447.

This brings the following question: Does the fact that the source path is needed to find a config file implies that the temporary files have to be created in the directory where the files are?

Probably I am missing something, but if this is the only reason, it does not seam strictly necessary. Even if needed in a parent folder of the file, the path structure can be reproduced in the temporary file directory.

**Comment by lunaryorn** [comment]
@atfornes I'm not sure whether I can follow you: jshint searches for configuration files relative to the location of the given source file.  I don't see how this could possible work if the source file is located in a temporary directory…

**Comment by atfornes** [comment]
Hi @lunaryorn,

I have done a shell script that illustrates how this can be done. it should be run from the folder where the file is and takes as parameter the file name. It creates in the $TMPDIR a temporary symbolic link to the closest jshint cofing file (.jshintsrc) and returns the path to that file.

Then, the checker should call jshint with the option --config that takes as a parameter the path to the temporary file that links to .jshintsrc config file

```bash
#! /bin/bash

while [[ ! -f .jshintsrc && $(pwd) != / ]]
do 
    cd ..
done;

## If not found
if [[ ! -f .jshintsrc ]]
then
    return 1
fi

symbolicLinkPath=${TMPDIR}flycheck_link_$1

jshintsrcPath=$(pwd)/.jshintsrc

if [[ -a $symbolicLinkPath ]]
then
    rm $symbolicLinkPath
fi

ln -s $jshintsrcPath $symbolicLinkPath

echo $symbolicLinkPath

exit 0
```
For a file called filename.js, it creates in the temporary file directory a link called flycheck_link_filename.js.

Jshint can be called now from the temp folder with this command:

jshint flycheck_filename.js --config flycheck_link_filename.js

Yo can also call it this way (from the filename.js directory and given you called the script file findJshintsrc.sh):
```
./findJshintsrc.sh filename.js | jshint ${TMPDIR}flycheck_filename.js --config $(</dev/stdin)
```

I can improve the code if it is welcome as ontribution. I am sorry but I think I am not able to contribute this in Emacs Lisp code without putting to much effort for learning the language. Hopefully somebody with more knowledge can translate it. I will try to check how to change flycheck code to be able to call the previous line of code instead of just jshint. Advices are welcome, I will start trying to change things around https://github.com/flycheck/flycheck/blob/master/flycheck.el#L6682

**Comment by atfornes** [comment]
the creation of the symbolic link might not be necessary if you can always call from the directory where the file to check is. If not, is a way to be able to run everything from the temporary file directory, just calling ```jshint flycheck_filename.js --config flycheck_link_filename.js```

Also, the code have to be improved, it will fail for the case of two files with the same name

**Comment by cpitclaudel** [comment]
I'm not sure that relying on external batch scripts and symlinking is something that we should do. Flycheck support on Windows is very good; depending on unix tools would make it a lot harder to maintain cross-platform compatibility.

**Comment by atfornes** [comment]
I aggree @cpitclaudel.

However, using the scripts is the fastest way I can both scratch my own itch and share the idea on how it can be done (previous attempt was not successful).

**Comment by lunaryorn** [comment]
@atfornes It's about `.jshintignore`, not `.jshintrc`, see #703.   We already deal with `.jshintrc` in Flycheck, but `jshint` doesn't offer an option for the path to `.jshintignore`.  That is why we need `source-inplace` for `jshint`, and I consider this to be a shortcoming of jshint, and not a bug in Flycheck.

I hope to be able to avoid that with #728, but I will not add complicated code to copy arbitrary files from the source tree over to a temporary directory.  That is _way_ too much effort to work around an issue that affects only a very small minority of all syntax checkers in Flycheck.  I'd rather like to see if #728 works for jshint as well.

**Comment by atfornes** [comment]
Fortunately, a way to specify the ```.jshintignore``` file exists in jshint: ```--exclude-path STRINGPass in a custom jshintignore file path```
I think this allows to avoid source-inplace for jshint checker (but not yet to jscs checker)

Aparently, the excludeFiles of jscs are already being resolved relatively to the config file https://github.com/jscs-dev/node-jscs/pull/234. This would solve #703 without the use or ```source-inplace```. However.... I am not able to make it work as expected locally. I will make some tests and open an issue at jscs if is still not working.

Thanks for helping :smile:

**Comment by lunaryorn** [comment]
@atfornes I've reverted #703 because it caused other issues as well.
