### ISSUE TITLE
flycheck-flake8-maximum-line-length not work

### ISSUE THREAD

**Issue by ColorFuzzy** [flycheck/flycheck#378]
1. I set flycheck-flake8-maximum-line-length to 160 `(setq flycheck-flake8-maximum-line-length 160)`
2. Flycheck marks all lines more than 79 chars to error.
3. I run command `M-x: flycheck-select-checkor` and choose `python-flake8`, it also marks all lines more than 79 chars to error.

others: flake8 is in my PATH, and `(executable-find "flake8")` returns the right value

I really don't know why, and thanks!

**Comment by kendriu** [comment]
It doesn't work for me, even if I set `(setq-default flycheck-flake8-maximum-line-length 160)`

**Comment by lunaryorn** [comment]
@kendriu Please open a new issue with details about your setup, and try to explain why you believe that it does not work.  Thank you :)
