### ISSUE TITLE
Some error... ignore until I provide more detailed info

### ISSUE THREAD

**Issue by marcinant** [flycheck/flycheck#434]
flycheck-error-list-set-mode-line: Wrong type argument: arrayp, nil
Error in post-command-hook (global-flycheck-mode-check-buffers): (wrong-type-argument arrayp nil)

**Comment by necktwi** [comment]
Bump after 3 years!
```
(use-package flycheck
  :ensure t
  :init (global-flycheck-mode))
```

When I open an empty `.c`/`.cpp` file I get this error and file won't open!

**Comment by fmdkdd** [comment]
@necktwi That's pretty cryptic.  Can you provide a trace by enabling `toggle-debug-on-error` before reproducing?

**Comment by necktwi** [comment]
you mean `debug-on-error`? which I've already set. I can't find `toggle-debug-on-error`. Here is the printed message
```
locate-dominating-file: Wrong type argument: stringp, nil
Company backend ’company-clang’ could not be initialized:
Wrong type argument: stringp, nil
Error in post-command-hook (global-flycheck-mode-check-buffers): (wrong-type-ar
gument stringp nil)
```

**Comment by necktwi** [comment]
It's because I'm changing default-directory.

**Comment by fmdkdd** [comment]
You should try to make a minimal Emacs configuration where you can reproduce the issue.  Otherwise I can't help you since the `use-package` definition works on my side.

**Comment by necktwi** [comment]
No, thanq! I got the fix!
