### ISSUE TITLE
javascript-eslint has trouble finding the right config files

### ISSUE THREAD

**Issue by xendk** [flycheck/flycheck#447]
I was getting different errors from flycheck running eslint and running it manually, so I looked into what flycheck and eslint does.

When not explicitly supplied a config file as an argument, eslint reads .eslintrc files from the directory of the file, and all parent directories and merge the settings together. Flycheck looks for the config file in the same way, but only supplies the first one to eslint.

So I'd suggest that the `flycheck-eslintrc` variable is defaulted to `nil` and that the `javascript-eslint` checker is changed to use `source-inplace` instead of `source`, to let eslint collect its configuration itself.

The alternative would be to have flycheck find all the configuration files, and supply them on the command line.

**Comment by azangru** [comment]
@jasonkuhrt So have you figured out how to disable jshint and enable eslint? I am now in the exact situation as you were: using jshint by default but would like to try eslint.

**Comment by jasonkuhrt** [comment]
```
  (setq flycheck-disabled-checkers '(javascript-jshint))
  (setq flycheck-checkers '(javascript-eslint))
```

**Comment by jasonkuhrt** [comment]
This no longer works, I'm not sure why.
