### ISSUE TITLE
How i control flycheck list errors

### ISSUE THREAD

**Issue by dongweiming** [flycheck/flycheck#448]
I have  a configuration for flycheck in init.el:

```
(use-package flycheck
  :config
  (progn
    (add-hook 'after-init-hook 'global-flycheck-mode)
    (add-hook 'before-save-hook 'flycheck-list-errors)))
```

I hope before i save buffer mandatory inspection, and list syntax errors. But when not has syntax errors , It also switch to the `* Flycheck errors *`, shows an empty buffer. How to solve when there is no syntax error this buffer will not display?

**Comment by ReneFroger** [comment]
Thanks for the future reference, it helped me a lot now.
