### ISSUE TITLE
Checking only contents of narrowing

### ISSUE THREAD

**Issue by srhb** [flycheck/flycheck#474]
Hello!

I'm trying to do the following:

Edit a markdown document in markdown mode
Clone to an indirect buffer
Narrow to a region
Switch to LaTeX mode

Unfortunately, the flycheck LaTeX checker does not seem to take into account the narrowed region, so Emacs gets extremely slow because of all the warnings from the entire markdown buffer outside of the narrowed region. Is it possible to restrict the flychecked part somehow?

**Comment by unhammer** [comment]
A more general solution would be to have a "buffer-transform" function that is/can be called before these external checkers. E.g. for one checker, I'd very much like to skip some stuff using built-in emacs functions, as well as apply narrowing, by, say, adding a function like

    (setq flycheck-mylint-buffer-transform
          (defun my-narrow-and-clean-buffer ()
            (let ((narrowed-contents (buffer-string)))
              (with-temp-buffer
                (insert narrowed-contents)
                (my-remove-certain-lines)
                (current-buffer)))))

and `flycheck-save-buffer-to-file` would do 

    (let ((b (flycheck-checker-buffer-transform checker)))
      (with-current-buffer (if b (funcall b) (current-buffer))
          …))

**Comment by cpitclaudel** [comment]
@unhammer Interesting idea.  As written this wouldn't work (the call to `b` returns a dead buffer), but you could add a separate "cleanup" function.

**Comment by unhammer** [comment]
Oh right, with-temp-buffer kills the buffer … so with some buffer-juggling we could avoid the cleanup:
    
    (setq flycheck-mylint-buffer-transform
          (defun my-narrow-and-clean-buffer (buf)
            (let ((narrowed-contents (with-current-buffer buf (buffer-string))))
              (with-temp-buffer
                (insert narrowed-contents)
                (my-remove-certain-lines)
                (current-buffer)))))
    
    ;; flycheck-save-buffer-to-file:
    (if-let ((buf (current-buffer))
             (tfm (flycheck-checker-buffer-transform checker)))
        (with-temp-buffer
          (tfm buf)
          do-stuff)
      do-stuff)

**Comment by unhammer** [comment]
I'm currently using this, which seems to do the right thing for me:
    
    (setq flycheck-mylint-buffer-transform
          (defun my-narrow-and-clean-buffer (buf)
            (let ((narrowed-contents (with-current-buffer buf (buffer-string)))
                  (offset (with-current-buffer buf
                            (save-excursion
                              (goto-char (point-min))
                              (save-restriction
                                (widen)
                                (line-number-at-pos))))))
              (insert (make-string (- offset 1) ?\n)) ; simplest way to correct line offsets
              (insert narrowed-contents))))
    
    (setq flycheck-mylint-buffer-transform
          (defun my-narrow-and-clean-buffer (buf)
            (let ((narrowed-contents (with-current-buffer buf (buffer-string))))
              (insert narrowed-contents))))
    
    (defun my-flycheck-checker-buffer-transform-varible (checker)
      "Get the buffer transform variable of CHECKER.
    
    The variable is named `flycheck-CHECKER-buffer-transform'."
      (intern (format "flycheck-%s-buffer-transform" checker)))
    
    (defun my-flycheck-checker-buffer-transform (checker)
      "Get the buffer transform function of CHECKER.
    
    The function is either the value of the variable
    `flycheck-CHECKER-buffer-transform', or nil."
      (let ((var (my-flycheck-checker-buffer-transform-varible checker)))
        (and (boundp var) (symbol-value var))))
    
    (defadvice flycheck-save-buffer-to-file (around advice-maybe-run-buffer-transform first (file-name) activate)
      (if-let ((buf (current-buffer))
               (tfm (my-flycheck-checker-buffer-transform (flycheck-get-checker-for-buffer))))
          (with-temp-buffer
            (funcall tfm buf)
            ad-do-it)
        ad-do-it))
