### ISSUE TITLE
Flycheck not working with Django files

### ISSUE THREAD

**Issue by gafalcon** [flycheck/flycheck#477]
I'm using Flycheck version: 0.21alpha1 (package: 20140908.952) on Emacs 24.3, it works correctly with python files except with django files. 
It only works if I add #!/usr/bin/env python at the beginning or if I rename the files. And also I noticed that if I create a file anywhere with the name of a django file like admin.py, views.py, models.py, then flycheck won't work on them.
Would you please explain me why this happens.. Thanks

**Comment by FabriceSalvaire** [comment]
Same issue https://github.com/fgallina/python-django.el

**Comment by cpitclaudel** [comment]
@FabriceSalvaire Can you clarify what the issue actually is?

**Comment by FabriceSalvaire** [comment]
I don't found how it happen but I got the Django mode in addition to the Python mode for some files like models.py etc. In this case flycheck is disabled, probably because major mode is Django.

```
Django mode defined in ‘django-mode.el’:
Major mode for Django web framework.

In addition to any hooks its parent mode ‘python-mode’ might have run,
this mode runs the hook ‘django-mode-hook’, as the final step
during initialization.
```

**Comment by cpitclaudel** [comment]
Ah, I see (I think?).  I think your issue is described at https://github.com/flycheck/flycheck/issues/506
