### ISSUE TITLE
Flycheck with C++14?

### ISSUE THREAD

**Issue by MaikKlein** [flycheck/flycheck#479]
I found a way to enable C++11 support but I am not sure how I would enable C++14 support? I think I would need to add the following flags to the clang checker 

-stdlib=libc++ -std=c++1y

How would I do this?

**Comment by vyorkin** [comment]
both links are broken now

**Comment by fmdkdd** [comment]
@vyorkin Granted, but that answer was rather old.

- [flycheck-clang-language-standard](http://www.flycheck.org/en/latest/languages.html#variable-flycheck-clang-language-standard)
- [flycheck-clang-language-library](http://www.flycheck.org/en/latest/languages.html#variable-flycheck-clang-standard-library)
