### ISSUE TITLE
Add support for Julia

### ISSUE THREAD

**Issue by Wilfred** [flycheck/flycheck#502]
I'd love to see support for Julia in flycheck.

@pao has written an elisp snippet here: https://gist.github.com/pao/e65029bf88650e592929 (from https://github.com/tonyhffong/Lint.jl/issues/43)

It should just be a matter of creating a pull request including this patch and some unit tests. I'm happy to do it unless anyone beats me to it.

**Comment by gdkrmr** [comment]
https://github.com/gdkrmr/flycheck-julia
