### ISSUE TITLE
Underlines extending into linum-mode gutter

### ISSUE THREAD

**Issue by ryankask** [flycheck/flycheck#504]
I just upgraded to Emacs 24.4 and noticed this:

![2014-10-21 at 08 49](https://cloud.githubusercontent.com/assets/81891/4714774/de9cd68c-58f6-11e4-95b1-eb59d4804dcc.png)

I don't remember this happening in 24.3. Is this the correct behavior?

**Comment by kenixer** [comment]
I'm having exactly same issue, and I'm just using vanilla emacs with prelude. What's the problem?

**Comment by fmdkdd** [comment]
@kenixer You'll have to provide more information about your setup in order to determine where the issue is coming from.  Be sure to test a stock `emacs -Q` without prelude as well.

**Comment by kenixer** [comment]
Yes, there is not a single problem when start emacs with `emacs -Q`.

**Comment by kenixer** [comment]
I just fixed this...this can be fixed by putting `(set-face-underline-p 'linum nil)` in `init.el`. Hope this can help many people.

**Comment by cpitclaudel** [comment]
Note that linum-mode is deprecated (line numbers are supported natively in Emacs' master branch), so it might not be worth spending time to fix this.

**Comment by kenixer** [comment]
Oh, I didn't know that. Then how can I activate that? I updated emacs to the latest, but I don't see any line number as default.

**Comment by cpitclaudel** [comment]
M-x display-line-numbers-mode, I think
