### ISSUE TITLE
Can't use python-pylint checker with custom major-mode

### ISSUE THREAD

**Issue by angrybacon** [flycheck/flycheck#506]
For educationnal purposes, I'm writing an Emacs major mode for Python. First step for me is to underline unused imports, then add a shortcut to remove those unused imports.

``` elisp
(defun yapm-delete-unused-import ()
  (message "It works!"))


(defvar yapm-mode-map
  (let ((map (make-sparse-keymap)))
    (define-key map "[C-c d]" 'yapm-delete-unused-import)
    map)
  "Keymap for `yapm-mode'.")


    ;;;###autoload
(define-derived-mode yapm-mode python-mode "yapm"
  "Yet another Python mode.")

(add-hook 'yapm-mode-hook 'flycheck-mode)
(flycheck-select-checker python-pylint)


(provide 'yapm-mode)
```

I assume Flycheck doesn't know (by default) that he may use `python-piylint` to check `yapm-mode` buffers. So I tried <kbd>M-x</kbd> `flycheck-select-checker` <kbd>RET</kbd> `python-pylint`.

```
user-error: Can't use syntax checker python-pylint in this buffer
```

Syntax checking works fine in a `python-mode` buffer.

**Comment by ackalker** [comment]
@lunaryorn Please document `flycheck-add-mode` (in the info file and perhaps even in the `README.md` file).
I was about to make a feature request along the line of "Please add support for checking in derived modes" when I happened to stumble across thisvery issue. It fits my needs precisely: enable Bash syntax checking in pkgbuild-mode.

**Comment by lunaryorn** [comment]
@ackalker Indeed, the documentation for this function is missing.  Please file a separate issue that we can keep track of this flaw.

**Comment by ackalker** [comment]
@lunaryorn done, see #869
