### ISSUE TITLE
Flycheck using GCC as checker is not recognizing asprintf function when mysql.h is in use

### ISSUE THREAD

**Issue by kozross** [flycheck/flycheck#509]
If you have like this:

```
#include <my_global.h>
#include <mysql.h>
#include <stdio.h>

int main (void) {
    char* s;
    asprintf(s, "%d\n", 10);
    free(s);
}
```

The code works fine, but Flycheck gives a warning on the asprintf line, claiming implicit declaration of that function. I assume that _GNU_SOURCE is set in one of the mysql headers (as Flycheck warns me if I try to define it again), but it seems that Flycheck doesn't recognize this, even with the mysql headers in the include path.

**Comment by mgalgs** [comment]
Depending on the compiler version you might need `-D_GNU_SOURCE` since `asprintf` is a gnu extension.
