### ISSUE TITLE
Wrote an extension to allow syntax checking D using GDC - what can I do to have it added to Flycheck?

### ISSUE THREAD

**Issue by kozross** [flycheck/flycheck#519]
Not an issue as much as a 'I'm a noob when it comes to contributing to free software projects' type question here. I've written a checker for D using GDC, and would like to have it considered for inclusion into Flycheck. However, I have no idea how to do that - could someone please enlighten me? I'd like to help improve a project I'm so reliant on and have found so useful, but I just don't know how.

**Comment by lunaryorn** [comment]
@kozross Closing due to the lack of activity.
