### ISSUE TITLE
Error fixers

### ISSUE THREAD

**Issue by swsnr** [flycheck/flycheck#530]
Add support for error fixers
# Proposed API

Add a `flycheck-try-fix-error-at-point` command, which finds a `flycheck-error` at point and invokes all “fixer” functions in a new abnormal `flycheck-fix-error-functions` hook with the `flycheck-error` object.  Each function in this hook may try to fix this error inline in the current buffer, and return non-nil if it succeeded to do so.  Otherwise it shall return `nil`.  `flycheck-try-fix-error-at-point` will invoke all functions until the first one returns non-nil.

If there are multiple errors at point, the command could either
- prompt for an error to fix,
- or signal a `user-error`.

Feedback on this API is very welcome.
# Implementing new fixers

Flycheck itself will **not** provide any fixers.  This is entirely out of Flycheck's scope, since it's too much unrelated code to maintain.

However, we will provide a `flycheck-fixers` repository in the Flycheck org which will contain a `flycheck-fixers` package with **simple** fixers.  This will mostly be maintained by the community.  More complicated fixers, particularly those that require a deep understanding of the current language, should be maintained in separate packages, though.

Inviting @purcell to this discussion.

**Comment by gracjan** [comment]
Nice idea!

**Comment by gracjan** [comment]
Note: error/warning fixing functionality could help haskell-mode to shed some weight and use flycheck for hlint. hlint offers fixup suggestions and hs-lint-mode makes use of that. Would be so much better if this part was inside flycheck.

**Comment by lunaryorn** [comment]
@gracjan There are man features that should be in Flycheck.  This is a nice addition but it is not my top priority.  It's only available for a small subset of syntax checkers.  Most errors can't be fixed automatically. 

To be honest, if you're waiting for me to implement this you'll have to wait a long time.  On my personal backlog, there are more important things.  In particular there's a dire need for refactoring to provide better support for modes such as Ensime, Merlin or Irony to use Flycheck as a display backend for their own errors.  

I'm sorry but if you'd like to see this feature soon you'll have to implement it yourself and open a pull request.

Note, though, that my point from the original description still stands:  Flycheck itself will only provide the API for error fixers.  It'll _not_ add any fixers on its own, that's just way too much for me to maintain.  Any actual implementation for fixing errors from hlint will have to be distributed independently, probably as part of Flycheck Haskell or Haskell Mode.

**Comment by gracjan** [comment]
haskell-mode would also benefit from from Flycheck error display improvements.

I was able to google Ensime, what is Merlin or Irony?

**Comment by Sarcasm** [comment]
Merlin is an Ocaml thing I think (https://github.com/the-lambda-church/merlin)
Irony is https://github.com/Sarcasm/irony-mode

> On my personal backlog, there are more important things. In particular there's a dire need for refactoring **to provide better support** for modes such as Ensime, Merlin or Irony to use Flycheck as a display backend for their own errors.

Do you have an issue about this somewhere? I had some ideas for flycheck that could be useful for irony but thought about it enough for now to propose you something. Anyway, I will be happy to provide feedback when you work on it, do not hesitate to add me to the issue.

**Comment by lunaryorn** [comment]
@Sarcasm There's no issue yet.

**Comment by ibrahima** [comment]
As a random note, yesterday I came across this as I wanted to autofix some scss-lint feedback, so I spent some time writing some elisp to solve the problem for my specific use case. The API @lunaryorn described seems quite flexible and reasonable to me, and I might end up trying to implement it over the weekend.

For those who are curious, you can start with something like

```elisp
(defun flycheck-iterate-errors (fixer)
  "Loop through flycheck errors and apply FIXER to them."
  (interactive)
  (cl-loop for error in flycheck-current-errors
           do
           (fixer error))
  )
```

In my case, I was trying to fix the property sort order to match what scss-lint suggests, which was pretty easy with transpose-lines. Full example is [here](https://gist.github.com/ibrahima/e3d1227d545538251e9119fcf8241e00), beware, I'm an elisp noob and it's probably ugly code. I used cl-lib and s.el though I may or may  not have actually needed them. But yeah, this seems interesting enough and not really that complex so I might take a stab at generalizing and submitting a PR if I have some free time!

**Comment by cpitclaudel** [comment]
Seconded :) We'll be very very happy to guide and help you with this, if you want to implement it :)

**Comment by lunaryorn** [comment]
@ibrahima I've sent you an invitation for our org, which gives you push access to our repositories.  You'll not be able to push to the protected `master` branch but you don't need a fork to prepare pull requests anymore :)

**Comment by ibrahima** [comment]
Hmm, so the described public API in post 1 seemed quite straightforward. My implementation is below. Interestingly enough, the function I wrote earlier for fixing SCSS-lint property order errors worked (mostly)[1] without any modifications. I still have a few more thoughts below.

```elisp
(defcustom flycheck-fix-error-functions nil
  "Functions to attempt to fix errors. ..."
  :group 'flycheck
  :type 'hook
  :package-version '(flycheck . "0.29")
  :risky t)

(defun flycheck-try-fix-errors-at-point ()
  "Attempts to fix errors at point using the list of fixer functions."
  (interactive)
  (let ((err (car-safe (flycheck-overlay-errors-at (point)))))
    (if err
        (run-hook-with-args-until-success 'flycheck-fix-error-functions err)
      (message "No errors at point to fix!"))))
```

1) Does it make sense to have separate hooks for each language mode or something like that? I can imagine that if a lot of people write fixers for this and you have like 100 fixers in this hook, 95 of which are irrelevant for a given mode, it might be inefficient, but computers are fast these days, so maybe as long as the fixers exit early it's fine? This puts the onus on the fixer to check the mode and whatnot, but they should already have to interrogate the error to know if the fixer applies to begin with, so if the first conditional is to check the major mode maybe that's not so bad.

2) I actually can imagine a scenario where fixer functions give users some choices about how to resolve an error. For example, let's say SCSS-lint reports an error about a duplicated property declaration, eg.

```css
display: none;
color: red;
display: inline-block;
```

The fix would clearly be to remove one of the duplicated declarations, and a fixer function could prompt the user to choose which one to keep. Seems like a popup [[menu](ma)]([url]([url]([url](url)))) like magit-popup or hydra would easily do the job there. Though it seems like this implementation detail is not something Flycheck even has to know about, because all it cares about is calling some functions on an error until one of them returns true, if such a function prompts the user for input I'm thinking that would just work happily.

Any thoughts/feedback on my approach? Thanks!

[1] Not super relevant to this discussion, but I realized after trying to rewrite the elisp in Ruby, that it doesn't actually handle the case where the linter error is not on the first line of a block, because the error message includes all properties in the block, including those that are correctly sorted above the error. But for the purposes of this demonstration it worked!

**Comment by lunaryorn** [comment]
@ibrahima Could you open a pull request for the implementation?  I'd like to discuss the code, and maybe the approach as well, and that's much easier if you can write inline comments on the diff :blush:

To your comments:

1) I guess we could call ourselves happy if we ever get 100 error fix functions.  We don't even have 100 syntax checkers 😉  But even if we get that much success I think calling 100 functions out of which 95 just check a condition and return nil will be fast enough, even on older systems.

I'd also suggest 3rd party packages to use buffer-local additions to `flycheck-fix-error-functions` if an error fixer only applies to a certain buffer, i.e. add a setup function to `foo-mode-hook` which in turn adds a fixer to the local value of `flycheck-fix-error-functions` by passing a non-nil LOCAL arg to `add-hook`.

**Comment by lunaryorn** [comment]
Ad 2) To be honest this situation didn't even occur to me.  You caught me be surprise here :blush:

I haven't thought about it but at a first glance I'd leave the choice of the interface in such cases to the error fixer function.  I don't think that it'd happen often enough to warrant a dedicated infrastructure in Flycheck, and then, I presume making a generic "choose your fix" interface would not be easy.  I presume the details will really depend on the syntax checker and the kind of fixes suggested.

I do think that we may end up with a generic interface for prompts but I'd first like to see how error fixers are used in the wild, how often they actually need to prompt, and what kinds of prompts they need.

I guess in the end we'll have something like the quick fix tool tip in Intellij, but I think it's better to design that after the fact than try and anticipate the needs of 3rd party packages ahead of time.

**Comment by chrisdone** [comment]
If you're looking for ideas about the UX, in Intero we have "suggestions" (based on reading suggestions from error messages provided by GHC) and the UI looks like this: http://commercialhaskell.github.io/intero/#suggestions

![](http://commercialhaskell.github.io/intero/gifs/suggestions.gif)

**Comment by alanz** [comment]
This approach could work well for the [codeAction request](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#code-action-request) in the Language Server Protocol.

I have started adding some support at https://github.com/alanz/emacs-lsp/tree/hie but need to decide how to present the UI.  My initial thought was to piggy back off the `:error-explainer`.

**Comment by jyp** [comment]
Since progress on this issue seemed halted I've implemented a similar functionality in another package. https://github.com/jyp/attrap
Maybe it'll be helpful.

**Comment by swsnr** [comment]
This issue wasn't updated in a long time, and I am no longer interested, so I'm closing this issue to clean up my issues list.
