### ISSUE TITLE
Strange flycheck message in Emacs-Lisp mode "Emacs not compiled with dbus support"

### ISSUE THREAD

**Issue by danielcnorris** [flycheck/flycheck#539]
Whenever flycheck checks my .el files, I get the following message:
"""
Suspicious state from syntax checker emacs-lisp: Checker emacs-lisp returned non-zero exit code 255, but no errors from output: peculiar error: "Emacs not compiled with dbus support"

Checker definition probably flawed.
"""
I'm running Emacs 24.4.1 in iTerm2 on OS X 10.9, installed via Homebrew. 

Is this expected behavior? Is there a way to silence it?

Possibly related issue https://lists.gnu.org/archive/html/bug-gnu-emacs/2014-10/msg00839.html.

Thank you!

**Comment by lunaryorn** [comment]
Closing due to the lack of activity. Seems to be an upstream issue anyways.
