### ISSUE TITLE
New third party plugin for C++: flycheck-irony

### ISSUE THREAD

**Issue by Sarcasm** [flycheck/flycheck#548]
Hello @lunaryorn,

This is not an issue but just a post to inform you that today I have published [flycheck-irony](https://github.com/Sarcasm/flycheck-irony), a simple checker for C, C++ and Objective-C that uses [irony-mode](https://github.com/Sarcasm/irony-mode).

The integration went almost entirely smoothly except the fact that I had some `nil` flycheck errors passed to the callback and the error message was a bit difficult to understand or debug. Since the callback was called in irony-mode process filter, it's probably entirely my fault that it was difficult to debug.

The checker will probably evolve to handle more things correctly, such as error cases or halting/interruption of the error checking.

Thanks for your work on `flycheck` and for the recently introduced generic checkers.

You may, or may not, want to link to this new checker in the documentation.

Best,
Guillaume

**Comment by Sarcasm** [comment]
Just for the record, I regularly stumble upon cases where a file cannot compile but the error comes from a header files.

For example right now I have a file that cannot compile because I'm not following the function contract, a static_assert is triggered in the header but not in the source file. According to flycheck my file compiles but that is not true in practice.

Also I'm wondering, one day I may want to do something when the buffer compiles successfully, for example to re-index the file (or run another checker), if there is an error in the file that shows up in a header, I wouldn't want to do these steps. Will that work with the current design?

**Comment by lunaryorn** [comment]
@Sarcasm I'm not sure whether I understood you correctly, but why can't you just aggregate errors from included files, and show them on the corresponding include line in the current file?

IOW, if the current buffer `foo.cpp` includes `foo.h`, and there's an error in `foo.h`,  just show the error (or a summary of all errors in the include, like the current GCC/Clang checkers in Flycheck do) on the `#include "foo.h"` line in `foo.cpp`.

**Comment by Sarcasm** [comment]
> @Sarcasm I'm not sure whether I understood you correctly, but why can't you just aggregate errors from included files, and show them on the corresponding include line in the current file?

Well, I didn't ask but I was wondering if it was the way to go, I will take this road then.

> IOW, if the current buffer foo.cpp includes foo.h, and there's an error in foo.h, just show the error (or a summary of all errors in the include, like the current GCC/Clang checkers in Flycheck do) on the #include "foo.h" line in foo.cpp.

That will start getting difficult when the error is not in `foo.h` directly but in `bar.h` that is included by `foo.h` but that's my problem.

Thank you.

**Comment by lunaryorn** [comment]
Well, conceptually you need to break down all reports to the done being
checked.  Flycheck is file/buffer based, so you need to show all errors
affecting a for in the corresponding buffer.  There's simply no other place
where Flycheck could show errors.

Clang/GCC fold include errors recursively, so the problem is already solved
in Flycheck.  You may want to look at it.
Am 09.03.2015 13:21 schrieb "Guillaume Papin" <notifications@github.com>:

**Comment by Sarcasm** [comment]
Makes sense, thank you.
