### ISSUE TITLE
Missing dependency to let-alist when installing on emacs 24.3.1

### ISSUE THREAD

**Issue by mikavilpas** [flycheck/flycheck#551]
Hi, I stumbled upon this error when installing on emacs 24.3.1:

`Package`let-alist-1.0.1' is unavailable`

I notice flycheck now requires `let-alist` which I don't have.
I didn't know about that package, but I googled for it and found this, stating that it's new for emacs 25.1:

http://endlessparentheses.com/new-on-elpa-and-in-emacs-25-1-let-alist.html

Is this accidental, or is there a way to work around this somehow?

**Comment by sergeyu** [comment]
Check http://stackoverflow.com/questions/26108655/error-updating-emacs-packages-failed-to-download-gnu-archive

**Comment by d12frosted** [comment]
The same. Just did `git pull` and found that error as well. Wasn't aware of `let-alist` package and haven't seen anything in dependencies list. Thats good that I run into this issue.

**Comment by lunaryorn** [comment]
@d12frosted Please install via package.el from MELPA or MELPA Stable.  I give no support for anything else.  Specifically, if you install directly from Git, it's your job to ensure that all dependencies are present and setup, including autoloads.  If anything breaks, you are on your own.

**Comment by d12frosted** [comment]
@lunaryorn oh, take no offence :D I understand that I am on my own. Just wanted to give a thank to op for opening this issue, so I found what I need a bit faster.
