### ISSUE TITLE
Clang checker pitfall

### ISSUE THREAD

**Issue by maryqueenofscots2nd** [flycheck/flycheck#557]
By mistake (but not uncommon) I put the include paths under the "Includes" option instead of the similarly named  `Include Path` option. Flycheck didn't complain (that's ok...) but it did have the effect of shutting up clang entirely without a trace, it just quietly "vanished" from the error list.

It took me 20 minutes (I'm lying - more) to figure out what happened. Some child proofing would have been welcome.

Just started using Flycheck today and it's wonderful! Thanks!

**Comment by lunaryorn** [comment]
@maryqueenofscots2nd Closing due to the lack of activity.  Feel free to comment if you have more information.
