### ISSUE TITLE
php-phpcs checker doesn't list errors when flycheck-php-phpcs-executable is 1.4.2

### ISSUE THREAD

**Issue by dhaley** [flycheck/flycheck#561]
Hi, with flycheck 0.22, the php-phpcs checker doesn't run on buffer.

First I run flycheck-select-checker and choose php-phpcs.  When I run flycheck-next-error, I get 'No more Flycheck errors.'

I have verified this by running Emacs -Q and only requiring the php-mode and flycheck packages.

However, if I run C-c ! C-c php-phpcs (run syntax checker as compile command) I get the proper phpcs output output: 

https://gist.github.com/dhaley/645fde60cb730396d393

What could be the cause of the syntax checker not running on the buffer.  Let me know what other info I can provide.  Here are a few other of my settings:

% phpcs --version
PHP_CodeSniffer version 2.0.0RC5 (beta) by Squiz (http://www.squiz.net)

%  phpcs -i
The installed coding standards are MySource, PEAR, PHPCS, PSR1, PSR2, Squiz and Zend

**Comment by lunaryorn** [comment]
@dhaley Do the error appears in `M-x flycheck-list-errors`?

**Comment by dhaley** [comment]
No, that buffer is completely blank.

**Comment by mgudemann** [comment]
Hi, I think I have the same problem with `flycheck-mercury', cf. https://github.com/flycheck/flycheck-mercury/issues . I works perfectly with Flycheck 0.21. I have not yet had the time to look deeper into it.

**Comment by dhaley** [comment]
My flycheck lib is the TAG of 0.22 from git (not using the ELPA package).  My php-mode is the latest HEAD of https://github.com/ejmr/php-mode.  Oh and I'm running Emacs 24.4 with only these minor modes enabled -- started with Emacs -Q:

Enabled minor modes: Abbrev Auto-Composition Auto-Compression
Auto-Encryption Blink-Cursor Electric-Indent File-Name-Shadow Flycheck
Font-Lock Global-Font-Lock Line-Number Mac-Mouse-Wheel Menu-Bar
Tool-Bar Tooltip Transient-Mark

**Comment by lunaryorn** [comment]
@mgudemann I don't think so.  I commented on your issue, which I think is an incompatibility with the new requirements for `:error-parser` functions.

**Comment by lunaryorn** [comment]
@dhaley This suggests that Flycheck fails to parse any errors, but I cannot reproduce this issue in the test suite. All PHP tests pass, with Emacs 24.3 and `phpcs 2.1.0`.  

What does `C-h v flycheck-current-errors` show, when typed in an affected buffer?  Also, can you try to run the PHP tests?  Use the following commands:

```
$ cask install
$ cask update
$ test/run.el '(language php)'
```

**Comment by dhaley** [comment]
flycheck-current-errors is nil for the buffer.

Here is the result of "test/run.el '(language php)'"

https://gist.github.com/dhaley/6da11331b31821fa2d12

**Comment by dhaley** [comment]
@lunaryorn  I'm guessing this might be a difference between Emacs 24.3 ands 24.4.  Do you have a way to run your testes with 24.4?

**Comment by dhaley** [comment]
@lunaryorn @xendk I was able to get the Drupal standard working by doing the following:

downgrading phpcs to 1.4.2
downgrading flycheck to 0.21

This is because phpcs 2.1.0 does not work well with the Drupal 7 standard.  It looks like phpcs 2.10 is only supporting Drupal 8, which isn't out for another 1+ years.

And it looks like flycheck > 0.21 does not support phpcs 1.4.2 or older than 0.21 well.

Sebastian, can you write a test for the php-phpcs checker to still support phpcs 1.4.2.  I'm thinking a lot of people wanting to Syntax Check Drupal 7 will run into this same problem.

For now, I'll just have to not upgrade to 0.22.  Let me know if I can provide more information.

**Comment by lunaryorn** [comment]
Set the `$EMACS` environment variable to the Emacs executable you'd like to test with. The output you've shown points to an issue in PHP Mode itself, though, which is entirely unrelated.

**Comment by lunaryorn** [comment]
Sorry, I can't follow you.  What exactly is not supported here?  And what am I supposed to do?

**Comment by lunaryorn** [comment]
Specifically why does Flycheck not work with phpcs 1.4?

**Comment by dhaley** [comment]
Basically, I can't get the php-phpcs checker to run with phpcs 1.4.2.

It worked fine for flycheck 0.21 but broke in 0.22.

You can downgrade phpcs with:
% pear uninstall PHP_CodeSniffer
% pear install PHP_CodeSniffer-1.4.2

**Comment by lunaryorn** [comment]
And what about this Drupal thing?  Your original comment did not mention Drupal at all?

**Comment by lunaryorn** [comment]
*What* does not work? Please, try to be precise.  And please, show the output of phpcs 1.4.

**Comment by dhaley** [comment]
Yeah, the main standard I need to run is 'Drupal', which comes from this project: https://www.drupal.org/project/coder.

According to these instructions and my testing, the Drupal 7 Standard requires phpcs 1.4:

https://www.drupal.org/node/1419988

**Comment by dhaley** [comment]
The output of phpcs 1.4.2 that works with flycheck 0.21 is (from flycheck-list-errors):

![flycheck](https://cloud.githubusercontent.com/assets/746864/5620112/c34f9b3c-94e5-11e4-949c-88c701c67d7c.png)

**Comment by dhaley** [comment]
When I keep everything the same and upgrade to flycheck 0.22, flycheck-list-errors has an empty buffer.

**Comment by lunaryorn** [comment]
@dhaley And the output of `C-c ! C-c` with **Flycheck 0.22**?  That's what I'm interested here, because your observation suggests, that Flycheck can't parse XML output from 1.42.

**Comment by lunaryorn** [comment]
@dhaley Besides, according to the page that you linked, the Drupal standard should work with phpcs 2.1:

> You'll need version 1.4.1 **or higher.**

Isn't that a bug in the Drupal standard?

**Comment by dhaley** [comment]
@lunaryorn 

Here is the output from `C-c ! C-c` with Flycheck 0.22:

https://gist.github.com/dhaley/2e6ec309ed897f7a5f4f

**Comment by lunaryorn** [comment]
@dhaley Sorry, but I still can't reproduce this issue.  When I downgrade phpcs to 1.4.2 with the commands you provided, the test suite fails, but only because phpcs 1.4 reports different errors.  But Flycheck still succeeds to parse errors fro phpcs 1.4.2:

![bildschirmfoto 2015-01-06 um 10 51 50](https://cloud.githubusercontent.com/assets/224922/5626925/1092b2d8-9592-11e4-9cc7-c8a2d97ba334.png)

I did not try with the Drupal standard, because I don't know how to install it, but I don't see how the phpcs standard should make a difference here.  After all, it only affects the contents of reports, but not the report format, and Flycheck should be able to parse errors regardless of the standard used.

**Comment by dhaley** [comment]
@lunaryorn  It looks like the issue with Flycheck 0.22 not being compatibly with phpcs 1.4.2 has nothing to do with the Drupal standard.

The error-list being empty also happens for the default flycheck-phpcs-standard of 'PEAR'.

When flycheck-phpcs-standard is nil, phpcs uses it's default which is PEAR.  Using this standard, when I run `flycheck-next-error`, I get on empty `flycheck-list-errors`.  But when I run `flycheck-compile`, I get these results:

 https://gist.github.com/dhaley/88dea4a6cfc7fa41283c

Also, I did this test with /Applications/Emacs.app/Contents/MacOS/Emacs -Q (Emacs 24.4).  Sebastian, is it possible that I don't have some package loaded, which is why I get different behavior than you?

![emacs-q](https://cloud.githubusercontent.com/assets/746864/5631786/885379c6-9586-11e4-8aee-705334b8bba1.png)

**Comment by lunaryorn** [comment]
@dhaley Well, I used `emacs -Q`, so it's unlikely that you are missing a package.  And I don't think that Flycheck is incompatible with phpcs 1.4.2.  I worked just fine when I tried.

I really have no idea why it doesn't work in your case.  I presume, typing `C-c ! c` doesn't change anything, does it?  And what about other checkers, e.g. Clang in a C file?  Do these work fine?

**Comment by lunaryorn** [comment]
@dhaley  Besides, can you show the output of `M-x flycheck-verify-checker` (ideally, a screenshot) in any affected buffer?

**Comment by dhaley** [comment]
Clang seems to work fine.

![clang](https://cloud.githubusercontent.com/assets/746864/5632444/054b82de-958c-11e4-851d-8f4948608ff3.png)

**Comment by dhaley** [comment]
Here is a screenshot of 'flycheck-verify-setup'

![flycheck-verify-setup](https://cloud.githubusercontent.com/assets/746864/5632472/486a84c0-958c-11e4-8d6a-d60b2aeb276a.png)

**Comment by dhaley** [comment]
@lunaryorn I don't have the function `flycheck-verify-checker`.

These are the interactive functions I have:

![flycheck_commands](https://cloud.githubusercontent.com/assets/746864/5632550/d935d0ea-958c-11e4-8fec-3f80df0be8a4.png)

**Comment by dhaley** [comment]
@lunaryorn Do you think there is a timeout issue.  I noticed that flycheck compile with php-phpcs takes at least three seconds.  Is flycheck possibly giving up before it receives STDOUT from phpcs?

**Comment by lunaryorn** [comment]
@dhaley Sorry for the typo, I meant `flycheck-verify-setup`, of course.  I updated my comment, and removed yours, to avoid further confusion.

I don't think that it's a timeout issue, simply because there is no such timeout in Flycheck.  Flycheck waits inifinitely for syntax checks to finish.  And in any case, three seconds isn't that long:  My init file takes more than 10 seconds to check with `emacs-lisp`, and it works fine.

**Comment by dhaley** [comment]
What about this setting?  `flycheck-display-errors-delay'

I'm wondering if it's somehow related to my compiled Emacs mac port:

https://lists.gnu.org/archive/html/emacs-devel/2014-10/msg00725.html

I'm also doing a `(load file)` on the php-mode.el and flycheck.el which I have in my lisp load path rather than using the packaged versions.

I'm also still on Mavericks rather than Yosemite.  I've got another laptop with Yosemite that I will try the tests out there.

Let me try the tests on my other laptop with the packaged version of php-mode and flycheck and see if that makes a difference.

**Comment by lunaryorn** [comment]
@dhaley `flycheck-display-errors-delay` is unrelated.  It's the delay between moving point onto an error and showing the error message in the mode line.

It might be related to the Mac port, I don't know.  I haven't used it since a long time, and I don't support it anyway.  Please test in a proper GNU Emacs without any patches.

**Comment by dhaley** [comment]
@lunaryorn I noticed this:

When I run `M-: (flycheck-start-current-syntax-check 'php-phpcs)`

`#<process flycheck-php-phpcs<1>>`

the process it launches is this:

ps -ef | grep php
2121158019 88937 81663   0 10:47AM ??         0:00.88 /Applications/MAMP/bin/php/php5.5.18/bin/php /Applications/MAMP/bin/php/php5.5.18/bin/phpcs --report=checkstyle /var/folders/zs/q4v0ywhd181b1wmfd6sfwmzsz6wlc3/T/flycheck81663OgZ/sws_fg.module

But the file /var/folders/zs/q4v0ywhd181b1wmfd6sfwmzsz6wlc3/T/flycheck81663OgZ/sws_fg.module doesn't exist.

Does flycheck make some kind of temp file to check that it then removes?

**Comment by lunaryorn** [comment]
@dhaley No, Flycheck removes temporary files only after the checker has finished.  However, depending on how long the check runs, these files are very short-lived, so it may already be gone by the time you check whether it exists.  `ps -ef | grep php` is just a snapshot of the current state, and if you check the existence of the file just half a second later, Flycheck may already have finished and removed the file in between.

**Comment by lunaryorn** [comment]
@dhaley Do you have any news on this issue?  Did you try to debug it?

I'm very sorry that I can't really help, but I absolutely failed to reproduce this issue, and I'm entirely at a loss about what could possibly cause this issue.

**Comment by ssplawn** [comment]
I am running into what looks to be the same issue. Ive tried it with Emacs 24.1 and 24.4 (I upgraded just to see if it would get rid of it) and with codesniffer 1.5.5 and 2.2.0 
I am on OSX 10.7.5 using the brew install.

**Comment by lunaryorn** [comment]
@ssplawn Can you add any new debugging information?

**Comment by ssplawn** [comment]
If you have any suggestions of what to run, I certainly will. This afternoon I will try to make time to learn how to run the tests. Im a total greenhorn as far as emacs development is concerned.

**Comment by lunaryorn** [comment]
@ssplawn I don't.  If I had any left, I'd have gone through them with @dhaley.

**Comment by periklis** [comment]
Same issue here on flycheck 0.23 and phpcs 2.2.0/2.3.0 with
GNU Emacs 24.4.90.1 (x86_64-apple-darwin14.1.0, Carbon Version 157 AppKit 1344.72)
Any idea how to debug the whole phpcs-checker loop in flycheck lisp code beyond flycheck-verify-setup?

**Comment by periklis** [comment]
i tried to step in with edebug. At least the phpcs process return correctly the error list. Is this helpful for your testcases?

```elisp
 flycheck-parse-checkstyle("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<checkstyle version=\"2.3.0\">\n<file name=\"/Users/username/Projects/aproject/dot-emacs/tmp/flycheck10639jEO/MyScript.php\">\n <error line=\"213\" column=\"5\" severity=\"error\" message=\"Opening brace must be the last content on the line\" source=\"Squiz.Functions.MultiLineFunctionDeclaration.ContentAfterBrace\"/>\n <error line=\"224\" column=\"8\" severity=\"warning\" message=\"Shorthand possible. Replace &quot;Doctrine\\DBAL\\Connection&quot; with &quot;Connection&quot;\" source=\"MO4.Formatting.UnnecessaryNamespaceUsage\"/>\n <error line=\"263\" column=\"8\" severity=\"warning\" message=\"Shorthand possible. Replace &quot;Doctrine\\DBAL\\Connection&quot; with &quot;Connection&quot;\" source=\"MO4.Formatting.UnnecessaryNamespaceUsage\"/>\n</file>\n</checkstyle>\n" php-phpcs #<buffer TranslationExportCommandTest.php>)
```

**Comment by lunaryorn** [comment]
@periklis It does help in that it rules out a possible culprit, but it still doesn't point to the real cause, and since I have entirely failed to reproduce this issue, I can still not continue to debug from this point.

Do you have the time to dig deeper, and find out at which place the list of errors that was successfully parsed from phpcs gets lost?

**Comment by periklis** [comment]
@lunaryorn I am not very familiar with edebug, but sure why not dig deeper and find the root cause. Would you mind to to give me a typical backtrace path after flycheck-parse-checkstyle for putting some breakpoints?

**Comment by lunaryorn** [comment]
@periklis You don't have to use edebug, there are other means of debugging Emacs, too.

`flycheck-parse-checkstyle` is called from `flycheck-parse-output`, which in turn is called from `flycheck-finish-checker-process` and ultimately from `flycheck-handle-signal`.  The latter is automatically called by Emacs, when the checker process exits.

**Comment by periklis** [comment]
@lunaryorn: Any good proposal to drop edebug?

**Comment by lunaryorn** [comment]
@periklis I don't know.  I can't even imagine where this bug comes from, so I am a loss at how to debug it.  I just meant to say, that you probably don't have to use edebug.

**Comment by periklis** [comment]
I tracked the issue down to the ```finish-checker-process funtion```, where ```flycheck-fix-error-filename``` is called. There seems to be an issue with the following part of the code, where the temporary filename is replaced by the current buffer's filename:
```elisp
(when (-any? (apply-partially #'flycheck-same-files-p filename)
                   buffer-files)
        (setq filename (buffer-file-name)))
```
At least the debugger never steps into the setq code. Can you explain what this function is doing? I am new to the elisp api.

**Comment by lunaryorn** [comment]
@periklis Do you have symlinks somewhere along the path to the file being checked?

**Comment by periklis** [comment]
No symlinks used on the file being checked.

**Comment by lunaryorn** [comment]
@periklis Mmh…

**Comment by lunaryorn** [comment]
@periklis Thanks.  I'll take a look.

**Comment by mikkelricky** [comment]
I'm experiencing this issue as well on OS X, and my investigations have sent me down the same path as @periklis has followed. 
The temporary files are written to /var/ which is a symlink to /private/var/. phpcs reports file paths where symlinks are followed, i.e. /private/var/..., but these paths do not match the ones used internally by flycheck (/var/...).

**Comment by lunaryorn** [comment]
@mikkelricky I see.  I'll fix it.

**Comment by periklis** [comment]
:+1:

**Comment by lunaryorn** [comment]
@dhaley @periklis I *think* I fixed this issue, but I'd like to hear from you if PHP CS now works fine with the next MELPA build.

**Comment by periklis** [comment]
@lunaryorn when is the next build expected? Is it once a day?

**Comment by lunaryorn** [comment]
@periklis Sorry, but I don't know the current MELPA build schedule.

**Comment by periklis** [comment]
Many thanks, it works for me now again! Great tdd work!

**Comment by mikkelricky** [comment]
Since only "some syntax checker always output canonical file names with all symbolic links resolved", I think that we may have to check both cases, e.g.
```
(defun flycheck-same-files-p (file-a file-b)
  "Determine whether FILE-A and FILE-B refer to the same file."
  (or
   (string= (directory-file-name (expand-file-name file-a))
            (directory-file-name (expand-file-name file-b)))
   ;; We must resolve symbolic links here, since some syntax checker always
   ;; output canonical file names with all symbolic links resolved.  See
   ;; https://github.com/flycheck/flycheck/issues/561
   (string= (directory-file-name (file-truename file-a))
            (directory-file-name (file-truename file-b)))))

However, I'm not an expert and may be mistaken.

**Comment by lunaryorn** [comment]
@mikkelricky We don't.  `file-truename` is a proper superset of `expand-file-name`.

**Comment by lunaryorn** [comment]
@mikkelricky That said, it's probably a good idea to try the simple test first, and avoid the (comparatively expensive) file system access, if the paths are already equal.  Would you like to open a PR?

**Comment by lunaryorn** [comment]
@mikkelricky Never mind, I already changed the code accordingly.  Thanks for calling this to my attention!
