### ISSUE TITLE
Why is there an ellipsis in the message of Flycheck errors buffer?

### ISSUE THREAD

**Issue by Sarcasm** [flycheck/flycheck#562]
Hi,

I'm wondering what is the purpose of the ellipsis that appears at the end of the messages in the `*Flycheck errors*` buffer, this is visible on the gif for example:

![screencast.gif](https://raw.githubusercontent.com/flycheck/flycheck/master/doc/images/screencast.gif)

I thought for a while that the messages where incomplete/truncated but no. I looked at the code but I can't figure out where it's coming from: flycheck, tabulated-list-mode?

**Comment by lunaryorn** [comment]
It's from the truncation logic in Tabulated List Mode, and occurs on columns with no width.  I don't think there's no easy way to work around this for Flycheck.

Closing.

**Comment by Sarcasm** [comment]
Okay, I see. It looks like the reason this doesn't happen with the `*Packages*` (`M-x package-list-packages`) or `*Process List*` (`M-x list-processes RET`) buffers is that they picked up the last column for lengthy messages. After putting "Checker" between "Level" and "ID", leaving "Message" to the end the ellipses have indeed disappeared.

**Comment by lunaryorn** [comment]
@Sarcasm Originally, the error list was indeed that way, but I changed it at a user's request, who argued that the checker is the least interesting information in the list, and shouldn't occupy precious space before the message, which is arguably the most important thing.

**Comment by Sarcasm** [comment]
Okay. Have you thought about cheating with the tabulated list format and concatenate Message and Checker together, so checker can still be after message but message will lose the ellipsis?

...but that will break sorting so it will that is more code to cause more issues, bad idea.

Question answer, forget about it, I can live with the ellipses.

**Comment by lunaryorn** [comment]
@Sarcasm Well, you could try and get it fixed in Emacs upstream, if you want.

**Comment by Sarcasm** [comment]
That would be the right thing to do indeed, I think I saw a FIXME in the code about that but I will need to look more closely.
