### ISSUE TITLE
flycheck-compile and generic checkers

### ISSUE THREAD

**Issue by Sarcasm** [flycheck/flycheck#563]
I was curious about what was `flycheck-compile` seen on another issue. It looks like it doesn't play nice with generic checkers. I tried with the `irony` checker which was completed in the minibuffer but I get an error ("hard error" I think not a user error).

```
Debugger entered--Lisp error: (void-variable flycheck-irony-executable)
  flycheck-checker-executable(irony)
  flycheck-compile(irony)
  call-interactively(flycheck-compile record nil)
  command-execute(flycheck-compile record)
  execute-extended-command(nil "flycheck-compile")
  call-interactively(execute-extended-command nil nil)
```

Maybe irony shouldn't be completed, or maybe something should be made to display the flycheck-errors returned by irony without executing any program.

**Comment by Sarcasm** [comment]
Great, thank you! :)

**Comment by lunaryorn** [comment]
@Sarcasm You are welcome.  Thanks for your valuable feedback.  I like that someone goes after me and catches all the little issues I conveniently overlooked, or entirely missed!  :+1: Many thanks for your help!
