### ISSUE TITLE
Remove flycheck-ghc-* options as no longer useful

### ISSUE THREAD

**Issue by gracjan** [flycheck/flycheck#565]
In the light of flycheck-ghc-args other options are confusing and get in the way.

I volunteer to do this, just need confirmation that this is a planned change.

**Comment by lunaryorn** [comment]
It's not, what made you think so?  These options are still useful, as local variables and for the customise interface.

**Comment by gracjan** [comment]
Oh, you closed this issues. Does it mean you do not want to hear the reasons?

**Comment by lunaryorn** [comment]
I closed this issue, because I'll not remove these options.
