### ISSUE TITLE
Global flycheck mode should not enable itself in *grep* buffers

### ISSUE THREAD

**Issue by ikirill** [flycheck/flycheck#569]
In a grep buffer the mode is `grep-mode`, which is derived from parent mode `compilation-mode`, which is in turn *not* derived from `special-mode`, but has `'special` mode-class.

So when `flycheck-may-enable-mode` runs, it uses `derived-mode-p` and thinks it's okay to return `t` because no parent of `grep-mode` is `special-mode`. 

    flycheck-version "0.23snapshot (package: 20150115.1159)"
    GNU Emacs 24.4.1 (x86_64-apple-darwin13.4.0, NS apple-appkit-1265.21)

In my grep buffers this led to some weirdness where I couldn't follow links to files, but I'm not sure how that happened or how flycheck interferes with it. I don't think it should be enabled at all.

I think this line is the problem: https://github.com/flycheck/flycheck/blob/master/flycheck.el#L2469

**Comment by LefterisJP** [comment]
ha you got me. I was about to write the same thing here. I got the same problem for a *compilation* and an *AG search* buffer which also derive from compilation mode. I guess that if you changed that conditional to:
```
  (not (or (derived-mode-p 'compilation-mode)
           (derived-mode-p 'special-mode)
           (derived-mode-p 'comint-mode)
           (flycheck-ephemeral-buffer-p)
           (flycheck-encrypted-buffer-p)
           (and (buffer-file-name)
                (file-remote-p (buffer-file-name) 'method)))))
```
this problem would be fixed

**Comment by ikirill** [comment]
Well, `(derived-mode-p 'compilation-mode)` is *far* too specific, and the problem would still exist for other special modes. A better solution would be to check if each parent mode of current mode is either derived from `special-mode` or has `mode-class` set to `special`.

**Comment by ikirill** [comment]
Actually, no, better is just to add another check for `(eq (get major-mode 'mode-class) 'special)`. I think derived modes inherit their parent's mode-class property, so this should work for all special modes.

**Comment by LefterisJP** [comment]
Hm .. I don't know how to do that. I thought that `(derived-mode-p)` was checking the whole hierarchy somehow. But I guess it only checks the first parent? 

Compilation mode is far from specific at least for me. Buffers derived from it cover basically every special buffer I use in my day job.

**Comment by ikirill** [comment]
This isn't really relevant, but `derived-mode-p` checks the whole hierarchy. If you are not sure how to reimplement it, you can always look at its source code, it's quite straightforward:

    (defun derived-mode-p (&rest modes)
      "Non-nil if the current major mode is derived from one of MODES.
    Uses the `derived-mode-parent' property of the symbol to trace backwards."
      (let ((parent major-mode))
        (while (and (not (memq parent modes))
                    (setq parent (get parent 'derived-mode-parent))))
        parent))

**Comment by LefterisJP** [comment]
Oh I see. So what I missed was that compilation mode buffers are *not* derived by `special-mode` but they only have a special `mode-class` value (which is not the same thing). Interesting. And now it all makes sense :)

**Comment by ptrv** [comment]
> In my grep buffers this led to some weirdness where I couldn't follow links to files

Having the same issue with `ag.el`. Checking also for `mode-class` `special` fixes the problem.
