### ISSUE TITLE
make checker: security risks, possibility of accidental loss of data

### ISSUE THREAD

**Issue by ackalker** [flycheck/flycheck#573]
I'm very, very sad to have to submit this, but I feel I must.

Using the current makefile checker in Flycheck can have serious consequences for data integrity and security.
The problem is that running `make -n` or `make -q` may execute arbitrary code.

A harmless example Makefile:

```make
# VAR will be assigned the value "Hi there!"
VAR = $(shell echo "Hi there!")

# The string "Hi there, again!" will be output because of the '+'
foo:
        +echo "Hi there, again!"
```

In this case, both `echo` commands *will* be executed (the first one silently), regardless if `make -n` or `make -q` is used to check.
The implications when editing a Makefile with Flycheck make checker active can be quite serious: when a command being typed is incomplete, it could match and execute another command which could do serious damage.

Perhaps it is better to use a checker based on Makefile::Parser - search.cpan.org : http://search.cpan.org/~agent/Makefile-Parser-0.216/lib/Makefile/Parser.pm or some such.

See also: What’s Wrong With GNU make? - Conifer Systems : http://www.conifersystems.com/whitepapers/gnu-make/

Really sad story, but not unlike the problems with checking shell script syntax using the shell itself...

**Comment by ackalker** [comment]
It is possible to mitigate the risk somewhat: see http://stackoverflow.com/a/22360807/588561

After a little test, I would suggest using `make SHELL=/bin/true -n -f Makefile` or equivalent. Of course, the value for SHELL needs to be adapted for different operating systems...yuck.

**Comment by lunaryorn** [comment]
@ackalker I wasn't aware of this.  If there is no way to prevent make from executing anything, we have no choice but to remove the make checker entirely.

**Comment by ackalker** [comment]
Please see my comment above about setting SHELL to a harmless no-op on the commandline. A drawback of this is that variables computed from shell commands will not get the right values, which can lead to false positives (i.e. errors which really aren't errors) for things like targets computed from these variables.
For example:
```make
VAR=$(shell echo foo)

$(VAR).xml:
        touch $@ # actually, do something useful to try and create foo.xml

foo.html: foo.xml
        xsltproc foo.xsl foo.xml > foo.html
```

would produce an error, something like `Don't know how to make target 'foo.xml'`, because VAR would be empty instead of having the value `foo` during syntax checking.

**Comment by lunaryorn** [comment]
@ackalker Well, it's not that simple.  We cannot currently set arbitrary environment variables for syntax checkers in Flycheck. IOW, Flycheck lacks the infrastructure for this workaround.

Besides, setting `$SHELL` seems… a little flaky, doesn't it?  After all, Make will still try to run shell commands… but then again, I don't know Make enough to assess whether this would really work.

And generally, I don't want to maintain hacky workarounds for specific syntax checkers.  Setting `$SHELL` is not an option for me, as a matter of principle.  I simply don't want to have such hacks in my code, so as I said in #572, if we don't find a way to prevent Make from doing anything stupid in a reliable way, without hacks of this kind, I'll remove Make this weekend.

Note that this doesn't mean the end of Make support at all.  This is free software after all:  You can always copy the checker into your own configuration, or make your own `flycheck-make` package from it.

**Comment by ackalker** [comment]
Ah, I think I wasn't clear in this, in `make SHELL=...`, SHELL isn't an environment variable! It is a Make variable (POSIX calls it a macro) specified on the command line, just as any other commandline parameter, and it should be treated in a special way according to POSIX (i.e. it is not just a GNU extension).

**Comment by ackalker** [comment]
Quoting from http://pubs.opengroup.org/onlinepubs/009695399/utilities/make.html:
```
The SHELL macro shall be treated specially. It shall be provided by make and set to the pathname of the shell command language interpreter (see sh). The SHELL environment variable shall not affect the value of the SHELL macro. If SHELL is defined in the makefile or is specified on the command line, it shall replace the original value of the SHELL macro, but shall not affect the SHELL environment variable. Other effects of defining SHELL in the makefile or on the command line are implementation-defined.
```

**Comment by ackalker** [comment]
I've tested the Perl module `Makefile::Parser`, but alas, no, that's not going to be it either, at least for now. While it has a decent test suite, it currently fails almost all of them, see for example: http://cpantesters.org/cpan/report/40162592-7f82-11e4-9696-c7ea56d63282
Tests fail in different ways for different setups, results on my system had different errors.

**Comment by lunaryorn** [comment]
@ackalker So you mean `make SHELL=/bin/true`?  Are you *sure* that this is enough to completely prevent code execution in the make checker?

**Comment by ackalker** [comment]
@lunaryorn 
It will only prevent accidental code execution. Truly mean, malicious hackers could still set `SHELL=<something bad>` in the Makefile itself.

Come to think of it, even if one has absolutely good intentions, merely editing the line `SHELL=/bin/<incomplete command>` could cause trouble.
Such is the curse of tools like make and most shells, where even the act of letting the tool read in and parse a script can have side-effects...

**Comment by ackalker** [comment]
Before deciding to nix the make checker, perhaps you could borrow a trick from Flymake (with a twist): require users to have a (dummy) target named `check-syntax` in their Makefiles, to indicate that they are aware of the risks of having `make` parse it, like so:
```make
check-syntax:
```
Obviously, you would have to manually check (without using `make`!) that the Makefile indeed contains such a target before allowing the make checker to run. Perhaps using a regex like `^check-syntax:$`.

**Comment by lunaryorn** [comment]
@ackalker I'll remove the Make checker then.  It's not worth it, for me.  YMMV, but as I said, you are free to copy the syntax checker, make your modifications, and add it to your configuration, or maintain it as a separate package.

Flymake does not check Makefiles at all.  It uses the `check-syntax` target to check whatever the Makefile *builds*: For instance, if there's a C file and Flymake finds a Makefile for it, it'd use `make CHK_SOURCES=<source> check-syntax` to check the *C file*.  The purpose of this is to make it easy to use the same settings that the build uses for syntax checking as well.

Flycheck, however, as a different philosophy and design idea, which is why I didn't add this feature.

**Comment by ackalker** [comment]
@lunaryorn 
<blockquote>Flymake does not check Makefiles at all. It uses the check-syntax target to check whatever the Makefile builds</blockquote>
That's why I said: "with a twist". I wasn't implying exact same functionality, the target could serve as a kind of flag which could enable the otherwise disabled checker. The same thing could of course be done using a file-local variable (which also doesn't need searching the Makefile for a regex).
It is sad to see the make checker go, but Flycheck is your project, you decide.

**Comment by lunaryorn** [comment]
@ackalker I'm not in a position to invent a special target just for Flycheck. You'd have a hard time anyway to convince anyone to add a special target to their makefiles to support a single extension for a single editor.  IOW, if I required a special target for the makefile checker, it'd effectively be removed anyway, because no one could use it, at least in projects that are not their own.

I don't understand, why you should be “sad” to see the make checker removed: It's easy enough to simply copy it to your configuration, so what's the problem?

**Comment by ackalker** [comment]
@lunaryorn 
<blockquote>I'm not in a position to invent a special target just for Flycheck. You'd have a hard time anyway to convince anyone to add a special target to their makefiles to support a single extension for a single editor.</blockquote>
The target would be strictly for temporary use, given the risks involved, and should not be shipped in the distributed Makefile.
Anyway, a (file or directory)-local variable would be better. As for including things for specific use, I can't count the number of times I've seen tagging, linting, checking etc. targets in Makefiles (although not to lint the Makefile itself), Gruntfiles, SCons files, WAF projects, etc, which were only useful when certain tools are available. Heck, Emacs header lines and Vim file-local variables only make sense when using that particular editor.

Regarding my sadness to see the checker go: I know where to find it, but future Flycheck users might not even realize there ever was a Makefile checker in the first place, let alone go digging for it in Git history to pull it out from the dust of time.

**Comment by lunaryorn** [comment]
@ackalker There's a difference between a target that *uses* a certain tool, and a target that *supports* a certain tool.  A `lint` target that uses cppcheck only works if you have cppcheck, but it's still useful for the project as a whole, whereas a `syntax-check` target is useful only for Flycheck.

If you care for the “visibility” of the make checker, you can maintain it as a separate package, i.e. `flycheck-make`.  There are already a dozen or more extensions to Flycheck, which are perfectly visible, so I see not why the burden of this complexity should be put upon *my* shoulders.
