### ISSUE TITLE
Use SCSS-lint rather than SCSS

### ISSUE THREAD

**Issue by iainbeeston** [flycheck/flycheck#582]
It would be great if flycheck could use scss-lint in scss-mode, as it's a far more powerful linter than sass.

Sass is a very conservative linter and rarely complains. There is another linter available for scss named [scss-lint](https://github.com/causes/scss-lint) that not only performs syntax checking but also gives stylistic advice as well (I'm a ruby developer by trade and for me the difference is like using `ruby` for linting vs `rubocop`). Unfortunately I'm not sure how to go about patching flycheck myself.

**Comment by lunaryorn** [comment]
@iainbeeston Look at past pull requests for new checkers (you'll find them under the “checker” label).  I'd welcome a better SCSS checker, but I do not have the time to add one myself.

**Comment by iainbeeston** [comment]
I made a start (basing it on the sass checker) but then realised there was
more to it than I expected. I'll try to scrape some time together and
finish it.

**Comment by lunaryorn** [comment]
@iainbeeston Please feel free open a pull request right away, even if it's not complete.  That gives me something to work on, even if you can't complete it, and I can give you early feedback.

**Comment by iainbeeston** [comment]
Thanks, that will be helpful

**Comment by iainbeeston** [comment]
I've created #598 for this. I have some questions, which I'll add to the PR

**Comment by lunaryorn** [comment]
@iainbeeston Great, awesome!  Closing this as duplicate.
