### ISSUE TITLE
ccpcheck checker should support include paths like the clang and gcc checkers

### ISSUE THREAD

**Issue by nickbroon** [flycheck/flycheck#589]
cppcheck takes a -I option that works in similar way to the -I options clang and gcc accept.
Flycheck should support setting this option as it does for these other checkers, so that cppcheck can more completely check code.

**Comment by lunaryorn** [comment]
Feel free to open a pull request.

**Comment by acr4** [comment]
PR #687 submitted to resolve this issue (sorry for the double post, just being thorough)

**Comment by lunaryorn** [comment]
Closing this one as duplicate then.
