### ISSUE TITLE
Rust Multiline Type Errors

### ISSUE THREAD

**Issue by mystor** [flycheck/flycheck#592]
In rustc 1.0.0-Alpha 2, type error reports has changed such that the type information is now on a separate line from the `error:` text. The pattern for capturing error messages to display should be changed to actually capture the type information, rather than just `mismatched types:` (which is what is currently reported by Flycheck).

Flycheck Version: Flycheck version: 0.23snapshot (package: 20150207.329)

**Comment by lunaryorn** [comment]
@mystor Would you mind to show me a type error of this kind?

**Comment by mystor** [comment]
You can experiment with some errors in the [rust playpen](play.rust-lang.org). 
Here are a few type errors (`<anon>` is where the file name would be):

```
<anon>:6:7: 6:11 error: mismatched types:
 expected `core::option::Option<u32>`,
    found `u32`
(expected enum `core::option::Option`,
    found u32) [E0308]
<anon>:6     a(5u32);
               ^~~~
```

```
<anon>:6:7: 6:11 error: mismatched types:
 expected `&u32`,
    found `u32`
(expected &-ptr,
    found u32) [E0308]
<anon>:6     a(5u32);
               ^~~~
```

```
<anon>:7:9: 7:14 error: mismatched types:
 expected `u32`,
    found `u64`
(expected u32,
    found u64) [E0308]
<anon>:7     x = a(&x);
                 ^~~~~
```
