### ISSUE TITLE
customizing the global-flycheck-mode variable

### ISSUE THREAD

**Issue by chillum** [flycheck/flycheck#595]
Hi,

I've just installed Flycheck and it's a very nice thing.

But I'm having an issue with it. I have 0.23-cvs from MELPA (20150207.329) and GNU Emacs 24.4.1 on OS X.

I do: `M-x customize-group`, `flycheck`. I change `Global Flycheck Mode` to `on` and save it.

My Emacs won't start, customize inserts this into my init file:
```elisp
(custom-set-variables
...
 '(global-flycheck-mode t nil (flycheck))
...
)
```

This results in a syntax error in Emacs: `flycheck` is not defined.

As a work-around I can use: `(global-flycheck-mode t)` in my `.emacs`.

I tried to change `'(global-flycheck-mode t nil (flycheck))` to `'(global-flycheck-mode t)`, but in this case the global mode is not initialized.

**Comment by lunaryorn** [comment]
@chillum I think this is an issue in Emacs itself.  May I ask how you installed Flycheck?  Did you use package.el?

**Comment by chillum** [comment]
> I have 0.23-cvs from MELPA (20150207.329)

I have MELPA in `package-archives` (I have my `~/.emacs` [on the GitHub](https://github.com/chillum/.emacs.d/blob/master/init.el) and I did: `M-x package-list-packages`, select `flyspell` and install it. After this, I restart Emacs, do `M-x customize-group flycheck`, set the `Global Flycheck Mode` to `on`, save, restart Emacs and get this behaviour. Now I have FlyCheck `20150325.58` from MELPA and still have this behaviour. But I've discovered that if i do `(require 'flycheck)` before my `(custom-...)` stuff, there's no error.

But anyway, that's not the way `M-x customize` should work -- this is actually the system to eliminate writing Lisp in your config file.

**Comment by lunaryorn** [comment]
@chillum It appears that package.el and customize do not interact well in this aspect.  I asked emacs-devel about this, see https://lists.gnu.org/archive/html/emacs-devel/2015-03/msg00897.html.

In the mean time, I'm afraid there's little I can do.  It's an upstream issue that Flycheck cannot work around.

**Comment by chillum** [comment]
Uhm, frankly, I have one more workaround: `(package-initialize)` before `(custom-...)`.

At the moment, I don't understand one important thing on the topic: why we have to use `'(global-flycheck-mode t nil (flycheck))` instead of `'(global-flycheck-mode t)`.

**Comment by lunaryorn** [comment]
That is not a “workaround”, it's just how you'd use package.el in your init file.  But I see not how that is compatible with your aim to keep code out of your init file and let customize do all setup, and in any case it's not something that Flycheck could do for you.

I'm not sure what you refer to in your second paragraph.  In case you mean the code written to your init file by customize:  That's simply how customize works, and it's not something that Flycheck can control.  `(global-flycheck-mode t)` is not a customize setting, it's just the imperative function call which enables Global Flycheck Mode explicitly.  It's what customize.el would do internally if you enable a global mode through customize.

**Comment by chillum** [comment]
My question was actually: why does the function call look like `(global-flycheck-mode t)` and the custom setting looks like `'(global-flycheck-mode t nil (flycheck))`: in this example `flycheck` is a symbol, where the first problem is (the second one is proper autoloading of flycheck if it's customized).

I've looked through some other packages and found that globally enabling some MELPA modes in customize generally does not work. At this point, I agree, it's an upstream issue, but would suggest to remove the `flycheck-global-mode` custom variable at all and suggest users to enable it with `(global-flycheck-mode t)`. It may be a confusing thing: it needs workarounds to work. But what if some people already use that custom variable and removing this would break their configs?

Maybe, we just should leave everything at current point and wait for a newer better Emacs.

**Comment by lunaryorn** [comment]
@chillum I do not know how customize works, and how it stores and represents settings.  I do not use customize at all.

I agree, that we can't offer a customize interface for Global Flycheck Mode currently.  I changed the code and the documentation accordingly, so from now on and until the issue is fixed upstream `(add-hook 'after-init-hook #'global-flycheck-mode)` is the only official way to enable Flycheck.
