### ISSUE TITLE
R linter intruding into Julia code in ESS buffers 

### ISSUE THREAD

**Issue by mindbound** [flycheck/flycheck#607]
When writing code in Julia, sometimes (especially when declaring modules) I get an error message from r-lintr, which probably shouldn't happen in Julia mode:

```
Suspicious state from syntax checker r-lintr: Checker r-lintr returned non-zero exit code 1, but no errors were output: Error in if (low > 0L) { : missing value where TRUE/FALSE needed
Calls: lint -> retrieve_lint -> lapply -> FUN -> find_new_line
Execution halted

Checker definition probably flawed.
```

**Comment by lunaryorn** [comment]
@mindbound Indeed, this shouldn't happen.  The R checker is only used for ESS Mode.   Does Julia Mode somehow use ESS Mode for anything?

**Comment by lunaryorn** [comment]
@mindbound Did you solve the issue?

**Comment by mindbound** [comment]
Using the standalone Julia mode (provided by the Julia repo) obviously "solves" the problem, since it doesn't depend on or interact with the ESS mode. The problem with Julia minor mode within ESS, however, remains as described in OP.

**Comment by lunaryorn** [comment]
@mindbound No offense meant, but you should have said that in your OP.   I don't know anything about ESS, and I assumed that you were using the standard Julia major mode.

As a quick fix, you can add `r-lintr` to `flycheck-disabled-checkers`, by adding the following to your init file:

```cl
(setq-default flycheck-disabled-checkers '(r-lintr))
```

Ideally, Flycheck would only use `r-lintr` if the current buffer contains R code.  Do you know how I could check that? Is there an R minor mode as well?

Inviting @dholm since he contributed the `r-lintr` checker.

**Comment by mindbound** [comment]
You're right, I should have done that. Right now I have gone back to the standard Julia major mode but thanks for the suggestion.

**Comment by dholm** [comment]
@lunaryorn I hadn't heard of this language before.  I'll see if I can reproduce the issue.

**Comment by lunaryorn** [comment]
@dholm Did you find something to solve this issue?  Probably some kind of minor mode or other indicator that makes sure that the current buffer really contains R code?

**Comment by lunaryorn** [comment]
@dholm @mindbound I'm closing this issue due to the lack of activity.

**Comment by farrellm** [comment]
Yes, ESS sets a buffer local variable ```ess-language``` that gives the language of the buffer. In particular, it is set to "S" for R buffers and "julia" for Julia buffers.

**Comment by lunaryorn** [comment]
@farrellm Thanks, but that's not needed.  I'll just re-open this one.

**Comment by lunaryorn** [comment]
@mindbound @farrellm I added a `:predicate` which checks the value of `ess-language` and only uses `r-lintr` if the language is `S`.

Thanks for reporting this issue, and for helping me out to fix it!
