### ISSUE TITLE
Make Flycheck automatically find packages in Cabal sanboxes (Haskell)

### ISSUE THREAD

**Issue by mrkkrp** [flycheck/flycheck#608]
According to [this issue](https://github.com/flycheck/flycheck/issues/293#issuecomment-31580700), Flycheck now has necessary variables that can be used to support Cabal sandboxes. Indeed, I find `flycheck-ghc-package-datebases` very useful. I searched for a way to make Flycheck automatically find `cabal.sandbox.config` file and use `package-db` value from it without success. Then I wrote something myself.

[Here is the code I've written](https://github.com/mrkkrp/dot-emacs/blob/master/.emacs#L475-L489). Would it be of any interest for Flycheck project? I wanted to make pull request, but it's not so easy to understand how such a big project works and I was not sure that my way of solving the problem is acceptable for Flycheck.

**Comment by lunaryorn** [comment]
Are you not aware of https://github.com/flycheck/flycheck-haskell?

**Comment by mrkkrp** [comment]
Oh, I missed that. When I asked on various IRC channels none happened to tell me about this repo. Thank you!

**Comment by mrkkrp** [comment]
I think I should close the issue, sorry for distraction.

**Comment by lunaryorn** [comment]
@mrkkrp You are welcome :)  Thank you for using Flycheck!
