### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by swsnr** [flycheck/flycheck#616]
Add API documentation to Sphinx.  Should just briefly list the important API, we shouldn't duplicate the docstrings.

**Comment by lunaryorn** [comment]
We should actually generate it automatically, with a little Emacs script that reads `doc/api.texi.template` substitutes certain placeholders with the symbol's docstring wrapped in a `@verbatim` environment, and writes the result to `doc/api.texi` which is in turn included by `flycheck.texi`.

**Comment by swsnr** [comment]
This issue wasn't updated in a long time, and I am no longer interested, so I'm closing this issue to clean up my issues list.
