### ISSUE TITLE
Rust check warning !

### ISSUE THREAD

**Issue by douglarek** [flycheck/flycheck#617]
A hyper demo (https://github.com/hyperium/hyper#example):

![rust-check](https://www.evernote.com/shard/s224/sh/7870d888-4da9-4b79-a127-974d63aa8929/72336f5497e4729c97e796fed6e68b4a/res/178fb989-72aa-4db2-a88b-e8975e5f3182/skitch.png)

```
Flycheck version: 0.23snapshot (package: 20150401.1008)
GNU Emacs 24.4.1 (x86_64-apple-darwin14.0.0
rustc 1.0.0-dev (built 2015-04-03)
cargo 0.0.1-pre-nightly (84d6d2c 2015-03-31) (built 2015-04-01)
```

But I can build it with `cargo build` and no errors.

**Comment by lunaryorn** [comment]
@douglarek Obviously you need to configure the syntax checker to find your dependencies.  Take a look at the [available options](http://www.flycheck.org/manual/latest/Supported-languages.html#index-Language_002c-Rust), or use https://github.com/flycheck/flycheck-rust, which provides some automatism.

**Comment by douglarek** [comment]
@lunaryorn I use `flycheck-rust`, this is my config:
```
(eval-after-load 'flycheck
     '(add-hook 'flycheck-mode-hook #'flycheck-rust-setup))
```

**Comment by lunaryorn** [comment]
@douglarek You probably missed https://github.com/flycheck/flycheck-rust/issues/6…
