### ISSUE TITLE
Elixir checker will eval .exs files

### ISSUE THREAD

**Issue by mattly** [flycheck/flycheck#627]
While `elixirc` will generate output errors, this is more of a side-effect for its main purpose of generating beam bytecode. Elixir also has `.exs` files which are not meant to be compiled, and running `elixirc` on them will instead execute them.

From digging around in the options for both `elixir` and `elixirc` it seems there's no way to get the errors for an `.exs` file. While I'm going to bring this up for the Elixir project, in the meantime we shouldn't eval code just because it's open.

I'm working up a PR for this, but in the meantime wanted to post the issue.

**Comment by lunaryorn** [comment]
Duplicate of #628
