### ISSUE TITLE
Add flycheck-substituted-command-wrapper-function to mangle command after substitution

### ISSUE THREAD

**Issue by lunaryorn** [flycheck/flycheck#629]
>  It'll allow extensions to transform the command after the argument substitution. IOW, it'll get the command as given to call-process, and can do whatever it wants to do with the command.

Primarily for Nix support, see #610 for discussion.

**Comment by purcell** [comment]
Nice.

**Comment by svenkeidel** [comment]
I want to help implementing this feature. I'm also a NixOS user, so I can test this first hand. I started looking through the source where this function could fit in. I would change [these lines](https://github.com/flycheck/flycheck/blob/master/flycheck.el#L4490-L4496) and pass the results to the `flycheck-substituted-command-wrapper-function`.

A problem are calls of `executable-find`. In NixOS executables like `hlint` are made available on a project level, not system-wide. One way to check if a executable is available in a project is to execute the following command: `nix-shell --command 'whereis hlint'`. This is the same way you would wrap every call to a checker with `flycheck-substituted-command-wrapper-function`. My suggestion would be to add a `flycheck-executable-find` function that uses the wrapper function and `whereis` to check if a executable is available in a project or not. The second step would be to replace every occurence of `executable-find` with `flycheck-executable-find`.

What do you think of my suggestions? I upload a prototype of this shortly.

Best,
Sven

**Comment by svenkeidel** [comment]
I have ignored the `executable-find` problem for now. The prototype is [here](https://github.com/flycheck/flycheck/compare/master...svenkeidel:command-wrapper-function)

**Comment by lunaryorn** [comment]
I like the implementation, though there are some minor issues, or things that I'd like to do differently.  For instance while I understand the motivation for `cons` being the default, it's a rather strange thing from a user's perspective.  I'd rather expect `nil` or something along the lines here.  Please do feel free to open a pull request where we can discuss the details of the implementation.  I'll definitely merge it.

I'm not particularly convinced of a `flycheck-executable-find` function that calls `whereis`.  That smells like a very bad hack.  We could add a `flycheck-executable-find` option, though, defaulting to `executable-find`.  You could then override it with a custom function that goes through nix.  Again, I'd welcome a pull request.

That's the most I'd be willing to do for Nix though.  I understand that it's the hot new cool thing(TM), but it's also a nuisance because it doesn't play well with standard Unix patterns (i.e. a `$PATH` where all executables are), and do not want to bloat Flycheck's code to work around these limitations of Nix.

**Comment by svenkeidel** [comment]
Ok, I will improve my implementation and open a pull request in the next few days.

**Comment by lunaryorn** [comment]
@svenkeidel Great!
