### ISSUE TITLE
Foodcritic tries files that doesn't belong to chef cookbooks

### ISSUE THREAD

**Issue by jsirex** [flycheck/flycheck#631]
Here is two use cases:
I'm trying to open `/home/sirex/proj/<projectname>/chef/environments/production` file. It is actually Berksfile. It not recognized (fundamental) and I have to manually enable ruby-mode.
Then, flycheck tries to check this file with foodcritic. But I haven't any folder called `recipes` or `cookbooks` in `/home/sirex/proj/<projectname>/chef/`

Second use case, when I'm actually in cookbook and editing 3rd party file, for example `spec/default_spec.rb` it also tries to check it with foodcritic.

Need help to understand conditions which triggers this check.

**Comment by lunaryorn** [comment]
The conditions are in the [`:predicate` of the food critic checker](https://github.com/flycheck/flycheck/blob/0a86a1790ee793c8c80d647a0c58eaa0cea433f9/flycheck.el#L5499).  Feel free to improve them, and open a pull request :)

**Comment by jsirex** [comment]
Unfortunately, I cannot understand few functions in the code. I'm not a elisp programmer.

But I'll will try later to understand it and fix

**Comment by lunaryorn** [comment]
Closing in favour of #679
