### ISSUE TITLE
haskell-hlint checker gets confused by flycheck's temporary files

### ISSUE THREAD

**Issue by ikirill** [flycheck/flycheck#642]
I get the following hlint warning with `flycheck-20150503.1047`:

       63   5 warning         Reduce duplication
    Found:
      locPos <- attribLocation' program "position" FloatVec2
      vertexAttribArray locPos $= Enabled
      vertexAttribPointer locPos $=
        (ToFloat, VertexArrayDescriptor 2 Float 0 nullPtr)
      bufferData' ArrayBuffer positions StaticDraw
    Why not:
      Combine with /Users/***/src/flycheck_EnvelopesGLFW.hs:141:5... (haskell-hlint)

It seems hlint uses the temporary filename, and although I'm not sure what the warning is for, though, because the line numbers are all wrong (line 63 is the end of a comment line at the end of imports, and about 10 lines away from actual code location).

I'm guessing it's because at https://github.com/flycheck/flycheck/blob/a5a283b74fc7957c870c9931aea84f194d2961b9/flycheck.el#L6265 `haskell-hlint` uses `source-inplace` instead of `source-original`? Would it make sense to use `source-original` instead? I'm not sure if that works with modified buffers, though, or what else that would break.

[Edit] On second thought, this seems to be an hlint issue: it gave me bad line numbers, and that confused me into thinking something about temporary files messed it up and that the warnings flycheck was showing weren't valid. Sorry, my fault!

**Comment by lunaryorn** [comment]
@ikirill I'm glad to see that the issue is solved.  Thanks for reporting nonetheless, since it may help other Flycheck users.

**Comment by ikirill** [comment]
@lunaryorn https://github.com/ndmitchell/hlint/issues/126
