### ISSUE TITLE
f90-mode fortran-gfortran: flycheck not highlighting symbols and not moving between errors

### ISSUE THREAD

**Issue by captainponky** [flycheck/flycheck#654]
Hi,

At least two features of flycheck, error highlighting and moving to next/previous errors, are not working for me in f90-mode for fortran code.
Several sensible errors and warnings are indeed displayed by flycheck in a minibuffer, but none of them are indicated either in the fringes or highlighted in the buffer. Also when I try to move between errors it reads "No more Flycheck errors".

Any ideas where to start searching for the problem/solution would be appreciated.

Suspicious lines I noticed which are displayed in the minibuffer along with the error messages found by flycheck are
- "Suspicious state from syntax checker fortran-gfortran: Checker fortran-gfortran returned non-zero exit code 1, but no errors from output..." which is written before the list of errors
- "Checker definition probably flawed." which is written after the list of errors

M-x: flycheck-version returns 0.24snapshot (package: 20150524.144)
and everything is green from M-x: flycheck-verify.
Thanks.
Ian

**Comment by lunaryorn** [comment]
@captainponky Do you see any errors in error list, i.e. `C-c ! l`?

**Comment by captainponky** [comment]
No. The resulting buffer is empty.

**Comment by lunaryorn** [comment]
@captainponky Then there's a bug in the definition of the Fortran syntax checker.  

I can fix it, but I don't do any Fortran and have no clue of this language (the checker was contributed).  I'll need a *minimal* Fortran example (less than 10 lines if possible) from you that has an error which Flycheck doesn't show.

**Comment by captainponky** [comment]
The following little program gives me all the problems I described. Flycheck displays the error in a minibuffer and any time with `C-c ! c` but nothing shows up with `C-c ! l`.
```
program minimal_example_flycheck
  write (*, *) "Where is my error?" (It's here)
end program minimal_example_flycheck
```

**Comment by captainponky** [comment]
I have had a look into what seems to be going on and find my error messages are output from gfortran in a different format than was the case in #414 which seems to have been the basis for the :error-patterns in flycheck now. By changing some periods to colons and getting rid of some newline characters in the :error-patterns I was able to get things working properly. 

For clarity, by changing 
```
:error-patterns
((error line-start (file-name) ":" line "." column ":\n"
        (= 3 (zero-or-more not-newline) "\n")
        (or "Error" "Fatal Error") ": " (message) line-end)
 (warning line-start (file-name) ":" line "." column ":\n"
          (= 3 (zero-or-more not-newline) "\n")
          "Warning: " (message) line-end))
```

to 

```
:error-patterns
((error line-start (file-name) ":" line ":" column ": "
        ;; (= 3 (zero-or-more not-newline) "\n")
        (or "Error" "Fatal Error") ": "
        (message) line-end)
 (warning line-start (file-name) ":" line ":" column ": "
          ;; (= 3 (zero-or-more not-newline) "")
          "Warning: " (message) line-end))
```
flycheck worked as should for my error messages which were of the form
`/Users/ian/minimal_example_flycheck.f90:3:35: Error: Syntax error in WRITE statement at (1)`

It would be nice to have the error-patterns written in a way that works for both types of error messages.

**Comment by lunaryorn** [comment]
@captainponky I'll fix it some day, but I do not use Fortran, so I'm neither in the best position to fix this issue, nor does it have a high priority for me—on the contrary.  

Patches and pull requests would be very welcome.

**Comment by lunaryorn** [comment]
@captainponky I'm sorry to say that I've changed my mind.  I'll not try and fix this one myself, because I do not know Fortran, and the error messages from `gfortran` are a bloody mess to parse.  It'd take me a lot of time to get right, time which I think is better spent on more important features of Flycheck than individual syntax checkers.

I'm closing this issue as `wontfix`, but I'll happily review and merge pull requests that properly address this issue, or ideally even re-factor the whole way of parsing Fortran messages.

**Comment by captainponky** [comment]
@lunaryorn Thanks anyways. Hopefully I will get around to contributing a proper fix for this someday. But it's not a priority write now for me either.

**Comment by lunaryorn** [comment]
@captainponky I'm sorry that I was unable to solve this issue for, and I hope this doesn't mar Flycheck experience for you.

**Comment by captainponky** [comment]
Nah, flycheck is not marred at all. Flycheck is great. 
I hope to fix this part of it one day, since I use fortran often, but not today.
Ian
Date: Sat, 1 Aug 2015 10:31:52 -0700

**Comment by sebastianbeyer** [comment]
The error message format in gfortran changed in version 5, as noted here: https://github.com/scrooloose/syntastic/issues/1465 
I am now wondering if it would be more advisable to build an error-pattern that matches both of the two variants or adding some additional logic to determine the compiler in use and select the pattern accordingly?

**Comment by lunaryorn** [comment]
@sebastianbeyer The former.  I do not like to have code in Flycheck that tries to determine and adapt to different versions of a tool.  This would end up in way too much code and way too much maintenace effort.

But if a understand the referenced issue aright, it is possible to parse both formats with a single pattern.  I'd welcome a pull request that implements a corresponding fix for Flycheck.

**Comment by sebastianbeyer** [comment]
Okai, I'll try to build this. I am still new to this elisp stuff, so it might take me a while ;-) Can you point me to some more info about the `zero-or-more` etc. regex stuff? I could not find the definition and it is not a standard elisp feature is it?
Thank you!

**Comment by lunaryorn** [comment]
@sebastianbeyer See `C-h f rx` :smile:

**Comment by sebastianbeyer** [comment]
Ah that's nice! 
I made a pull request. Since I have not yet made any contributions to large projects before, I hope it is correct as I did it. 
Travis has support for `gfortran-5`, but I do not now how to make it use both versions.
