### ISSUE TITLE
Flycheck in C++11 mutex include

### ISSUE THREAD

**Issue by poulet-g** [flycheck/flycheck#656]
Hello,
I get this code:
#include "test.hh"
#include \<mutex\>

Test::Test()
{
}

Test::~Test()
{
}

void Test::getVal() const
{
}

void Test::setVal(int val)
{
_val = val;
}

void Test::start(int val)
{
}
Then, when I include the mutex header flycheck send me an error but when I go to the mutex file in /usr/include/c++/4.6/ there is no one error.

**Comment by lunaryorn** [comment]
*What* error?

**Comment by poulet-g** [comment]
Indeed there is no error but the mutex include is underline in red :(

**Comment by lunaryorn** [comment]
@poulet-g Please make a screenshot of the affected line, and show me the output of `C-c ! v` and `C-c ! l` from the affected buffer.

**Comment by lunaryorn** [comment]
@poulet-g Do you have any difficulties to execute the commands that I asked for?

**Comment by poulet-g** [comment]
Sorry it seems to be are the highlighter which is buggy.

**Comment by lunaryorn** [comment]
I'm sorry but I can't follow you… please provide the output of the commands I've asked for and a detailed description of the issue.   Otherwise I'll be unable to help you.

**Comment by poulet-g** [comment]
it seems that it s not the flycheck plugin which is bugging I m sorry about that.

**Comment by lunaryorn** [comment]
I'm closing this issue then.
