### ISSUE TITLE
javascript-eslint on jsx file

### ISSUE THREAD

**Issue by expez** [flycheck/flycheck#663]
Hey

There's a bunch of tutorials about setting up eslint for React lying around, like [this one](http://codewinds.com/blog/2015-04-02-emacs-flycheck-eslint-jsx.html).

When I try I just get:

`user-error: Can't use syntax checker javascript-eslint in this buffer`.

The error message makes me think that you're gonna find this issue annoying, as you've labeled this as a user error.  Given that others have made this work it's somewhat obvious that this is a "user error" but the error gives no indication about why what I'm trying to do is *wrong*.

Here's the offending code:

```el
(defun my-maybe-jsx-mode-hook ()
  (when (and (buffer-file-name)
             (string= (file-name-extension (buffer-file-name)) "jsx"))
    (modify-syntax-entry ?< "(>")
    (modify-syntax-entry ?> ")<")
    (sp-local-pair 'js2-mode "<" "/>")
    (flycheck-select-checker 'javascript-eslint)))
```

**Comment by lunaryorn** [comment]
If you have issues with instructions in a particular blog post, please ask the author of that post for help.

I'll try to improve the error message, but ultimately it's just how it says:  you're trying to enable the checker in a buffer which it doesn't support.  Why that happens is hard to say from your code snippet, as it's obviously not complete (where do you call this hook function?)

I'll need to see your complete Flycheck setup, but I'd prefer if you asked the author of that post.

**Comment by expez** [comment]
> you're trying to enable the checker in a buffer which it doesn't support. 

How does flycheck determine this?  As you probably know eslint is a pluggable linter so the set of linters supported isn't static.

> where do you call this hook function?

As part of `js2-mode-hook`, but just calling `(flycheck-select-checker 'javascript-eslint)`.

This is my flycheck related config:

```el
(add-hook 'after-init-hook #'global-flycheck-mode)
(setq flycheck-completion-system 'ido)

(defun magnars/adjust-flycheck-automatic-syntax-eagerness ()
  "Adjust how often we check for errors based on if there are any.

This lets us fix any errors as quickly as possible, but in a
clean buffer we're an order of magnitude laxer about checking."
  (setq flycheck-idle-change-delay
        (if flycheck-current-errors 0.5 5.0)))

;; Each buffer gets its own idle-change-delay because of the
;; buffer-sensitive adjustment above.
(make-variable-buffer-local 'flycheck-idle-change-delay)

(add-hook 'flycheck-after-syntax-check-hook
          'magnars/adjust-flycheck-automatic-syntax-eagerness)

;; Remove newline checks, since they would trigger an immediate check
;; when we want the idle-change-delay to be in effect while editing.
(setq flycheck-check-syntax-automatically '(save
                                            idle-change
                                            mode-enabled))
```

>  I'd prefer if you asked the author of that post

They're all using `web-mode`, (though that gave me the same error). I'd like to use js2-mode for React code.

**Comment by lunaryorn** [comment]
@expez Flycheck looks at the major mode and other things, depending on the specific syntax checker.  For eslint, it's any of JS Mode, JS2 Mode or JS3 Mode.  The message hence tells you that you are trying to enable eslint in an unsupported major mode.

> As part of js2-mode-hook, but just calling (flycheck-select-checker 'javascript-eslint) in a js2-mode buffer is all that's required to trigger this user error.

I'd like to see the output of `C-c ! v` in that buffer then.

**Comment by expez** [comment]
The problem was with the path to the executable, which was located locally in `node_modules/.bin` instead of being installed globally and on path.  This was obvious after learning about `C-c ! v`.  Thanks for your help!

**Comment by aguynamedben** [comment]
I'm trying to get that post working too. @jeffbski (author of that post) any ideas?

The post does work for getting web-mode and flycheck working nicely on .js/.jsx files. But this line:
```eslint
(flycheck-add-mode 'javascript-eslint 'web-mode)
```
causes flycheck's to run the javascript-eslint checker for **any** web-mode file—when I open a .scss using web-mode, I get JavaScript errors/warnings because flycheck is running .scss through ESLint.

Has anybody found a solution for this? It seems the core issue is that web-mode is a single mode that prefers to be configured by file type (i.e. .js, .jsx, .scss, .html, etc.) and flycheck prefers to determine the linter definitively by mode (which is always web-mode when dealing with these files).

One solution would be if flycheck supported configuring linters by file type (instead of only by major mode), but that doesn't seem likely. web-mode is hugely popular for doing Emacs for web development.

**Comment by fmdkdd** [comment]
@aguynamedben You could inspect the filename of the buffer before enabling `javascript-eslint`:

```emacs-lisp
(flycheck-add-mode 'javascript-eslint 'web-mode)
(setf (flycheck-checker-get 'javascript-eslint 'enabled)
      (lambda ()
        (and
         (string-match-p "\\.js" buffer-file-name)
         (flycheck-checker-get 'javascript-eslint 'enabled))))
```

**Comment by cpitclaudel** [comment]
Hmm @fmdkdd isn't that going to loop?

Something like this maybe?

```elisp
(defun my--is-js ()
  (string-match-p "\\.js\\'" buffer-file-name))

(add-function :before-while (flycheck-checker-get 'javascript-eslint 'enabled) #'my--is-js)
```

**Comment by fmdkdd** [comment]
@cpitclaudel Right, either save the old function or use an advice.  I fixed the snippet.

**Comment by aguynamedben** [comment]
@fmdkdd @cpitclaudel Thank you very much for trying to help me. I'm trying to get either of your solutions working with my use-package config and in either case I can't get past this error:

```
Error (use-package): flycheck/:config: Symbol’s function definition is void: \(setf\ flycheck-checker-get\)
```

When running `M-x` (with helm) I don't see command for `flycheck-checker-get`.

When I run `M-:` and enter `(flycheck-checker-get 'javascript-eslint 'enabled)` to see what the return value is, I get:
```
#[0 "ÃÀ!Á?ÄÀ!Á )ÅÆÇÈÀ$É" [javascript-eslint #[0 "ÂÀ!ÃÀ!Á?Á " [javascript-eslint #[0 "À " [flycheck-eslint-config-exists-p] 1] flycheck-find-checker-executable flycheck-temp-files-writable-p] 2] default-directory flycheck-valid-checker-p flycheck-compute-working-directory lwarn flycheck :warning "%S is no valid Flycheck syntax checker.
Try to reinstall the package defining this syntax checker." nil] 5]
```

The relevant part of my config (uses [use-package](https://github.com/jwiegley/use-package)):
```elisp
(use-package flycheck
  :ensure t
  :custom
  (flycheck-display-errors-delay 0)
  :config
  (global-flycheck-mode)

  ;; disable json-jsonlist checking for json files
  ;; disable jshint since we prefer eslint checking
  (setq-default flycheck-emacs-lisp-initialize-packages t
                flycheck-disabled-checkers '(json-jsonlist javascript-jshint handlebars))

  ;;(flycheck-add-mode 'javascript-eslint 'web-mode)

  ;; Fixups
  ;; use eslint with web-mode for js/jsx files
  (flycheck-add-mode 'javascript-eslint 'web-mode)
  (let ((old-enabled (flycheck-checker-get 'javascript-eslint 'enabled)))
    (setf (flycheck-checker-get 'javascript-eslint 'enabled)
          (lambda ()
            (and
             (string-match-p "\\.js" buffer-file-name)
             (funcall old-enabled)))))

  ;; Workaround for eslint loading slow
  ;; https://github.com/flycheck/flycheck/issues/1129#issuecomment-319600923
  (advice-add 'flycheck-eslint-config-exists-p :override (lambda() t)))
```

Any ideas?

**Comment by cpitclaudel** [comment]
> That one is surprising. Can't seem to reproduce on my end :/

Does use-package compile these forms?
If so, you need to `(require 'flycheck)` first

**Comment by fmdkdd** [comment]
The `:config` section compiles to an `(eval-after-load 'flycheck ...`.  But the point is I get no error at runtime, and the change to `enabled` is in effect, so I don't know what is going wrong in @aguynamedben's case.
