### ISSUE TITLE
 false positive  "xxx.h file not found" error

### ISSUE THREAD

**Issue by ac0x** [flycheck/flycheck#664]
My source folder structure is as below:

CMakeLists.txt
main.cpp
foo/
   - foo.h
   - foo.cpp
bar/
   - bar.h
   - bar.cpp

and flycheck reported "foo/foo.h file not found" in the "bar/bar.h"

am I missing sth?

**Comment by lunaryorn** [comment]
You have to setup the include paths correctly, obviously. Flycheck can't know that `foo.h` is supposed to be `foo/foo.h` from `bar.h`, and it doesn't read CMake build settings automatically.

Take a look at `flycheck-clang-include-path` and `flycheck-gcc-include-path` respectively.

**Comment by ac0x** [comment]
This is a duplicate of issue #665
