### ISSUE TITLE
How to specify dir to the search path for the include files (for c/c++)

### ISSUE THREAD

**Issue by ac0x** [flycheck/flycheck#665]
My source folder stucture is as below:

CMakeList.txt
foo/
    -- foo.h
    -- foo.cpp
bar/
    -- bar.h
    -- bar.cpp

In bar/bar.h, I include "foo/foo.h", but flycheck reported "foo/foo.h file not found".
It seems flycheck doesn't know from where to locate header files, so how to add the search path of header files to flycheck?

**Comment by lunaryorn** [comment]
@ac0x  The [Flycheck manual](http://www.flycheck.org/manual/latest/Supported-languages.html#index-Language_002c-C_002fC_002b_002b) has a comprehensive list of customization options for C/C++ syntax checking, including those options that set the include paths for C/C++.

Please be aware that you can also comment on closed issues in case of further questions, in which case I can reopen the issue, and avoid duplication.

**Comment by ac0x** [comment]
@lunaryorn Thanks. I just noticed that I can specify include paths relative to the file being checked.

If having at most one directory level for sources (like me), a crude but simple solution is as below:

```
(defun my-c-mode-common-hook ()
  (setq flycheck-clang-include-path (list "..")))
(add-hook 'c-mode-common-hook 'my-c-mode-common-hook)
```
