### ISSUE TITLE
Pop-up is messed up

### ISSUE THREAD

**Issue by Eilie** [flycheck/flycheck#666]
For some reason flycheck compilation error popup can't be displayed over text so it chooses to add each line of compilation error popup at the end of existing line:
![](http://i.imgur.com/ETbqtzl.png)

Maybe i've built my emacs without some important use flag for this to work properly?

**Comment by lunaryorn** [comment]
@Eilie I do not know.  Flycheck has no such popup.  It's an issue in flycheck-pos-tip or flycheck-popup, whichever you're using of these.

Closing as invalid.
