### ISSUE TITLE
Haskell GHCJS support

### ISSUE THREAD

**Issue by geraldus** [flycheck/flycheck#667]
Hi Sebastian!  I want Flycheck to support GHCJS.  It's a Haskell to JavaScript compiler.

It has it's own package database, there is a `ghcjs-pkg` executable which is replacement for `ghc-pkg`.   There is a `ghcjs` compiler, which can be used instead of `ghc` to compile separate files, and `cabal-install` tool have GHCJS support since version 1.22.0.0.  Can you give some instructions how to put all this together make Flycheck work for GHCJS project?

**Comment by lunaryorn** [comment]
@geraldus You could try to set `flycheck-haskell-ghc-executable` to `ghcjs`, presuming that it is sufficiently compatible with GHC.  If it's not you'll have to write a custom syntax checker for it.  Take a look at the Flycheck manual, and the existing syntax checkers.

**Comment by geraldus** [comment]
@lunaryorn super cool! I've set `flycheck-haskell-ghc-executable` to `ghcjs` via **.dir-locals.el** file and it works like a charm so far!  Thank you.
