### ISSUE TITLE
User-provided verification functions are ignored by flycheck-define-command-checker

### ISSUE THREAD

**Issue by drvink** [flycheck/flycheck#672]
`flycheck-define-command-checker` does not use what the user provides for `:verify` and instead always uses `flycheck-verify-command-checker`, which only checks for the executable the user provided as the `:command`.  However, the documentation for `flycheck-define-command-checker` specifically states that the user can provide a custom `:verify` function, and that they should be sure to call `flycheck-verify-command-checker` themselves within the provided function, so this appears to be a bug.

See https://github.com/flycheck/flycheck/blob/ec3fa3ce5ac007edd73ec69230bc20bb37cb6efd/flycheck.el#L4022

**Comment by lunaryorn** [comment]
@drvink Ah, thanks for reporting.  I'll fix it, but I'd like to know whether this flaw blocks you in some way.  If not, I'd tackle some other things first, which I think are more important than this one—few people actually use custom verification functions, I regularly need to point authors of generic checkers to this debugging tool.

**Comment by drvink** [comment]
Sorry for the delay in replying--it's not a blocker, no worries!

**Comment by lunaryorn** [comment]
@drvink Fixed, thank you for reporting.  I also added `:verify` functions to some built-in checkers for better debugging.
