### ISSUE TITLE
Problem in parsing Puppet Messages

### ISSUE THREAD

**Issue by Ladeburger** [flycheck/flycheck#675]
This the parser for puppet doesnt catch all error Statements, the Message in the Log is:
`Suspicious state from syntax checker puppet-parser: Checker puppet-parser returned non-zero exit code 1, but no errors from output: Error: Could not parse for environment jahe_dev: Syntax error at 'stage' at /tmp/flycheck19432d0B/init.pp:16:9`

The Error could be triggered by the following Statement:

    class { 'base::root'
     stage => init,
    }

The Error is the missing ':' after the Ressource Name

**Comment by lunaryorn** [comment]
I'll fix it eventually but it doesn't have high priority for.  If you'd like to have it fixed quickly, you'll have to do it yourself and open a pull request.

**Comment by lunaryorn** [comment]
@Ladeburger Closing as duplicate then.
