### ISSUE TITLE
rfringe integration

### ISSUE THREAD

**Issue by thelema** [flycheck/flycheck#678]
Would be nice to have rfringe integration with flycheck.  I'm not experienced enough with emacs to write myself, or would be sending pull request.  Here's what it could look like (pulled from http://emacswiki.org/emacs/FixmeMode request for rfringe support): http://imgur.com/RqBj7.png

There is example integration in rfringe for flymake:
```
(defadvice flymake-post-syntax-check (after
                                      rfringe-indicate-flymake-status
                                      activate compile)
  (rfringe-remove-managed-indicators)
  (let ((err-count (flymake-get-err-count flymake-err-info "e"))
        (warn-count (flymake-get-err-count flymake-err-info "w")))

    (if (or (/= 0 err-count) (/= 0 warn-count))
       (mapc (lambda (item)
               (message "rfringe: marking error at line %d" (car item))
               (rfringe-create-relative-indicator (rfringe--char-pos-for-line (car item))))
             flymake-err-info))))
```

Maybe I just need help translating this for flycheck, so it can be added to ... documentation of flycheck? code of flycheck? code of rfringe?

Thanks much for your awesome flycheck package!

**Comment by lunaryorn** [comment]
@thelema Based on your example, I've come up with [flycheck-rfringe.el](https://gist.github.com/lunaryorn/c5e0e0885c29d234b0f8).  I didn't test it, though, and I'll neither fix nor maintain it.

I'm sorry, but I do not want to be bothered with EmacsWiki packages with no proper code repository, no proper issue tracking, and above all no responsible maintainer.

Feel free to use it, or make your own MELPA package of it, but any flaws, mistakes or errors in that code are yours to fix.   You're on your own with this.

**Comment by lunaryorn** [comment]
PS: If you'd like to use that library, please make a copy of it somewhere, on Github, in the EmacsWiki or in any other place you like.  I tend to clean up my Gist every once in a while, and might then delete this Gist.

**Comment by thelema** [comment]
I understand your hesitation to be bothered by packages like rfringe, and appreciate your willingness nonetheless to try and create something to fill this gap.  I'll try it out and if I have any problems, I understand I'm not to bother you with them.

**Comment by lunaryorn** [comment]
@thelema If you have any issues or questions, or need help, I'd recommend you to ask at https://emacs.stackexchange.com.
