### ISSUE TITLE
Rework food-critic

### ISSUE THREAD

**Issue by lunaryorn** [flycheck/flycheck#679]
The food-critic syntax checker currently suffers from some issues, notably #631 and #626, and some other nuisances.

We need to find a way for food-critic to properly lint recipes and `metadata.rb`, and we need to improve the `:predicate` to strictly limit food-critic to recipes and related files.  Additionally, we should probably chain food-critic to rubocop, to have ruby-linting as well.

**Comment by lunaryorn** [comment]
Ideas, feedback and above all patches and pull requests are very welcome.

**Comment by cpitclaudel** [comment]
This hasn't seen progress in 5 years, so closing it.
