### ISSUE TITLE
Flycheck can't find third party installed packages (Emacs Lisp)

### ISSUE THREAD

**Issue by mrkkrp** [flycheck/flycheck#683]
Maybe I just don't know how to configure it, it seems Flycheck doesn't see packages installed via standard package manager. When I write `(require 'some-package)` I get this message in the minibuffer:

> Cannot open load file: No such file or directory, some-package

First line containing `require` is underlined and I don't see information about the rest of my code. Can you please tell me how to fix this? I'm sure it's not a bug, since problems with Emacs Lisp is something you would have immediately noticed. Thank you.

**Comment by mrkkrp** [comment]
Should I use Cask to let Flycheck know where the packages are? I'm not sure.

**Comment by lunaryorn** [comment]
By default Flycheck checks Emacs Lisp files in a clean environment.  You can change the load path for Flycheck with the option `flycheck-emacs-lisp-load-path`, or tell Flycheck to load your installed packages with `flycheck-emacs-lisp-initialize-packages`.  Please take a look at the docstrings of these options for more information.

If you're using Cask, you can install [flycheck-cask](https://github.com/flycheck/flycheck-cask) to make Flycheck use the packages installed with Cask for each file in a Cask-based project.

**Comment by mrkkrp** [comment]
Thank you very much! This solves my problem. As always, Flycheck is awesome!
