### ISSUE TITLE
Help with setting flycheck-clang-include-path using dir-locals-set-class-variables

### ISSUE THREAD

**Issue by jralls** [flycheck/flycheck#690]
This question is as much about emacs-lisp as about flycheck, but it's flycheck that's making me crazy.
As I'm sure you know, dir-locals-set-class-variables takes a nested alist that looks something like:
((nil . ((flycheck-clang-include-path . ((list "/home/john/foo" "/home/john/bar"))))))

I've tried several variations on that theme -- I really want to defvar something with the paths so than I can construct a complicated set easily and cleanly -- and they all trip up on the 
Error while checking syntax automatically: (error "Value ((list \"/home/john/foo\" \"/home/john/bar\")) of flycheck-clang-include-path for option \"-I\" is not a list of strings")

How do I construct it so that it sees a list of strings?

**Comment by lunaryorn** [comment]
@jralls Use `M-x add-dir-local-variable` and take a look at the result.  In particular, note that `.dir-locals.el` contains _literal_ lists, whereas your example shows that you are trying to call the `list` function, which does not work on `.dir-locals.el`.

If you have further questions about directory variables, please ask at http://emacs.stackexchange.com.

**Comment by jralls** [comment]
Thanks, that showed me the right way.

**Comment by jralls** [comment]
Now I've found a better way, thanks to http://stackoverflow.com/questions/7334565/how-can-i-move-php-mode-settings-from-emacs-to-dir-locals-el:

(defvar include-path (list ("foo" "bar" "baz")))
(dir-locals-set-class-variables 'foo-project
        '((c-mode . ((eval . (setq flycheck-clang-include-path include-path))))))

Provided here for the benefit of future searchers.
