### ISSUE TITLE
flycheck-pylint with python virtualenv

### ISSUE THREAD

**Issue by sandroden** [flycheck/flycheck#692]
Hi, thanks for this wonderful peace of code that worked just fine out of the box!

I can't understand if it's possible to force flycheck  to use a  specific virtualenv for pylint. I get import errors due to the fact that it doesn't seem to use my virtualenv.

I also opened a question on [stackoverflow] (http://stackoverflow.com/questions/31443527/how-can-i-make-flycheck-use-virtualenv) with some more details. I tried using pyvenv-workon from the shell and subsequently C-c ! s python-pylint and the errors show anyway. Is there solution?

Thanks in advance
sandro
*:-)

**Comment by lunaryorn** [comment]
You can set `flycheck-python-pylint-executable` to point to a `pylint` executable inside a virtualenv.  Other than that, Flycheck provides no special support for virtualenvs.

**Comment by sandroden** [comment]
That's perfect, thanks. I didn't note it.

**Comment by lunaryorn** [comment]
@sandroden Take a look at https://github.com/lunaryorn/.emacs.d/blob/master/lisp/flycheck-virtualenv.el.  It's a small piece of code from my Emacs configuration that sets the executable automatically if `python-shell-virtualenv-root` is set.  It should be easy to adapt this to other mechanisms, i.e. get the current Projectile project name, and take the `pylint` for a virtualenvwrapper virtualenv with the same name, or so.

I meant to release this code, but I never got to polishing it, and nowadays I don't write much Python anymore, and have little time for another package to maintain.
