### ISSUE TITLE
Jade checker not working 

### ISSUE THREAD

**Issue by robbyoconnor** [flycheck/flycheck#693]
@lunaryorn -- is there anything in the Jade checker submitted and recently merged in #686 that would cause it to fail  -- I see nothing but maybe you have more insight than I do-- I want to believe that it's not broken -- and am working to fix it ASAP.  I find it **egregious** that it is broken -- not even sure it IS broken...

**Comment by lunaryorn** [comment]
I do not know.  The tests still pass, and without any further information it is impossible to say anything else.  Can you provide any information other than that it's broken, i.e. an error message or at least a description of the faulty behaviour?

**Comment by robbyoconnor** [comment]
@lunaryorn is there a real-time avenue of support?

**Comment by robbyoconnor** [comment]
Okay my tests pass -- so it's a problem with my setup -- not flycheck -- which makes me feel relieved -- I do not want the reputation of contributing code that does not work as expected...At least I got that this narrowed down.
