### ISSUE TITLE
Extend `flycheck-checker-pattern-to-error-regexp` to support custom levels

### ISSUE THREAD

**Issue by cpitclaudel** [flycheck/flycheck#699]
When passed a custom error level, the pcase in `flycheck-checker-pattern-to-error-regexp` returns `nil`, causing messages at that level to be highlighted as errors. This makes it tricky to add custom levels that are not errors.

I can think of an easy fix: we could add an extra keyword arg to define-checker, maybe `compilation-error-level`, which would be any of `('error 'warning 'info)`. The we would replace `(level-no (pcase level` by `(level-no (pcase (flycheck-get-compilation-error-level level)`. This would be backwards-compatible, as existing custom levels would return `nil`, causing the whole `pcase` to return `nil` just as before.

Would such a patch be useful enough to warrant inclusion? If so, I'll provide it.

**Comment by lunaryorn** [comment]
Well, the only place where that is used in Flycheck is `C-c ! C-c` and that's really just a debugging tool.  I'd not invest too much time into it.

I'd accept a patch that fixes compilation patterns for compile mode, but I'd prefer a different approach.  We should add an additional property to error levels, i.e. `compilation-level`, that is either 0, 1 or 2 and maps the level to the corresponding level of compile mode.

**Comment by cpitclaudel** [comment]
Ok, that sounds pretty easy. PR coming soon!
