### ISSUE TITLE
Linting jsx files

### ISSUE THREAD

**Issue by iainbeeston** [flycheck/flycheck#706]
I use web-mode to edit [jsx](https://facebook.github.io/jsx/) files. They're javascript, with embedded xml. [jscs](http://jscs.info) has support for linting them (if you tell jscs to use the [facebook fork of esprima](https://github.com/facebook/esprima) in your .jscs config file) but flycheck doesn't allow me to select jscs as the checker for jsx files.

When I use `flycheck-select-checker` to select `javascript-jscs` I get a `Can't use syntax checker javascript-jscs in this buffer` error. This is possibly because I'm in web-mode - the only checker available to me in web mode is handlebars, but web-mode is the only major mode I've found that has good support for editing jsx files.

Ideally what I'd like to happen is for jscs to be a valid checker in web-mode, but only when the file is a jsx file and only when esprima-fb is available. Unfortunately I'm not sure how to make that happen.

**Comment by iainbeeston** [comment]
Incidentally, web-mode does have support for editing regular javascript and css files.

**Comment by lunaryorn** [comment]
@iainbeeston You can use `flycheck-add-mode` to add Web Mode to jscs in your Emacs configuration, but I'll not add Web Mode support for Flycheck anymore, at least until Web Mode gives us a proper API to check what language it actually contains.  It's been a mess to support before I removed it, and handlebars is an exception which I'm not particularly happy about.

**Comment by iainbeeston** [comment]
That's fair, thanks for explaining
