### ISSUE TITLE
javascript-standard checker can't be used

### ISSUE THREAD

**Issue by yamafaktory** [flycheck/flycheck#707]
Hi,
I am trying to use flycheck-select-checker with javascript-standard which returns "Can't use syntax checker javascript-standard in this buffer", and I am quite unsure about what is the issue there (standard is perfectly working in the terminal).

```lisp
(require 'flycheck)
(add-hook 'after-init-hook #'global-flycheck-mode)
(flycheck-select-checker 'javascript-standard)
```

By the way, thanks for the awesome work!

**Comment by lunaryorn** [comment]
@yamafaktory  In case you're on OS X, install and configure [exec-path-from-shell](https://github.com/purcell/exec-path-from-shell), restart Emacs and try again.  Otherwise show me a screenshot or a copy of the output of `C-c ! v` (aka `M-x flycheck-verify-checker`) in an affected buffer.

**Comment by yamafaktory** [comment]
@lunaryorn many thanks for the help!

Given output is:

```
Syntax checkers for buffer qipp-services-auth.js in js2-mode:

  javascript-jshint
    - predicate:  nil
    - executable: Not found

  javascript-eslint
    - predicate:  nil
    - executable: Not found

  javascript-gjslint
    - predicate:  nil
    - executable: Not found

  javascript-jscs
    - predicate:  nil
    - executable: Not found

  javascript-standard
    - predicate:  nil
    - executable: Not found

Flycheck Mode is enabled.
```

Then I guess it could be related to my setup (zsh with nvm), I will investigate further!

**Comment by lunaryorn** [comment]
@yamafaktory I'm closing this issue then, because it's strictly not an issue in Flycheck itself, but please feel free to add further comments if you need more help on this one.  Thanks for reporting and thanks for your feedback :smile:
