### ISSUE TITLE
I want to toggle flycheck errors window

### ISSUE THREAD

**Issue by mrlee23** [flycheck/flycheck#710]
Hi, I'm very appreciated your project.

command `flycheck-list-erros` has not a toggle feature(delete flycheck errors window), so I want you to add command can toggling. It will be convenient for briefly check errors using flycheck errors window.

Like this:
```elisp
(defun flycheck-list-errors-toggle ()
  "Toggle the error list for the current buffer."
  (interactive)
  (let ((flycheck-errors-window (get-buffer-window flycheck-error-list-buffer)))
	(if (not (window-live-p flycheck-errors-window))
		(call-interactively 'flycheck-list-errors)
	  (delete-window flycheck-errors-window))))
```

**Comment by lunaryorn** [comment]
@mrlee23 Thanks for this idea.  It's a cool feature, but I think it's better fit for your own configuration or an independent extension, the more since there are different approaches to implement this feature.

For instance, I have a `display-buffer-alist` entry for the error list which pins it to the bottom side window, combined with a custom command to close the side window.  This works more like the typical error list dock windows in modern IDEs like Visual Studio or IntelliJ.

Closing as `wontfix`.

**Comment by Sarcasm** [comment]
> For instance, I have a display-buffer-alist entry for the error list which pins it to the bottom side window, combined with a custom command to close the side window. This works more like the typical error list dock windows in modern IDEs like Visual Studio or IntelliJ.

This sounds interesting, do you think you could share this code?

**Comment by lunaryorn** [comment]
@Sarcasm I wrote about it on my blog a few months ago, at <http://www.lunaryorn.com/2015/04/29/the-power-of-display-buffer-alist.html>.

Alternatively take a look at my [init file](https://github.com/lunaryorn/.emacs.d/blob/master/init.el), and watch out for the `display-buffer-alist` setting and the `lunaryorn-window` package declaration.

**Comment by Sarcasm** [comment]
Thanks ;)

**Comment by harrifeng** [comment]
@Sarcasm , I had one naive but simple solution, of course you can bind this toggle function to other keys than f8.

```
(defun` toggle-flycheck-error-buffer ()
  "toggle a flycheck error buffer."
  (interactive)
  (if (string-match-p "Flycheck errors" (format "%s" (window-list)))
      (dolist (w (window-list))
        (when (string-match-p "*Flycheck errors*" (buffer-name (window-buffer w)))
          (delete-window w)
          ))
    (flycheck-list-errors)
    )
  )
(global-set-key (kbd "<f8>") 'toggle-flycheck-error-buffer)
```
