### ISSUE TITLE
HLint does not use `flycheck-ghc-args`

### ISSUE THREAD

**Issue by ntc2** [flycheck/flycheck#713]
HLint does not use the `flycheck-ghc-args` setting. So, for example, custom settings of `flycheck-ghc-args` needed to define Cabal's backwards compatibility macros (`MIN_VERSION_*`) don't help the HLint flychecker, which still complains that they these macros are undefined. See https://github.com/flycheck/flycheck-haskell/issues/39#issuecomment-126771263 for more details.

**Comment by lunaryorn** [comment]
We cannot blindly pass GHC arguments to Hlint.  We'd need a separate option for hlint, but that needs a PR from you or someone else, because I have currently no need for that myself.
