### ISSUE TITLE
Add checker for groovy programming language

### ISSUE THREAD

**Issue by mbezjak** [flycheck/flycheck#715]
It can be done by following:

 * http://www.groovy-lang.org/mailing-lists.html#nabble-td365810
 * https://github.com/groovy/groovy-core/blob/master/src/main/org/codehaus/groovy/control/ErrorCollector.java

**Comment by lunaryorn** [comment]
@mbezjak I do not use Groovy, and will not write a syntax checker for it myself.  I have neither the time nor the motivation.  Please open a pull request which adds the checker to Flycheck with tests and documentation.

**Comment by lunaryorn** [comment]
Closing as `wontfix`.

**Comment by mbezjak** [comment]
I'm in the process of doing just that. I opened an issue just so I could reference it in `CHANGES.md`

**Comment by lunaryorn** [comment]
@mbezjak :smile: That's nice, but not needed at all.  I'll reference the PR in CHANGES, because that's the relevant issue.
