### ISSUE TITLE
Flycheck error Invalid search bound

### ISSUE THREAD

**Issue by hotpxl** [flycheck/flycheck#719]
I encountered something like this. I have `debug-on-error` turned on so you can see the stack trace. I blurred some paths. Do you have any idea what might have caused this?

![Imgur](http://i.imgur.com/BQ81vOR.jpg)

**Comment by lunaryorn** [comment]
@hotpxl Where does `fringe-helper-modification-func` come from?  It's neither part of Emacs nor of Flycheck…

**Comment by hotpxl** [comment]
I guess it's from git-gutter. I will have it disabled and test for a while. Thanks!

**Comment by lunaryorn** [comment]
@hotpxl I'll close this issue as invalid then.  If it still breaks, please add another comment and I'll reopen it.

Meanwhile, you can report this issue to git-gitter, and try diff-hl, which is an alternative to git-gutter.
