### ISSUE TITLE
What is the proper way to selectively turn off flycheck?

### ISSUE THREAD

**Issue by Malabarba** [flycheck/flycheck#723]
There are many buffers where I would like flycheck to not run (dir-locals, scratch, and root-owned files). Is there a variable I can configure to tell `global-flycheck-mode` on which buffers it should actually activate? 

Or should I just add a function to the mode-hook that turns it off in those buffers?

**Comment by lunaryorn** [comment]
@Malabarba I'd argue that a hook is the proper way to selectively do things in Emacs :)  Other than that, Flycheck only offers to disable it's mode for specific major modes, as per `flycheck-global-modes`.  

I think we should probably exclude `.dir-locals.el` from the `emacs-lisp` checker in Flycheck itself, but why wouldn't you want to check scratch buffers?  Besides, as far as the initial buffer is concerned, Flycheck won't check that anyway, since it's not backed by a file…

It also won't check root-owned files, because these should be in read only mode, and Flycheck doesn't check read only buffers.

**Comment by Malabarba** [comment]
> but why wouldn't you want to check scratch buffers? Besides, as far as the initial buffer is concerned, Flycheck won't check that anyway, since it's not backed by a file…

That's strange, I could have sworn that non-file buffers were checked as well. I even had an advice for preventing that. But now I can't reproduce it, so maybe I'm just going nuts.

> It also won't check root-owned files, because these should be in read only mode, and Flycheck doesn't check read only buffers.

Except I sometimes use `toggle-read-only` to play around with the buffer visiting the root file, and then flycheck immediately turns on. The fact that it turns on isn't a huge deal, the problem is that it'll keep throwing errors at me whenever I make an edit, because it can't create the flycheck file.

Maybe this can be considered a bug? It's really corner-case, but perhaps flycheck should stop trying if it can't create the file.

-----

Besides that, I like to disable flycheck in files that are not properly formatted as elisp packages, just to reduce unwanted noise. These could be test files or some of my personal config files. But there's really no way for flycheck to predict these situations, which is why I was asking if there was a variable for that. But I can just keep using hooks and advices instead. :)

**Comment by lunaryorn** [comment]
@Malabarba Generally Flycheck will check non-file buffers, but the `emacs-lisp` checker specifically doesn't work for such buffers, hence it won't check scratch.

Flycheck trying to write to places it can't write to is surely bug, but one that I'd close as `wontfix`.  It's so small a corner case that it's really not worth spending a lot of time on.  You're the first to hit this in two years.  As always, I'll accept PRs, but I won't try and fix that myself.  And besides, you can always explicitly `M-x flycheck-mode` to disable Flycheck, if it's not working correctly.

I'm not sure what you mean in your last paragraph.  How can your personal configuration files not be “properly formatted”?  I mean, Emacs is supposed to evaluate them, so they're supposed to be syntactically valid?

Or does "formatted" refer to the checkdoc warnings?  In that case, use `M-x flycheck-disable-checker` to disable individual syntax checkers, or set `flycheck-disabled-checkers` via file or directory variables.  For instance, you could put `emacs-lisp-checkdoc` into that variable in `~/.emacs.d/.dir-locals.el` to keep checkdoc warnings out of your init files.

Closing as `wontfix`.

**Comment by Malabarba** [comment]
> Or does "formatted" refer to the checkdoc warnings? 

Precisely.

> In that case, use M-x flycheck-disable-checker to disable individual syntax checkers, or set flycheck-disabled-checkers via file or directory variables. For instance, you could put emacs-lisp-checkdoc into that variable in ~/.emacs.d/.dir-locals.el to keep checkdoc warnings out of your init files.

Thanks, I wasn't aware of this. Look's like it's what I need! :+1:

**Comment by lunaryorn** [comment]
@Malabarba I'm closing this issue as fixed then.

**Comment by cpitclaudel** [comment]
I've opened https://github.com/flycheck/flycheck/pull/1635 to fix this

**Comment by zoechi** [comment]
I was looking for a way to disable flycheck for dependencies, for example when I look up function parameters or otherwise investigate 3r-party dependencies.
A preferred way would be to provide a list of directories that should be ignored completely. I don't want to disable LSP for example, because I still want code navigation.

**Comment by cpitclaudel** [comment]
@zoechi please open a separate issue; it'll make it easier to discuss the problem
