### ISSUE TITLE
Indenting multi-line error messages

### ISSUE THREAD

**Issue by cpitclaudel** [flycheck/flycheck#731]
Hi Sebastian,

At this time, multiline error messages are flushed left: `tabulated-list-mode` makes no effort to align the left sides of column values that span multiple lines. This makes multiline error messages a bit hard to read:

![multiline error](https://cloud.githubusercontent.com/assets/8181630/9351260/bfff1d4e-460c-11e5-8073-6d4f75ebd6d3.png)

Things look a lot better to me with the right indentation:

![multiline error with indent](https://cloud.githubusercontent.com/assets/8181630/9351259/bffe925c-460c-11e5-8030-f2ced9abb79e.png)

If we wanted to always do this, we could use the fact that `tabulated-list-mode` lets us customize the entry printing function, allowing us to slightly adjust it to insert the right indentation. I got the results shown above by adding

```elisp
(setq label (replace-regexp-in-string "\n" (concat "\n" (make-string x ?\s) "⤷") label t t))
```

to the implementation of `tabulated-list-print-col`. This seems to work well, but it does require duplicating the definitions of `tabulated-list-print-entry` and `tabulated-list-print-col` in Flycheck (that's about 60 lines of code).

What do you think? Does this sound like a desirable feature? Are there other easy ways in which we could achieve the same effect?

**Comment by lunaryorn** [comment]
@cpitclaudel We can simply compute the (fixed) offset of the message column, and manually prepend a corresponding amount of whitespace to all but the first line of messages in `flycheck-error-list-make-entry`.   I'd prefer this approach to duplicating parts of Tabulated List Mode in Flycheck.

Ultimately, though, I think that this is an issue in Tabulated List Mode itself, and we should at least `M-x report-emacs-bug` to make Emacs upstream aware.

However, personally I don't consider this issue particularly important.  It's a minor visual flaw in the error list, but it doesn't really have an adverse effects other than not looking that nice and making messages slightly harder to read.  I'll merge a PR, but I don't think that I'll spend my own time on fixing it.

Closing as `wontfix`—which just means that it's not something that I'll work on.  A PR or patch would be really welcome, as always :smiley:
