### ISSUE TITLE
Errror with php-phpcs checker

### ISSUE THREAD

**Issue by exu** [flycheck/flycheck#737]
Hi I have following error when trying to check php file with phpcs checker: 

Suspicious state from syntax checker php-phpcs: Checker php-phpcs returned non-zero exit code 1, but no errors from output:   

<?xml version="1.0" encoding="UTF-8"?>
<checkstyle version="2.3.3">
<file name="/tmp/flycheck1608RuU/JoinJobTest.php">
 <error line="20" column="12" severity="error" message="Missing function doc comment" source="Symfony2.Commenting.FunctionComment.Missing"/>
</file>
</checkstyle>

Checker definition probably flawed.

My emacs:
GNU Emacs 24.5.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.16.2) of 2015-04-20 on bitzer.hoetzel.info

Flycheck version: 0.25snapshot (package: 20150821.47)

**Comment by cpitclaudel** [comment]
Hi exu,
Do you have an example of a file showing this behaviour?

**Comment by exu** [comment]
Any file :) for example

    <?php
    
    /**
     * @author Jacek Wysocki <jacek.wysocki@gmail.com>
     */
    class Something
    {
        public function __construct($options=array())
        {
            if (is_array($options)) {
                foreach ($options as $k => $v) {
                    $this->$k = $v;
                }
            }
    
        }
    }

give me 

    Suspicious state from syntax checker php-phpcs: Checker php-phpcs returned non-zero exit code 1, but no errors from output:   
    
    <?xml version="1.0" encoding="UTF-8"?>
    <checkstyle version="2.3.3">
    <file name="/tmp/flycheck1608sYE/test.php">
     <error line="6" column="5" severity="error" message="Missing class doc comment" source="Symfony2.Commenting.ClassComment.Missing"/>
     <error line="7" column="5" severity="error" message="Expected 0 spaces before opening brace; 4 found" source="PEAR.Classes.ClassDeclaration.SpaceBeforeBrace"/>
     <error line="8" column="16" severity="error" message="Missing function doc comment" source="Symfony2.Commenting.FunctionComment.Missing"/>
    </file>
    </checkstyle>
    
    Checker definition probably flawed.

**Comment by exu** [comment]
When I'm running it from shell it returns result code == 1

    ❯ phpcs ~/src/test.php 
    
    FILE: /home/exu/src/test.php
    ----------------------------------------------------------------------
    FOUND 8 ERRORS AND 1 WARNING AFFECTING 5 LINES
    ----------------------------------------------------------------------
     3 | ERROR   | [ ] Missing short description in doc comment
     5 | WARNING | [ ] PHP version not specified
     5 | ERROR   | [ ] Missing @category tag in file comment
     5 | ERROR   | [ ] Missing @package tag in file comment
     5 | ERROR   | [ ] Missing @license tag in file comment
     5 | ERROR   | [ ] Missing @link tag in file comment
     6 | ERROR   | [ ] Missing class doc comment
     7 | ERROR   | [x] Expected 0 spaces before opening brace; 4 found
     8 | ERROR   | [ ] Missing function doc comment
    ----------------------------------------------------------------------
    PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY
    ----------------------------------------------------------------------
    
    Time: 17ms; Memory: 3.25Mb
    
                                                                                                      
    ~/src/github.com/exu master*
    ❯ echo $?
    1

**Comment by lunaryorn** [comment]
@exu Where does the blank line in the beginning of the output come from?  Do you have any special settings in `php.ini`?

**Comment by exu** [comment]
no, there is no special php.ini settings 

But I have also problem with go checker: 

    Suspicious state from syntax checker go-build: Checker go-build returned non-zero exit code 2, but no errors from output: go: GOPATH entry cannot start with shell metacharacter '~': "~/"

    Checker definition probably flawed.

**Comment by exu** [comment]
Ok go is working ok it was problem with GOPATH

**Comment by lunaryorn** [comment]
@exu Can you show the output of `phpcs --report=checkstyle foo.php` where `foo.php` is a PHP file with phpcs warnings?

**Comment by exu** [comment]
Hi sorry for delay but I was on vacation. Here you are: 

    ❯ phpcs  --report=checkstyle --standard=PSR2 t.php 
    <?xml version="1.0" encoding="UTF-8"?>
    <checkstyle version="2.3.3">
    <file name="/home/exu/src/ioki.com.pl/ngmel-dev/t.php">
     <error line="1" column="1" severity="warning" message="A file should declare new symbols (classes, functions, constants, etc.) and cause no other side effects, or it should execute logic with side effects, but should not do both. The first symbol is defined on line 64 and the first side effect is on line 2." source="PSR1.Files.SideEffects.FoundWithSymbols"/>
     <error line="64" column="1" severity="error" message="Each class must be in a namespace of at least one level (a top-level vendor name)" source="PSR1.Classes.ClassDeclaration.MissingNamespace"/>
     <error line="104" column="1" severity="error" message="Each class must be in a file by itself" source="PSR1.Classes.ClassDeclaration.MultipleClasses"/>
     <error line="104" column="1" severity="error" message="Each class must be in a namespace of at least one level (a top-level vendor name)" source="PSR1.Classes.ClassDeclaration.MissingNamespace"/>
     <error line="146" column="143" severity="warning" message="Line exceeds 120 characters; contains 143 characters" source="Generic.Files.LineLength.TooLong"/>
     <error line="159" column="133" severity="warning" message="Line exceeds 120 characters; contains 135 characters" source="Generic.Files.LineLength.TooLong"/>
     <error line="172" column="133" severity="warning" message="Line exceeds 120 characters; contains 136 characters" source="Generic.Files.LineLength.TooLong"/>
     <error line="207" column="128" severity="warning" message="Line exceeds 120 characters; contains 128 characters" source="Generic.Files.LineLength.TooLong"/>
    </file>
    </checkstyle>

**Comment by lunaryorn** [comment]
@exu The output looks fine, and I can't reproduce the issue locally.  Please check your Emacs environment.  Particularly:

- Check that the PHP version in Emacs is the same as in your terminal.  Use `M-: (process-lines "php" "--version")` to determine the PHP version in Emacs.
- Likewise, check that phpcs in your Emacs is the same as in your terminal.

**Comment by kostajh** [comment]
I'm seeing something similar, so I figured I would add it here (let me know if you'd prefer a new issue):

```
Suspicious state from syntax checker php-phpcs: Checker php-phpcs returned non-zero exit code 2, but no errors from output: ERROR: the "DrupalPractice and Drupal" coding standard is not installed. The installed coding standards are MySource, PSR2, Zend, Squiz, PHPCS, PEAR, PSR1, DrupalPractice and Drupal

Checker definition probably flawed.
```

`php` and `phpcs` versions are identical if run from command line or using `M-: (process-lines "php" "--version")`

I should note that I haven't changed my configuration for Flycheck/Drupal mode lately, and up until quite recently (a week? two?) the checker worked flawlessly in Emacs.

**Comment by exu** [comment]
@lunaryorn It looks the same
```
PHP 5.4.26 (cli) (built: Sep 18 2015 13:45:49) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies
    with Xdebug v2.3.2, Copyright (c) 2002-2015, by Derick Rethans

("PHP 5.4.26 (cli) (built: Sep 18 2015 13:45:49) " "Copyright (c) 1997-2014 The PHP Group" "Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies" "    with Xdebug v2.3.2, Copyright (c) 2002-2015, by Derick Rethans")

PHP_CodeSniffer version 2.3.3 (stable) by Squiz (http://www.squiz.net)

("PHP_CodeSniffer version 2.3.3 (stable) by Squiz (http://www.squiz.net)")
```

Could it be related to old php version? (I need it for legacy project) - I'm using PHP with phpbrew.

**Comment by lunaryorn** [comment]
@exu I do not know.  Actually I'm just making wild guesses, for I have no clue what could cause this issue.  All that I see is that the unit tests pass in our testing environment, which indicates that it's possibly a local issue with your configuration.  But since I don't really know PHP at all, I'm a little lost now.

I see, though, that forgot to ask for a specific thing:  Would you mind to show the output of `C-c ! C-c php-phpcs` in an affected buffer?

**Comment by lunaryorn** [comment]
@exu I'm closing this due to the lack of activity.  If you can provide any additional information, please feel free to comment, and I'll reopen it.

**Comment by lovett** [comment]
Hello, I have some additional information about this issue.

I ran across the same error as was originally reported, using v2.6.1 of phpcs. As hinted at in an earlier comment by @lunaryorn, the problem appears to be the two blank newlines added by phpcs prior to emitting the checkstyle XML document when running in non-verbose, non-interactive mode. When I remove these newlines, flycheck is happy. When I put them back in, the "Checker definition probably flawed" error message returns. The checkstyle XML itself is otherwise fine.

[Here is where the offending newlines appear](https://github.com/squizlabs/PHP_CodeSniffer/blob/19ee67081a15ede42ae080d555d5e953316fcc26/CodeSniffer.php#L683). It doesn't look like they are a recent addition in phpcs. Maybe flycheck's XML parsing was more tolerant of leading whitespace in the past? Just guessing.

**Comment by cpitclaudel** [comment]
Hi @lovett,

Thanks for the input. Could it be that $showProgress is true on some machines, but not others?

**Comment by lovett** [comment]
Thank you @cpitclaudel, `$showProgress` was the indeed the culprit.

I was using a custom phpcs standard (set with `flycheck-phpcs-standard`) which contained a flag (`<arg value="sp" />`) that caused `$showProgress` to be turned on. This is something I picked up from the [phpcs wiki](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Annotated-ruleset.xml). This argument is nice for CLI output because it tells you which rule triggered a linting error. But it has the side effect of introducing the unwanted newlines that interfere with flycheck.

I had thought I could set the `sp` arg by itself, which is different from what is shown on the phpcs wiki. I'll instead do that in a different way so that there is no interference.
