### ISSUE TITLE
Replace the GIF with a annotated screenshot of Flycheck at work

### ISSUE THREAD

**Issue by lunaryorn** [flycheck/flycheck#743]
I'd like to replace the README "video" with an annotated static screenshot of Flycheck.   Take a look at the [screenshots of the Napkin App](https://itunes.apple.com/us/app/id581789185?mt=12&ign-mpt=uo%3D4) to get an idea of what I mean.

I think the video does a bad job of demonstrating what specific features Flycheck actually provides, and the "animation" very quickly tends to feel "noisy" when looking at the Github page.  A static image, which has "annotations" and highlights for each specific feature of Flycheck (i.e. the error list, the mode line reporting, the fringe indicators, the underlines, etc.) provides more information with less noise.

@tonini, @purcell, @cpitclaudel Your opinions?

**Comment by tonini** [comment]
I like the idea, I had the same thought too for Alchemist's README (to remove these noisy GIF's). 
But I find it kind of hard to bring all features and highlights on one image at once. 

I think it's worth the effort, maybe have a look at jetbrains product presentation images, I quite like the loupe effect. https://www.jetbrains.com/webstorm/?fromMenu

**Comment by cpitclaudel** [comment]
I think it's a great idea. I like the gif, but I think in the case of Flycheck features could be conveyed just as clearly by a static image. And if we wanted to highlight specific features, we could add smaller screenshots further down the page.

**Comment by purcell** [comment]
:+1:

**Comment by cpitclaudel** [comment]
Here's some code that I use before taking screenshots:

```elisp
(defun prepare-for-screenshot ()
  (interactive "P")
  (load-theme 'tango t)
  (menu-bar-mode -1)
  (tool-bar-mode -1)
  (fringe-mode '(4 . 4))
  (setq-default cursor-type nil))
```

**Comment by lunaryorn** [comment]
@tonini @cpitclaudel @purcell I've made a first draft of an annotated screenshot.

![annoted flycheck screenshot 19 09 15 1 40 59 nachm](https://cloud.githubusercontent.com/assets/224922/9976029/109c1a42-5ed4-11e5-9a99-52d48058c8a1.png)

You can see it in action in [this preliminary branch](https://github.com/flycheck/flycheck/tree/annotated-screenshot-for-readme#readme).  If you'd like to work on it yourself, I can send you the original screenshot and the Napkin source file.

If you'd like to make your own screenshot, the `test/init.el` file which I previously only used to test Flycheck in a clean session, now also has `M-x flycheck-prepare-screenshot`, which reproduces the settings used in this screenshot (font, framesize, etc.).   I've deliberately chosen the default theme to show a "pure" Emacs.  Please feel free to suggest a better theme.

The source file shown in the screenshot is `helpers.py` from Flask—if you know any better "popular" library for demonstrating Flycheck, please tell me (I tried some Haskell libraries, but they are shockingly clean!).

**Comment by purcell** [comment]
:+1:

**Comment by cpitclaudel** [comment]
Looks awesome! The only thing that I find surprising is the fringe indicator. Why is the `?` sign mirrored? Also, maybe "error underline" should read "warning underline"?

**Comment by lunaryorn** [comment]
@cpitclaudel 

> Looks awesome! The only thing that I find surprising is the fringe indicator. Why is the ? sign mirrored? 

Uhm, I never realized that it was mirrored.  I don't use these indicators a lot, and just picked a built-in indicator of Emacs.  Maybe we should define our own indicators, that look a little nicer.

> Also, maybe "error underline" should read "warning underline"?

Good point, will fix it.

**Comment by lunaryorn** [comment]
@cpitclaudel It would appear that the mirroring is actually a regression in Emacs snapshot (which I took the screenshot with).  That is also why the colours are inverted, with the foreground colour apparently becoming the background color and vice versa.

In Emacs 24.5 everything looks fine.  I'll take another screenshot in a stable version, but meanwhile I got the idea that we should have new fringe indicators as well, see #750, so I'll put this on hold until that PR is merged :)

**Comment by lunaryorn** [comment]
![annoted flycheck screenshot 21 09 15 6 40 24 nachm](https://cloud.githubusercontent.com/assets/224922/9998126/3a0d91fe-6090-11e5-8239-0b9399768640.png)

Next try, now with the new indicators.  I'd install this image tomorrow if there are no objections or further suggestions :)
