### ISSUE TITLE
tar not found when trying to install from melpa

### ISSUE THREAD

**Issue by DanPallas** [flycheck/flycheck#744]
When trying to install flycheck thorugh the package manager I get this error: 

File error: https://melpa.org/packages/flycheck-20150831.1343.tar, Not found

**Comment by cpitclaudel** [comment]
Try `package-refresh-contents`? You probably have an outdated package database.

**Comment by DanPallas** [comment]
You're right. That was it. I haven't used emacs in a few years. Thank you.

**Comment by cpitclaudel** [comment]
My pleasure; enjoy Flycheck!

**Comment by apmattil** [comment]
thanks.
