### ISSUE TITLE
Let c/c++-clang use compile-commands.json

### ISSUE THREAD

**Issue by jlargentaye** [flycheck/flycheck#747]
This is a wishlist item.

In a large pre-existing project, each file may be compiled with different options (defines, include paths...). It's not worth defining all the flycheck-clang-* options for each.

However, there is a way to generate a database the unambiguously lists all the compilation options for every compiled file in a project: http://clang.llvm.org/docs/JSONCompilationDatabase.html

As the linked doc says, this database can be generated natively with CMake. However, even if you don't use CMake, I was successfully and easily able to generate it on OS X with BEAR (https://github.com/rizsotto/Bear) which wraps around your native build system (GNU Make in my case).

YCMd (via https://github.com/abingham/emacs-ycmd) already uses this system to understand how to compile a file with Clang. It would be nice if Flycheck could use it as well.

**Comment by jlargentaye** [comment]
After further researching, I see that this is already possible via https://github.com/kumar8600/flycheck-clangcheck.

Sorry for the noise! It may be useful to update the doc about this.

**Comment by lunaryorn** [comment]
@jlargentaye Closing then.

**Comment by root42** [comment]
This checker can't be enabled anymore it seems. Last update is from 2015. Is there any way to get c/c++-clang to honor compile-commands.json?
