### ISSUE TITLE
How to override directory from which a checker is called

### ISSUE THREAD

**Issue by purcell** [flycheck/flycheck#754]
In ELM projects it is normal to put an `elm-package.json` in the root folder, and source code inside a `src` subdir. To compile files inside `src`, we must run `elm-make src/Foo.elm` from the root directory: that command cannot be run inside `src`, much like regular `make`, because there is no `elm-package.json` there.

`flycheck-elm` uses `elm-make` command, but of course the command fails in the above situation because the working directory always matches the directory of the source file being flychecked.

Is there a way to tell the checker to try to run the command from a containing directory? I couldn't find a corresponding checker option.

**Comment by lunaryorn** [comment]
@purcell There isn't (yet), see #312.  Closing as duplicate, if you don't mind.

**Comment by purcell** [comment]
Oh, awesome, yes, that will do the trick nicely, thanks.
