### ISSUE TITLE
Problems with Drupal codingstandard and PHPCS

### ISSUE THREAD

**Issue by kostajh** [flycheck/flycheck#755]
Hello,

`php-phpcs` using the `Drupal` coding standard provided by [Coder](https://www.drupal.org/project/coder) worked without any issue until recently (unfortunately, I don't recall the exact day it stopped working -- somewhere in the last 2 weeks).

If I open a Drupal module file, I see this message:

```
ERROR: the "DrupalPractice and Drupal" coding standard is not installed. The installed coding standards are MySource, PSR2, Zend, Squiz, PHPCS, PEAR, PSR1, DrupalPractice and Drupal
```

Output of `phpcs -i` is:

```
The installed coding standards are MySource, PSR2, Zend, Squiz, PHPCS, PEAR, PSR1, DrupalPractice and Drupal
```

Note that "DrupalPractice" and "Drupal" are two separate coding standards.

I've configured `drupal-mode` such that "Drupal" is set as the standard, as evidenced by `M-x describe-variable`:

```
flycheck-phpcs-standard is a variable defined in `flycheck.el'.
Its value is "Drupal"
Original value was nil
```

It seems that no matter what I do, flycheck tries to use `phpcs` with the non-existent `DrupalPractice and Drupal` coding standard. I looked at `drupal-mode`, in particular [this line](https://github.com/arnested/drupal-mode/blob/4bd52836b3f534bfec2653e5eee1532f01387c5a/drupal/phpcs.el#L37) but that seems unlikely to be the culprit especially since it hasn't changed since 2013.

I should also note that if I try to do `flycheck-compile` using `drupal-phpcs`, I get the message that `user-error: Cannot use syntax checker drupal-phpcs in this buffer`

Finally, `phpmd` and `php -l` seem to be unaffected.

Here's my verify-setup output:

```
Syntax checkers for buffer aggregator.module<drupal> in php-mode:

  php
    - predicate:  t
    - executable: Found at /usr/bin/php

  php-phpmd
    - predicate:  t
    - executable: Found at /home/kosta/.composer/vendor/bin/phpmd

  php-phpcs
    - predicate:  t
    - executable: Found at /home/kosta/.composer/vendor/bin/phpcs

Flycheck Mode is enabled.
```

I'm on Flycheck 0.24 -- I had been on the latest build from MELPA, but switched to MELPA Stable earlier today to see if that would fix the issue.

**Comment by lunaryorn** [comment]
Does Flycheck still work if you select another standard, i.e. set `flycheck-phpcs-standard` to `"Zend"`, for instance?

I'm not sure where the syntax checker `drupal-phpcs` comes from, but it's definitely not part of Flycheck.  If that's where the error comes from please contact the maintainer of that syntax checker.

**Comment by kostajh** [comment]
Thanks for getting back to me so quickly. Yes, it does work with `PSR2`, sorry I forgot to include that in the bug report.

As a test, I just removed the `DrupalPractice` directory from the directory containing the `Drupal` and `DrupalPractice` coding standards, so that `phpcs -i` yields `The installed coding standards are MySource, PSR2, Zend, Squiz, PHPCS, PEAR, PSR1 and Drupal`

And now Flycheck uses `phpcs` properly in Drupal buffers! I think you're probably right, that this is an issue with `drupal-mode` (in particular the line I linked to in the bug report), but it seems odd that it only recently broke, because that bit of functionality hasn't been altered in nearly two years.

**Comment by lunaryorn** [comment]
@kostajh I'm closing this issue as invalid then, because it's essentially not an issue in Flycheck itself, but rather in a 3rd party library or in your personal setup.  I'm sorry that I can't help you any better, but I don't use PHP, and have no clue how phpcs actually works.  Sorry.
