### ISSUE TITLE
Racket checker seems to be missing increment-error-columns

### ISSUE THREAD

**Issue by cpitclaudel** [flycheck/flycheck#756]
(Self-assigning this one)

I did some racket hacking this week-end, and it looks like the racket checker returns 0-based indices, although the definition doesn't account for this.

**Comment by lunaryorn** [comment]
@cpitclaudel I understand that you're going to make this change?

**Comment by cpitclaudel** [comment]
Yup

**Comment by lunaryorn** [comment]
@cpitclaudel If you've racket locally, you should be able to run the tests without the VM, too.  Just do `test/run.el '(language racket)'`
