### ISSUE TITLE
Windows with bash from git: Suspicious state from syntax checker python-pylint

### ISSUE THREAD

**Issue by paugier** [flycheck/flycheck#770]
On Windows 7, I got this error:

Suspicious state from syntax checker python-pylint: Checker python-pylint returned non-zero exit code 16, but no errors from output: ^[[7;33m************* Module fluidlab.instruments.flycheck_drivers^[[0m
flycheck_drivers.py:39:4:^[[1mC^[[0m:^[[1mmissing-docstring^[[0m:^[[1mMissing method docstring^[[0m
flycheck_drivers.py:53:12:^[[1mC^[[0m:^[[1minvalid-name^[[0m:^[[1mInvalid variable name "v"^[[0m
flycheck_drivers.py:79:4:^[[1mC^[[0m:^[[1mmissing-docstring^[[0m:^[[1mMissing method docstring^[[0m

^] actually represents only one character.

- GNU Emacs 25.0.50.1 (x86_64-w64-mingw32)
- flycheck just install with cask
- pylint-script.py 1.4.2, astroid 1.3.4, common 0.63.2
- Python 2.7.10 |Anaconda 2.3.0 (64-bit)| (default, Sep 15 2015, 14:26:14) [MSC v.1500 64 bit (AMD64)]

**Comment by lunaryorn** [comment]
I'm sorry, but you're on your own.  Flycheck does [not support Windows officially](http://www.flycheck.org/manual/latest/Installation.html#Installation)—I simply do not want to spent my time with Windows :relaxed: 

Closing as wont fix.

**Comment by cpitclaudel** [comment]
As a small note, I'll add that this could be an issue with the error script adding color annotations to its output (it shouldn't when it talks to Flycheck). This in turn might be due to weird combination of Cygwin and Python (?)
