### ISSUE TITLE
Rubocop checker error

### ISSUE THREAD

**Issue by Pitometsu** [flycheck/flycheck#771]
```
Checker definition probably flawed.
Suspicious state from syntax checker ruby-rubocop: Checker ruby-rubocop returned non-zero exit code 1, but no errors from output: invalid option: --stdin
```
*UPD:* I use `0.30.0`, because new depend on parser version that incompatible with ruby `2.2.0`.

**Comment by lunaryorn** [comment]
Since 27db2b25aa0cbc9419282f3fbcd9f76b281782b0 you need RuboCop 0.34 for Flycheck.  You need to update RuboCop, downgrade Flycheck, or use your own syntax checker definition for `ruby-rubocop`.

Closing as won't fix:  I'll not restore support for older RuboCop versions again.
