### ISSUE TITLE
Rubycritic integration

### ISSUE THREAD

**Issue by Pitometsu** [flycheck/flycheck#773]
It's a feature request. Is it possible to integrate [rubycritic](https://github.com/pedrocarmona/rubycritic) like [here](https://github.com/pedrocarmona/SublimeLinter-contrib-rubycritic)
```
rubycritic --format emacs
```

**Comment by lunaryorn** [comment]
@Pitometsu I'm closing this issue as won't fix, because I'll not add this myself.  Please open a pull request.
