### ISSUE TITLE
flycheck is not available on MELPA

### ISSUE THREAD

**Issue by d12frosted** [flycheck/flycheck#780]
Can't install `flycheck` from MELPA. Also, opening `flycheck` page on [MELPA](http://melpa.org/#/flycheck) says that packages is not available.

**Comment by lunaryorn** [comment]
I'm not sure why you're reporting this issue to me instead to MELPA? 

Anyone, I've [asked on Twitter](https://twitter.com/lunaryorn/status/661837975081324544), and I'm inviting @purcell

**Comment by d12frosted** [comment]
Yeah, probably it's not the right place, but from 220+ packages I've just installed, only `flyckeck` and `flycheck-*` are not available, so I thought that you might be interested. In any case, I've opened [issue](https://github.com/milkypostman/melpa/issues/3266) on MELPA as well.

**Comment by d12frosted** [comment]
It's available now. Sorry for the panic.
