### ISSUE TITLE
Every key I type causes file to save

### ISSUE THREAD

**Issue by felipebueno** [flycheck/flycheck#781]
Hello! 

I'm using ```Emacs + Flycheck``` to develop my React Native apps. For some reason, every key I type causes the emulator to auto reload. I tried a few things to narrow down the problem and found out it only happens when ```flycheck-mode``` is on.

Here's is my ```Flycheck``` config:
```clojure
(require 'flycheck)

;; turn on flychecking globally
(add-hook 'after-init-hook #'global-flycheck-mode)

;; disable jshint
(setq-default flycheck-disabled-checkers
              (append flycheck-disabled-checkers
                      '(javascript-jshint)))

;; use eslint with web-mode for jsx files
(flycheck-add-mode 'javascript-eslint 'web-mode)

;; disable json-jsonlist checking for json files
(setq-default flycheck-disabled-checkers
              (append flycheck-disabled-checkers
                      '(json-jsonlist)))
```

![gif](https://camo.githubusercontent.com/0b922f37aeff75eb4a2f1ee1a12688429c964c2e/687474703a2f2f672e7265636f726469742e636f2f6442554a516b623577742e676966)

![gif](https://camo.githubusercontent.com/98141bc02024df88a699a0e34a102428ad37bfe3/687474703a2f2f672e7265636f726469742e636f2f6a756132726342704d552e676966)

Is this supposed to happen? Am I missing something?

ps: This issue was originally posted on React Native's repository https://github.com/facebook/react-native/issues/3927

**Comment by cpitclaudel** [comment]
How does the emulator decide whether to reload? Does it maybe just check whether a file has changed in the project's directory?

**Comment by felipebueno** [comment]
Hey, I've found a (temporary?) solution. I customized the flycheck-check-syntax-automatically to be:
[X] After the buffer was saved
[  ] After the buffer was changed and idle
[  ] After a new line was inserted
[X] After `flycheck-mode' was enabled

It's working ok now. I didn't know that Flycheck should save the file every time it performs a check. Is this true?

**Comment by felipebueno** [comment]
@cpitclaudel It's supposed to happen only when the file is saved. [Watchman](https://facebook.github.io/watchman/) detects the change and it causes the emulator to reload.

**Comment by felipebueno** [comment]
Oh I think I understand now. The problem is that watchman detects any change on ANY file on the project. I'm looking at Flycheck's source and saw that it saves a temporary the buffer to a temp file when performing checks.

**Comment by felipebueno** [comment]
So the "problem" here is Watchman not Flycheck. I think I can ignore certain files using the ```.whatchmanconfig```. I'll try that.

**Comment by cpitclaudel** [comment]
Yup, that's the trick. Flycheck is using a temporary in the same folder

**Comment by felipebueno** [comment]
Thanks :) :+1:

**Comment by lunaryorn** [comment]
@felipebueno The latest Flycheck from MELPA should not create temporary files for Javascript anymore.

**Comment by felipebueno** [comment]
Hi, @lunaryorn !

I have the latest version from MELPA Stable installed. 

```0.24```

<img width="430" alt="screen shot 2015-11-06 at 11 26 19" src="https://cloud.githubusercontent.com/assets/241271/10998088/c2864ba4-8479-11e5-9192-7f52f0fee423.png">

**Comment by lunaryorn** [comment]
@felipebueno Ah, I see.  That change is not on MELPA Stable yet.  Actually, the last release was really a long time ago :flushed:   Now that I know that there's actually someone using MELPA Stable :relaxed: I'll try to put out another release this weekend… and hopefully get into a habit of releasing more frequently :blush:

**Comment by felipebueno** [comment]
Hahah nice. Thanks, @lunaryorn :+1: :smile: 

I use stable because some major packages I use tend to break a lot on unstable. 😅

**Comment by lunaryorn** [comment]
@felipebueno Flycheck should not break on MELPA proper.  We have a test suite to ensure that.  Or at least, it shouldn't break in ways that you won't see on MELPA Stable, too:  We do make backwards incompatible changes from time to time, even in stable releases.  That's why we are not 1.0 yet :relaxed:

**Comment by felipebueno** [comment]
Hi, @lunaryorn sorry for bothering you with that again but are you still planning to put out the release on MELPA Stable? :sweat_smile:

**Comment by lunaryorn** [comment]
@felipebueno I do, but please understand that I can't give no ETA.  There are a couple of things I'd like to get done before the next release to provide the base for the things to come, and I don't know how long that'll take.  

In the mean time, I'd recommend you to use Flycheck from MELPA.  We hardly ever break things there, promised! :relaxed:

**Comment by lunaryorn** [comment]
@felipebueno I've just pushed Flycheck 0.25.  The new release should be on MELPA Stable within the next few hours.
