### ISSUE TITLE
Add Stylelint checker

### ISSUE THREAD

**Issue by lunaryorn** [flycheck/flycheck#785]
http://stylelint.io

**Comment by PhilippBaschke** [comment]
I am working on a PR. Should be done soon! :blush:

**Comment by lunaryorn** [comment]
@PhilippBaschke :+1: :clap:  Thank you :relaxed:

**Comment by nickmccurdy** [comment]
#903 should be merged, can we close this please?

**Comment by fmdkdd** [comment]
@nickmccurdy Good catch.
