### ISSUE TITLE
Only display errors after point has moved

### ISSUE THREAD

**Issue by swsnr** [flycheck/flycheck#788]
Currently we start error display unconditionally in `post-command-hook`, even if the command didn't change `point`.  This leads to a slightly awkward user experience (see https://github.com/flycheck/flycheck-pos-tip/issues/7).

At some point we should track point during error display and only display errors if the command actually moved point.

**Comment by lunaryorn** [comment]
@PierreR I won't work on this any time soon.  As far as I'm concerned, there are many way more important things to do in Flycheck.  Maybe @cpitclaudel takes this.

Otherwise you'll have to wait a long time for me to fix it (sorry).  A pull request would be welcome.

**Comment by cpitclaudel** [comment]
I could look into this (I have a paper deadline next Friday though, so probably not before that) :) I've had a quick look just now, but it actually caused me to run into another issue; I'll post to flycheck-pos-tip.

@lunaryorn,Would it be enough to save the point in a buffer-local variable? Won't we run into trouble when multiple windows show the same buffer? (maybe we're ok with the current behaviour persisting in that case)

**Comment by lunaryorn** [comment]
@cpitclaudel  I haven't yet thought about this at all.   I don't know how we could fix this.

If we used a buffer local variable, we should probably reset it when the active window changes.  Only one window can be active at a time, and we'd only need to track point position in the active window.

**Comment by lunaryorn** [comment]
@cpitclaudel Do we have any news on this issue?  Should we try and fix it?

**Comment by cpitclaudel** [comment]
Definitely; I've just been very busy of late.

**Comment by jimmywongroo** [comment]
Is there any movement or branch up for this issue?

**Comment by cpitclaudel** [comment]
Nope, I haven't touched it, and lunaryorn has transferred maintainership of this repo to @fmdkdd and me (and a large team of other people ^^).  I haven't had much time lately. On the other hand, this should be reasonably fixable, so if someone took a crack at it I'd be happy to review/shepherd a PR.

**Comment by swsnr** [comment]
This issue wasn't updated in a long time, and I am no longer interested, so I'm closing this issue to clean up my issues list.
