### ISSUE TITLE
Add protobuf support

### ISSUE THREAD

**Issue by lunaryorn** [flycheck/flycheck#790]
Take from https://github.com/edvorg/flycheck-protobuf, see https://github.com/edvorg/flycheck-protobuf/issues/3
- [ ] Copy processing syntax checker from repo (with original author data for Git)
- [ ] Install on testing VM
- [ ] Add a test case
- [ ] Remove recipe from MELPA
- [ ] Remove checker from upstream project

**Comment by marsam** [comment]
Given that the protobuf checker is [already part of flycheck](https://github.com/flycheck/flycheck/pull/1125), and the [flycheck-protobuf](https://github.com/melpa/melpa/pull/4382) recipe has been removed from melpa. I think this issue can be closed.

**Comment by lunaryorn** [comment]
@marsam You're right; closed :)
