### ISSUE TITLE
 Symbol's function definition is void: seq-do

### ISSUE THREAD

**Issue by xlighting** [flycheck/flycheck#791]
The minibuffer shows the following stuff when I enable flycheak-mode in a emacs lisp mode buffer
      Checker definition probably flawed.

And I found  these  in *message* buffer:
      Wrote /tmp/flycheck_init.el13096tNT
      Symbol's function definition is void: seq-do

**Comment by syohex** [comment]
Do you install [seq.el](https://github.com/NicolasPetton/seq.el) ? `seq.el` is a dependency of flycheck. How do you install flycheck ? seq.el is installed automatically if you use package management tools like package.el.

**Comment by cpitclaudel** [comment]
Indeed, something looks fishy here. We have a Cask configuration if you want to use the git sources, too.

**Comment by xlighting** [comment]
M-x package-install

**Comment by syohex** [comment]
Could you reinstall and retry after uninstall flycheck and seq packages ?

**Comment by xlighting** [comment]
I did it, but the problem keeps .
the problem happended after I upgrading flycheck to flycheck-20151114.1448 (from melpa)

**Comment by cpitclaudel** [comment]
Can you also give more details? Your version of emacs and your OS for example may be useful.

**Comment by cpitclaudel** [comment]
```
Wrote /tmp/flycheck_init.el13096tNT
```
does not make much sense to me. Perhaps you could try to give us a recipe starting from a clean emacs (`emacs -Q`)?

**Comment by xlighting** [comment]
I tried ,  the problem didn't happen in a clean eamcs  (my version: "GNU Emacs 24.4.3 (x86_64-unknown-linux-gnu, GTK+ Version 3.16.7)  of 2015-09-26 on xlight-arch")
but I get these when I use  my configs 
Suspicious state from syntax checker emacs-lisp: Checker emacs-lisp returned non-zero exit code 255, but no errors from output: Wrote /tmp/flycheck_init.el22750Y0V
Symbol's function definition is void: seq-do
Checker definition probably flawed.

what should i do

**Comment by xlighting** [comment]
Ok 
,maybe 
 (setq flycheck-emacs-lisp-load-path 'inherit)
causes it

**Comment by xlighting** [comment]
This problem happends again when I use spacemacs ( with loading  the emacs-lisp layer )
( I tested it with emacs24.4,24.5 on archlinux and windows7) 

The error message:
Suspicious state from syntax checker emacs-lisp: Checker emacs-lisp returned non-zero exit code 255, but no errors from output: Wrote /tmp/flycheck_helm-apt.el31281hMY
Symbol's function definition is void: seq-do

I think the following config causes the problem
(setq flycheck-emacs-lisp-load-path 'inherit)
but I don't know why

**Comment by syohex** [comment]
Can you see `seq-do` by following step ?

1. `M-: (require 'seq)`
2. `M-x describe-function`, `seq-do`

**Comment by xlighting** [comment]
Yes , seq-do exists

**Comment by lunaryorn** [comment]
Sorry, my bad.  Will push a new release that fixes this one.

**Comment by lunaryorn** [comment]
I've just pushed Flycheck 0.25.1 with a fix for this issue.  The next MELPA build should put the fixed version in MELPA and MELPA Stable.

I'm terribly sorry for the inconvenience.

**Comment by xlighting** [comment]
Thank you :-)

**Comment by lunaryorn** [comment]
@xlighting Thank you for reporting this and for bearing with my blunder :blush:
