### ISSUE TITLE
Gitter chats

### ISSUE THREAD

**Issue by lunaryorn** [flycheck/flycheck#796]
Should we open and announce a Gitter chatroom for Flycheck?  Probably two, one for users and another for developers?

@cpitclaudel Do you think that we need an internal Gitter chat room for Flycheck where we can have private discussions about things?

Blocked by #819

**Comment by cpitclaudel** [comment]
I have no particular familiarity with Gitter; if you've had positive experiences with it, maybe it's a good idea :) Re private discussions, I wonder how much superior they'd be to email? (I get email on my phone)

**Comment by lunaryorn** [comment]
I don't know.  I haven't really used it yet. I've just seen it appearing in various Emacs projects, like Cider and Spacemacs.  About a month ago or so, I temporarily created a chat room for Flycheck and added a badge to README, but the resonance was marginal…

Compared to mails Gitter chats have the advantage of being open to all contributors.  You don't have to remember to include all of them in `To:`.  But then again, it's just us two, so it doesn't really matter, does it? ;)

**Comment by cpitclaudel** [comment]
We could try it. Until we have other people hanging in there though I'm not too sure about spreading support across issues + gitter. Your call ^^

**Comment by lunaryorn** [comment]
That's what I'm unsure about, too: Issues play well with Google, StackExchange, etc.  Gitter not so.

I'd like to ask @bbatsov and @syl20bnr about their experience with Gitter?  Does it “work”?  Does it help users of your project?  Does it help you with maintenance and support?

**Comment by syl20bnr** [comment]
In the case of Spacemacs it surely helps for support between users, it is
an invaluable benefit for such project and is one of the selling point
since it is built to be community driven.

@StreakyCobra was able to start a big issue cleanup campaign thanks to this
channel, the facilities offered out of the box by gitter (slick GitHub
integration, history retention, easy to spot and go to mentions, etc...)
surely helped a lot to start this campaign.

In the end I'm not sure that Spacemacs would have get such momentum as
quickly without the gitter chat, any GitHub user can join by a single click
on a button, this is really helpful.

There is also an IRC bridge so people can join the Gitter chat via their
IRC client (so you can join it from within Emacs, Spacemacs users seem to
prefer the ERC layer which offers more feature).

For a package project there is no cons to not create your official gitter
channel. You can consult it at your own pace since there is history
retention and you will get emails when someone mention you.

Le mardi 17 novembre 2015, Sebastian Wiesner <notifications@github.com> a
écrit :

> That's what I'm unsure about, too: Issues play well with Google,
> StackExchange, etc. Gitter not so.
>
> I'd like to ask @bbatsov <https://github.com/bbatsov> and @syl20bnr
> <https://github.com/syl20bnr> about their experience with Gitter? Does it
> “work”? Does it help users of your project? Does it help you with
> maintenance and support?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/flycheck/flycheck/issues/796#issuecomment-157441734>.
>


-- 
-syl20bnr-

**Comment by syl20bnr** [comment]
Also it would worth to ask @tarsius about his experience regarding Magit
and gitter. I believe he has opened it only to allow users to interact, he
is not often in the chat.

Le mardi 17 novembre 2015, Sylvain Benner <sylvain.benner@gmail.com> a
écrit :

> In the case of Spacemacs it surely helps for support between users, it is
> an invaluable benefit for such project and is one of the selling point
> since it is built to be community driven.
>
> @StreakyCobra was able to start a big issue cleanup campaign thanks to
> this channel, the facilities offered out of the box by gitter (slick GitHub
> integration, history retention, easy to spot and go to mentions, etc...)
> surely helped a lot to start this campaign.
>
> In the end I'm not sure that Spacemacs would have get such momentum as
> quickly without the gitter chat, any GitHub user can join by a single click
> on a button, this is really helpful.
>
> There is also an IRC bridge so people can join the Gitter chat via their
> IRC client (so you can join it from within Emacs, Spacemacs users seem to
> prefer the ERC layer which offers more feature).
>
> For a package project there is no cons to not create your official gitter
> channel. You can consult it at your own pace since there is history
> retention and you will get emails when someone mention you.
>
> Le mardi 17 novembre 2015, Sebastian Wiesner <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> a écrit :
>
>> That's what I'm unsure about, too: Issues play well with Google,
>> StackExchange, etc. Gitter not so.
>>
>> I'd like to ask @bbatsov <https://github.com/bbatsov> and @syl20bnr
>> <https://github.com/syl20bnr> about their experience with Gitter? Does
>> it “work”? Does it help users of your project? Does it help you with
>> maintenance and support?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/flycheck/flycheck/issues/796#issuecomment-157441734>.
>>
>
>
> --
> -syl20bnr-
>


-- 
-syl20bnr-

**Comment by lunaryorn** [comment]
@syl20bnr Thanks for your input :blush:

**Comment by tarsius** [comment]
You would probably have to make sure to be around a lot, at least initially. In the Magit chat we developers aren't around much, which appears to make it less likely for users to stick around, after they got the help they were looking for. The hope was that some users would stay and then help others, but they need an incentive to do so. Maybe the developers chatting among themselves (with the possibility of users joining in) is incentive enough, so I would recommend not splitting into two channels.

**Comment by lunaryorn** [comment]
@tarsius Thanks for your input :relaxed:

@tarsius @syl20bnr  I'm concerned that Gitter draws support and questions away from “discoverable” (read, visible in Google search :wink:) channels—Github issues and StackExchange mostly—into a somewhat “private” area that doesn't appear in search results and is much harder to search.

Do you see an adverse effect on support on StackExchange or Github issues since you have Gitter chats?

**Comment by lunaryorn** [comment]
I've spoken to some people now, and I've only heard good things about Gitter, so I think I'll add a Gitter chat for Flycheck.  I'll notify you when it's there so that you can join.

**Comment by cpitclaudel** [comment]
Thanks!

**Comment by lunaryorn** [comment]
Follow up in #820
