### ISSUE TITLE
Document ourselves

### ISSUE THREAD

**Issue by lunaryorn** [flycheck/flycheck#800]
Flycheck has grown a lot in the last year.  We now have a second maintainer (@cpitclaudel :heart_eyes:) and we get more and more contributions from others.  I must admit that I'm somewhat overwhelmed, and can't really keep up with all that needs to be done.  I'm afraid that Flycheck is not a very sustainable project in its current form.

I'd like to change that, and incidentally I've recently read a [pretty nice blog post on the topic](http://writing.jan.io/2015/11/20/sustainable-open-source.html).  My aim is ultimately to make myself superfluous :blush: and turn Flycheck into a sustainable project with a thriving community where I'm just one among many and which can easily go on without myself :relaxed:

----

There's a lot of work that needs to be done to even get close to this vision.  Roughly we need to

1. Automate/document our technical rules, workflow and processes (e.g. commit message rules, release process, merging of PRs, testing, etc.).  That'll mostly be my job, because currently I'm running all of this somewhat implicitly.
2. Document our “community” processes (code of conduct, responsibilities, decision making processes, on-boarding contributors, etc.).  That's something I can't do alone.

----

My goal with all of this issue to get more people to contribute and to get the _right_ people to contribute.  My vision is that someone who's never contributed to open source before has no trouble with making their first contribution to Flycheck, neither technically (i.e. how to do that) nor personally (i.e. we become a safe space for _all_ contributors).

@purcell @cpitclaudel I'd really welcome your feedback and your ideas on your topic.  I'm particularly interested in what you're missing from this project documentation- and process-wise, @cpitclaudel, because you're the first who's contributing on a regular basis, and in your experiences, @purcell, in so many different communities :relaxed:

I'd also like to hear @jwiegley's opinion and listen to @tarsius experiences. :blush:

Please feel free to invite other people as well :relaxed:

**Comment by jwiegley** [comment]
@lunaryorn I think this is a good step to make, especially as it may free you up to create other new and wonderful things. :)

**Comment by cpitclaudel** [comment]
I agree wholeheartedly with your feelings. I feel the first step here could be to get more people to hang around this bug tracker. If anything, answering simple questions may be a good way to get started (and may alleviate your workload). On the other hand, emphasizing flycheck-as-a-framework may be a good way to get contributions, too (this is from personal experience: most of the stuff I contributed was stuff that I also got to directly use in my work on dafny-mode as part of the boogie-friends package). 

Beyond this, I'm not too sure. A few years ago I was working on a Windows backup program, and it gathered a total of 300'000 downloads and exactly one patch (!). On the other hand, translations for the UI were much easier to get (possibly because they didn't have to come from programmers?)

**Comment by purcell** [comment]
I wonder if separating the various checkers out into separate packages would make this less of an issue? ie. if the core is small, and people find it easy to write, test and publish checkers elsewhere, then that might be a good outcome. Just a thought.

**Comment by lunaryorn** [comment]
@purcell I don't think so.  It'd just impose different problems onto Flycheck, but not necessarily increase our speed.  The “large” stories in our backlog (annotation mode, error fixers, etc.) would be “core” problems anyway.

**Comment by lunaryorn** [comment]
We now have a contributor's guide, a maintainer's guide, a documented review process, automation for most of the maintenance stuff, so I think we are fairly complete to document ourselves as a project.

Of course there's still much to do and to improve (#1094, for instance ) , but I don't think that we still need to keep this story open.  I'm closing this issue and the corresponding milestone.
