### ISSUE TITLE
Multiple independent checkers without explicit chaining?

### ISSUE THREAD

**Issue by phst** [flycheck/flycheck#807]
Hi,

sorry for the abstract and lengthy discussion and the open-ended questions; please correct me if I misunderstood something about the design. Consider the following situation. Three independent packages define one checker each. Let's call the checkers A, B, and C. It is desirable that in a certain mode all three checkers should run, in the order A → B → C. Suppose that A doesn't know that B and C exist. Now we want to get this to work no matter which of the checkers are actually defined, with the constraint that all defined checkers can be run. My understanding is that currently this requires B to install itself as a next checker of A, and C to install itself as a next checker of B if B is defined and as a next checker of A if A is defined, and C to remove itself from the next checker list of A once B gets installed. Is that correct? Would it be feasible to provide a generic function to implement such requirements? Right now it seems that the design of the next checker functionality requires global knowledge about existing checkers, so packages defining checkers have a hard time if they assume an open world where arbitrary checkers can be installed by arbitrary packages in arbitrary order. Would it eventually be possible to migrate away from the explicit next-checker-list design so that all applicable checkers get applied automatically, maybe with a priority for ordering?

Thanks.

**Comment by lunaryorn** [comment]
I'm not sure whether I understood you correctly.  Is this just a theoretical design idea, or do you have an concrete issue with the current system?

I like your idea conceptually, but it raises some question about the implementation, and I'm not sure what problems it really solves.  Sure, the current system implies some knowledge about existing checkers, but there are only so many linting tools for any given language.  And picking any kind of “priority” implies a certain knowledge about the set of linting tools as well, doesn't it?

**Comment by phst** [comment]
This is a concrete issue with a combination of some private/internal and third-party checkers, so unfortunately I can't point at code, but it's also a theoretical issue. As Flycheck well-deservedly becomes more and more popular, people will put checkers in whatever packages they like, or in their private configurations, etc.. Currently the checker definitions operate under a closed-world assumption, which simplifies things a lot, but eventually breaks down. A priority does require some knowledge and is certainly not a panacea, but I think it would reduce the amount of global knowledge that checkers are required to have. For example, it would be relatively easy to decide that checkdoc should have low priority, without knowing what other checkers might be around.

**Comment by lunaryorn** [comment]
Flycheck provides `flycheck-add-next-checker` to hook into the chain, doesn't that solve your problem?  I mean, how many checkers did you define in your configuration that this would get out of hand?  Can you share the code privately, i.e. in a private Gitter chat or per mail?  

I'd really like to see _concrete_ code to priorise this issue.   I understand that the current system is pretty static, and that we should probably come up with a better open that's less closed and less static, if only for the sake of beauty and elegancy, but as long as it's just a theoretical problem—which I think it is—it has a very low priority on our backlog, so low that we never might get to it.  We have very large issues (see #800 or #774) that are inhibiting Flycheck's growth and adoption _now_.

I understand that this answer is not at all good to you, and I'm sorry, but unfortunately we have only a lot to do in so little time :disappointed: 

However, if you could come up with a prototype implementation of a new API for this purpose and open a PR, that'd be great!  :heart_eyes: 

I'm sorry that I can't provide any better help :cry:

**Comment by phst** [comment]
No problem, I'll try to find another way. Closing for now, maybe we can revisit this later.
