### ISSUE TITLE
Add Liquid Haskell checker

### ISSUE THREAD

**Issue by lunaryorn** [flycheck/flycheck#809]
See https://github.com/themattchan/flycheck-liquidhs.el/issues/1.
- [ ] Copy processing syntax checker from repo (with original author data for Git)
- [ ] Install on testing VM
- [ ] Add a test case
- [ ] Remove recipe from MELPA
- [ ] Remove checker from upstream project

**Comment by cpitclaudel** [comment]
I think this works well as a separate package, so no need to keep this issue open.
