### ISSUE TITLE
Flycheck on golang

### ISSUE THREAD

**Issue by douglarek** [flycheck/flycheck#815]
```
Flycheck error display error: (error Window system frame should be used)
```
did anything I missed ?

**Comment by douglarek** [comment]
resolved

**Comment by lunaryorn** [comment]
Please provide your Emacs version, your Flycheck version and the name and version of your operating system. If you have any Flycheck extensions installed please provide their names and versions as well.

Please also try to produce a step-by-step recipe to reproduce the bug.  Ideally, [reproduce the bug in `emacs -Q`](http://www.lunaryorn.com/2015/11/29/reproduce-bugs-in-emacs-Q.html).

**Comment by lunaryorn** [comment]
Well, at least describe what the issue was and you resolved it.  I mean no offense but as such it's just a waste of everyone's time 😒

**Comment by douglarek** [comment]
@lunaryorn sorry, my mistake; I always run Emacs in terminal, so I did this:

```
(when (display-graphic-p)
  (eval-after-load 'flycheck
    '(custom-set-variables
      '(flycheck-display-errors-function #'flycheck-pos-tip-error-messages))))
```
