### ISSUE TITLE
Is it possible to exclusive error/warning from a library (C++)

### ISSUE THREAD

**Issue by enzochiau** [flycheck/flycheck#816]
I am using third party's C++ library which are working file. When I include files from that library, Flycheck would list warning/error from that library as something like `In file included from ...` or `In include XXXX ...` . 

I expect to only see warning/error for my own code. So is there any way to exclusive massages related to the third party library?

**Comment by lunaryorn** [comment]
@enzochiau You can suppress warnings from header files by adding them to the system include path, i.e. by adding `-isystem /path/to/my/library` to `flycheck-clang-args` or `flycheck-gcc-args`.

You cannot suppress errors from header files, though.  If the header file is faulty the compiler simply can't compile the current file anymore.
