### ISSUE TITLE
(file-error "Cannot open load file" "no such file or directory" "seq")

### ISSUE THREAD

**Issue by azer** [flycheck/flycheck#823]
I've just started getting this error when I open my emacs. here is full output;

```
   0 Debugger entered--Lisp error: (file-error "Cannot open load file" "no such file or directory" "seq")
   1   require(seq)
   2   eval-buffer(#<buffer  *load*-478897> nil "/Users/azer/emacs/libs/flycheck/flycheck.el" nil t)  ; Reading at buffer position 318$
   3   load-with-code-conversion("/Users/azer/emacs/libs/flycheck/flycheck.el" "/Users/azer/emacs/libs/flycheck/flycheck.el" nil t)
   4   require(flycheck)
   5   eval-buffer(#<buffer  *load*-31935> nil "/Users/azer/emacs/config/flycheck.el" nil t)  ; Reading at buffer position 95
   6   load-with-code-conversion("/Users/azer/emacs/config/flycheck.el" "/Users/azer/emacs/config/flycheck.el" nil nil)
   7   load("/Users/azer/emacs/config/flycheck.el" nil nil t)
   8   load-file("~/emacs/config/flycheck.el")
   9   load-conf-file("flycheck")
```

My emacs setup: http://github.com/azer/emacs

**Comment by cpitclaudel** [comment]
Hey @azer,

Thanks for your message. Looking at the message, I'm going to guess that you're using Emacs 24, and that you installed Flycheck manually. Is that right?

If so, then my bet is that you forgot to install `seq`, which Flycheck depends on. Could you check that?

Thanks!

**Comment by lunaryorn** [comment]
@azer Please make sure that you have all dependencies of Flycheck installed, including `seq`.  You can find the complete list of dependencies in the `Package-Requires:` header.

Please be aware that we do _not_ support installing Flycheck through Git submodules.  Please use Emacs' built-in package manager to install Flycheck from MELPA or MELPA Stable.

Closing as invalid.
