### ISSUE TITLE
flycheck-phpcs stuck when using standard-input

### ISSUE THREAD

**Issue by zarybnicky** [flycheck/flycheck#827]
Using default configuration (20151219.122) on Windows 10 and Emacs 24.4, flycheck freezes emacs while running the phpcs checker (I get a blank screen after a while). When I manually kill the phpcs process (`C:\WINDOWS\system32\cmd.exe /c c:\Users\Jakub\AppData\Roaming\Composer\vendor\bin\phpcs.bat --report=checkstyle`), emacs resumes.

When I manually run the same command in cmd.exe, copy-paste the file contents, and input C-z RET, phpcs processes the input as expected. If I edit flycheck.el to have flycheck-phpcs use tmp files, it works just fine.

I'm unsure how to debug this further - while I've been using Emacs for some time now, I haven't used or debugged elisp much...

**Comment by lunaryorn** [comment]
@zarybnicky I'm sorry that Flycheck does not work for you, but please note that we [do not support Windows](http://www.flycheck.org/manual/latest/Installation.html#index-Windows) officially.  I am closing this issue as `invalid`, being reported for a system that we do not support.

I have no idea why it'd hang on Windows, but I do not have access to a Windows system to try.  Unless someone else steps in I'm afraid that you have to debug this issue yourself.  A similar issue is known for eslint and nodejs, see #794.  You may find clues in that discussion.

**Comment by zarybnicky** [comment]
Thanks for the response. For now, I'll continue to switch flycheck-phpcs back to input via filename manually, reverting 74d1ce1.

**Comment by cpitclaudel** [comment]
@zarybnicky Could you try the fix-794 branch? I've added details and instructions on the thread of bug #794.

**Comment by zarybnicky** [comment]
Yes, the latest version from MELPA works fine. Sorry for the late response, phpcs checker didn't work for me with the branch and I didn't have the time to investigate more at that moment.
