### ISSUE TITLE
Redirect go build output to /dev/null 

### ISSUE THREAD

**Issue by lunaryorn** [flycheck/flycheck#838]
See https://github.com/flycheck/flycheck/pull/831#issuecomment-168014385, apparently go build can now cope with redirections to /dev/null.

Need to find out when this was fixed and update our go syntax checkers accordingly.

@gfrey Could you shed some light on this?

**Comment by gfrey** [comment]
@lunaryorn Only thing I found was that redirect to `/dev/null` works when explicitly mentioning the files to compile (see https://github.com/golang/go/issues/4851#issuecomment-66074944). That is why it worked for me.

**Comment by lunaryorn** [comment]
Already, it seems that the problem is still there.  Thank you for the update, I'm closing this issue again.

**Comment by dominikh** [comment]
@lunaryorn `-o /dev/null` now works because of commit golang/go@76811213d7f927c15220c91b4c47af7028af4f47 – naturally it only works with Go 1.6+, and not on Windows (for the lack of a /dev/null)

**Comment by lunaryorn** [comment]
@dominikh Flycheck redirects to the platform-dependent null device, e.g. `NUL` on Windows.  Would that work on Windows?

**Comment by dominikh** [comment]
I don't know anything about Windows, really. If NUL is a file that isn't regular, then yeah, that commit should work for NUL.

**Comment by lunaryorn** [comment]
@dominikh Ah, ok.  I don't either :grin:, but I guess we'll find someone who does sooner or later to answer this question.  

Meanwhile I'll leave this issue open and move it into our list of windows issues.

Thank you very much for your feedback, it's nice to see that Go changes for the better :+1:

**Comment by syohex** [comment]
I confirmed that `go build -o NUL foo.go` successes(and without errors) on Go 1.6 beta2

**Comment by lunaryorn** [comment]
@syohex Thank you very much for this information. We'll change Go to use `null-device` then; but I guess we should wait until at least Go 1.7, shouldn't we?

**Comment by syohex** [comment]
We should wait 1.6. 1.6 is not released yet. Now 1.6-RC1 was released.

**Comment by dominikh** [comment]
Not everybody will immediately update to Go 1.6, though. There should be a grace period.

**Comment by syohex** [comment]
Ah, I see.

**Comment by drewwells** [comment]
If this ever gets implemented, then there is a hard requirement inside flycheck for Go 1.6. Maybe it should instead check for the version then perform /dev/null redirection.

```
-> % go version
go version go1.6rc2 darwin/amd64
```

**Comment by lunaryorn** [comment]
@drewwells Yes, there will be a hard requirement; we will not perform version checks.  We didn't do in the past, and we won't do in the future; these checks are too much effort for too little gain from our point of view, particularly since it's easy enough for users to simply re-define the syntax checker for older Go versions in their own Emacs configuration.

**Comment by drewwells** [comment]
If this does land, I'd like to see the workaround for this and probably others would too.

Most developers I know are still using 1.4.x because it compiles significantly faster than 1.5 or 1.6. This continuing burden on compilation speed continues on in 1.7 starting off twice as slow as 1.6 https://groups.google.com/forum/#!topic/golang-dev/TerfinvPffw.

**Comment by lunaryorn** [comment]
@drewwells The workaround would be to either stick with an older version of Flycheck or to copy the `go-build` definition from an older Flycheck version to your Emacs configuration.

But please understand that we can have only so much regard for users who deliberately choose to stay behind, for whatever reason.

**Comment by lunaryorn** [comment]
@flycheck/go @gfrey Is there an ETA for Go 1.7 already?

**Comment by dominikh** [comment]
@lunaryorn The planned release date is August 1.

**Comment by lunaryorn** [comment]
@dominikh Thanks :)

**Comment by lunaryorn** [comment]
From the news it would appear that Go 1.7 has been released.  @flycheck/go, do you think that we can now finally change Flycheck to redirect Go's output to `/dev/null`?

**Comment by dominikh** [comment]
@lunaryorn Sounds good to me. I've sent a PR.
