### ISSUE TITLE
Massive slow-down in the presence of diff-hl-mode

### ISSUE THREAD

**Issue by purcell** [flycheck/flycheck#841]
I've been working today with a large ledger file and `flycheck-ledger`. There's a big block of added transactions (highlighted in the fringe in green by `diff-hl`) and inside that block there are ~50 errors/warnings highlighted by `flycheck`. 

The checker process itself runs in ~0.2s, but the overall `flycheck` cycle takes over 7s. Disabling `diff-hl-mode` solves this problem. I presume there's a clash in the overlay handling. Profiling with `elp` certainly indicated that `flycheck-add-overlay` was taking ~0.2s per error.

Any ideas? /cc @dgutov

**Comment by lunaryorn** [comment]
@purcell 7s seconds is a massive blow, but I'm not sure whether there's anything I can do in Flycheck.  We don't use overlays in any unusual way, other than that our approach to adding fringe icons appears to be a hack—the standard hack though to add fringe icons, and there's no other way as far as I know.

Overlays have bad performance characteristics; they appear to have quadratic complexity for many operations.  I hope that we can find a way to solve this, but I fear that the answer will be that there's no solution other than disabling one of these modes.

**Comment by purcell** [comment]
Yeah, I probably need to look into disabling `diff-hl` or its overlays while `flycheck` is updating, then re-enabling it afterwards.

**Comment by dgutov** [comment]
Flycheck adds overlays slowly, but `diff-hl` updates quickly enough? How come? I add one overlay per line, as well as one per hunk. Does that come out to less than 50 in the said ledger file?

I've just created a 400-line diff, and the file updated just as snappily. I'm sure overlays do have quadratic complexity, but the multiplier must be low enough.

**Comment by lunaryorn** [comment]
@dgutov I don't think that the overhead is low in this situation.

A large chunk of changes implies a lot of diff-hl overlays. Flycheck now needs to add 50 potentially overlapping overlays in top of these.  Emacs has to figure out the overlay priorities in all overlapping areas.  Depending on how overlays are implemented—I don't know how—that can be a costly task.

That'd also explain why disabling either mode fixes the performance: there are simply no overlapping overlays anymore.

That's all speculation of course but I think it's a reasonable explanation and fits all that I've heard about overlays.

But to be sure we'd need a core developer to weigh in.  Anyone up for an emacs-devel thread?  I'd prefer to not have to post there, to be honest, so if anyone of you could do that I'd be very happy 😊

**Comment by cpitclaudel** [comment]
Hi all,

I tried to create a repro in preparation for a discussion, but the small example below doesn't have the problem on my machine. Does it on anyone else's?

```elisp
(with-current-buffer (get-buffer-create "*overlay-stacking-bug*")
  (erase-buffer)
  (fundamental-mode)

  (dotimes (i 50)
    (insert "AAAAAAAAAAAAAAAAAAA\nBBBBBBBBBBBBBBBBBBB\n")
    (forward-line -2)
    (let ((ov (make-overlay (point-at-bol) (point-at-eol))))
      (overlay-put ov 'priority 10)
      (overlay-put ov 'face '(:background "red")))
    (forward-line 1)
    (let ((ov (make-overlay (point-at-bol) (point-at-eol))))
      (overlay-put ov 'priority 15)
      (overlay-put ov 'face '(:background "green")))
    (let ((ov (make-overlay (- (point-at-bol) 3) (+ (point-at-bol) 3))))
      (overlay-put ov 'priority 20)
      (overlay-put ov 'face '(:underline t :background "blue")))
    (forward-line 1))
  (display-buffer (current-buffer)))
```

If not, do we know what is different between this example and the larger one involving Flycheck and hl-line-mode? Is it specifically margin icons?

**Comment by cpitclaudel** [comment]
Even with margin bitmaps I can't seem to get something slow:

```elisp
(defvar --before
  #("!" 0 1
    (display
     (left-fringe flycheck-fringe-bitmap-double-arrow
                  flycheck-fringe-warning))))

(defvar --before-2
  #("!" 0 1
    (display
     (left-fringe exclamation-mark
                  flycheck-fringe-warning))))

(with-current-buffer (get-buffer-create "*overlay-stacking-bug*")
  (erase-buffer)
  (fundamental-mode)

  (dotimes (i 50)
    (insert "AAAAAAAAAAAAAAAAAAA\nBBBBBBBBBBBBBBBBBBB\n")
    (forward-line -2)
    (let ((ov (make-overlay (point-at-bol) (point-at-eol))))
      (overlay-put ov 'priority 10)
      (overlay-put ov 'face '(:background "red"))
      (overlay-put ov 'before-string --before))
    (let ((ov (make-overlay (+ 1 (point-at-bol)) (point-at-eol))))
      (overlay-put ov 'priority 12)
      (overlay-put ov 'face '(:background "grey"))
      (overlay-put ov 'before-string --before-2))
    (forward-line 1)
    (let ((ov (make-overlay (point-at-bol) (point-at-eol))))
      (overlay-put ov 'priority 15)
      (overlay-put ov 'face '(:background "green")))
    (let ((ov (make-overlay (- (point-at-bol) 3) (+ (point-at-bol) 3))))
      (overlay-put ov 'priority 20)
      (overlay-put ov 'face '(:underline (:style wave :color "yellow") :background "blue")))
    (forward-line 1))
  (display-buffer (current-buffer)))
```

**Comment by dgutov** [comment]
> Does it on anyone else's?

Not on mine. Both variants evaluate instantaneously.

**Comment by dgutov** [comment]
@lunaryorn

> Depending on how overlays are implemented—I don't know how—that can be a costly task.

It could, but so far I haven't seen the degradation myself. When some can create a reproduction scenario, we should still file a bug. So far it sounds like it could be a Mac-specific problem.

**Comment by lunaryorn** [comment]
@dgutov I haven't see it either, and I'm on OS X.  I'll try the recipes of @cpitclaudel tomorrow.

@cpitclaudel Thank you very much for your efforts in trying to reproduce this! 👍

**Comment by lunaryorn** [comment]
@dgutov I tried [@cpitclaudel's snippet](https://github.com/flycheck/flycheck/issues/841#issuecomment-168764826) with no "luck": The overlays insert instantly on OS X, in a recent `emacs25` build.

@purcell Would you mind to try that snippet as well?

**Comment by purcell** [comment]
Thanks all. That snippet evaluates instantaneously for me too. I'll see if I can construct a reproducible example, but it might be a few days or a week before I have time to do so.

**Comment by purcell** [comment]
I tried in https://github.com/purcell/flycheck-issue-841 to reproduce this with fresh simple input files, both ruby and ledger format, but had no luck, so I guess I'll close this for now and circle back next year when I do my accounts again... sigh.

**Comment by dgutov** [comment]
It might be a rather tricky problem related to overlay allocation or the like.

I recall something similar happening with just a handful of overlays that were allocated and discarded quickly: at some point in the Emacs session I got a big slowdown, but it was gone after restart, and wasn't at all stable across files (even big ones), and so on: https://github.com/company-mode/company-mode/pull/57#issuecomment-36209032

**Comment by purcell** [comment]
@dgutov Yeah, I think I didn't try restarting Emacs the first time I saw the issue. I'll be on the lookout for it.

**Comment by lunaryorn** [comment]
@purcell @dgutov Thank you for your feedback.  Please feel free to re-open if the issue occurs again.
