### ISSUE TITLE
Write maintainer guide

### ISSUE THREAD

**Issue by lunaryorn** [flycheck/flycheck#842]
Add a `MAINTAINING.md` to Flycheck, which provides guidelines and processes for maintaining Flycheck.

Specifically:

- [x] Document versioning policy
- [x] Release process and guidelines
- [x] Triaging bugs and using our waffle board (partially already documented in the contributor guide)
- [x] Reviewing and merging pull requests
- [x] ~~Assessing feature requests~~
- [x] ~~Github teams and repo access?~~

**Comment by lunaryorn** [comment]
Blocked by #797.

**Comment by lunaryorn** [comment]
@cpitclaudel If you'd like to see additional topics covered by this guide, please tell me :relaxed:

**Comment by cpitclaudel** [comment]
The first four items sound good! I've been impressed by the quality of your code reviews. And your notes on merging by cherry-picking were definitely useful :)

**Comment by lunaryorn** [comment]
Thank you for these kind words 😊

**Comment by lunaryorn** [comment]
Following #1093 I think this is mostly complete.
