### ISSUE TITLE
haskell-stack-ghc breaks flycheck on non-stack projects

### ISSUE THREAD

**Issue by slpopejoy** [flycheck/flycheck#847]
Change #711 breaks cabal-only projects, if you have stack on your PATH.

It appears that flycheck will ignore a checker if it's command isn't on the PATH. Thus haskell-stack-ghc will not fire on systems without `stack` installed. However this is insufficient for users using stack on some projects but not others. 

Workaround is of course to disable the checker and maybe use dir-locals to turn it back on. However I'm hoping there's a way to check for a `stack.yaml` in the project root and enable the checker then?

Thanks, Stuart

**Comment by lunaryorn** [comment]
Should we tie the `stack-ghc` syntax checker to the presence of `stack.yaml`?  Wouldn't that break Cabal-only project for Stack users without a global GHC installation?

**Comment by slpopejoy** [comment]
I use a globally-installed GHC. If one uses stack to manage GHC, it's still possible to build w/o a stack.yaml? I would think cabal just expects to find `ghc` on the path ...

**Comment by lunaryorn** [comment]
@slpopejoy I don't know.  All my Haskell code uses Stack.

We can easily limit the `stack-ghc` to only apply if there's a `stack.yaml`. @flycheck/haskell , do you think that'd break anything?

**Comment by purcell** [comment]
When I added the stack-detection logic to `haskell-mode` so that `haskell-process-type`'s `auto` option would do the right thing, it was a bit fiddly to get right, but I think the solution was checking for both `stack.yml` and the `stack` executable. IIRC it's possible to have `stack.yml` files which aren't called `stack.yml`...

**Comment by lunaryorn** [comment]
@purcell As far as I know, you can set `$STACK_YAML`.  We'd really need to take that into account, though, because some projects seem to have two or more different stack configurations for different GHC versions.

**Comment by cpitclaudel** [comment]
What's the situation with Haskell nowadays? Is anything still needed here? I see that we closed #857 in the past, which is too bad :/ But on the other hand we have https://github.com/flycheck/flycheck-haskell/ now, so I'm not sure how we should proceed (cc @sergv).

**Comment by purcell** [comment]
Yeah, something like #857 would be a good move, IMO.

**Comment by cpitclaudel** [comment]
Ok, I'll rebase it.  One question: now that we have a function to compute the stack working directory, is it enough to check whether that function returns nil?

**Comment by purcell** [comment]
> Ok, I'll rebase it.

I'm not sure the code is quite right yet, to be honest: I think it might explode if it hits a possibly-nil value returned by `(getenv "STACK_YAML")`. I'd probably use a variable to optionally set a fallback dir in placed of the env var.

> One question: now that we have a function to compute the stack working directory, is it enough to check whether that function returns nil?

Oh, which function is that?

**Comment by purcell** [comment]
I see that flycheck haskell finds the root dir using the output of
```
(process-lines stack
                                            "--no-install-ghc"
                                            "path" "--project-root")
```
which could work nicely here too.

**Comment by cpitclaudel** [comment]
> which could work nicely here too.

Yup, I went that route, and rewrote the patch from scratch. See #1721.
