### ISSUE TITLE
Feature Request: New CSS Checker ( Recess )

### ISSUE THREAD

**Issue by Announcement** [flycheck/flycheck#863]
# [RECESS](https://twitter.github.io/recess/)
*Twitter's CSS Hinter*
> ## What It Does
> Use RECESS as a **linter** to keep your styles tidy and consistent.
>
> The rules are as follows (you can disable individual rules if you don’t want to abide by them):
> - **noIDs** - Don’t style IDs like `#foo`
> - **noJSPrefix** - Don’t style `.js-` prefixed classnames
> - **noOverqualifying** - Don’t overqualify your selectors, like `div#foo.bar`
> - **noUnderscores** - Don’t use underscores when naming classes, like `.my_class`
> - **noUniversalSelectors** - Don’t use the universal selector, `*`
> - **zeroUnits**  - Don’t add the unit to a value of 0, like `0px`
> - **strictPropertyOrder** - Enforce a strict property order (order defined [here](https://github.com/twitter/recess/blob/master/lib/lint/strict-property-order.js#L36))
> 
> RECESS can also **compile** your styles! Powered by the LESS tokenizer, this means you can compile both CSS and LESS source files directly. The compiler will normalize whitespace, strip units from 0 values, and reorder your properties for you.

## RECESS CLI
```shell
npm install --global recess
recess web-view.css
```
## Output
```
Analyzing the following files: web-view.css                    
                                                               
FILE: web-view.css                                             
STATUS: Busted                                                 
FAILURES: 3 failures                                           
                                                               
Id's should not be styled                                      
       1. #web-view-iframe                                     
                                                               
Incorrect property order for rule ".web-view-toolbar"          
                                                               
  Correct order below:                                         
                                                               
       6.  width: 100%;                                        
       7.  height: 35px;                                       
       8.  padding: 5px 10px;                                  
       9.  background-color: #f2f2f2;                          
                                                               
Incorrect property order for rule ".web-view-toolbar .icon"    
                                                               
  Correct order below:                                         
                                                               
      12.  color: black;                                    
      13.  background: #fff;                                   
      14.  border: 1px solid #ccc;                             
```

**Comment by cpitclaudel** [comment]
Hi @Announcement,

This would be great to have. Flycheck is very easy to extend; would you like to help create the checker definition? Basically we'll need to:

* Figure out whether we can make the output a bit more machine-friendly; looking at the example you gave, there are no line or column numbers; recess can probably be made to output them, and we need them to highlight the right places.
* Write a flycheck checker definition; @lunaryorn wrote [detailed instructions](http://www.flycheck.org/manual/latest/Syntax-checker-definitions.html#Syntax-checker-definitions) for that. The final bit of code will probably be no more than 10 lines long, though :)

Then we'll update the docs to mention the new checker. We can help with any of these parts; just let us know if anything is unclear!

**Comment by Simplify** [comment]
Recess is no longer maintained: https://github.com/twitter/recess

**Comment by lunaryorn** [comment]
@Simplify Thank you for making us aware. I closed this issue.
