### ISSUE TITLE
Flycheck SDK error when recompiling .emacs

### ISSUE THREAD

**Issue by mcandre** [flycheck/flycheck#866]
Each Emacs session, the first time I try to compile my .emacs, I get an error with respect to Flycheck SDK path.

https://github.com/mcandre/dotfiles/blob/master/.emacs

**Comment by cpitclaudel** [comment]
Hi,

Can you minimize your .emacs to reproduce the error with a small amount of code, starting from `emacs -Q`?

Thanks!

**Comment by mcandre** [comment]
The problem happens when I byte compile my .emacs. See a similar problem here:

https://github.com/chrisbarrett/swift-mode/pull/67

**Comment by cpitclaudel** [comment]
I understand, but I don't think it's reasonable to expect me to debug your .emacs :) Either post a copy of the actual error, or a minimal snippet that allows me to reproduce it.

**Comment by mcandre** [comment]
The problem appears when I (require) dart-mode or swift-mode, and then attempt to byte-compile my .emacs.

**Comment by cpitclaudel** [comment]
@mcandre I'm sorry, but you still haven't stated what the problem actually is (or I missed it?). This being Flycheck's tracker, I don't really see what dart-mode or swift-mode have to do with it. If you me to help, please at least tell me what the problem is.

**Comment by lunaryorn** [comment]
@mcandre Please provide an *exact copy* of the error message, and a minimal example that allows to reproduce the error.   I do not know what you mean with "Flycheck SDK path".

We'll need more information to be able to help you.

Thank you

**Comment by lunaryorn** [comment]
@mcandre I'm closing this issue due to the lack of activity.  Please feel free to leave further comments with the information we asked for, and we'll reopen the issue if needed.

Thank you.
