### ISSUE TITLE
Please document the function `flycheck-add-mode`

### ISSUE THREAD

**Issue by ackalker** [flycheck/flycheck#869]
There is currently no documentation for this function in the info file.

**Comment by fmdkdd** [comment]
There is info manual anymore, but we still have to document these functions in the Rest manual.  Closing in favor of #928.

**Comment by togakangaroo** [comment]
I don't see this function at all in latest versions, did it get removed?

**Comment by fmdkdd** [comment]
@togakangaroo https://github.com/flycheck/flycheck/blob/master/flycheck.el#L2279
