### ISSUE TITLE
javascript-jshint definition issue since PR 825

### ISSUE THREAD

**Issue by cwhatley** [flycheck/flycheck#871]
This PR breaks for me: https://github.com/flycheck/flycheck/pull/825

This PR calls jshint with `--extract`, but my jshint (2.9.1) expects an equals sign like `--extract=XXX` and when I load a js file now, I get an error message about jshint not liking `--extractnil`.

Flycheck version: 0.26snapshot (package: 20160207.255)

**Comment by lunaryorn** [comment]
@cwhatley Sorry, should be fixed with the next MELPA update.

**Comment by cwhatley** [comment]
Bonus! Apologies for not taking the time to submit a patch.

**Comment by lunaryorn** [comment]
@cwhatley You're welcome :relaxed:
