### ISSUE TITLE
flycheck-flake8-maximum-line-length not work

### ISSUE THREAD

**Issue by kendriu** [flycheck/flycheck#872]
I have set `flycheck-flake8-maximum-line-length` to 99 in my configs:
    
    (use-package flycheck
				:ensure t
				:config
				(add-hook 'after-init-hook #'global-flycheck-mode)
				;; flycheck looks for libraries in load-path variable
				(setq-default flycheck-emacs-lisp-load-path 'inherit)
				(setq-default flycheck-flake8-maximum-line-length 99)
				)

But in my python files I still have error:

    E501 line too long (94 > 79 characters)

Flycheck version: 20160117.1029
Emacs version: GNU Emacs 25.1.50.1 (x86_64-apple-darwin15.2.0, NS appkit-1404.34 Version 10.11.2 (Build 15C50)) of 2016-01-12
Flake8 version:  2.5.2

**Comment by lunaryorn** [comment]
@kendriu Please show the output of `M-x flycheck-verify-setup` and the output of `C-c ! C-c python-flake8`, in an affected buffer.

Please also ensure that your Flycheck version is up to date.

**Comment by kendriu** [comment]
`flycheck-verify-setup` ouptput

  python-flake8
    - predicate:  t
    - executable: Found at /usr/local/bin/flake8

  python-pylint
    - predicate:  nil
    - executable: Not found

  python-pycompile
    - predicate:  t
    - executable: Found at /usr/local/bin/python

Flycheck Mode is enabled.

python-flake8 output:
-*- mode: compilation; default-directory: "~/sources/vagrant/app/safari/backend/tests/unit/chat/" -*-
Compilation started at Wed Feb 10 12:13:08

flake8 --format\=default --max-line-length 99 - < /Users/kendriu/sources/vagrant/app/safari/backend/tests/unit/chat/test_conversationservice.py

Compilation finished at Wed Feb 10 12:13:08

**Comment by lunaryorn** [comment]
@kendriu There's no error in the `python-flake8` output; where does the `E501` error appear?  Can you show a screenshot?

**Comment by kendriu** [comment]
https://www.dropbox.com/s/opsff66fhwxq5qk/Screenshot%202016-02-10%2015.13.16.png?dl=0

**Comment by lunaryorn** [comment]
@kendriu The error does not come from Flycheck.  Take a look at the mode line, it says `FlyC`.  If it were a Flycheck error, it'd read `FlyC:1/0`.

Something else also checks your buffer for error.  At a wild guess, I'd say it's Flymake; you're using Elpy which as far as I know turns Flymake on.  Probably @jorgenschaefer can tell.

I'm closing this issue as `invalid`.

**Comment by jorgenschaefer** [comment]
If you are using Elpy, make sure to remove `elpy-module-flymake` from `elpy-modules` so Elpy won't enable flymake for you. :-)

**Comment by kendriu** [comment]
Thanks all for your help.
I removed `elpy-module-flymake` with command:

    (remove-hook 'elpy-modules 'elpy-module-flymake)

An it stoped showing `E501` error

**Comment by lunaryorn** [comment]
@kendriu Great.  I'm happy that your problem is solved.

By the way, are you aware that you can directly attach images to comments?  I've edited [your comment](https://github.com/flycheck/flycheck/issues/872#issuecomment-182392120) accordingly :smiley:

**Comment by kendriu** [comment]
@lunaryorn Didn't knew that. Thanks.
