### ISSUE TITLE
Elixir language support

### ISSUE THREAD

**Issue by wende** [flycheck/flycheck#877]
Elixir's community is vastly growing. It's already bigger than Erlang's.
It'd be nice to see a support for that language

**Comment by cpitclaudel** [comment]
Indeed, it would be very cool! Do you think you could help us write and test the checker definition? It should be pretty easy :) There's comprehensive documentation here: http://www.flycheck.org/manual/latest/Syntax-checker-definitions.html#Syntax-checker-definitions , and the final code will probably be no more than 10 lines long.

**Comment by lunaryorn** [comment]
@wende We used to have basic Elixir support, but had to remove it.  See #630.

We welcome contributions that provide a new approach to Elixir.  Please feel free to open a pull request.  Our new [Contributing guide](https://github.com/flycheck/flycheck/pull/868) hopefully gives you a gentle introduction to contributing to Flycheck.

Thank you.

**Comment by kthelgason** [comment]
There are some good standalone linters and syntax checkers for elixir [(dogma)](https://github.com/lpil/dogma) is one. These are quite easy to integrate into flycheck. Is there any interest in a PR adding support for one?

**Comment by cpitclaudel** [comment]
Hi @kthelgason,

Sure, we're definitely interested! Provided it doesn't have the issue that our original checker did, of course :)

Clément.

**Comment by wende** [comment]
There is one by @obmarg here
https://github.com/obmarg/flycheck-elixir-dogma
I already integrated that into my spacemacs layer and it works great

**Comment by kthelgason** [comment]
@wende Yeah, I saw his checker afterwards, and what I wrote was really similar.
There are some issues with it though, it supposedly only works with a specific version of dogma (although that's probably dogma's problem).

**Comment by wende** [comment]
I don't have any problems with that.
But dogma has to be installed as an archive, because it tries to launch mix in the directory the buffer's file is in, not in the root of the project

**Comment by lunaryorn** [comment]
Now that we've got dogma in Flycheck, is this still an issue?

**Comment by aaronjensen** [comment]
dogma now, credo soon. Dialyzer (dialyxir) next when I get a chance. 

A basic syntax checker could be useful, especially since credo doesn't report specific syntax errors. I understand the concern around executing code during compilation so it'd probably be fine to avoid that, but the syntax check method suggested in #630 could be helpful.

**Comment by kthelgason** [comment]
I'm not sure there is a good reason for keeping this issue open though. But I agree with @aaronjensen that there are lots of improvements to be made, and I too would really like to support credo (there is a separate issue for that: #1062)

**Comment by lunaryorn** [comment]
I'm closing this issue then.  Thanks for your help ☺️

**Comment by lunaryorn** [comment]
@kthelgason Ah, thanks for actually closing it :blush: I'm always getting these buttons under the comment form wrong 😕
