### ISSUE TITLE
Add issue template?

### ISSUE THREAD

**Issue by lunaryorn** [flycheck/flycheck#881]
https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by lunaryorn** [comment]
@cpitclaudel I'm not sure about this one.  It sounds like a nice idea, but I'm afraid that a big template would put off users, all the more since it'd be difficult to find one that serves all needs (e.g. bugs, feature requests, discussions, etc.).  I'd rather let users report liberally and then ask them for information that we need—we're not drowning in bug reports after all.

What do you think?

**Comment by cpitclaudel** [comment]
I don't think that we've had very many issues with incomplete bug reports; there's been a few, but asking for more information isn't very hard, and if the OP won't provide it then they probably wouldn't fill the template properly either, I guess.
And indeed, your code has very few bugs ^^ With that and the fact that our audience is pretty tech-savvy, I don't think issue templates are crucial.

**Comment by lunaryorn** [comment]
@cpitclaudel Thanks for your opinion.  I'll close this issue as `wontfix` :relaxed:

**Comment by lunaryorn** [comment]
I'm re-opening this one, because I've seen how Ensime does it and really like it:  They don't use the issue template as an actual template, but rather as some kind of a welcome message which has some general guidelines and a prominent thank you.  You're actually supposed to delete the template once you've read it.

I really like this way of greeting new and old contributors :heart_eyes: so I'll add something similar for Flycheck, too.

**Comment by cpitclaudel** [comment]
:+1:
