### ISSUE TITLE
Support for acting on error ids

### ISSUE THREAD

**Issue by cmarqu** [flycheck/flycheck#882]
The compiler I wrote a flycheck extension for (https://github.com/cmarqu/flycheck-hdl-irun) produces unique error ids (like many other checker tools).
In my case, there is another tool available (called ``nchelp``) which prints additional information for each error id. It would be nice if there was something built into flycheck which would allow me to use this output.
Some ideas:
- make the error id in the checker tool output interactive, e.g. display a tooltip with the nchelp output, or open another buffer with the nchelp output when I click on the error id
- add the nchelp output to the existing error tooltip (which may lead to a large tooltip however, I have seen nchelp output that spanned ten lines)

Note that the nchelp output - while being pure ASCII text - cannot always be reflown, i.e. it sometimes contains code examples that are indented etc.  A working heuristic could be to reflow everything except lines that start with whitespace.

(Also, the nchelp output sometimes contains references to language reference manual sections. This could be another link in the lookup chain, but that's probably overkill.)

**Comment by lunaryorn** [comment]
I'm not sure what kind of support you'd like to see from Flycheck here.  Flycheck does provide an API to access error IDs, e.g. `flycheck-error-id` on a Flycheck error object.  Combined with the existing API to list errors at point, etc. that should be enough to write an extension that provides additional commands on error IDs.  You could even write a custom error display function that adds additional information based on the error ID.

What do you need specifically beyond that?

With regards to the built-in tooltip, I'm not in favour of letting extensions add arbitrary content to it.  The tooltip should provide the error and nothing else, to keep it responsive and to the point.  If there are additional options for that error, like a documentation lookup or a quick fix or whatever, these options should be provided by separate commands.

Besides, you'll understand that we can provide only very limited support for a proprietary tool like nchelp.  While we can guide you through Flycheck's API and provide help for Flycheck-specific issues, you're on your own with problems regarding nchelp and its output.

**Comment by lunaryorn** [comment]
@cmarqu Did my comment help you, or do you have further questions about error IDs?  Do you need specific help with Flycheck's API?

**Comment by cmarqu** [comment]
Sorry, things changed at work so it will be a few weeks/months (if ever) until I can try to work on this again. Feel free to close this issue or put on hold as you see fit.

**Comment by lunaryorn** [comment]
@cmarqu I'm closing this issue then.
