### ISSUE TITLE
Define versioning policy following 1.0

### ISSUE THREAD

**Issue by lunaryorn** [flycheck/flycheck#892]
Use semver, but loose some restrictions on backwards compatibility.  We should be able to make breaking changes to syntax checker definitions without having to bump the major version.

**Comment by lunaryorn** [comment]
Actually, given the overwhelming preference for MELPA over MELPA (200k vs. 3k) downloads, I don't think anymore that this is worth the effort.

I'd rather go for the systemd scheme now: A single increasing version number.  The next release would be 1, then 2, 3, 4, etc…

@cpitclaudel What do you think?

**Comment by cpitclaudel** [comment]
I think I like your new avatar, but that's unrelated. On the subject at hand, I do think indeed that versioning is a minor issue, given that most people don't even see the version number we pick (due to MELPA). But I like it as a way to mark milestones; so maybe 1.0, 1.1, 1.2 etc? And 2.0 for the next big thing (?) :)

**Comment by lunaryorn** [comment]
@cpitclaudel Thanks :blush:  

Back to topic, I agree that it's unimportant, at least our current distribution channels.  I see your point about milestones, but I didn't use versions this way in the past, and I don't think that we have the resources for anything other than "continuous releases from `master`" versioning model, do we? And do we want to spent resources on something that's a minor issue?

**Comment by lunaryorn** [comment]
On the other hand, a continuous version would simplify so many things: We'd have no complex bumping logic for version numbers, we'd not have to consider backwards compatibility nor make promises about it (which we don't do anyway currently), we don't need complex releases processes, we don't need to make decisions about what goes into a version or not, etc.

**Comment by cpitclaudel** [comment]
> We'd have no complex bumping logic for version numbers, we'd not have to consider backwards compatibility nor make promises about it

Oh, I see :) Then I'm all for continuous version number.

**Comment by lunaryorn** [comment]
We'll use a continuous number them :)  What works for systemd can't be too bad for us :sunglasses:
