### ISSUE TITLE
Default JavaScript linter

### ISSUE THREAD

**Issue by jacksonrayhamilton** [flycheck/flycheck#893]
Should JSHint remain the default JavaScript linter, or should ESLint be the default? Here is my evaluation of the two linters (with respect to their default status in Flycheck):

# JSHint

## Pros

- Was the default for a while (therefore, leaving it there prevents a breaking change)
- Has been around longer, and thus is probably used by more projects

## Cons

- More opinionated than ESLint, thereby suitable for fewer projects
- Only focused on code quality (not formatting)

# ESLint

## Pros

- Unopinionated; only checks for parse errors by default
- Also does formatting checking, potentially making it a better default as an "all-in-one" (no need to run `javascript-jscs` as a next checker)
- Maybe a more popular choice for newer projects

## Cons

- Setting it as default causes breaking change
- Probably used in fewer projects overall

Personally, I use both, and detect which one to use based on the project. But maybe other people will be negatively affected by ae2dd6eaf8feb229d6ab6284ff1aec17f8bc2d84, so I'm posing this issue.

BTW, for anyone who is affected, this is the detection code I use:

```js
(defun jrh-locate-dominating-file (regexp)
  "Locate a directory with a file matching REGEXP."
  (locate-dominating-file
   default-directory
   (lambda (directory)
     (> (length (directory-files directory nil regexp t)) 0))))

(defconst jrh-jshint-regexp
  (concat "\\`" (regexp-quote ".jshintrc") "\\'"))

(defconst jrh-eslint-regexp
  (concat "\\`" (regexp-quote ".eslintrc") "\\(\\.\\(js\\|ya?ml\\|json\\)\\)?\\'"))

(defun jrh-js2-mode-hook ()
  (cond
   ((jrh-locate-dominating-file jrh-jshint-regexp)
    (flycheck-select-checker 'javascript-jshint))
   ((jrh-locate-dominating-file jrh-eslint-regexp)
    (flycheck-select-checker 'javascript-eslint))))

(add-hook 'js2-mode-hook #'jrh-js2-mode-hook)
```

Maybe this would matter less if Flycheck looked for configuration files as a means of detecting which linter to use.

**Comment by lunaryorn** [comment]
Thank for you thorough analysis.  Do I understand correctly that you're not personally affected by the changed preferences?  In other words, currently we discuss purely on theoretical grounds?  I'm just trying to assess the urgency of this issue.

I don't see a decisive argument for either side, but I would like to point out that backwards compatibility is not our concern currently—hence the 0.x version numbers—and we'll only make limited guarantees about backward compatibilities in future.  We made breaking changes [in all last releases](http://www.flycheck.org/changes.html).

As such, I currently don't see a compelling argument for either side, and am inclined to stay with the current preference for eslint, purely for personal preference :relaxed:

Please feel free to invite other people into our discussion if they can add further information that helps us to define the preference of Javascript linters.  It'd be great to hear some voices from the Javascript community here :blush:

**Comment by jacksonrayhamilton** [comment]
> Do I understand correctly that you're not personally affected by the changed preferences?

I was affected momentarily, but then I generalized my linter checking code to what is posted above, and then I was no longer affected.

**Comment by lunaryorn** [comment]
We do dynamically detect linters based on configuration files in some cases, but in this case that's not a viable option I think.  I think it's a legitimate use case to run `eslint` for syntax checking alone, e.g. in a throw-away node.js script.  In addition to that eslint has quite a complex algorithm for finding its configuration files which we'd have to somewhat mirror in order to accurately determine whether a eslint configuration is applicable for the current file.

However, we already have powerful options to customise syntax checker selection, above all `flycheck-disabled-checkers` which lets you locally disable specific syntax checkers.  

For this reason I presume that only few people are actually affected by this issue, since most will have chosen one or another syntax checker for their project anyway I guess.

**Comment by jacksonrayhamilton** [comment]
This issue hasn't gotten much outside attention, so I assume the change bodes well with most Flycheck JavaScripters. I am liking ESLint more and more, so I'm perfectly fine with this default.

> For this reason I presume that only few people are actually affected by this issue, since most will have chosen one or another syntax checker for their project anyway I guess.

Hm, I dunno. At least in the JavaScript community, I suspect there are plenty of people who use different linters; out of curiosity, or due to working at a company that follows the latest fads, or because they contribute to a variety of open source projects. (I actually just described myself. Is that rare? Might be a good question to ask in #920.)

**Comment by lunaryorn** [comment]
@jacksonrayhamilton I'll close this issue then.  We'll keep the current defaults.

> I actually just described myself. Is that rare?

I do not know.  I'm the wrong person to ask.  I must admit that I loathe the language and pity the ecosystem :blush:, and all that I have on my system is the minimum viable environment I need for work, and that only includes eslint :relaxed:
