### ISSUE TITLE
A checker for textlint?

### ISSUE THREAD

**Issue by kozross** [flycheck/flycheck#899]
I recently came across [this](https://github.com/textlint/textlint), and thought it would make for a really nice Flycheck checker in a place where Flycheck hasn't really gone before (ordinary text). I don't know if this falls outside its scope, but it'd be something I'd really love to have.

**Comment by lunaryorn** [comment]
@kozross It's surely within our scope, and it's a great idea.  Please feel free to open a pull request :relaxed:

**Comment by kozross** [comment]
I came across something *very* similar which could be integrated [here][1]. What should I do to make this part of 'core' Flycheck, if anything? 

[1]: https://github.com/amperser/proselint/blob/master/plugins/flycheck/flycheck-proselint.el

**Comment by lunaryorn** [comment]
@kozross We would happily accept a pull request for this syntax checker.  Please follow our [Pull Request](https://github.com/flycheck/flycheck/blob/master/CONTRIBUTING.md#pull-requests) guide lines for further information.

We would like to ask that the pull request maintains proper authorship, though, i.e. commits should be attributed to @suchow.  And we prefer if @suchow explicitly agreed to add their syntax checker to Flycheck.

**Comment by suchow** [comment]
You have my blessing to the extent that I am legally able to give it. A similar version of that code was originally posted on http://unconj.ca/blog/linting-prose-in-emacs.html, and then modified by @unhammer in https://github.com/amperser/proselint/issues/37.

**Comment by unhammer** [comment]
Is textlint the same as proselint? (I don't think my .el changes were big enough to be copyrightable, but just in case I hereby allow licensing it under whatever flycheck uses.)

**Comment by suchow** [comment]
@unhammer — they're different, but it seems this issue has expanded in scope a little to include proselint.

**Comment by robstewart57** [comment]
I've written up an approach that works well for me: https://www.macs.hw.ac.uk/~rs46/posts/2018-12-29-textlint-flycheck.html

This implements textlint as a flycheck checker.

textlint doesn't apply any rules automatically, they must be explicitly installed with `npm` and specified explicitly with `--rule` when running `textlint`. This is a key design philosophy of textlint: as a __pluggable__ natural language linting tool.

Does this hold back the idea of building a textlint checker directly into flycheck?

**Comment by fmdkdd** [comment]
> Does this hold back the idea of building a textlint checker directly into flycheck?

It would mean duplicating the rules in your Emacs config, so it would add friction.

Can you specify the rules in a config file instead?

**Comment by robstewart57** [comment]
> Can you specify the rules in a config file instead?

Funny you should ask.

Someone has packaged a textlint flycheck checker based on that blog post, where instead all the rules are specific in a config file:

https://github.com/kisaragi-hiu/flycheck-textlint

**Comment by fmdkdd** [comment]
Okay great.  If they or you ever want to include it in Flycheck, then send a PR.

**Comment by cpitclaudel** [comment]
We merged that checker 1 day after this last message, so this is all done :)
