### ISSUE TITLE
Drop in-emacs manual?

### ISSUE THREAD

**Issue by lunaryorn** [flycheck/flycheck#901]
I'm really fed up with Texinfo.  I'd love to go back to [Sphinx](http://www.sphinx-doc.org) and readthedocs as build service.  ReStructuredText is so much easier to write than Texinfo, and I think it's much more friendly to us as maintainers and to newcomers.

However, Sphinx' support for Texinfo is inferior.  When we used Sphinx in the past we worked around this with a lot of extensions to Sphinx, which were tedious to write and maintain.  I don't want to do that again.

Hence we'd have to drop support for Info manuals essentially.  I for my part am totally for it; I'd rather wait and hope for Emacs to add support for a better manual format that we build to.  Texinfo is only used within Gnu and Emacs nowadays; it's a dead end and a rotten technology.  I'd just throw it out, rather than try and continue to cope with it.

But what do you think?

/cc @cpitclaudel @purcell @jwiegley @bbatsov

**Comment by bbatsov** [comment]
I completely agree.

**Comment by lunaryorn** [comment]
Sometimes I wished we had Google Analytics for Emacs… I'm dying to find out how many of my users actually ever looked at the manual in Emacs :grin:

**Comment by tzz** [comment]
I'm sure many of you have seen https://lwn.net/Articles/625072/

And from me:

https://lists.gnu.org/archive/html/help-gnu-emacs/2010-05/msg00175.html

rule #1 of writing manuals:

They Won't Read It.

followed by rule #2:

They Still Won't Read It.

and then rule #3:

They'll Complain About It.

**Comment by lunaryorn** [comment]
@tzz Thanks for your feedback, but… I must admit that I'm not sure what to make of it.  Do you agree with my point of view? Or not?  Or do you think that all efforts for a manual are vain?

**Comment by tzz** [comment]
@lunaryorn I was trying to say that the vast majority of users don't read manuals, replying to your question about how many of your users look at your manual. Good UI is worth much more than a good manual. So I would use the documentation markup that's most comfortable for the developers with local project scope, which is probably RST.

I am especially skeptic of claims that any particular documentation markup language will solve software usability issues, or that it's causing them.

**Comment by lunaryorn** [comment]
I appreciate your opinion, but this is not the place for it.  If you seek to continue the discussion about Emacs' own manual format, please do so on emacs-devel.

Our own situation and our own preferences are very different from Emacs' and only little of was said in favour or against Texinfo on emacs-devel applies to us.  There's so much that's blocking and discouraging contributions to Emacs that the manual format hardly adds anything to the equation.

----

But I think that it does add something to our equation. Contributing on Github is as is as it gets, to the point where formats matter.  There's a reason why only a tiny minority of Emacs packages even includes a Texinfo manual.

We *did* have contributors who expressed distaste at Texinfo.  They did contribute to documentation anyway, for sure, but why should we stick to a format that's hard for us, hard for contributors, and disconnected from the rest of the world?

That's why I'm curious to learn whether people do read our manual in Emacs.  Besides, I *know* that they do read the online manual at http://www.flycheck.org, because I track visits with Google Analytics.

**Comment by tzz** [comment]
@lunaryorn I **was** talking about Flycheck in particular, not about Emacs (and the link was relevant to you only as far as TexInfo itself, intending to show that even for Emacs itself it's not a beloved format). Sorry if I gave an impression otherwise.

Anyhow, my vote is to use RST or Markdown because they are much better than TeX derivatives.

**Comment by lunaryorn** [comment]
@tzz Oh, I totally misunderstood your comments then 😳😔. I'm really really sorry! 

Thank you very much for your feedback and your opinion! 😊. That's three (me included) in favour of Sphinx, at the expense of a Info manual for Emacs 😎

**Comment by cpitclaudel** [comment]
+1 for dropping TeXinfo :) I for one am not very good at browsing documentation in Emacs anyway, but I did read the docs on Flycheck's website.

**Comment by jwiegley** [comment]
As a person who has read the Emacs manual several times, I must say that I *love* it being in Info format, as it allows me to seamlessly consult it while programming, without changing environments or having to use a Web browser. For other things I have to use a Web or PDF browser to read documentation, and it's a far inferior experience.

That said, I understand the complaints against Texinfo.  The main problem with RST/Markdown, etc., is they just aren't rich enough to communicate all the information Texinfo can (indices, anyone?).  For my own documentation at work I use straight LaTeX; for my own projects, Markdown.  The fracture burns us.

**Comment by lunaryorn** [comment]
So do I @jwiegley, but the pain of maintaining Texinfo isn't worth the convenience of reading docs in Emacs, all the more as only few documentation is available as Info anyway.  I for my part mostly read docs in the excellent Dash app for OS X nowadays, and sometimes resort to browsing docs with EWW.

Markdown is no alternative indeed, and ReST alone neither, but ReST is an extensible markup format and the aforementioned Sphinx processor enriches with various features for documentation, including indices, structured definitions, cross references, etc.  I've written large documentation with it, and think that it's an excellent substitute for Texinfo.

I'm very much in favour of using it again for Flycheck. 😊

**Comment by spwhitton** [comment]
As the maintainer of the Debian packaging of flycheck, I'd like to request that if you switch to another format please ensure that it can be built from the git repository without making any network connections.  Then I can include it in `/usr/share/doc/elpa-flycheck`.  That's just as good as Texinfo from Debian's point of view :)

**Comment by lunaryorn** [comment]
@spwhitton I'll try to keep this in mind, but I hope you'll understand that I cannot make a promise.

**Comment by manuel-uberti** [comment]
I love reading manuals inside Emacs, but have no experience on writing them so I don't know about how hard it is to maintain them. The little I know of Flycheck, I know it because of the in-emacs manual. 

However, as long as there is a manual, I'm happy to follow the new way. :-)

**Comment by lunaryorn** [comment]
We now have a new Sphinx-based website, see #923, and will now slowly port the Texinfo manal over to Sphinx.  For now, the old Texinfo manual i still there, but eventually we'll drop it as when the migration is complete.
