### ISSUE TITLE
Checker for gettext .po file using msgfmt

### ISSUE THREAD

**Issue by wbolster** [flycheck/flycheck#902]
See summary. :)

**Comment by lunaryorn** [comment]
@wbolster Thank you very much for this suggestion.  We welcome a pull request that adds such a checker.

**Comment by cpitclaudel** [comment]
There is already a Flycheck checker for po files at https://github.com/petere/emacs-flycheck-po ; @petere, would you like to merge it into Flycheck, or at least publish it on MELPA?
