### ISSUE TITLE
php-phpcs throws error on new file creation

### ISSUE THREAD

**Issue by shanavas786** [flycheck/flycheck#907]
In global-flycheck-mode, when a new php file is created, it throws the following error.

```
Suspicious state from syntax checker php-phpcs: Checker php-phpcs returned non-zero exit code 2, but no errors from output: ERROR: You must supply at least one file or directory to process.

Usage: phpcs [-nwlsaepvi] [-d key[=value]]
    [--report=<report>] [--report-file=<reportfile>] [--report-<report>=<reportfile>] ...
```

Emacs version 24.4.1
Flycheck version 0.26

**Comment by lunaryorn** [comment]
Would you please tell me your phpcs version?

**Comment by shanavas786** [comment]
PHP_CodeSniffer version 1.5.5 (stable) by Squiz (http://www.squiz.net)

**Comment by lunaryorn** [comment]
That is a very old version of phpcs.  Please check whether the issue still exists with the latest release of phpcs.

**Comment by shanavas786** [comment]
Upgraded to PHP_CodeSniffer version 2.5.1 (stable) by Squiz (http://www.squiz.net). The issue is still remaining.
![out](https://cloud.githubusercontent.com/assets/5337197/13749004/95acf720-ea10-11e5-9646-8ca62238bdf1.gif)

**Comment by shanavas786** [comment]
accidentally closed.

**Comment by lunaryorn** [comment]
@shanavas786 Does this also happen when the buffer has contents?

**Comment by shanavas786** [comment]
No, works fine on existing files. It is the error thrown by phpcs command when run on a non-existing file. I think flycheck has to ignore the error.

**Comment by lunaryorn** [comment]
Would you mind to run the following commands and paste the entire output here?

```console
$ touch empty.php
$ phpcs --report=checkstyle < empty.php
```

**Comment by shanavas786** [comment]
➜ touch empty.php
➜ phpcs --report=checkstyle < empty.php
ERROR: You must supply at least one file or directory to process.

Usage: phpcs [-nwlsaepvi] [-d key[=value]] [--colors] [--no-colors]
    [--report=<report>] [--report-file=<reportFile>] [--report-<report>=<reportFile>] ...
    [--report-width=<reportWidth>] [--generator=<generator>] [--tab-width=<tabWidth>]
    [--severity=<severity>] [--error-severity=<severity>] [--warning-severity=<severity>]
    [--runtime-set key value] [--config-set key value] [--config-delete key] [--config-show]
    [--standard=<standard>] [--sniffs=<sniffs>] [--encoding=<encoding>]
    [--extensions=<extensions>] [--ignore=<patterns>] [--bootstrap=<bootstrap>] <file> ...
                      Set runtime value (see --config-set) 
        -n            Do not print warnings (shortcut for --warning-severity=0)
        -w            Print both warnings and errors (this is the default)
        -l            Local directory only, no recursion
        -s            Show sniff codes in all reports
        -a            Run interactively
        -e            Explain a standard by showing the sniffs it includes
        -p            Show progress of the run
        -v[v][v]      Print verbose output
        -i            Show a list of installed coding standards
        -d            Set the [key] php.ini value to [value] or [true] if value is omitted
        --help        Print this help message
        --version     Print version information
        --colors      Use colors in output
        --no-colors   Do not use colors in output (this is the default)
        <file>        One or more files and/or directories to check
        <bootstrap>   A comma separated list of files to run before processing starts
        <encoding>    The encoding of the files being checked (default is iso-8859-1)
        <extensions>  A comma separated list of file extensions to check
                      (extension filtering only valid when checking a directory)
                      The type of the file can be specified using: ext/type
                      e.g., module/php,es/js
        <generator>   Uses either the "HMTL", "Markdown" or "Text" generator
                      (forces documentation generation instead of checking)
        <patterns>    A comma separated list of patterns to ignore files and directories
        <report>      Print either the "full", "xml", "checkstyle", "csv"
                      "json", "emacs", "source", "summary", "diff"
                      "svnblame", "gitblame", "hgblame" or "notifysend" report
                      (the "full" report is printed by default)
        <reportFile>  Write the report to the specified file path
        <reportWidth> How many columns wide screen reports should be printed
                      or set to "auto" to use current screen width, where supported
        <sniffs>      A comma separated list of sniff codes to limit the check to
                      (all sniffs must be part of the specified standard)
        <severity>    The minimum severity required to display an error or warning
        <standard>    The name or path of the coding standard to use
        <tabWidth>    The number of spaces each tab represents



➜ phpcs --report=checkstyle  empty.php 
<?xml version="1.0" encoding="UTF-8"?>
<checkstyle version="2.5.1">
<file name="/home/shanavas/test/empty.php">
 <error line="1" column="1" severity="warning" message="No PHP code was found in this file and short open tags are not allowed by this install of PHP. This file may be using short open tags but PHP does not allow them." source="Internal.NoCodeFound"/>
</file>
</checkstyle>

**Comment by lunaryorn** [comment]
@shanavas786 Flycheck does not give file names to `phpcs`.  As you can see in the syntax checker definition we pass the contents of the buffer to standard input of `phpcs`.  Unfortunately, though, while phpcs seems to work fine on an empty file it appears to choke on empty standard input.

I changed Flycheck to skip phpcs if the buffer is empty to workaround this issue, but I'd argue that it's actually a bug in phpcs.

**Comment by twlz0ne** [comment]
Seems issue is back.

<pre>
(emacs-version) ;; => "GNU Emacs 25.2.1 (x86_64-apple-darwin15.6.0) of 2017-02-27"
(flycheck-version) ;; => <b>"31snapshot (package: 20170223.247)"</b>
(shell-command-to-string "phpcs --version") ;; => "PHP_CodeSniffer version 2.8.0 (stable) by Squiz (http://www.squiz.net)"
</p>

**Comment by cpitclaudel** [comment]
@twlz0ne Can you provide the same details as above, in a new issue? Thanks!

**Comment by twlz0ne** [comment]
@cpitclaudel After confirmation, I found that the problem was caused by org-mode. By pressing <kbd><sTAB</kbd><kbd>php</kbd><kbd>C-c '</kbd>, i got a buffer which size is 1:

<img width="640" alt="emacs-org-mode_empty-buffer-size-1" src="https://cloud.githubusercontent.com/assets/2653486/23586894/1755e2fa-01da-11e7-9d99-f059039f498d.png">

Than i create an advice to fix it:

``` elisp
(defun around/flycheck-buffer-empty-p (f &rest ARG)
  (let ((n (apply 'buffer-size ARG)))
    (cond ((= n 0) t)
          ((= n 1)
           (let ((matched (string-match "\\`\\*Org Src .* ]\\*\\'" (apply 'buffer-name ARG))))
             (if (null matched)
                 nil
               (zerop matched))))
          (t nil))))

(advice-add 'flycheck-buffer-empty-p :around #'around/flycheck-buffer-empty-p)
```

Maybe the better way is:

```elisp
(devar minimal-size 5)
(defun flycheck-buffer-empty-p (&optional buffer)
  (<= (buffer-size buffer) minimal-size))
```

Although it is not a flycheck issue, but it would be nice if there were an option to decide when to start check.

**Comment by cpitclaudel** [comment]
Interesting, thanks.  Does the size matter, or is it just a problem with fully blank buffers?
Also, it seems that org-mode sets buffer-file-name to `"[*Org Src <file name here>[ php ]*]"` for buffers created with `C-'`. Isn't that wrong?
