### ISSUE TITLE
Contribution guidelines contain an incorrect gem instruction

### ISSUE THREAD

**Issue by kozross** [flycheck/flycheck#914]
The instructions say this:

> We recommend that you install all tools for ``verify:*`` with ``gem install travis rubocop markdownlint`` if you intend to work on Flycheck over a longer time.

``markdownlint`` is meant to be installed by calling ``gem install mdl``.

**Comment by lunaryorn** [comment]
Thank you for reporting :)  I've fixed the contributing guide.
