### ISSUE TITLE
``rake check:fast`` fails at the Markdown step on branch

### ISSUE THREAD

**Issue by kozross** [flycheck/flycheck#915]
As per the contribution guidelines, I forked Flycheck, made the changes to ``flycheck.el``, and tried to run ``rake check:fast`` locally. This gave me the following error:

    [koz@Emi flycheck]$ rake check:fast
    travis lint --exit-code --no-interactive
    valid
    mdl --style admin/markdown_style AUTHORS.md CHANGES.md CONDUCT.md CONTRIBUTING.md README.md
    README.md:1: MD041 First line in file should be a top level header
    rake aborted!
    Command failed with status (1): [mdl --style admin/markdown_style AUTHORS.m...]
    /home/koz/documents/programming/elisp/flycheck/Rakefile:108:in `block (2 levels) in <top (required)>'
    Tasks: TOP => check:fast => verify:all => verify:markdown
    (See full trace by running task with --trace)

As I haven't even touched ``README.md``, I'm not sure what I did to cause this. Any help is appreciated.

**Comment by lunaryorn** [comment]
@kozross Thank you for reporting this issue.  The latest mdl release introduced a new warning.  Fixed now.
