### ISSUE TITLE
``rake init`` fails to do anything

### ISSUE THREAD

**Issue by kozross** [flycheck/flycheck#917]
Still following the contribution guidelines, I tried running ``rake init`` to set up local dependencies. I instead got this:

    [koz@Emi flycheck]$ rake init
    rake aborted!
    Don't know how to build task 'init'

    (See full trace by running task with --trace)

I installed the dependencies described in the guidelines (specifically Rake, Travis, Rubocop and MDL). Am I missing something critical?

**Comment by lunaryorn** [comment]
Oh, it's `rake init:all`, actually.  Fixed, and sorry for the hassle :disappointed:
