### ISSUE TITLE
``rake check:fast`` fails on Flycheck head clone

### ISSUE THREAD

**Issue by kozross** [flycheck/flycheck#918]
I get past the Travis, Markdown and Rubocop stages, but then I eventually hit this:

    # omitting some output
    Checking /home/koz/.emacs.d/.cask/24.5.1/bootstrap/shut-up-20150423.522...
    Compiling /home/koz/.emacs.d/.cask/24.5.1/bootstrap/shut-up-20150423.522/shut-up-autoloads.el...
    Compiling /home/koz/.emacs.d/.cask/24.5.1/bootstrap/shut-up-20150423.522/shut-up-pkg.el...
    Wrote /home/koz/.emacs.d/.cask/24.5.1/bootstrap/shut-up-20150423.522/shut-up-pkg.elc
    Compiling /home/koz/.emacs.d/.cask/24.5.1/bootstrap/shut-up-20150423.522/shut-up.el...

    In end of data:
    shut-up.el:150:1:Warning: the following functions are not known to be defined:
        shut-up-write-region-original, shut-up-load-original
    Wrote /home/koz/.emacs.d/.cask/24.5.1/bootstrap/shut-up-20150423.522/shut-up.elc
    Done (Total of 2 files compiled, 1 skipped)
    Contacting host: melpa.org:80
    Generating autoloads for package-build.el...
    Generating autoloads for package-build.el...done
    Saving file /home/koz/.emacs.d/.cask/24.5.1/bootstrap/package-build-20160129.1332/package-build-autoloads.el...
    Wrote /home/koz/.emacs.d/.cask/24.5.1/bootstrap/package-build-20160129.1332/package-build-autoloads.el
    (No changes need to be saved)
    Checking /home/koz/.emacs.d/.cask/24.5.1/bootstrap/package-build-20160129.1332...
    Compiling /home/koz/.emacs.d/.cask/24.5.1/bootstrap/package-build-20160129.1332/package-build-autoloads.el...
    Compiling /home/koz/.emacs.d/.cask/24.5.1/bootstrap/package-build-20160129.1332/package-build-pkg.el...
    Wrote /home/koz/.emacs.d/.cask/24.5.1/bootstrap/package-build-20160129.1332/package-build-pkg.elc
    Compiling /home/koz/.emacs.d/.cask/24.5.1/bootstrap/package-build-20160129.1332/package-build.el...
    Wrote /home/koz/.emacs.d/.cask/24.5.1/bootstrap/package-build-20160129.1332/package-build.elc
Done (Total of 2 files compiled, 1 skipped)

    In toplevel form:
    flycheck.el:74:13:Error: Cannot open load file: no such file or directory, let-alist
    rake aborted!
    Command failed with status (1): [cask exec emacs -Q --batch -L . -f batch-b...]
/home/koz/documents/programming/elisp/flycheck/Rakefile:80:in `block in <top (required)>'
    Tasks: TOP => check:fast => compile:all => compile:elc => flycheck.elc
    (See full trace by running task with --trace)

Is something amiss, or did I miss a step?

**Comment by lunaryorn** [comment]
@kozross I'd need to see your *exact* commands.  Are you sure that you're running on current `master`?  `let-alist` is built-in in upcoming Emacs 25, so this particular failure could only occur on Emacs 24.

**Comment by kozross** [comment]
Sure thing. Here is exactly what I ran, along with output:

    [koz@Emi ~]$ git clone https://github.com/flycheck/flycheck
    Cloning into 'flycheck'...
    remote: Counting objects: 17604, done.
    remote: Compressing objects: 100% (15/15), done.
    remote: Total 17604 (delta 5), reused 1 (delta 1), pack-reused 17588
    Receiving objects: 100% (17604/17604), 13.63 MiB | 1.68 MiB/s, done.
    Resolving deltas: 100% (10977/10977), done.
    Checking connectivity... done.
    [koz@Emi ~]$ cd flycheck/
    [koz@Emi flycheck]$ rake check:fast
    travis lint --exit-code --no-interactive
    valid
    mdl --style admin/markdown_style AUTHORS.md CHANGES.md CONDUCT.md CONTRIBUTING.md README.md
    rubocop --config .rubocop.yml Rakefile admin/lib/flycheck/lint.rb admin/lib/flycheck/travis.rb admin/lib/flycheck/util.rb
    Inspecting 4 files
    ....

    4 files inspected, no offenses detected
    14 files linted, no style errors detected
    cask exec emacs -Q --batch -L . -f batch-byte-compile flycheck.el

    In toplevel form:
    flycheck.el:74:13:Error: Cannot open load file: no such file or directory, let-alist
    rake aborted!
    Command failed with status (1): [cask exec emacs -Q --batch -L . -f batch-b...]
    /home/koz/flycheck/Rakefile:80:in `block in <top (required)>'
    Tasks: TOP => check:fast => compile:all => compile:elc => flycheck.elc
    (See full trace by running task with --trace)

In case it matters, ``emacs --version`` says I'm running 24.5.1.

**Comment by lunaryorn** [comment]
Ah, sorry, I thought you were running on Emacs head.  My mistake.

Still, you're missing `rake init:all` here.  You'll need to install Cask and run `rake init:all` or `cask install` in order to have all required Emacs Lisp libraries, including `let-alist`, available.

**Comment by lunaryorn** [comment]
Thinking of it, our process here is probably too complicated.  I'm currently porting our manual over to Sphinx, and as part of this process I'll try get rid of all this complexity.  You shouldn't need to go through all this, and I'll probably get rid of all this Rake stuff and replace it with some simple shell scripts.

**Comment by kozross** [comment]
OK, thanks for that. I'll close this issue.
