### ISSUE TITLE
A Flycheck survey?

### ISSUE THREAD

**Issue by lunaryorn** [flycheck/flycheck#920]
Following https://github.com/melpa/melpa/issues/3493 I had the idea that we could probably run a survey (e.g. Typeform) which asks a couple of questions to users of Flycheck (e.g. OS, Emacs version, MELPA versus MELPA stable, how often they update, what programming languages they use Flycheck with, etc.).

We could then announce this survey on Twitter, Reddit, etc., and probably find a way to promote the survey in Flycheck itself.

I'd really love to get to know our users.

@cpitclaudel What do you think?

**Comment by cpitclaudel** [comment]
Would be nice! We already know about MELPA v. MELPA Stable though, right?
One annoying bit here is that since all the checkers are packaged together, we don't get to know how many people use each of them. But the only workaround that I can think of (one package per language) would be a pain for users.

**Comment by jacksonrayhamilton** [comment]
Flycheck is essential to my development flow. I'm happy to see it continue to improve, and analytics (a survey) should bring insights on what to do better.

**Comment by lunaryorn** [comment]
I'll prepare a typeform when I've some spare time, with a couple of basic questions:

- Emacs version (multiple choice)
- OS (multiple choice)
- Installation method (ELPA, elget, custom, multiple choice)
- Update frequency (daily, weekly, monthly, infrequently, etc.)
- Languages used (multiple choice, multiple selection)
- Upgrade experience (seamless or breaking?)
- What feature is missed most? (Multiple choice from some open issues)
- Satisfaction with Flycheck (1 to 10)
- NPS
- General feedback (free text)

Please post suggestion for further questions.  And if anyone has an idea how we could somehow propose the survey to Flycheck users in Emacs with minimal interruption that'd be awesome!

**Comment by jacksonrayhamilton** [comment]
> And if anyone has an idea how we could somehow propose the survey to Flycheck users in Emacs with minimal interruption that'd be awesome!

When a user places point on an erroneous line, after the linter's message, if the date is between the start of the survey and its end, append this message: "(Flycheck checked your code, but will you check our survey? `(setq flycheck-survey-2016 nil)` to hide this message.)"

**Comment by kozross** [comment]
@jacksonrayhamilton I think that's an excellent idea, much like the survey.

**Comment by lunaryorn** [comment]
@jacksonrayhamilton Indeed, that's a good idea :+1:

**Comment by cpitclaudel** [comment]
Sounds good, though I wonder it it might be a bit too invasive/disruptive. Ideally we want to ping people at a point when they are not focused on a high-attention task.

What about a message wrapped in `eval-when-compile`? It would be displayed when updating Flycheck, which is presumably a good time.

**Comment by lunaryorn** [comment]
@cpitclaudel I'm not sure.  I guess many people ignore messages during installation…

Maybe load time is better?

And then, is a message appended to an error message really that disruptive?  I'm not sure…

**Comment by cpitclaudel** [comment]
Not sure either :) I was thinking of something like `pop-to-buffer` during package update, but that might be disruptive.

What about (in addition to other solutions) an info (or lower) level message in the error list?

**Comment by cpitclaudel** [comment]
I don't think we need a survey at the moment, or at least the use we'll get from the results will be lower than the cost of the disruption to our users, I expect.
