### ISSUE TITLE
Add an interactive spec to flycheck-stop

### ISSUE THREAD

**Issue by cpitclaudel** [flycheck/flycheck#922]
Hey Sebastian,

Any objection to adding `(interactive)` to `flycheck-stop`? It makes it easier to bind it to a key (and that comes in handy when a rogue checker goes on a loop).

**Comment by lunaryorn** [comment]
@cpitclaudel Are you aware that `flycheck-clear` interrupts checkers when given a prefix argument?  In other words, you can already press `C-u C-c ! C` to interrupt a syntax checker.

**Comment by cpitclaudel** [comment]
I was not :)

**Comment by lunaryorn** [comment]
@cpitclaudel Does it solve you problem?

**Comment by cpitclaudel** [comment]
It does, and it's not obvious that there are any case in which running just flycheck-stop would be better. Thanks!
