### ISSUE TITLE
Remove legacy Texinfo manual

### ISSUE THREAD

**Issue by lunaryorn** [flycheck/flycheck#924]
After #928 when all relevant content is in the new manual.  #616 can come afterwards.

**Comment by lunaryorn** [comment]
@cpitclaudel What do you think about removing the legacy manual now?  For sure, we're still missing the developer docs in the new manual, but some of the user information in the legacy manual is outdated, and I fear that it's confusing to users…

**Comment by cpitclaudel** [comment]
I think we can go ahead and remove it.  Keeping the copy of the HTML page around might still be nice, though, to point users to it if needed.

**Comment by lunaryorn** [comment]
Well, the manuals for the older versions are still available via readthedocs, so we'll continue to serve the legacy manual that way.

**Comment by lunaryorn** [comment]
IOW, http://www.flycheck.org/en/30/#the-developer-guide would still link to an existing copy of the old manual; it's just `latest` and future releases that'll not include the legacy manual anymore.

**Comment by cpitclaudel** [comment]
Yup, that's great.
