### ISSUE TITLE
Support for checking AWK scripts

### ISSUE THREAD

**Issue by ackalker** [flycheck/flycheck#929]
It would be nice for Flycheck to have support for checking AWK scripts.
I think this is quite doable, and in a safe way, too, contrary to what one might expect.
Please see [this SO answer](http://stackoverflow.com/a/7212314/588561) for details.

**Comment by cpitclaudel** [comment]
Yup, good call; that SO answer looks convincing. 

We don't have a very rich history of accepting checkers that massage the input too much, but in this case it seems pretty minimal. @lunaryorn will make the final call on that.

Here's an idea: can you try to write a checker definition based on that SO answer? I can help if anything from http://www.flycheck.org/en/latest/_downloads/flycheck.html#Syntax-checker-definitions is unclear. Then we can decide whether it should go into flycheck itself, or as a separate package; but in any case it will be useful!

Cheers,
Clément.

**Comment by lunaryorn** [comment]
@ackalker We'll certainly accept an AWK checker if it's safe—which the SO answer seems to promise, for GNU AWK at least.

 I will not however add it myself; I don't even use awk.  My priorities are elsewhere. Please feel welcome to open a pull request that adds this syntax checker to Flycheck, though, and ask questions if you need help with defining this syntax checker for Flycheck.

Please take a look at our [Contributor's Guide](http://www.flycheck.org/en/latest/contributor/contributing.html) for more information about contributing to Flycheck.

**Comment by ackalker** [comment]
Thanks for the quick replies :) I'll look into it when I have some spare time.

**Comment by cpitclaudel** [comment]
@ackalker did you get around to writing that checker? @unhammer has one at https://gist.github.com/unhammer/bc58677ceb3d72755174537a05486f7c ; maybe we could integrate it in Flycheck?

**Comment by unhammer** [comment]
I'll happily sign the CLA if needed :)

**Comment by cpitclaudel** [comment]
That would be great :) Do you want to open a PR? ^^

**Comment by unhammer** [comment]
I may need some help there. https://www.flycheck.org/en/latest/contributor/contributing.html#pull-requests says I need to install cask and do `make check specs unit`. I did

    $ curl -fsSL https://raw.githubusercontent.com/cask/cask/master/go | python
    $ export PATH="$HOME/.cask/bin:$PATH"

but then I get

    $ make check specs unit
    cask exec emacs -Q --batch -L .  -l maint/flycheck-format.el -f flycheck/batch-check-format
    Cannot open load file: No such file or directory, f
    make: *** [Makefile:110: check-format] Error 255

Am I missing something obvious? This is on flycheck master.

**Comment by unhammer** [comment]
Oh if I run just the `cask` command first I can run the tests, sorry for the noise (seems like something `Makefile` could do though?)

**Comment by cpitclaudel** [comment]
> Am I missing something obvious? This is on flycheck master.

You were missing make init :)  It's not obvious; I'll update the text.
