### ISSUE TITLE
flycheck hangs emacs in Python code when editing docstrings that are too long

### ISSUE THREAD

**Issue by sonictk** [flycheck/flycheck#944]
Hi: 

When I am editing a Python file in emacs with flycheck-mode enabled, whenever I am editing a docstring that is over 80 characters, emacs just freezes, and I have to keep spamming C-g and try to move the marker to somewhere outside of the offending line in order to regain control of emacs. This is happening on any platform that I'm running emacs on (Win/OSX/Fedora); I'm wondering if there is something that I could do to avoid this issue other than to disable flycheck-mode entirely (Which I have resorted to doing for the time being)?

Setting the highlighting mode for flycheck to use lines instead as suggested in another issue did not resolve the problem.

This is the script I was editing in question:

```
#!/usr/bin/env python
# -*- coding: UTF-8 -*-

""" Module pyside_utils: This module contains classes useful for dealing with
PySide in Mari.
"""

import mari

from PySide.QtGui import QApplication


def get_mari_main_window():
    """
    This method returns the main Mari ``QMainWindow`` instance as a ``QWidget``.

    :return: ``QWidget``
    """

    # Activate the Mari window to be in focus
    mari.app.activateMainWindow()

    mari_main_window = QApplication.activeWindow()

    return mari_main_window
```

I am using emacs Prelude as my configuration.

Thanks!

**Comment by lunaryorn** [comment]
Hello.

Thank you very much for reporting this issue.  We will try to address it as soon as possible.  However, we need additional information from you.  Please tell us

- your Emacs version, as in `M-x emacs-version`,
- your Flycheck version, as in `M-x flycheck-version`,
- and the output of `M-x flycheck-verify-setup` in an affected buffer.

Please also include the versions of the syntax checking programs you were using if possible.  It'd be awesome if you could try to [reproduce the bug in `emacs -Q`](http://www.lunaryorn.com/2015/11/29/reproduce-bugs-in-emacs-Q.html) as well, to rule out that Prelude is interfering with Flycheck.

Please add a comment with all this information.  If you think that you already provided all necessary information please tell us as well.   If you have difficulties with specific steps please do not hesitate to ask.

Thank you very much for using Flycheck, and for taking the time to report this issue.  We are looking forward to work with you to solve this problem :blush:

-----

This is one of me [saved replies](https://github.com/blog/2135-saved-replies).  I am using this feature to help me reduce the time spend on triaging issues in Flycheck :relaxed:  If you feel that saved replies are not appropriate, please tell me.  Thank you.

**Comment by lunaryorn** [comment]
This issue appears to be inactive; I am closing it.

If you can provide the requested information or bring in additional arguments please leave a comment, and we will look at this case again, and re-open the issue if need be.

Thank you for your feedback and your support.

-----

This is one of me [saved replies](https://github.com/blog/2135-saved-replies).  I am using this feature to help me reduce the time spend on triaging issues in Flycheck :relaxed:  If you feel that saved replies are not appropriate, please tell me.  Thank you.
