### ISSUE TITLE
Undefined constant or method for all external gems (required at the beginning) used 

### ISSUE THREAD

**Issue by mguthmuller** [flycheck/flycheck#945]
Hi, 

I'm using flycheck (version 0.26 snapshot package 20160302.1046) with rubocop (version 0.35.1) in emacs (version 24.4.1).

My configuration set in my .emacs file is:
`(add-hook 'after-init-hook #'global-flycheck-mode)`
`(global-flycheck-mode)`
`(setq flycheck-rubocoprc "~/.rubocop.yml")` 

Flycheck is thus automatically enabled when I run emacs. My problem is that an error is reported for each line in my code in which I'm using an external gem. For example: 

`require 'rest-client'`
`RestClient::Request.new(:method => :get, :url ...)`

Flycheck with Rubocop reports: 

> Undefined constant RestClient::Request
> Undefined constant RestClient

If I execute rubocop outside of emacs, there is no error.

Any idea?

**Comment by lunaryorn** [comment]
Hello.

Thank you very much for reporting this issue.  We will try to address it as soon as possible.  However, we need additional information from you.  Please tell us the output of `M-x flycheck-verify-setup` in an affected buffer.  Please also update Flycheck first.

Please add a comment with all this information.  If you think that you already provided all necessary information please tell us as well.   If you have difficulties with specific steps please do not hesitate to ask.

Thank you very much for using Flycheck, and for taking the time to report this issue.  We are looking forward to work with you to solve this problem :blush:

-----

This is one of me [saved replies](https://github.com/blog/2135-saved-replies).  I am using this feature to help me reduce the time spend on triaging issues in Flycheck :relaxed:  If you feel that saved replies are not appropriate, please tell me.  Thank you.

**Comment by mguthmuller** [comment]
Thanks for the quick anwser!

I've updated flycheck, the last version installed is 20160411.910 but the problem is still there.

The result of `M-x flycheck-verify-setup` is:

> Syntax checkers for buffer test.rb in ruby-mode:
> 
>   chef-foodcritic
>     - predicate:  nil
>     - executable: Not found
> 
>   ruby-rubocop
>     - predicate:  t
>     - executable: Found at /usr/local/bin/rubocop
> 
>   ruby-rubylint
>     - predicate:  t
>     - executable: Found at /usr/local/bin/ruby-lint
> 
>   ruby
>     - predicate:  t
>     - executable: Found at /usr/local/bin/ruby
> 
>   ruby-jruby
>     - predicate:  nil
>     - executable: Not found
> 
> Flycheck Mode is enabled.  Use C-u C-c ! x to enable disabled
> checkers.

**Comment by lunaryorn** [comment]
@mguthmuller Well, the output shows that you also have `ruby-lint` installed and working.  That's where these additional warnings come from; take a look at `C-c ! l` and you'll see that these are reported from ruby-lint.

Use `C-c ! x` to disable ruby-lint, or add it to `flycheck-disabled-checkers` to disabled it permanently.

**Comment by mguthmuller** [comment]
Oh ok, I'm sorry, I thought it was flycheck warnings.

Thank you!

**Comment by lunaryorn** [comment]
@mguthmuller Never mind, you're welcome.  Thanks for taking the time to ask, I hope that you enjoy Flycheck.  

Have fun :+1:
