### ISSUE TITLE
Adding TSLint checker into standard Flycheck

### ISSUE THREAD

**Issue by Simplify** [flycheck/flycheck#947]
Hello,

I'm author and maintainer of [flycheck-typescript-tslint](https://github.com/Simplify/flycheck-typescript-tslint) package. I'll like to include that code into standard Flyckeck, if you want that. I try to contact you about that on Gitter, but didn't got any reply.

TSLint is currently standard for linting TypeScript. Config for TSLint, `tslint.json`, is comes with most TypeScript projects and it's included with `angular2-quickstart`. I think that having this as standard is Flycheck would be great. If you agree, I'll try make PR in the coming days, including tests and documentation. Even I use GNU Emacs for more than 10 years, I'm new to Elisp, so please be critical :)

One another thing worth mentioning is that ESLint, checker for JavaScript, have [experimental extension](https://github.com/eslint/typescript-eslint-parser) for TypeScript.

**Comment by cpitclaudel** [comment]
Hey @Simplify,

Thanks for contributing! Yes, I think we'd love to include support for TSLint. Can you prepare a pull request?

**Comment by Simplify** [comment]
Yes, I'll do it in the next few days.

**Comment by cpitclaudel** [comment]
Thanks!

**Comment by lunaryorn** [comment]
@Simplify Thank you very very much!
