### ISSUE TITLE
Fortran MPI support problem

### ISSUE THREAD

**Issue by gxiaotian** [flycheck/flycheck#950]
I am coding a scientific calculation program with fortran. It utilizes mpif90 as a compiler to perform parallel computing. however, flycheck seems not to support this compiler. It uses gfortran to check my code, and show me a error that "can't open included file mpi.h". What can I do to solve this problem? Thank you so much!

**Comment by cpitclaudel** [comment]
Hi there,

Thanks for your message! We don't currently have support for other Fortran compilers than gfortran, but it should be easy to add new ones. Would you like to try it yourself? I'll be happy to help.

**Comment by gxiaotian** [comment]
Great! I would like to try it! Could you please recommend me some manuals or tutorial about flycheck backend?

**Comment by cpitclaudel** [comment]
Wonderful! @lunaryorn wrote [nice docs](https://htmlpreview.github.io/?https://github.com/flycheck/flycheck/blob/master/doc/legacy/flycheck.html#Syntax-checker-definitions) on extending Flycheck (we're right in the process of migrating the docs to a nicer format, so this link is a one-page archive of the original TexInfo manual).

You may also be interested by the way the [current gfortran checker](https://github.com/flycheck/flycheck/blob/master/flycheck.el#L6502) is defined :)
Let me know if you need help with anything.

**Comment by gxiaotian** [comment]
Cool! I will try it soon. Thanks a lot!

**Comment by lunaryorn** [comment]
If mpif90 has the same command line interface as gfortran you could also try to set flycheck-fortran-gfortran-executable to "mpif90".

**Comment by lunaryorn** [comment]
@gxiaotian Did you try my suggestion?

**Comment by gxiaotian** [comment]
I have tried it, but there is still something wrong. I am new to emacs lisp, and a little busy recently. Don't hurry, I will learn how to do it as soon as possible.

**Comment by lunaryorn** [comment]
@gxiaotian Were you able to solve this problem?

**Comment by gxiaotian** [comment]
@lunaryorn Sorry. I don't have so much time to work on it, although I really want to. If you can solve it, I will very appreciate it. By the way, mpicxx, a mpi compiler for cpp, is not supported neither. Thank you so much!

**Comment by lunaryorn** [comment]
@gxiaotian We cannot solve this issue without your help.

We need you to try whether changing the executable works, and if it doesn't, give us a precise description of how it breaks.

What does "wrong" mean?  How did it fail?

I understand that you're short of time—who isn't, after all?—but if you can't work with us on this issue for a foreseeable time, I'd rather prefer to close this issue as we'd still need to confirm it, which is impossible without your help.

**Comment by gxiaotian** [comment]
@lunaryorn I just changed the command of "flycheck-define-checker fortran-gfortran" from "gfortran" to "mpif90" and it works. And the same thing happened to "gcc" and "mpicxx". I forgot recompile the lisp code last time, so it didn't work then.

**Comment by cpitclaudel** [comment]
Ah, great! You may be interested in `flycheck-set-checker-executable`, too: this way you won't have to modify Flycheck's sources.

```
(flycheck-set-checker-executable CHECKER &optional EXECUTABLE)

This function is for interactive use only;
in Lisp code Set the executable variable directly instead

Set the executable of CHECKER in the current buffer.

CHECKER is a syntax checker symbol.  EXECUTABLE is a string with
the name of a executable or the path to an executable file, which
is to be used as executable for CHECKER.  If omitted or nil,
reset the executable of CHECKER.

Interactively, prompt for a syntax checker and an executable
file, and set the executable of the selected syntax checker.
With prefix arg, prompt for a syntax checker only, and reset the
executable of the select checker to the default.

Set the executable variable of CHECKER, that is,
‘flycheck-CHECKER-executable’ to EXECUTABLE.  Signal
‘user-error’, if EXECUTABLE does not denote a command or an
executable file.

This command is intended for interactive use only.  In Lisp, just
‘let’-bind the corresponding variable, or set it directly.  Use
‘flycheck-checker-executable-variable’ to obtain the executable
variable symbol for a syntax checker.
```
