### ISSUE TITLE
Cannot access https://www.flycheck.org/ ?

### ISSUE THREAD

**Issue by xuchunyang** [flycheck/flycheck#952]
After I found flycheck doesn't come with a info manual, I decided to visit flycheck's homepage. `C-h P flycheck` tells me the homepage url is: https://www.flycheck.org/, however I can't visit the site in Chrome, here is a screen shot:

![screen shot 2016-04-30 at 14 29 30](https://cloud.githubusercontent.com/assets/4550353/14934337/3350972c-0ee0-11e6-8b12-47bd38c3974b.png)

BTW, http://www.flycheck.org/ is accessible.

**Comment by cpitclaudel** [comment]
Thanks for spotting this!
The issue seems to be that our domain is set up with certificates covering `*.readthedocs.org`. Wild guess: https://blog.readthedocs.com/securing-subdomains/ (since https://flycheck.readthedocs.io/en/latest/ works fine too).

**Comment by lunaryorn** [comment]
@xuchunyang I'm sorry, that was a typo.  http://www.flycheck.org was never actually served over HTTPS.  I've fixed the URL.

**Comment by xuchunyang** [comment]
@lunaryorn It's okay. Thanks for the fix.
