### ISSUE TITLE
"Suspicious state" with unknown encoding

### ISSUE THREAD

**Issue by seanfarley** [flycheck/flycheck#954]
For a few days now, I've seen this error for every python file:

```
Flycheck mode enabled
Suspicious state from syntax checker python-flake8: Checker python-flake8 returned non-zero exit code 1, but no errors from output: Traceback (most recent call last):
  File "/opt/local/bin/flake8", line 9, in <module>
    load_entry_point('flake8==2.5.4', 'console_scripts', 'flake8')()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flake8/main.py", line 25, in main
    flake8_style = get_style_guide(parse_argv=True, config_file=DEFAULT_CONFIG)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flake8/engine.py", line 234, in get_style_guide
    styleguide = StyleGuide(**kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flake8/engine.py", line 154, in __init__
    self._styleguide = kwargs.pop('styleguide', NoQAStyleGuide(**kwargs))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pep8.py", line 1798, in __init__
    arglist, parse_argv, config_file, parser)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pep8.py", line 2084, in process_options
    options = read_config(options, args, arglist, parser)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pep8.py", line 2014, in read_config
    config.read(cli_conf)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/backports/configparser/__init__.py", line 698, in read
    with open(filename, encoding=encoding) as fp:
LookupError: unknown encoding: 

Checker definition probably flawed.
```

Is it possible that the `LANG` environment variable is not being sent to the subprocess?

**Comment by lunaryorn** [comment]
Hello.  Thank you for reporting this issue.  I'm not sure about it, though, for I've never seen this before, even though the Python checkers are really among the oldest ones in Flycheck.

May I ask what you mean with a "for a few days"?  Flycheck didn't change in the last few days in any way that could produce this effect.  Did you change something on your Emacs or Python setup recently?

**Comment by seanfarley** [comment]
I can reproduce this from the command line:

```shell
$ LANG= flake8 remotenames.py
```

Are you able to reproduce that? As for my setup, unfortunately, all three major components were upgraded: `flake8`, `emacs-mac`, and `flycheck`.

I can also see that:

```lisp
(shell-command "env")
```

doesn't have anything set for `LANG` (or `LC_` friends). Should `flycheck` send this variable?

**Comment by lunaryorn** [comment]
@seanfarley No, unfortunately I can't:

```console
$ flake8 --version
2.5.4 (pep8: 1.7.0, pyflakes: 1.0.0, mccabe: 0.4.0) CPython 3.5.1 on Darwin
$ flake8 doc/info.py
doc/info.py:73:80: E501 line too long (104 > 79 characters)
doc/info.py:111:80: E501 line too long (81 > 79 characters)
$ LANG= flake8 doc/info.py
doc/info.py:73:80: E501 line too long (104 > 79 characters)
doc/info.py:111:80: E501 line too long (81 > 79 characters)
$ LC_ALL= LANG= flake8 doc/info.py
doc/info.py:73:80: E501 line too long (104 > 79 characters)
doc/info.py:111:80: E501 line too long (81 > 79 characters)
```

I don't think that the problem lies with Flycheck.  We don't change the `process-environment` in any way when we start a syntax checker.  If `$LANG`'s in there it should propagate to the subprocess just fine.

But in your case it doesn't even seem to be in your environment at all—and how could Flycheck sent a variable that's not even there?  Besides, I can't even reproduce this: In my Emacs (standard Homebrew build of the latest pretest) `LANG`'s set to the right value—thought I don't know where that comes from, maybe I set it somewhere and have forgotten since, but `grep` didn't find anything at least.

Try to run `M-: (setenv "LANG" "en_US.ut8")` in your Emacs and see whether that fixes things.

**Comment by seanfarley** [comment]
Thanks for the info! Yeah, it looks like this is something with my setup then. Your fix does indeed work for me, so I'll add that to my config and try to investigate with my other settings. Thanks for the help!

**Comment by lunaryorn** [comment]
You're welcome.  Please don't hesitate to ask further question if you've got further problems with this.

And please do tell me what you've eventually found out about this problem.  I'm curious what's going on here, for I've never really understood how this locale stuff works in Emacs on OS X.

By the way, are you running a GUI session or a terminal Emacs?  Or do you probably use Emacs daemon in some way?

**Comment by seanfarley** [comment]
I use emacsclient normally through the [emacs-mac package](https://github.com/railwaycat/homebrew-emacsmacport). It could be a change there (since it was recently updated) that caused this but I haven't had the time to look at into it :-/
