### ISSUE TITLE
URL not found when trying to install flycheck

### ISSUE THREAD

**Issue by fjs2097** [flycheck/flycheck#963]
Hi, I am trying to install flycheck for my emacs (24.5.1 on linux) and am encountering the following issue : 
after adding the right repository into my package-archives as such :
(require 'package)
(add-to-list 'package-archives
              '("melpa" . "https://melpa.org/packages/") t)
(package-initialize)

and installing the package through the mini-buffer as such :
M-x package-install RET flycheck.

I get the following error : 
Contacting host: melpa.org:80
url-insert-file-contents: http://melpa.org/packages/dash-2.12.1.el: Not found 

I could not find others with a similar issue online hence I was wondering if you could help out.

thanks!

**Comment by cpitclaudel** [comment]
Hi @fjs2097,

Can you try `M-x package-update`, then `M-x package-install` again?

**Comment by fjs2097** [comment]
Thanks for the quick reply
M-x package-update is not recognized, gives me [No Match]

**Comment by Simplify** [comment]
Hi @fjs2097 
Try running `package-refresh-contents` before running `package-install`. 
Or install `flycheck` from the packages list after running `package-list-packages`.

**Comment by fjs2097** [comment]
it worked, as simple as that!
thanks for the help!

**Comment by cpitclaudel** [comment]
Woops, sorry, package-update is a personal binding :)
