### ISSUE TITLE
Online Flycheck manual is gone?

### ISSUE THREAD

**Issue by chrisdone** [flycheck/flycheck#965]
I was just reading your blog about generic syntax checkers: http://www.lunaryorn.com/2014/12/03/generic-syntax-checkers-in-flycheck.html

In here:

> flycheck-error-new-at then creates and returns a new flycheck-error object with the information obtained from Merlin. Note that you really need to fill the entire structure, except for those slots which are explicitly marked optional in [the documentation.](http://www.flycheck.org/en/latest/dev/api.html#el.struct.flycheck-error)

That documentation link is 404.

If you google "flycheck api", the manual seems to be 404:

http://www.flycheck.org/manual/latest/Flycheck-API.html

Where can I get a copy of the API?

**Comment by lunaryorn** [comment]
We're in the process of moving to a different manual format and the API docs aren't there yet.

Meanwhile you can take a look at the [old manual](http://www.flycheck.org/en/latest/_downloads/flycheck.html#Syntax-checker-definitions) and use the docstrings.

I'm sorry for the inconvenience.

**Comment by chrisdone** [comment]
Ta!

**Comment by lunaryorn** [comment]
@chrisdone Please follow #616 for progress on the API docs.

I'm sorry that I didn't add them earlier, but I didn't realise that anyone actually used these.
