### ISSUE TITLE
Problems with font names containing a dash '-'

### ISSUE THREAD

**Issue by maerten** [flycheck/flycheck#967]
Flycheck gives me an error in Spacemacs on OS X El Capitan:

Flycheck error display error: (error Invalid font name: -*-Inconsolata-dz for Powerline-normal-normal-normal-*-12 .... etc

After searching a bit around, the only solution I found was to rename the font on the system, or use it as the default Monospace font.
Please let me know if you need any more information or if there is any way I can help.

**Comment by lunaryorn** [comment]
Hello.

thank you for reporting this issue to Flycheck, but I don't think that it's a problem in Flycheck itself.

Did you report this issue to Spacemacs?

**Comment by maerten** [comment]
Hi,
No I haven't, but if you think it's not a problem in Flycheck, I will open the issue over there.
Thanks!
