### ISSUE TITLE
Error checking not run on C files

### ISSUE THREAD

**Issue by emacsuser123** [flycheck/flycheck#975]
Hello.

I'm using the latest Flycheck version from Melpa on Ubuntu 14.04.

I'm editing a C buffer, and it seems that flycheck is not displaying errors on the fly.
Well, it does, but only partially, and I think that not as expected.

If I do:  C-c ! v, I get everything green for clang, gcc and cppcheck predicates and executables, and Flycheck Mode is enabled.

- The first problem is that flycheck complains about project-specific .h files, included in /path/to/project-root/include directory. So, it says "file not found", although I do not have any problem when compiling the project, the .h file is found by the compiler without any problem.

- The second problem is that flycheck is not giving any feedback on any syntax-related mistake.

The flycheck-indication-mode is set to right-fringe.

My emacs version is 24.5.1, x64 and my flycheck version is 20160518.111 from Melpa.

P.S. I can reproduce the problem if I use emacs -Q.  Same behaviour.

Any idea?

Thanks a lot.
-Bob

**Comment by lunaryorn** [comment]
@emacsuser123 Did you configure Flycheck for your project, I.e. setup include paths, etc.?

**Comment by emacsuser123** [comment]
Hi.
Thanks for the prompt reply.
Well, yes, I guess.
I've got only two variables configured:
- flycheck-indication-mode = right-fringe
- flycheck-c/c++-quoted-include-directory = /path/to/include

Is there any other thing that needs to be done?

Thanks.
-Bob

**Comment by lunaryorn** [comment]
@emacsuser123 Where did you get `flycheck-c/c++-quoted-include-directory` from?  Flycheck doesn't define this variable; take a look at the [available options for C/C++](http://www.flycheck.org/en/latest/languages.html#c-c).

**Comment by emacsuser123** [comment]
To be honest, I have no idea.

Anyway, I have set both flycheck-gcc-include-path and flycheck-clang-include-path and now the error is gone.

For some reason I do not understand, only setting the gcc var was not enough, although I'm using the gcc compiler. I have clang also installed, but I guess the gcc var should enough in order to do the syntax check, right?

But The second error still persists. Somehow, I can type anything, and no error is notified.

Do you have any clue?

Thanks,
-Bob

**Comment by lunaryorn** [comment]
@emacsuser123 By default, Flycheck uses Clang, so unless you explicitly disabled Clang you won't be using GCC for syntax checking.

As for the second issue, I can't tell.  Your report is a little unclear.  What's missing exactly?  Just the fringe icon?  Or the in-buffer highlighting as well?  Do you use a GUI frame or a TTY frame?  Do errors appear in the error list (`C-c ! l`)?  

Can you provide a screenshot that shows the erroneous behaviour?  And probably provide a step-by-step recipe for me to reproduce the error in `emacs -Q`?

**Comment by emacsuser123** [comment]
Thanks.
My fault.... The way I had defined the flycheck-clang-include-path var was incorrect.
I have defined it correctly, and now errors are displayed.

Thanks
-Bob

**Comment by lunaryorn** [comment]
@emacsuser123 Thanks, I'm happy to hear that Flycheck works for you.  Have fun, and please tell us if you find anything missing, or have other issues with Flycheck. :blush:
