### ISSUE TITLE
cppcheck ERT test failure

### ISSUE THREAD

**Issue by spwhitton** [flycheck/flycheck#980]
With Flycheck 27 and cppcheck 1.73 (the latest upstream release), the test suite fails:

    Test flycheck-define-checker/c/c++-cppcheck/default condition:
        (ert-test-failed
         ((should
           (equal expected flycheck-current-errors))
          :form
          (equal
           ([cl-struct-flycheck-error #<killed buffer> c/c++-cppcheck "/home/swhitton/src/flycheck/test/resources/language/c_c++/style.cpp" 5 nil "Unused variable: unused" info "unusedVariable"]
            [cl-struct-flycheck-error #<killed buffer> c/c++-cppcheck "/home/swhitton/src/flycheck/test/resources/language/c_c++/style.cpp" 9 nil "Division by zero." error "zerodiv"]
            [cl-struct-flycheck-error #<killed buffer> c/c++-cppcheck "/home/swhitton/src/flycheck/test/resources/language/c_c++/style.cpp" 14 nil "Parameter 'foo' is passed by value. It could be passed as a (const) reference which is usually faster and recommended in C++." warning "passedByValue"])
           ([cl-struct-flycheck-error #<killed buffer> c/c++-cppcheck "/home/swhitton/src/flycheck/test/resources/language/c_c++/style.cpp" 5 nil "Unused variable: unused" info "unusedVariable"]
            [cl-struct-flycheck-error #<killed buffer> c/c++-cppcheck "/home/swhitton/src/flycheck/test/resources/language/c_c++/style.cpp" 9 nil "Division by zero." error "zerodiv"]))
          :value nil :explanation
          (proper-lists-of-different-length 3 2
                                            ([cl-struct-flycheck-error #<killed buffer> c/c++-cppcheck "/home/swhitton/src/flycheck/test/resources/language/c_c++/style.cpp" 5 nil "Unused variable: unused" info "unusedVariable"]
                                             [cl-struct-flycheck-error #<killed buffer> c/c++-cppcheck "/home/swhitton/src/flycheck/test/resources/language/c_c++/style.cpp" 9 nil "Division by zero." error "zerodiv"]
                                             [cl-struct-flycheck-error #<killed buffer> c/c++-cppcheck "/home/swhitton/src/flycheck/test/resources/language/c_c++/style.cpp" 14 nil "Parameter 'foo' is passed by value. It could be passed as a (const) reference which is usually faster and recommended in C++." warning "passedByValue"])
                                            ([cl-struct-flycheck-error #<killed buffer> c/c++-cppcheck "/home/swhitton/src/flycheck/test/resources/language/c_c++/style.cpp" 5 nil "Unused variable: unused" info "unusedVariable"]
                                             [cl-struct-flycheck-error #<killed buffer> c/c++-cppcheck "/home/swhitton/src/flycheck/test/resources/language/c_c++/style.cpp" 9 nil "Division by zero." error "zerodiv"])
                                            first-mismatch-at 2)))

**Comment by lunaryorn** [comment]
@spwhitton Well, these tests regularly fail with newer versions of the corresponding tools.  Feel free to update :)

**Comment by spwhitton** [comment]
@lunaryorn The problem is that one of the warnings has disappeared i.e. the new version detects only two problems, not three.  Is it likely that cppcheck removed their test, or do we have to update both the test and the test file?

**Comment by lunaryorn** [comment]
@spwhitton I don't know what cppcheck changed, but it's still reporting errors, so it's not totally broken for Flycheck and thus it's fine to just update the unit test itself.

**Comment by spwhitton** [comment]
Okay, I'll prepare a patch :)

-- 
Sean Whitton

**Comment by spwhitton** [comment]
Something quite strange is going on.  I would be grateful if you could take a look on your system.

Before my patch (reproduced from above):

    Test flycheck-define-checker/c/c++-cppcheck/default condition:
        (ert-test-failed
         ((should
           (equal expected flycheck-current-errors))
          :form
          (equal
           ([cl-struct-flycheck-error #<killed buffer> c/c++-cppcheck "/home/swhitton/src/flycheck/test/resources/language/c_c++/style.cpp" 5 nil "Unused variable: unused" info "unusedVariable"]
            [cl-struct-flycheck-error #<killed buffer> c/c++-cppcheck "/home/swhitton/src/flycheck/test/resources/language/c_c++/style.cpp" 9 nil "Division by zero." error "zerodiv"]
            [cl-struct-flycheck-error #<killed buffer> c/c++-cppcheck "/home/swhitton/src/flycheck/test/resources/language/c_c++/style.cpp" 14 nil "Parameter 'foo' is passed by value. It could be passed as a (const) reference which is usually faster and recommended in C++." warning "passedByValue"])
           ([cl-struct-flycheck-error #<killed buffer> c/c++-cppcheck "/home/swhitton/src/flycheck/test/resources/language/c_c++/style.cpp" 5 nil "Unused variable: unused" info "unusedVariable"]
            [cl-struct-flycheck-error #<killed buffer> c/c++-cppcheck "/home/swhitton/src/flycheck/test/resources/language/c_c++/style.cpp" 9 nil "Division by zero." error "zerodiv"]))
          :value nil :explanation
          (proper-lists-of-different-length 3 2
                                            ([cl-struct-flycheck-error #<killed buffer> c/c++-cppcheck "/home/swhitton/src/flycheck/test/resources/language/c_c++/style.cpp" 5 nil "Unused variable: unused" info "unusedVariable"]
                                             [cl-struct-flycheck-error #<killed buffer> c/c++-cppcheck "/home/swhitton/src/flycheck/test/resources/language/c_c++/style.cpp" 9 nil "Division by zero." error "zerodiv"]
                                             [cl-struct-flycheck-error #<killed buffer> c/c++-cppcheck "/home/swhitton/src/flycheck/test/resources/language/c_c++/style.cpp" 14 nil "Parameter 'foo' is passed by value. It could be passed as a (const) reference which is usually faster and recommended in C++." warning "passedByValue"])
                                            ([cl-struct-flycheck-error #<killed buffer> c/c++-cppcheck "/home/swhitton/src/flycheck/test/resources/language/c_c++/style.cpp" 5 nil "Unused variable: unused" info "unusedVariable"]
                                             [cl-struct-flycheck-error #<killed buffer> c/c++-cppcheck "/home/swhitton/src/flycheck/test/resources/language/c_c++/style.cpp" 9 nil "Division by zero." error "zerodiv"])
                                        first-mismatch-at 2)))

Then I apply this simple patch to update the values:

    diff --git a/test/flycheck-test.el b/test/flycheck-test.el
    index 643272a..a15a960 100644
    --- a/test/flycheck-test.el
    +++ b/test/flycheck-test.el
    @@ -3125,9 +3125,7 @@ of the file will be interrupted because there are too many #ifdef configurations
          "language/c_c++/style.cpp" '(c-mode c++-mode)
          '(5 nil info "Unused variable: unused" :id "unusedVariable"
              :checker c/c++-cppcheck)
    -     '(9 nil error "Division by zero." :id "zerodiv" :checker c/c++-cppcheck)
    -     '(14 nil warning "Parameter 'foo' is passed by value. It could be passed as a (const) reference which is usually faster and recommended in C++."
    -          :id "passedByValue" :checker c/c++-cppcheck))))
    +     '(9 nil error "Division by zero." :id "zerodiv" :checker c/c++-cppcheck))))

     (flycheck-ert-def-checker-test cfengine cfengine error
       (skip-unless (fboundp 'cfengine3-mode))

However, I then get this test failure:

    Test flycheck-define-checker/c/c++-cppcheck/default condition:
        (ert-test-failed
         ((should
           (equal expected flycheck-current-errors))
          :form
          (equal
           ([cl-struct-flycheck-error #<killed buffer> c/c++-cppcheck "/home/swhitton/src/flycheck/test/resources/language/c_c++/style.cpp" 5 nil "Unused variable: unused" info "unusedVariable"]
            [cl-struct-flycheck-error #<killed buffer> c/c++-cppcheck "/home/swhitton/src/flycheck/test/resources/language/c_c++/style.cpp" 9 nil "Division by zero." error "zerodiv"]
            [cl-struct-flycheck-error #<killed buffer> c/c++-cppcheck "/home/swhitton/src/flycheck/test/resources/language/c_c++/style.cpp" 14 nil "Parameter 'foo' is passed by value. It could be passed as a (const) reference which is usually faster and recommended in C++." warning "passedByValue"])
           ([cl-struct-flycheck-error #<killed buffer> c/c++-cppcheck "/home/swhitton/src/flycheck/test/resources/language/c_c++/style.cpp" 5 nil "Unused variable: unused" info "unusedVariable"]
            [cl-struct-flycheck-error #<killed buffer> c/c++-cppcheck "/home/swhitton/src/flycheck/test/resources/language/c_c++/style.cpp" 9 nil "Division by zero." error "zerodiv"]))
          :value nil :explanation
          (proper-lists-of-different-length 3 2
                                            ([cl-struct-flycheck-error #<killed buffer> c/c++-cppcheck "/home/swhitton/src/flycheck/test/resources/language/c_c++/style.cpp" 5 nil "Unused variable: unused" info "unusedVariable"]
                                             [cl-struct-flycheck-error #<killed buffer> c/c++-cppcheck "/home/swhitton/src/flycheck/test/resources/language/c_c++/style.cpp" 9 nil "Division by zero." error "zerodiv"]
                                             [cl-struct-flycheck-error #<killed buffer> c/c++-cppcheck "/home/swhitton/src/flycheck/test/resources/language/c_c++/style.cpp" 14 nil "Parameter 'foo' is passed by value. It could be passed as a (const) reference which is usually faster and recommended in C++." warning "passedByValue"])
                                            ([cl-struct-flycheck-error #<killed buffer> c/c++-cppcheck "/home/swhitton/src/flycheck/test/resources/language/c_c++/style.cpp" 5 nil "Unused variable: unused" info "unusedVariable"]
                                             [cl-struct-flycheck-error #<killed buffer> c/c++-cppcheck "/home/swhitton/src/flycheck/test/resources/language/c_c++/style.cpp" 9 nil "Division by zero." error "zerodiv"])
                                            first-mismatch-at 2)))

How can changing the expected value cause `flycheck-current-errors` to change?

**Comment by lunaryorn** [comment]
@spwhitton It doesn't, it just causes the test to fail at different stages.  Take a closer look at the test case definition: It tests the checker in C *and* C++.

Currently the test fails in the C buffer because the check behind the const reference error only applies to C++.  If you remove that error from the expected errors it passes C but fails subsequently in the C++ buffer where the check applies.

I've pushed a fix.

**Comment by spwhitton** [comment]
@lunaryorn Thank you for taking the time to fix this :)
