### ISSUE TITLE
Add RuboCop Minimum Version to Docs

### ISSUE THREAD

**Issue by sshaw** [flycheck/flycheck#989]
With the addition of the `--cache` option one must have RuboCop >= `0.34.0`.

**Comment by sshaw** [comment]
Or may be better to check the installed version and add the option based on that.

**Comment by lunaryorn** [comment]
@sshaw The minimum version is documented in `flycheck-describe-checker RET ruby-rubocop`, isn't it?  Which docs are you referring to?

We won't check version requirements for tools, or conditionally assemble command lines based on the detected versions—it's simply too much maintenance effort to keep such checks up to date.

**Comment by sshaw** [comment]
> @sshaw The minimum version is documented in flycheck-describe-checker RET ruby-rubocop..

Yes, I see it there. The docs I was refering to [are on the website](http://www.flycheck.org/en/latest/languages.html#syntax-checker-ruby-rubocop).
