### ISSUE TITLE
Checker php-phpcs returned non-zero exit code 2, unknown option --stdin

### ISSUE THREAD

**Issue by tarrsalah** [flycheck/flycheck#991]
### Error message
`Suspicious state from syntax checker php-phpcs: Checker php-phpcs returned non-zero exit code 2, but no errors from output: ERROR: option "--stdin-path=/home/tarrsalah/src/index.php" not known.`

### versions
|program| version|
|------|----------------|
|php |  7.0.4|
|emacs| 24.5.1|
| phpcs |2.2.0 (stable)|
|flycheck| 29snapshot (package: 20160606.302)|

### notes

- The error is reproducible by emacs -Q.
- the output of `flycheck-verify-checker`:

```
 php-phpcs
    - major mode: `php-mode' supported
    - predicate:  t
    - executable: Found at /home/tarrsalah/.config/composer/vendor/bin/phpcs
```

**Comment by lunaryorn** [comment]
Please update to the newest release of phpcs.  Flycheck needs version 2.6 or newer.
