### ISSUE TITLE
Would matching backwards help us with multiline errors?

### ISSUE THREAD

**Issue by cpitclaudel** [flycheck/flycheck#993]
Hey @lunaryorn,

Some checkers don't indent continuation lines in multiline messages; this makes it tricky to split consecutive messages. For example in ReStructuredText:

```
-*- mode: compilation; default-directory: "~/.emacs.d/lisp/compact-docstrings/" -*-
Compilation started at Sun Jun 19 23:30:00

rst2pseudoxml.py --report\=2 --halt\=5 - /dev/null < /home/clement/.emacs.d/lisp/compact-docstrings/README.rst
<stdin>:1: (ERROR/3) Error in "image" directive:
1 argument(s) required, 0 supplied.

.. image::
<stdin>:2: (ERROR/3) Error in "image" directive:
1 argument(s) required, 0 supplied.

.. image::

Compilation finished at Sun Jun 19 23:30:00
```

In this particular case it could  work to just parse until a blank line, but more generally there's an issue with multiline messages whose continuation lines are not clearly indented (or otherwise indicated).

Could parsing backwards instead of forwards work? The proposal algorithm looks like this:

```elisp
(let ((bound nil))
  (goto-char (point-max))
  (while (re-search-backward *error-regexp* bound t)
    (push *match* *errors*)
    (setq bound (match-beginning 0))))
```

The idea being to use the beginning of each match as a natural bound for the preceding one. I wonder if it would be useful to ship a function based on this, which we could point out to implementors of new checkers if they need to deal with multiline messages (IOW I'm not proposing to change any default; just to add a variant of this as a separate function that new checkers might use, just like we have XML and JSON)

What do you think?

**Comment by lunaryorn** [comment]
@cpitclaudel I'm not sure whether I understand the issue… but in any case I'd not like to include error parsers that we don't use ourselves.  IOW, if a different error parser for a certain checker fixes an issue or makes parsing simpler I'm all for it, but we should not include a parser just because it might possibly be useful.

I'd like to see a patch that shows why we need this.

**Comment by cpitclaudel** [comment]
Ok :) I need to find the time to write it :) Let's close this, and I'll reopen when I find time.
