### ISSUE TITLE
How do I remove the annoying underline in flycheck (using eslint)?

### ISSUE THREAD

**Issue by scarletsky** [flycheck/flycheck#997]
I am using spacemacs and flycheck-eslint as linter to check my React code.

Here is my project's `.eslintrc`,

```json
    {
      "extends": [
        "eslint:recommended",
        "plugin:react/recommended"
      ],
      "parser": "babel-eslint",
      "env": {
        "browser": true,
        "es6": true,
        "node": true
      },
      "parserOptions": {
        "ecmaFeatures": {
          "experimentalObjectRestSpread": true,
          "jsx": true
        },
        "sourceType": "module"
      },
      "plugins": [
        "react"
      ],
      "rules": {
        "semi": [0, "never"],
        "eqeqeq": 2,
        "no-console": 1,
        "no-unused-vars": [1, {"vars": "all", "args": "after-used"}],
        "comma-spacing": [2, {"before": false, "after": true}],
        "react/prop-types": [2, {
          "ignore": ["dispatch"]
        }]
      },
      "globals": {
        "__DEV_MODE__": true,
        "__API_SERVER__": true
      }
    }
```

I have set **NO** semicolon in the `.eslintrc`. I've try Atom Editor, Sublime Text3, VSCode, they work as expect.

But in spacemacs, I got the annoying underline hint.

[![enter image description here][1]][1]

  [1]: http://i.stack.imgur.com/SnWjQ.jpg

I know that I can remove the underline by putting the semicolon at the end, but in my project, semicolon is unnecessary...

Here is some information of my environment:

**Flycheck-verify-setup**
```
Syntax checkers for buffer App.jsx in js2-mode:

  javascript-eslint
    - predicate:  t
    - executable: Found at /usr/local/bin/eslint

  javascript-jshint (disabled)
    - predicate:  nil
    - executable: Not found

  javascript-gjslint
    - predicate:  nil
    - executable: Not found

  javascript-jscs
    - predicate:  nil
    - executable: Not found

  javascript-standard
    - predicate:  nil
    - executable: Not found

Flycheck Mode is enabled. Use SPC u C-c ! x to enable disabled checkers.
```

**Operating System**
macOS 10.11.4

**Emacs Version**
24.5.1

**Flycheck Version**

28snapshot (package: 20160519.303)

**Comment by lunaryorn** [comment]
These underlines are come from JS2 Mode not Flycheck.

I'm closing as invalid.

**Comment by Simplify** [comment]
Try setting `js2-strict-missing-semi-warning` to `nil` or in your case setting `js2-missing-semi-one-line-override` to `t` may work as well.

**Comment by scarletsky** [comment]
@lunaryorn I am so sorry. I will close this issue.
@Simplify  Thanks for your tips!
