### ISSUE TITLE
Flycheck HTML docs should not load images and javascript from third party servers

### ISSUE THREAD

**Issue by spwhitton** [flycheck/flycheck#999]
The offline HTML docs generated by `cd doc && make html` are a really nice resource.  However, they are not self-contained.  They load images and JavaScript from third party servers.  That means they don't work without a connection to the Internet.  Further, they could compromise the user's privacy.  Loading images provides information about the user's browsing of the docs to the image servers, and there is even embedded Google AdSense tracking code...

It would be great if the offline HTML docs were self-contained, or the Makefile had an option to build them without the external images and JavaScript.

**Comment by lunaryorn** [comment]
@spwhitton I wasn't aware that anyone would try to use our documentation offline.  We do not include the documentation in our packages.  Are you building the documentation yourself?

**Comment by spwhitton** [comment]
Yes, I'm building it from the git repository, like this:

    cd doc
    make html

**Comment by lunaryorn** [comment]
I'm trying to understand your use case to figure out whether we need to change Flycheck's doc build or whether we just need to find a fix for your case 😊

Are you just building the documentation for yourself?  Or do you intend to distribute it?

Besides what images do you refer to?  Can you probably compile a list of all external resources you'd like to disable?

**Comment by spwhitton** [comment]
Thank you for your interest in this issue :)  I'm trying to build the documentation it to include in Debian, in `/usr/share/doc/flycheck/html`.  So I think that this is just for my case (hence low priority).  [Here's a list of files](https://gist.github.com/spwhitton/a1528096a9c80b9d3755bc4db42058e5) and the external resources they contain.

**Comment by lunaryorn** [comment]
Well, but building for Debian extends to more than just a personal build, doesn't it 😄 I've only skimmed the list but it appears that it's all sidebar buttons and badges.  

Could you try to remove `about.html` from `html_sidebars` in `doc/conf.py`, rebuild the docs from scratch with `make -C doc clean html` and compile the list again?

If it's really just the sidebar it should be easy enough to add a configuration option to disable all of them :blush:

**Comment by spwhitton** [comment]
Thanks for the suggestion.  That shortens the list of errors, but some remain.  They are the Google Adsense code, and the image `forkme_right_darkblue_121621.png`.  Is there another file these might be included from?

**Comment by lunaryorn** [comment]
These come from the layout itself, but can be turned off with some configuration settings.

I could add an `OFFLINE` option to the Makefile to disable these and remove the buttons the sidebar.  Would that be ok?

You'll have to test it once in a while, though, for I have no use for this option myself and won't be able to guarantee that updates to the layout or changes to the docs won't break it.

**Comment by spwhitton** [comment]
On Tue, Jul 05, 2016 at 03:45:08AM -0700, Sebastian Wiesner wrote:
> These come from the layout itself, but can be turned off with some
> configuration settings.
> 
> I could add an OFFLINE option to the Makefile to disable these and remove the
> buttons the sidebar. Would that be ok?

That would be great.

> You'll have to test it once in a while, though, for I have no use for
> this option myself and won't be able to guarantee that updates to the
> layout or changes to the docs won't break it.

Yes, I would check it before every upload to Debian (so, shortly after
every time you make a release).

**Comment by lunaryorn** [comment]
@spwhitton Please take a look at #1014 for the new option.
